import buildlogic.mavenResourceFilterArgs
import io.camunda.gradle.pom.PomResolver
import org.apache.tools.ant.filters.ReplaceTokens
import org.gradle.api.file.DuplicatesStrategy
import org.gradle.api.tasks.bundling.Compression
import org.gradle.api.tasks.bundling.Tar
import org.gradle.api.tasks.bundling.Zip
import org.gradle.jvm.tasks.Jar

/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
  id("buildlogic.server-conventions")
  id("buildlogic.optimize-conventions")
}

val parentPom = providers.fileContents(layout.settingsDirectory.file("parent/pom.xml"))
val optimizeParentPom = providers.fileContents(layout.settingsDirectory.file("optimize/pom.xml"))
val optimizePom = providers.fileContents(layout.projectDirectory.file("pom.xml"))
val parentProperties = PomResolver(parentPom.asText.get()).properties()
val optimizeParentProperties = PomResolver(optimizeParentPom.asText.get()).properties()
val optimizePomResolver = PomResolver(optimizePom.asText.get())
val optimizeVersion = project.version.toString()
val optimizeElasticsearchVersion =
  optimizePomResolver.resolveProperty(
    "version.elasticsearch",
    parentProperties,
    optimizeParentProperties,
    optimizePomResolver.properties(),
  )
val optimizeDocsVersion =
  if (optimizeVersion.matches(Regex("\\d+\\.\\d+\\.\\d+-.+"))) {
    "develop"
  } else {
    optimizeVersion.substringBefore('-').replace(Regex("\\.\\d+$"), ".0")
  }
val resourceTokens =
  mapOf(
    "project.version" to optimizeVersion,
    "version.elasticsearch" to optimizeElasticsearchVersion,
    "docs.version" to optimizeDocsVersion,
  )

val optimizeDistroResources =
  tasks.register<Sync>("generateOptimizeDistroResources") {
    from("src") {
      filter(mavenResourceFilterArgs(resourceTokens), ReplaceTokens::class.java)
    }
    into(layout.buildDirectory.dir("generated/optimize-distro"))
  }

val optimizeBackendJar =
  layout.projectDirectory.file("../optimize/backend/build/libs/optimize-backend-$optimizeVersion.jar")
val upgradeOptimizeJar =
  layout.projectDirectory.file("../optimize/upgrade/build/libs/upgrade-optimize-$optimizeVersion.jar")

val assembleDist =
  tasks.register<Sync>("assembleDist") {
    group = "build"
    description = "Assemble the Camunda Optimize distribution"
    dependsOn(":optimize-backend:jar", ":upgrade-optimize:jar", optimizeDistroResources)

    // Yarn builds only run when producing a dist artifact, not during tests or compilation.
    dependsOn(":optimize-client:yarnBuild")
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    into(layout.buildDirectory.dir("camunda-optimize"))

    from(optimizeDistroResources)
    from(optimizeBackendJar)
    from(upgradeOptimizeJar) {
      into("upgrade")
      rename(
        "upgrade-optimize-$optimizeVersion.jar",
        "upgrade-optimize-to-$optimizeVersion.jar",
      )
    }
    from({ configurations.runtimeClasspath.get() }) {
      into("lib")
      exclude("optimize-backend-*.jar", "upgrade-optimize-*.jar", "upgrade-optimize-to-*.jar")
    }
    from(layout.projectDirectory.dir("../optimize/backend/src/main/resources/localization")) {
      into("config/localization")
    }
    from(layout.projectDirectory.dir("../optimize/backend/src/main/resources/logo")) {
      into("config/logo")
    }

    doLast {
      destinationDir
        .walkTopDown()
        .filter { it.isFile && (it.name == "optimize-startup.sh" || it.name == "upgrade.sh") }
        .forEach { it.setExecutable(true, false) }
    }
  }

val distTar =
  tasks.register<Tar>("distTar") {
    group = "build"
    description = "Create the Camunda Optimize tar.gz archive"
    dependsOn(assembleDist)
    compression = Compression.GZIP
    archiveBaseName.set("camunda-optimize")
    archiveVersion.set(optimizeVersion)
    archiveClassifier.set("production")
    archiveExtension.set("tar.gz")
    destinationDirectory.set(layout.buildDirectory.dir("distributions"))

    from(assembleDist) {
      eachFile {
        if (path == "optimize-startup.sh" || path == "upgrade/upgrade.sh") {
          permissions { unix(0b111101101) }
        }
      }
    }
  }

val distZip =
  tasks.register<Zip>("distZip") {
    group = "build"
    description = "Create the Camunda Optimize ZIP archive"
    dependsOn(assembleDist)
    archiveBaseName.set("camunda-optimize")
    archiveVersion.set(optimizeVersion)
    archiveClassifier.set("production")
    destinationDirectory.set(layout.buildDirectory.dir("distributions"))

    from(assembleDist) {
      eachFile {
        if (path == "optimize-startup.sh" || path == "upgrade/upgrade.sh") {
          permissions { unix(0b111101101) }
        }
      }
    }
  }

dependencies {
  implementation(project(":optimize-backend"))
  implementation(project(":upgrade-optimize"))
  implementation(libs.org.apache.logging.log4j.log4j.slf4j2.impl)
  implementation(libs.org.apache.logging.log4j.log4j.core)
}

group = "io.camunda.optimize"

description = "Optimize (Distro)"

tasks.named<Jar>("jar") { enabled = false }

tasks.named("assemble") { dependsOn(assembleDist, distTar, distZip) }
