/*
 * Copyright Camunda Services GmbH and/or licensed to Camunda Services GmbH under
 * one or more contributor license agreements. See the NOTICE file distributed
 * with this work for additional information regarding copyright ownership.
 * Licensed under the Camunda License 1.0. You may not use this file
 * except in compliance with the Camunda License 1.0.
 */

import type {
  ProcessInstance,
  ProcessDefinition,
  Variable,
  ElementInstance,
  Job,
} from '@camunda/camunda-api-zod-schemas/8.10';

import {
  MOCK_AGENT_INSTANCE_KEY,
  MOCK_AGENT_DEFINITION_KEY,
  MOCK_AGENT_DEFINITION_ID,
  MOCK_AGENT_LLM_CALL_1_KEY,
  MOCK_AGENT_LLM_CALL_2_KEY,
  MOCK_AGENT_LLM_CALL_3_KEY,
  MOCK_AGENT_SUBPROCESS_KEY,
} from './constants';

// Extended type for mock data — flowScopeKey is not in the API type but needed for scope filtering
type MockElementInstance = ElementInstance & {flowScopeKey: string};

export const MOCK_AGENT_PROCESS_INSTANCE: ProcessInstance = {
  processInstanceKey: MOCK_AGENT_INSTANCE_KEY,
  processDefinitionName: 'AI Agent Chat With Tools',
  processDefinitionId: MOCK_AGENT_DEFINITION_ID,
  processDefinitionKey: MOCK_AGENT_DEFINITION_KEY,
  processDefinitionVersion: 1,
  processDefinitionVersionTag: null,
  tenantId: '<default>',
  state: 'ACTIVE',
  startDate: '2026-03-26T14:30:00.000Z',
  endDate: null,
  hasIncident: false,
  parentProcessInstanceKey: null,
  parentElementInstanceKey: null,
  rootProcessInstanceKey: null,
  tags: [],
};

export const MOCK_AGENT_PROCESS_DEFINITION: ProcessDefinition = {
  name: 'AI Agent Chat With Tools',
  processDefinitionId: MOCK_AGENT_DEFINITION_ID,
  processDefinitionKey: MOCK_AGENT_DEFINITION_KEY,
  resourceName: 'ai-agent-chat-with-tools.bpmn',
  version: 1,
  versionTag: null,
  tenantId: '<default>',
  hasStartForm: false,
};

export const MOCK_AGENT_ELEMENT_INSTANCES: MockElementInstance[] = [
  {
    elementInstanceKey: MOCK_AGENT_INSTANCE_KEY,
    processInstanceKey: MOCK_AGENT_INSTANCE_KEY,
    processDefinitionKey: MOCK_AGENT_DEFINITION_KEY,
    processDefinitionId: MOCK_AGENT_DEFINITION_ID,
    elementId: MOCK_AGENT_DEFINITION_ID,
    elementName: 'AI Agent Chat With Tools',
    type: 'PROCESS',
    state: 'ACTIVE',
    hasIncident: false,
    flowScopeKey: MOCK_AGENT_INSTANCE_KEY,
    rootProcessInstanceKey: null,
    tenantId: '<default>',
    startDate: '2026-03-26T14:30:00.000Z',
    endDate: null,
    incidentKey: null,
  },
  {
    elementInstanceKey: '4451799813685001',
    processInstanceKey: MOCK_AGENT_INSTANCE_KEY,
    processDefinitionKey: MOCK_AGENT_DEFINITION_KEY,
    processDefinitionId: MOCK_AGENT_DEFINITION_ID,
    elementId: 'StartEvent_1',
    elementName: 'Task to perform received',
    type: 'START_EVENT',
    state: 'COMPLETED',
    hasIncident: false,
    flowScopeKey: MOCK_AGENT_INSTANCE_KEY,
    rootProcessInstanceKey: null,
    tenantId: '<default>',
    startDate: '2026-03-26T14:30:00.100Z',
    endDate: '2026-03-26T14:30:00.200Z',
    incidentKey: null,
  },
  {
    elementInstanceKey: '4451799813685005',
    processInstanceKey: MOCK_AGENT_INSTANCE_KEY,
    processDefinitionKey: MOCK_AGENT_DEFINITION_KEY,
    processDefinitionId: MOCK_AGENT_DEFINITION_ID,
    elementId: 'Gateway_0z6ctwk',
    elementName: null,
    type: 'EXCLUSIVE_GATEWAY',
    state: 'COMPLETED',
    hasIncident: false,
    flowScopeKey: MOCK_AGENT_INSTANCE_KEY,
    rootProcessInstanceKey: null,
    tenantId: '<default>',
    startDate: '2026-03-26T14:30:00.250Z',
    endDate: '2026-03-26T14:30:00.280Z',
    incidentKey: null,
  },
  {
    elementInstanceKey: MOCK_AGENT_SUBPROCESS_KEY,
    processInstanceKey: MOCK_AGENT_INSTANCE_KEY,
    processDefinitionKey: MOCK_AGENT_DEFINITION_KEY,
    processDefinitionId: MOCK_AGENT_DEFINITION_ID,
    elementId: 'AI_Agent',
    elementName: 'AI Agent',
    type: 'AD_HOC_SUB_PROCESS',
    state: 'ACTIVE',
    hasIncident: false,
    flowScopeKey: MOCK_AGENT_INSTANCE_KEY,
    rootProcessInstanceKey: null,
    tenantId: '<default>',
    startDate: '2026-03-26T14:30:00.300Z',
    endDate: null,
    incidentKey: null,
  },
  // LLM iteration 1 — nested under AI Agent subprocess
  {
    elementInstanceKey: MOCK_AGENT_LLM_CALL_1_KEY,
    processInstanceKey: MOCK_AGENT_INSTANCE_KEY,
    processDefinitionKey: MOCK_AGENT_DEFINITION_KEY,
    processDefinitionId: MOCK_AGENT_DEFINITION_ID,
    elementId: 'LLM_Call_1',
    elementName: 'Agent iteration 1',
    type: 'SUB_PROCESS',
    state: 'COMPLETED',
    hasIncident: false,
    flowScopeKey: MOCK_AGENT_SUBPROCESS_KEY,
    rootProcessInstanceKey: null,
    tenantId: '<default>',
    startDate: '2026-03-26T14:30:00.400Z',
    endDate: '2026-03-26T14:30:02.900Z',
    incidentKey: null,
  },
  // Tool: ListUsers — nested under LLM call 1
  {
    elementInstanceKey: '4451799813685020',
    processInstanceKey: MOCK_AGENT_INSTANCE_KEY,
    processDefinitionKey: MOCK_AGENT_DEFINITION_KEY,
    processDefinitionId: MOCK_AGENT_DEFINITION_ID,
    elementId: 'ListUsers',
    elementName: 'List users',
    type: 'SERVICE_TASK',
    state: 'COMPLETED',
    hasIncident: false,
    flowScopeKey: MOCK_AGENT_LLM_CALL_1_KEY,
    rootProcessInstanceKey: null,
    tenantId: '<default>',
    startDate: '2026-03-26T14:30:01.200Z',
    endDate: '2026-03-26T14:30:02.800Z',
    incidentKey: null,
  },
  // LLM iteration 2 — nested under AI Agent subprocess
  {
    elementInstanceKey: MOCK_AGENT_LLM_CALL_2_KEY,
    processInstanceKey: MOCK_AGENT_INSTANCE_KEY,
    processDefinitionKey: MOCK_AGENT_DEFINITION_KEY,
    processDefinitionId: MOCK_AGENT_DEFINITION_ID,
    elementId: 'LLM_Call_2',
    elementName: 'Agent iteration 2',
    type: 'SUB_PROCESS',
    state: 'COMPLETED',
    hasIncident: false,
    flowScopeKey: MOCK_AGENT_SUBPROCESS_KEY,
    rootProcessInstanceKey: null,
    tenantId: '<default>',
    startDate: '2026-03-26T14:30:02.950Z',
    endDate: '2026-03-26T14:30:04.150Z',
    incidentKey: null,
  },
  // Tool: LoadUserByID — nested under LLM call 2
  {
    elementInstanceKey: '4451799813685025',
    processInstanceKey: MOCK_AGENT_INSTANCE_KEY,
    processDefinitionKey: MOCK_AGENT_DEFINITION_KEY,
    processDefinitionId: MOCK_AGENT_DEFINITION_ID,
    elementId: 'LoadUserByID',
    elementName: 'Load user by ID',
    type: 'SERVICE_TASK',
    state: 'COMPLETED',
    hasIncident: false,
    flowScopeKey: MOCK_AGENT_LLM_CALL_2_KEY,
    rootProcessInstanceKey: null,
    tenantId: '<default>',
    startDate: '2026-03-26T14:30:03.000Z',
    endDate: '2026-03-26T14:30:04.100Z',
    incidentKey: null,
  },
  // Tool: GetDateAndTime — nested under LLM call 2
  {
    elementInstanceKey: '4451799813685030',
    processInstanceKey: MOCK_AGENT_INSTANCE_KEY,
    processDefinitionKey: MOCK_AGENT_DEFINITION_KEY,
    processDefinitionId: MOCK_AGENT_DEFINITION_ID,
    elementId: 'GetDateAndTime',
    elementName: 'Get Date and Time',
    type: 'SCRIPT_TASK',
    state: 'COMPLETED',
    hasIncident: false,
    flowScopeKey: MOCK_AGENT_LLM_CALL_2_KEY,
    rootProcessInstanceKey: null,
    tenantId: '<default>',
    startDate: '2026-03-26T14:30:03.050Z',
    endDate: '2026-03-26T14:30:04.150Z',
    incidentKey: null,
  },
  // LLM iteration 3 — nested under AI Agent subprocess
  {
    elementInstanceKey: MOCK_AGENT_LLM_CALL_3_KEY,
    processInstanceKey: MOCK_AGENT_INSTANCE_KEY,
    processDefinitionKey: MOCK_AGENT_DEFINITION_KEY,
    processDefinitionId: MOCK_AGENT_DEFINITION_ID,
    elementId: 'LLM_Call_3',
    elementName: 'Agent iteration 3',
    type: 'SUB_PROCESS',
    state: 'ACTIVE',
    hasIncident: false,
    flowScopeKey: MOCK_AGENT_SUBPROCESS_KEY,
    rootProcessInstanceKey: null,
    tenantId: '<default>',
    startDate: '2026-03-26T14:30:04.290Z',
    endDate: null,
    incidentKey: null,
  },
  // Tool: AskHumanToSendEmail — nested under LLM call 3
  {
    elementInstanceKey: '4451799813685035',
    processInstanceKey: MOCK_AGENT_INSTANCE_KEY,
    processDefinitionKey: MOCK_AGENT_DEFINITION_KEY,
    processDefinitionId: MOCK_AGENT_DEFINITION_ID,
    elementId: 'AskHumanToSendEmail',
    elementName: 'Ask human to send email',
    type: 'USER_TASK',
    state: 'ACTIVE',
    hasIncident: false,
    flowScopeKey: MOCK_AGENT_LLM_CALL_3_KEY,
    rootProcessInstanceKey: null,
    tenantId: '<default>',
    startDate: '2026-03-26T14:30:04.300Z',
    endDate: null,
    incidentKey: null,
  },
  {
    elementInstanceKey: '4451799813685040',
    processInstanceKey: MOCK_AGENT_INSTANCE_KEY,
    processDefinitionKey: MOCK_AGENT_DEFINITION_KEY,
    processDefinitionId: MOCK_AGENT_DEFINITION_ID,
    elementId: 'User_Feedback',
    elementName: 'User Feedback',
    type: 'USER_TASK',
    state: 'ACTIVE',
    hasIncident: false,
    flowScopeKey: MOCK_AGENT_INSTANCE_KEY,
    rootProcessInstanceKey: null,
    tenantId: '<default>',
    startDate: '2026-03-26T14:30:08.600Z',
    endDate: null,
    incidentKey: null,
  },
];

export const MOCK_AGENT_ELEMENT_STATISTICS = {
  items: [
    {
      elementId: 'StartEvent_1',
      active: 0,
      canceled: 0,
      incidents: 0,
      completed: 1,
    },
    {
      elementId: 'Gateway_0z6ctwk',
      active: 0,
      canceled: 0,
      incidents: 0,
      completed: 1,
    },
    {elementId: 'AI_Agent', active: 1, canceled: 0, incidents: 0, completed: 0},
    {
      elementId: 'LLM_Call_1',
      active: 0,
      canceled: 0,
      incidents: 0,
      completed: 1,
    },
    {
      elementId: 'LLM_Call_2',
      active: 0,
      canceled: 0,
      incidents: 0,
      completed: 1,
    },
    {
      elementId: 'LLM_Call_3',
      active: 1,
      canceled: 0,
      incidents: 0,
      completed: 0,
    },
    {
      elementId: 'ListUsers',
      active: 0,
      canceled: 0,
      incidents: 0,
      completed: 1,
    },
    {
      elementId: 'LoadUserByID',
      active: 0,
      canceled: 0,
      incidents: 0,
      completed: 1,
    },
    {
      elementId: 'GetDateAndTime',
      active: 0,
      canceled: 0,
      incidents: 0,
      completed: 1,
    },
    {
      elementId: 'AskHumanToSendEmail',
      active: 1,
      canceled: 0,
      incidents: 0,
      completed: 0,
    },
    {
      elementId: 'User_Feedback',
      active: 1,
      canceled: 0,
      incidents: 0,
      completed: 0,
    },
  ],
};

export const MOCK_AGENT_SEQUENCE_FLOWS = {
  items: [
    {processInstanceKey: MOCK_AGENT_INSTANCE_KEY, elementId: 'Flow_0pbzrme'},
    {processInstanceKey: MOCK_AGENT_INSTANCE_KEY, elementId: 'Flow_16otfp1'},
  ],
};

export const MOCK_AGENT_VARIABLES: Variable[] = [
  {
    variableKey: `${MOCK_AGENT_INSTANCE_KEY}-inputText`,
    name: 'inputText',
    value:
      '"Find the email address of user Leanne Graham and send her an invitation to the company offsite."',
    isTruncated: false,
    tenantId: '<default>',
    processInstanceKey: MOCK_AGENT_INSTANCE_KEY,
    scopeKey: MOCK_AGENT_INSTANCE_KEY,
    rootProcessInstanceKey: null,
  },
  {
    variableKey: `${MOCK_AGENT_INSTANCE_KEY}-inputDocuments`,
    name: 'inputDocuments',
    value: 'null',
    isTruncated: false,
    tenantId: '<default>',
    processInstanceKey: MOCK_AGENT_INSTANCE_KEY,
    scopeKey: MOCK_AGENT_INSTANCE_KEY,
    rootProcessInstanceKey: null,
  },
  {
    variableKey: `${MOCK_AGENT_SUBPROCESS_KEY}-agent`,
    name: 'agent',
    value: JSON.stringify({
      context: {
        state: 'WAITING_FOR_TOOL',
        metrics: {
          modelCalls: 3,
          tokenUsage: {
            inputTokenCount: 1959,
            outputTokenCount: 294,
          },
        },
        toolDefinitions: [
          {
            name: 'ListUsers',
            description:
              'Retrieves a list of all users from the user directory API',
            inputSchema: {type: 'object', properties: {}},
          },
          {
            name: 'LoadUserByID',
            description: 'Loads detailed user profile by numeric user ID',
            inputSchema: {
              required: ['id'],
              type: 'object',
              properties: {id: {type: 'number', description: 'The user ID'}},
            },
          },
          {
            name: 'GetDateAndTime',
            description: 'Returns the current date and time in ISO 8601 format',
            inputSchema: {type: 'object', properties: {}},
          },
          {
            name: 'AskHumanToSendEmail',
            description:
              'Requests a human operator to compose and send an email',
            inputSchema: {
              required: [
                'recipient_name',
                'recipient_email',
                'email_subject',
                'email_body',
              ],
              type: 'object',
              properties: {
                recipient_name: {type: 'string'},
                recipient_email: {type: 'string'},
                email_subject: {type: 'string'},
                email_body: {type: 'string'},
              },
            },
          },
          {
            name: 'FetchURL',
            description:
              'Fetches content from a given URL and returns the response body',
            inputSchema: {
              required: ['url'],
              type: 'object',
              properties: {
                url: {type: 'string', description: 'The URL to fetch'},
              },
            },
          },
        ],
      },
    }),
    isTruncated: true,
    tenantId: '<default>',
    processInstanceKey: MOCK_AGENT_INSTANCE_KEY,
    scopeKey: MOCK_AGENT_SUBPROCESS_KEY,
    rootProcessInstanceKey: null,
  },
  {
    variableKey: `${MOCK_AGENT_SUBPROCESS_KEY}-toolCallResults`,
    name: 'toolCallResults',
    value: JSON.stringify([
      {
        id: 'tooluse_ListUsers_abc123',
        name: 'ListUsers',
        content: {status: 'success'},
      },
      {
        id: 'tooluse_LoadUserByID_def456',
        name: 'LoadUserByID',
        content: {status: 'success'},
      },
      {
        id: 'tooluse_GetDateAndTime_ghi789',
        name: 'GetDateAndTime',
        content: {status: 'success'},
      },
    ]),
    isTruncated: true,
    tenantId: '<default>',
    processInstanceKey: MOCK_AGENT_INSTANCE_KEY,
    scopeKey: MOCK_AGENT_SUBPROCESS_KEY,
    rootProcessInstanceKey: null,
  },
];

export const MOCK_AGENT_JOBS: Job[] = [
  {
    jobKey: '4451799813685011',
    type: 'io.camunda.agenticai:aiagent-job-worker:1',
    worker: 'ai-agent-worker-1',
    state: 'CREATED',
    kind: 'BPMN_ELEMENT',
    listenerEventType: 'UNSPECIFIED',
    retries: 3,
    isDenied: null,
    deniedReason: null,
    hasFailedWithRetriesLeft: false,
    errorMessage: null,
    errorCode: null,
    customHeaders: {},
    deadline: null,
    endTime: null,
    processDefinitionId: MOCK_AGENT_DEFINITION_ID,
    processDefinitionKey: MOCK_AGENT_DEFINITION_KEY,
    processInstanceKey: MOCK_AGENT_INSTANCE_KEY,
    rootProcessInstanceKey: null,
    elementId: 'AI_Agent',
    elementInstanceKey: '4451799813685010',
    creationTime: '2026-03-26T14:30:00.300Z',
    lastUpdateTime: null,
    tags: [],
    tenantId: '<default>',
  },
];
