#!/bin/bash

set -e

# some JVM options to reduce JVM startup time, should be fine as the maven process is only shortliving
export MAVEN_OPTS="-client -XX:+TieredCompilation -XX:TieredStopAtLevel=1 -Xverify:none"

# run maven in offline mode, quiet (only errors) and with a thread per core
# specify checkstyle xml based on the multi module project root directory (requires maven 3.3.1+)
mvn -o -q -b incremental -T 1C com.mycila:license-maven-plugin:check com.coveo:fmt-maven-plugin:check org.apache.maven.plugins:maven-checkstyle-plugin:check -Dcheckstyle.config.location='${maven.multiModuleProjectDirectory}/build-tools/src/main/resources/check/.checkstyle.xml'
