/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(libs.org.agrona.agrona)
    api(project(":zeebe-msgpack-core"))
    api(project(":zeebe-util"))
    testImplementation(libs.junit.junit)
    testImplementation(libs.org.junit.jupiter.junit.jupiter.api)
    testImplementation(project(":zeebe-test-util"))
    testImplementation(libs.org.assertj.assertj.core)
    testImplementation(libs.org.mockito.mockito.core)
    testImplementation(libs.org.junit.jupiter.junit.jupiter.engine)
    testImplementation(libs.net.jqwik.jqwik.api)
}

description = "Zeebe Msgpack Value"
