/*
 * Copyright Camunda Services GmbH and/or licensed to Camunda Services GmbH under
 * one or more contributor license agreements. See the NOTICE file distributed
 * with this work for additional information regarding copyright ownership.
 * Licensed under the Camunda License 1.0. You may not use this file
 * except in compliance with the Camunda License 1.0.
 */
package io.camunda.zeebe.stream.api.records;

import com.fasterxml.jackson.annotation.JsonIgnore;
import io.camunda.zeebe.protocol.Protocol;
import io.camunda.zeebe.protocol.impl.encoding.AuthInfo;
import io.camunda.zeebe.protocol.impl.record.UnifiedRecordValue;
import io.camunda.zeebe.protocol.record.Record;
import io.camunda.zeebe.protocol.record.RecordMetadataDecoder;
import io.camunda.zeebe.protocol.record.RecordMetadataEncoder;
import io.camunda.zeebe.protocol.record.RecordType;

public interface TypedRecord<T extends UnifiedRecordValue> extends Record<T> {

  @Override
  long getKey();

  @Override
  T getValue();

  @JsonIgnore
  AuthInfo getAuthInfo();

  int getRequestStreamId();

  long getRequestId();

  int getLength();

  default boolean hasRequestMetadata() {
    return getRequestId() != RecordMetadataEncoder.requestIdNullValue()
        && getRequestStreamId() != RecordMetadataEncoder.requestStreamIdNullValue();
  }

  /**
   * Returns whether the record was distributed by a different partition. It can do so by decoding
   * the partition from the key and comparing it against the partition id of this record. If these
   * match the key was generated by the current partition. If not, the key was generated by a
   * different partition and then distributed to the current partition. Some commands will not have
   * a key, indicated by -1. This cannot occur when the command is distributed.
   *
   * @return a boolean indicating if the key was generated on the current partition
   */
  @JsonIgnore
  default boolean isCommandDistributed() {
    final boolean isCommand = RecordType.COMMAND == getRecordType();
    final long key = getKey();
    return isCommand && key != -1 && Protocol.decodePartitionId(key) != getPartitionId();
  }

  /**
   * Determines if the command is an internal command. Internal commands are commands that are
   * written by Zeebe itself and not by an external user.
   *
   * <p>A command is considered internal if it has no request metadata and no batch operation
   * reference.
   *
   * @return {@code true} if the command is an internal, {@code false} otherwise
   */
  @JsonIgnore
  default boolean isInternalCommand() {
    final boolean isCommand = RecordType.COMMAND == getRecordType();
    return isCommand
        && !hasRequestMetadata()
        && getBatchOperationReference() == RecordMetadataDecoder.batchOperationReferenceNullValue();
  }
}
