component/optimize:
  '(Optimize*)'
component/zeebe:
  '(Zeebe*)'
component/operate:
  '(Operate*)'
component/tasklist:
  '(Tasklist*)'
component/identity:
  '(Identity*)'
component/C8Run:
  '(C8Run*)'
needs component label:
  '(Not sure*)'
