{{/*
This template uses the Helm's "derivePassword" function to generate random password.

The "derivePassword" function generates predictable output, based on the content of its inputs: for
the same inputs, the same password will be generated.

This is not a very secure way to generate passwords ; however, for the purpose of the load tests, this is enough.
*/}}
apiVersion: v1
kind: Secret
metadata:
  name: camunda-credentials
type: Opaque
stringData:
{{- $keys := list
      "connectors-security-authentication-oidc-secret"
      "identity-admin-client-token"
      "identity-firstuser-password"
      "identity-keycloak-admin-password"
      "identity-keycloak-postgresql-admin-password"
      "identity-keycloak-postgresql-user-password"
      "identity-optimize-client-token"
      "identity-optimize-loadtest-client-secret"
      "identity-postgresql-admin-password"
      "identity-postgresql-user-password"
      (include "oc-secret-name" .)
-}}
{{- range $key := $keys }}
{{- $secretName := dict
            "namespace" $.Release.Namespace
            "user" $key
}}
  {{ printf "%s: \"%s\"" $key (include "generate-secret" $secretName) -}}
{{- end -}}
