{{- if eq .Values.leaderBalancer.endpoint "v2" }}
apiVersion: v1
kind: Secret
metadata:
  name: leader-balancer-credentials
type: Opaque
stringData:
  {{- $authServer := include "load-test-setup.load-test.client.auth-server-url" . }}
  {{- with .Values.leaderBalancer.client.oidc }}
  clientId: "{{ .clientId }}"
  # Same password as the one we are configuring through Keycloak in
  # "camunda-credentials.yaml" for: "{{ .secret.key }}"
  {{- $secretName := dict
            "namespace" $.Release.Namespace
            "user" .secret.key
  }}
  clientSecret: "{{ include "generate-secret" $secretName }}"
  {{ end -}}
  # Non-secret connection settings, reused from the load-test client's configuration.
  zeebeRestAddress: "{{ .Values.loadTest.client.oidc.zeebeRestAddress }}"
  authServer: "{{ $authServer }}"
  authorizationAudience: "{{ .Values.loadTest.client.oidc.authorizationAudience }}"
{{- end }}
