apiVersion: v1
kind: Secret
metadata:
  name: load-test-credentials
type: Opaque
stringData:
  {{- $authServer := include "load-test-setup.load-test.client.auth-server-url" . }}
  {{- with .Values.loadTest.client.oidc }}
  clientId: "{{ .clientId }}"
  # Same password as the one we are configuring through Keycloak in
  # "camunda-credentials.yaml" for: "{{ .secret.key }}"
  {{- $secretName := dict
            "namespace" $.Release.Namespace
            "user" .secret.key
  }}
  clientSecret: "{{ include "generate-secret" $secretName }}"
  zeebeRestAddress: "{{ .zeebeRestAddress }}"
  authServer: "{{ $authServer }}"
  authType: OAUTH
  zeebeGrpcAddress: "{{ .zeebeGrpcAddress }}"
  authorizationAudience: "{{ .authorizationAudience }}"
  {{ end -}}
