@startuml
[archiver] as archiver
[client] as client
[common] as common
[data-generator] as datagenerator
[distro] as distro
[els-schema] as elsschema
[importer-<verison>] as importer
[importer-common] as importercommon
[webapp] as webapp

package "QA" as qa {
  [batch-operation-performance-tests] as batch
  [data-generator] as datatests
  [import-old-zeebe-tests] as oldtests
  [import-performance-tests] as performance
  [integration-tests] as it
  [migration-performance-test] as migrationperf
  [migration-tests] as migration
  [query-performance-tests] as query
  [util] as util
}


archiver -- client
client -- common
common -- datagenerator
datagenerator -- distro
distro -- elsschema
elsschema -- importer
importer -- importercommon
importercommon -- webapp
webapp -- qa

note right of archiver: Archiver is the module responsible\nfor archiving completed processes\n instances
note right of client: Client is the module where the front-end\ncode lives in. After build/compile\nthis is packed inside webapp
note right of common: All the common code shared accross modules
note right of datagenerator: Module to generate testing data.\nUsed with dev-data profile
note right of elsschema: Module that contains all the\nschema for elastic. Definition\nof indexes/templates, entities, etc
note right of importer: Importer contains the logic to\nimport zeebe data (of a specific version)\ninto operate
note right of importercommon: Shared code among importer versions
note right of qa: QA module containing tests\n(mostly integration)
note right of webapp: The module of the actual webapp.\nContains most of the backend/controller logic
@enduml
