/*
 * This file was generated by the Gradle 'init' task.
 */

import org.gradle.api.artifacts.VersionCatalogsExtension

plugins {
    id("buildlogic.server-conventions")
}

val versionCatalog = extensions.getByType<VersionCatalogsExtension>().named("libs")

dependencies {
    implementation(project(":zeebe-exporter-api"))
    implementation(project(":zeebe-protocol"))
    implementation(project(":zeebe-util"))
    implementation(libs.com.fasterxml.jackson.core.jackson.annotations)
    implementation(libs.com.fasterxml.jackson.core.jackson.core)
    implementation(libs.com.fasterxml.jackson.core.jackson.databind)
    implementation(libs.org.jspecify.jspecify)
    implementation(libs.org.slf4j.slf4j.api)
    implementation(versionCatalog.findLibrary("io-opentelemetry-opentelemetry-api").get())
    implementation(versionCatalog.findLibrary("io-opentelemetry-opentelemetry-sdk").get())
    implementation(versionCatalog.findLibrary("io-opentelemetry-opentelemetry-sdk-common").get())
    implementation(versionCatalog.findLibrary("io-opentelemetry-opentelemetry-sdk-logs").get())
    implementation(versionCatalog.findLibrary("io-opentelemetry-opentelemetry-exporter-otlp").get()) {
        exclude(group = "io.opentelemetry", module = "opentelemetry-exporter-sender-okhttp")
    }
    runtimeOnly(versionCatalog.findLibrary("io-opentelemetry-opentelemetry-exporter-sender-jdk").get())

    testImplementation(project(":zeebe-exporter-test"))
    testImplementation(project(":zeebe-protocol-test-util"))
    testImplementation(versionCatalog.findLibrary("io-opentelemetry-opentelemetry-sdk-testing").get())
    testImplementation(libs.org.testcontainers.testcontainers)
    testImplementation(libs.org.testcontainers.testcontainers.junit.jupiter)
    testImplementation(libs.org.awaitility.awaitility)
    testImplementation(libs.org.mockito.mockito.core)
    testImplementation(versionCatalog.findLibrary("org-openjdk-jmh-jmh-core").get())
    testAnnotationProcessor(versionCatalog.findLibrary("org-openjdk-jmh-jmh-generator-annprocess").get())
}

description = "Camunda Analytics Exporter"
