/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    implementation(project(":zeebe-protocol"))
    implementation(project(":camunda-security-protocol"))
    implementation(libs.org.assertj.assertj.core)
    implementation(libs.javax.annotation.javax.annotation.api)
}

description = "Zeebe Protocol AssertJ Assertions"
