/*
 * This file was generated by the Gradle 'init' task.
 */

buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath(libs.org.assertj.assertj.assertions.generator)
    }
}

import com.google.common.reflect.TypeToken
import org.assertj.assertions.generator.AssertionsEntryPointType
import org.assertj.assertions.generator.BaseAssertionGenerator
import org.assertj.assertions.generator.description.converter.ClassToClassDescriptionConverter
import org.gradle.api.DefaultTask
import org.gradle.api.file.ConfigurableFileCollection
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.file.DuplicatesStrategy
import org.gradle.api.file.FileSystemOperations
import org.gradle.api.tasks.CacheableTask
import org.gradle.api.tasks.Classpath
import org.gradle.api.tasks.OutputDirectory
import org.gradle.api.tasks.TaskAction
import org.gradle.api.tasks.bundling.Jar
import org.gradle.api.tasks.compile.JavaCompile
import java.lang.reflect.Modifier
import java.net.URLClassLoader
import javax.inject.Inject

plugins {
    id("buildlogic.server-conventions")
}

@CacheableTask
abstract class GenerateAssertjAssertionsTask : DefaultTask() {
    @get:Classpath
    abstract val classDirs: ConfigurableFileCollection

    @get:Classpath
    abstract val classpath: ConfigurableFileCollection

    @get:OutputDirectory
    abstract val outputDir: DirectoryProperty

    @get:Inject
    abstract val fs: FileSystemOperations

    @TaskAction
    fun generate() {
        val outDir = outputDir.get().asFile
        fs.delete { delete(outDir) }
        outDir.mkdirs()

        val classDirFiles = classDirs.files
        val cp = classpath.files + classDirFiles
        val loader = URLClassLoader(
            cp.map { it.toURI().toURL() }.toTypedArray(),
            javaClass.classLoader,
        )

        try {
            val classNames = classDirFiles.flatMap { dir ->
                dir.walkTopDown()
                    .filter { it.isFile && it.extension == "class" }
                    .map { file ->
                        file.relativeTo(dir).invariantSeparatorsPath
                            .removeSuffix(".class")
                            .replace('/', '.')
                    }
                    .toList()
            }.toSet()
                .filter { it.startsWith("io.camunda.zeebe.protocol.record") }
                .filterNot {
                    it.endsWith(".package-info") ||
                        it.contains(".Immutable") ||
                        it.endsWith("Assert") ||
                        it.endsWith("Assertions")
                }

            val types = classNames
                .map { loader.loadClass(it) }
                .filterNot { it.simpleName == "package-info" }
                .filterNot { it.isSynthetic }
                .filterNot { Modifier.isPrivate(it.modifiers) }
                .map { TypeToken.of(it) }
                .toSet()
            val converter = ClassToClassDescriptionConverter()
            val generator = BaseAssertionGenerator()
            generator.setDirectoryWhereAssertionFilesAreGenerated(outDir)

            val descriptions = types.map { type ->
                val description = converter.convertToClassDescription(type)
                generator.generateCustomAssertionFor(description)
                description
            }.toSet()

            generator.generateAssertionsEntryPointClassFor(
                descriptions,
                AssertionsEntryPointType.STANDARD,
                null,
            )
            generator.generateAssertionsEntryPointClassFor(
                descriptions,
                AssertionsEntryPointType.SOFT,
                null,
            )
        } finally {
            loader.close()
        }
    }
}

val assertjGeneratedDir = layout.buildDirectory.dir("generated-sources/assertj-assertions")
val patchedAssertjGeneratedDir =
    layout.buildDirectory.dir("generated-sources/assertj-assertions-patched")
val generatedAssertjClassesDir = layout.buildDirectory.dir("generated-classes/assertj")

val protocolClassDirectories =
  configurations.create("protocolClassDirectories") {
    isCanBeConsumed = false
    isCanBeResolved = true
    isTransitive = false
  }
val protocolCompileClasspath = configurations.compileClasspath

val generateAssertjAssertions =
  tasks.register<GenerateAssertjAssertionsTask>("generateAssertjAssertions") {
    group = "code generation"
    description = "Generate AssertJ assertions for Zeebe protocol record types"

    classDirs.from(protocolClassDirectories)
    classpath.from(protocolCompileClasspath)
    outputDir.set(assertjGeneratedDir)
}

// Copy the generated assertions into a separate directory, patching the invalid Record<T>
// generics on the way. The generator therefore keeps exclusive ownership of its own output, which
// keeps it cacheable and up-to-date. `Sync` empties the destination before copying.
val patchRecordAssert = tasks.register<Sync>("patchRecordAssert") {
    group = "code generation"
    description = "Copy generated AssertJ assertions, patching RecordAssert generic types"
    dependsOn(generateAssertjAssertions)

    from(assertjGeneratedDir)
    into(patchedAssertjGeneratedDir)
    filesMatching("**/RecordAssert.java") {
        filter { line: String ->
            line
                .replace("T value", "RecordValue value")
                .replace("T actualValue", "RecordValue actualValue")
        }
    }
}

dependencies {
    add(
        protocolClassDirectories.name,
        project(":zeebe-protocol", configuration = "mainClasses"),
    )
    add(
        protocolClassDirectories.name,
        project(":camunda-security-protocol", configuration = "mainClasses"),
    )
    implementation(project(":zeebe-protocol"))
    implementation(project(":camunda-security-protocol"))
    implementation(libs.org.assertj.assertj.core)
    implementation(libs.javax.annotation.javax.annotation.api)
}

val compileGeneratedAssertjJava =
  tasks.register<JavaCompile>("compileGeneratedAssertjJava") {
    dependsOn(patchRecordAssert)
    source(patchedAssertjGeneratedDir)
    classpath = files(sourceSets["main"].compileClasspath, protocolClassDirectories)
    destinationDirectory.set(generatedAssertjClassesDir)
    options.encoding = "utf-8"
}

sourceSets.named("main") {
    output.dir(mapOf("builtBy" to compileGeneratedAssertjJava), generatedAssertjClassesDir)
}

tasks.named("classes") {
    dependsOn(compileGeneratedAssertjJava)
}

tasks.named<Jar>("jar") {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

val generatedAssertions = configurations.create("generatedAssertions") {
    isCanBeConsumed = true
    isCanBeResolved = false
}

artifacts {
    add("generatedAssertions", generatedAssertjClassesDir) {
        builtBy(compileGeneratedAssertjJava)
    }
}

description = "Zeebe Protocol AssertJ Assertions"
