/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(project(":camunda-security-core"))
    api(project(":camunda-security-protocol"))
    api(project(":camunda-search-domain"))
    api(project(":camunda-search-client-reader"))
    testImplementation(project(":zeebe-auth"))
    testImplementation(project(":zeebe-protocol"))
    testImplementation(libs.org.junit.jupiter.junit.jupiter.api)
    testImplementation(libs.org.junit.jupiter.junit.jupiter.params)
    testImplementation(libs.org.assertj.assertj.core)
}

description = "Camunda Security Services"
