/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(libs.junit.junit)
    api(libs.org.slf4j.slf4j.api)
    api(libs.org.apache.maven.surefire.surefire.myextensions.api)
    api(libs.org.apache.maven.surefire.maven.surefire.common)
}

description = "Zeebe Build Tools"
