{
 "title": "Elasticsearch",
 "tags": [
  "elastic",
  "as code"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(elasticsearch_cluster_health_status,cluster)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(atomix_role,namespace)"
    }
   },
   {
    "name": "index",
    "query": {
     "query": "label_values(elasticsearch_indices_store_size_bytes_total{cluster=~\"$cluster\", namespace=~\"$namespace\"}, index)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Not maintained",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<center>\n\n⚠️ **This dashboard is not maintained anymore.** Use the dashboards in the [camunda-observability](https://github.com/camunda/camunda-observability) repository instead.\n\n</center>"
   }
  },
  { "title": "Cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Cluster Health Status History",
   "type": "status-history",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "scalar(elasticsearch_cluster_health_status{color=\"green\",cluster=~\"$cluster\",namespace=~\"$namespace\"})\n+ scalar(elasticsearch_cluster_health_status{color=\"yellow\",cluster=~\"$cluster\",namespace=~\"$namespace\"}) * 2\n+ scalar(elasticsearch_cluster_health_status{color=\"red\",cluster=~\"$cluster\",namespace=~\"$namespace\"}) * 3",
     "legendFormat": "Health"
    }
   ]
  },
  {
   "title": "Current Cluster Health Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scalar(elasticsearch_cluster_health_status{color=\"green\",cluster=~\"$cluster\",namespace=~\"$namespace\"})\n+ scalar(elasticsearch_cluster_health_status{color=\"yellow\",cluster=~\"$cluster\",namespace=~\"$namespace\"}) * 2\n+ scalar(elasticsearch_cluster_health_status{color=\"red\",cluster=~\"$cluster\",namespace=~\"$namespace\"}) * 3",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Running Nodes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(elasticsearch_cluster_health_number_of_nodes{cluster=~\"$cluster\",namespace=~\"$namespace\"})/count(elasticsearch_cluster_health_number_of_nodes{cluster=~\"$cluster\",namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Active Data Nodes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "quantile(0.99, elasticsearch_cluster_health_number_of_data_nodes{cluster=~\"$cluster\",namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Pending Tasks",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "quantile(0.99, elasticsearch_cluster_health_number_of_pending_tasks{cluster=~\"$cluster\",namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Shards",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Active Shards",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 90 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "quantile(0.99, elasticsearch_cluster_health_active_shards{cluster=~\"$cluster\",namespace=~\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Active Primary Shards",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 4, "y": 90 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "quantile(0.99, elasticsearch_cluster_health_active_primary_shards{cluster=~\"$cluster\",namespace=~\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Initializing Shards",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 8, "y": 90 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "quantile(0.99, elasticsearch_cluster_health_initializing_shards{cluster=~\"$cluster\",namespace=~\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Relocating Shards",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 12, "y": 90 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "quantile(0.99, elasticsearch_cluster_health_relocating_shards{cluster=~\"$cluster\",namespace=~\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Unassigned Shards",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 16, "y": 90 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "quantile(0.99, elasticsearch_cluster_health_unassigned_shards{cluster=~\"$cluster\",namespace=~\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Delayed Unassigned Shards",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 20, "y": 90 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "quantile(0.99, elasticsearch_cluster_health_delayed_unassigned_shards{cluster=~\"$cluster\",namespace=~\"$namespace\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "Documents",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Documents indexed",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 131 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg(elasticsearch_indices_docs{cluster=~\"$cluster\",namespace=~\"$namespace\"})",
       "legendFormat": "Documents"
      }
     ]
    },
    {
     "title": "Index Size",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 131 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "avg(elasticsearch_indices_store_size_bytes{cluster=~\"$cluster\",namespace=~\"$namespace\"})",
       "legendFormat": "Index Size"
      }
     ]
    },
    {
     "title": "Documents Indexed Rate",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 151 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "avg(rate(elasticsearch_indices_indexing_index_total{cluster=~\"$cluster\",namespace=~\"$namespace\"}[1h]))",
       "legendFormat": "Indexing rate"
      }
     ]
    },
    {
     "title": "Search Rate",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 151 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "avg(rate(elasticsearch_indices_search_fetch_total{cluster=~\"$cluster\",namespace=~\"$namespace\"}[1h]))",
       "legendFormat": "Search rate"
      }
     ]
    },
    {
     "title": "Queue Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 160 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg(elasticsearch_thread_pool_queue_count{cluster=~\"$cluster\",namespace=~\"$namespace\", type!=\"management\"}) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Tripped circuit breakers",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 160 },
     "fieldConfig": { "defaults": { "unit": "tripped/s" } },
     "targets": [
      {
       "expr": "avg(rate(elasticsearch_breakers_tripped{cluster=~\"$cluster\", namespace=~\"$namespace\"}[$__rate_interval])) by (breaker)",
       "legendFormat": "{{ breaker }}"
      }
     ]
    }
   ]
  },
  {
   "title": "System",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "bucketAggs": [
        { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "expr": "avg(avg_over_time(irate(elasticsearch_process_cpu_seconds_total{cluster=~\"$cluster\",namespace=~\"$namespace\"}[3m])[15m:2m])) by (type)",
       "legendFormat": "CPU Usage"
      }
     ]
    },
    {
     "title": "Total heap memory",
     "type": "stat",
     "gridPos": { "h": 9, "w": 3, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(elasticsearch_jvm_memory_max_bytes{area=\"heap\",cluster=~\"$cluster\",namespace=~\"$namespace\"})",
       "legendFormat": "Heap size"
      }
     ]
    },
    {
     "title": "Available heap used",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 10, "x": 3, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "avg(avg_over_time(elasticsearch_jvm_memory_used_bytes{area=\"heap\",cluster=~\"$cluster\",namespace=~\"$namespace\"}[15m]) / elasticsearch_jvm_memory_max_bytes{area=\"heap\",cluster=~\"$cluster\",namespace=~\"$namespace\"})",
       "legendFormat": "Percentage of heap used"
      }
     ]
    },
    {
     "title": "GC duration",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 11, "x": 13, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(irate(elasticsearch_jvm_gc_collection_seconds_sum{cluster=~\"$cluster\",namespace=~\"$namespace\"}[1m])) by (gc)",
       "legendFormat": "{{ gc }}"
      }
     ]
    },
    {
     "title": "Thread Pools",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg(elasticsearch_thread_pool_active_count{cluster=~\"$cluster\",namespace=~\"$namespace\", type!=\"management\"}) by (type)",
       "legendFormat": "{{ type }}"
      }
     ]
    },
    {
     "title": "Thread pool rejections",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg(rate(elasticsearch_thread_pool_rejected_count{cluster=~\"$cluster\",namespace=~\"$namespace\", type!=\"management\"}[$__rate_interval]))",
       "legendFormat": "{{ name }} {{ type }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Cluster Activity",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Activity by indices",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 308 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "avg by (index) (\n  rate(elasticsearch_index_stats_refresh_total{cluster=~\"$cluster\",namespace=~\"$namespace\", index=~\"${index:raw}\"}[$__rate_interval]) +\n  rate(elasticsearch_index_stats_merge_total{cluster=~\"$cluster\",namespace=~\"$namespace\", index=~\"${index:raw}\"}[$__rate_interval]) +\n  rate(elasticsearch_index_stats_indexing_index_total{cluster=~\"$cluster\",namespace=~\"$namespace\", index=~\"${index:raw}\"}[$__rate_interval]) +\n  rate(elasticsearch_index_stats_indexing_delete_total{cluster=~\"$cluster\",namespace=~\"$namespace\", index=~\"${index:raw}\"}[$__rate_interval]) +\n  rate(elasticsearch_index_stats_flush_total{cluster=~\"$cluster\",namespace=~\"$namespace\", index=~\"${index:raw}\"}[$__rate_interval]) +\n  rate(elasticsearch_index_stats_get_total{cluster=~\"$cluster\",namespace=~\"$namespace\", index=~\"${index:raw}\"}[$__rate_interval]) +\n  rate(elasticsearch_index_stats_search_fetch_total{cluster=~\"$cluster\",namespace=~\"$namespace\", index=~\"${index:raw}\"}[$__rate_interval]) +\n  rate(elasticsearch_index_stats_search_query_total{cluster=~\"$cluster\",namespace=~\"$namespace\", index=~\"${index:raw}\"}[$__rate_interval]) +\n  rate(elasticsearch_index_stats_search_scroll_total{cluster=~\"$cluster\",namespace=~\"$namespace\", index=~\"${index:raw}\"}[$__rate_interval]) +\n  rate(elasticsearch_index_stats_search_suggest_total{cluster=~\"$cluster\",namespace=~\"$namespace\", index=~\"${index:raw}\"}[$__rate_interval])\n)",
       "legendFormat": "{{ index }}"
      }
     ]
    },
    {
     "title": "Activity by operations",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 316 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "avg(rate(elasticsearch_index_stats_refresh_total{cluster=~\"$cluster\",namespace=~\"$namespace\", index=~\"${index:raw}\"}[$__rate_interval]))",
       "legendFormat": "refresh"
      },
      {
       "expr": "avg(rate(elasticsearch_index_stats_merge_total{cluster=~\"$cluster\",namespace=~\"$namespace\", index=~\"${index:raw}\"}[$__rate_interval]))",
       "legendFormat": "merge"
      },
      {
       "expr": "avg(rate(elasticsearch_index_stats_indexing_index_total{cluster=~\"$cluster\",namespace=~\"$namespace\", index=~\"${index:raw}\"}[$__rate_interval]))",
       "legendFormat": "indexing: {{index}}"
      },
      {
       "expr": "avg(rate(elasticsearch_index_stats_indexing_delete_total{cluster=~\"$cluster\",namespace=~\"$namespace\", index=~\"${index:raw}\"}[$__rate_interval]))",
       "legendFormat": "delete"
      },
      {
       "expr": "avg(rate(elasticsearch_index_stats_flush_total{cluster=~\"$cluster\",namespace=~\"$namespace\", index=~\"${index:raw}\"}[$__rate_interval]))",
       "legendFormat": "flush"
      },
      {
       "expr": "avg(rate(elasticsearch_index_stats_get_total{cluster=~\"$cluster\",namespace=~\"$namespace\", index=~\"${index:raw}\"}[$__rate_interval]))",
       "legendFormat": "get"
      },
      {
       "expr": "avg(rate(elasticsearch_index_stats_search_fetch_total{cluster=~\"$cluster\",namespace=~\"$namespace\", index=~\"${index:raw}\"}[$__rate_interval]))",
       "legendFormat": "search fetch"
      },
      {
       "expr": "avg(rate(elasticsearch_index_stats_search_query_total{cluster=~\"$cluster\",namespace=~\"$namespace\", index=~\"${index:raw}\"}[$__rate_interval]))",
       "legendFormat": "search query"
      },
      {
       "expr": "avg(rate(elasticsearch_index_stats_search_scroll_total{cluster=~\"$cluster\",namespace=~\"$namespace\", index=~\"${index:raw}\"}[$__rate_interval]))",
       "legendFormat": "search scroll"
      },
      {
       "expr": "avg(rate(elasticsearch_index_stats_search_suggest_total{cluster=~\"$cluster\",namespace=~\"$namespace\", index=~\"${index:raw}\"}[$__rate_interval]))",
       "legendFormat": "search suggest"
      }
     ]
    }
   ]
  },
  {
   "title": "Indices",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Store Size (primary shards)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 91 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "max(elasticsearch_indices_store_size_bytes_primary{namespace=~\"$namespace\", index=~\"${index:raw}\"}) by (index)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "# of documents",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 91 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg(elasticsearch_indices_docs_total{namespace=~\"$namespace\", index=~\"${index:raw}\"}) by (index)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "refresh",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 99 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "avg(rate(elasticsearch_index_stats_refresh_total{cluster=~\"$cluster\",namespace=~\"$namespace\", index=~\"${index:raw}\"}[$__rate_interval])) by (index)",
       "legendFormat": "{{index}}"
      }
     ]
    },
    {
     "title": "merge",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 99 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "avg(rate(elasticsearch_index_stats_merge_total{cluster=~\"$cluster\",namespace=~\"$namespace\", index=~\"${index:raw}\"}[$__rate_interval])) by (index)",
       "legendFormat": "{{index}}"
      }
     ]
    },
    {
     "title": "indexing",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 99 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "avg(rate(elasticsearch_index_stats_indexing_index_total{cluster=~\"$cluster\",namespace=~\"$namespace\", index=~\"${index:raw}\"}[$__rate_interval])) by (index)",
       "legendFormat": "{{index}}"
      }
     ]
    },
    {
     "title": "delete",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 99 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "avg(rate(elasticsearch_index_stats_indexing_delete_total{cluster=~\"$cluster\",namespace=~\"$namespace\", index=~\"${index:raw}\"}[$__rate_interval])) by (index)",
       "legendFormat": "{{index}}"
      }
     ]
    },
    {
     "title": "flush",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 106 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "avg(rate(elasticsearch_index_stats_flush_total{cluster=~\"$cluster\",namespace=~\"$namespace\", index=~\"${index:raw}\"}[$__rate_interval])) by (index)",
       "legendFormat": "{{index}}"
      }
     ]
    },
    {
     "title": "get",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 106 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "avg(rate(elasticsearch_index_stats_get_total{cluster=~\"$cluster\",namespace=~\"$namespace\", index=~\"${index:raw}\"}[$__rate_interval])) by (index)",
       "legendFormat": "{{index}}"
      }
     ]
    },
    {
     "title": "search fetch",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 113 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "avg(rate(elasticsearch_index_stats_search_fetch_total{cluster=~\"$cluster\",namespace=~\"$namespace\", index=~\"${index:raw}\"}[$__rate_interval])) by (index)",
       "legendFormat": "{{index}}"
      }
     ]
    },
    {
     "title": "search query",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 113 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "avg(rate(elasticsearch_index_stats_search_query_total{cluster=~\"$cluster\",namespace=~\"$namespace\", index=~\"${index:raw}\"}[$__rate_interval])) by (index)",
       "legendFormat": "{{index}}"
      }
     ]
    },
    {
     "title": "search scroll",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 113 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "avg(rate(elasticsearch_index_stats_search_scroll_total{cluster=~\"$cluster\",namespace=~\"$namespace\", index=~\"${index:raw}\"}[$__rate_interval])) by (index)",
       "legendFormat": "{{index}}"
      }
     ]
    },
    {
     "title": "search suggest",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 113 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "avg(rate(elasticsearch_index_stats_search_suggest_total{cluster=~\"$cluster\",namespace=~\"$namespace\", index=~\"${index:raw}\"}[$__rate_interval])) by (index)",
       "legendFormat": "{{index}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Indices Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Elastichsearch Indices",
     "type": "table",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 132 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "max(elasticsearch_indices_store_size_bytes_primary{namespace=~\"$namespace\", index=~\"${index:raw}\"}) by (index)",
       "legendFormat": "{{index}}"
      }
     ]
    }
   ]
  }
 ]
}