/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(project(":zeebe-protocol"))
    api(project(":zeebe-msgpack-core"))
    api(project(":zeebe-msgpack-value"))
    api(project(":zeebe-util"))
    api(project(":camunda-security-protocol"))
    api(libs.org.agrona.agrona)
    implementation(libs.org.slf4j.slf4j.api)
    api(libs.com.fasterxml.jackson.core.jackson.databind)
    api(libs.com.fasterxml.jackson.core.jackson.annotations)
    api(libs.com.fasterxml.jackson.core.jackson.core)
    api(libs.org.msgpack.jackson.dataformat.msgpack)
    api(libs.com.fasterxml.jackson.datatype.jackson.datatype.jsr310)
    api(project(":zeebe-auth"))
    testImplementation(project(":zeebe-test-util"))
    testImplementation(libs.org.junit.jupiter.junit.jupiter.engine)
    testImplementation(libs.org.junit.jupiter.junit.jupiter.api)
    testImplementation(libs.org.junit.jupiter.junit.jupiter.params)
    testImplementation(libs.org.assertj.assertj.core)
}

description = "Zeebe Protocol Implementation"
