/*
 * Copyright Camunda Services GmbH and/or licensed to Camunda Services GmbH under
 * one or more contributor license agreements. See the NOTICE file distributed
 * with this work for additional information regarding copyright ownership.
 * Licensed under the Zeebe Community License 1.1. You may not use this file
 * except in compliance with the Zeebe Community License 1.1.
 */
package io.camunda.zeebe.topology.changes;

import io.camunda.zeebe.scheduler.future.ActorFuture;
import io.camunda.zeebe.topology.state.ClusterTopology;
import io.camunda.zeebe.topology.state.TopologyChangeOperation;
import io.camunda.zeebe.util.Either;
import java.util.List;

public interface TopologyChangeCoordinator {

  /**
   * Applies the given operations to the current cluster topology. The operations are applied
   * asynchronously. The future is completed when the topology change has started successfully, but
   * before completing. To query the status of the topology change, use {@link #hasCompletedChanges}
   * with the version of the returned ClusterTopology.
   *
   * <pre>
   *  final ActorFuture<ClusterTopology> topologyWithPendingChanges =
   *         coordinator.applyOperations(operations).join();
   *  final var topologyChangeIsCompleted =
   *         coordinator.hasCompletedChanges(topologyWithPendingChanges.version()).join();
   * </pre>
   *
   * @param operations the operations to apply
   * @return a future which is completed with the intermediate topology with pending operations
   */
  ActorFuture<ClusterTopology> applyOperations(List<TopologyChangeOperation> operations);

  /**
   * @param version version of the ClusterTopology returned by {@link #applyOperations(List)}
   * @return a future that completes with true if the topology change has completed, false otherwise
   */
  ActorFuture<Boolean> hasCompletedChanges(final long version);

  ActorFuture<ClusterTopology> getCurrentTopology();

  /**
   * Applies the operations generated by the requestTransformer to the current cluster topology. If
   * no operations is returned by requestTransformer, the future completes successfully with no
   * change to the cluster topology.
   *
   * @param requestTransformer the request transformer that generates the operations to apply
   * @return a future which is completed when the topology change has started successfully.
   */
  ActorFuture<TopologyChangeResult> applyOperations(TopologyChangeRequest requestTransformer);

  record TopologyChangeResult(
      ClusterTopology currentTopology,
      ClusterTopology finalTopology,
      List<TopologyChangeOperation> operations) {}

  @FunctionalInterface
  interface TopologyChangeRequest {

    /**
     * Returns a list of operations to apply to the current topology. The operations will be applied
     * in the given order in the list.
     *
     * @param currentTopology the current cluster topology
     * @return an Either with the list of operations to apply or an exception if the request is not
     *     valid.
     */
    Either<Exception, List<TopologyChangeOperation>> operations(
        final ClusterTopology currentTopology);
  }
}
