namespace ?= __NAMESPACE__
secondary_storage ?= __STORAGE_TYPE__
enable_optimize ?= __ENABLE_OPTIMIZE__

# Overrides from common defaults:
# - physical tenants are not supported for this version.
physical_tenants_rdbms_values_file =

include ../common.mk
