/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(project(":zeebe-util"))
    api(project(":zeebe-msgpack-core"))
    api(libs.org.camunda.feel.feel.engine)
    api(project(":zeebe-feel-tagged-parameters"))
    api(libs.org.scala.lang.scala.library)
    api(libs.org.agrona.agrona)
    api(libs.org.slf4j.slf4j.api)
}

description = "Zeebe FEEL Integration"
