/*
 * Orchestration Cluster REST API
 * API for communicating with a Camunda 8 cluster.
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.camunda.client.protocol.rest;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.camunda.client.protocol.rest.AdHocSubProcessActivateActivityReference;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.io.UnsupportedEncodingException;
import java.net.URLEncoder;
import java.util.StringJoiner;

/**
 * AdHocSubProcessActivateActivitiesInstruction
 */
@JsonPropertyOrder({
  AdHocSubProcessActivateActivitiesInstruction.JSON_PROPERTY_ELEMENTS
})
@com.fasterxml.jackson.annotation.JsonInclude(com.fasterxml.jackson.annotation.JsonInclude.Include.NON_NULL)
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-07-24T12:02:12.602366536Z[Etc/UTC]", comments = "Generator version: 7.12.0")
public class AdHocSubProcessActivateActivitiesInstruction {
  public static final String JSON_PROPERTY_ELEMENTS = "elements";
  @javax.annotation.Nonnull
  private List<AdHocSubProcessActivateActivityReference> elements = new ArrayList<>();

  public AdHocSubProcessActivateActivitiesInstruction() {
  }

  public AdHocSubProcessActivateActivitiesInstruction elements(@javax.annotation.Nonnull List<AdHocSubProcessActivateActivityReference> elements) {
    
    this.elements = elements;
    return this;
  }

  public AdHocSubProcessActivateActivitiesInstruction addElementsItem(AdHocSubProcessActivateActivityReference elementsItem) {
    if (this.elements == null) {
      this.elements = new ArrayList<>();
    }
    this.elements.add(elementsItem);
    return this;
  }

  /**
   * Activities to activate.
   * @return elements
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ELEMENTS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<AdHocSubProcessActivateActivityReference> getElements() {
    return elements;
  }


  @JsonProperty(JSON_PROPERTY_ELEMENTS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setElements(@javax.annotation.Nonnull List<AdHocSubProcessActivateActivityReference> elements) {
    this.elements = elements;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AdHocSubProcessActivateActivitiesInstruction adHocSubProcessActivateActivitiesInstruction = (AdHocSubProcessActivateActivitiesInstruction) o;
    return Objects.equals(this.elements, adHocSubProcessActivateActivitiesInstruction.elements);
  }

  @Override
  public int hashCode() {
    return Objects.hash(elements);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AdHocSubProcessActivateActivitiesInstruction {\n");
    sb.append("    elements: ").append(toIndentedString(elements)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `elements` to the URL query string
    if (getElements() != null) {
      for (int i = 0; i < getElements().size(); i++) {
        if (getElements().get(i) != null) {
          joiner.add(getElements().get(i).toUrlQueryString(String.format("%selements%s%s", prefix, suffix,
              "".equals(suffix) ? "" : String.format("%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    return joiner.toString();
  }

}

