/*
 * Orchestration Cluster REST API
 * API for communicating with a Camunda 8 cluster.
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.camunda.client.protocol.rest;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.camunda.client.protocol.rest.BatchOperationTypeEnum;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.io.UnsupportedEncodingException;
import java.net.URLEncoder;
import java.util.StringJoiner;

/**
 * BatchOperationCreatedResult
 */
@JsonPropertyOrder({
  BatchOperationCreatedResult.JSON_PROPERTY_BATCH_OPERATION_KEY,
  BatchOperationCreatedResult.JSON_PROPERTY_BATCH_OPERATION_TYPE
})
@com.fasterxml.jackson.annotation.JsonInclude(com.fasterxml.jackson.annotation.JsonInclude.Include.NON_NULL)
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-07-24T12:02:12.602366536Z[Etc/UTC]", comments = "Generator version: 7.12.0")
public class BatchOperationCreatedResult {
  public static final String JSON_PROPERTY_BATCH_OPERATION_KEY = "batchOperationKey";
  @javax.annotation.Nullable
  private String batchOperationKey;

  public static final String JSON_PROPERTY_BATCH_OPERATION_TYPE = "batchOperationType";
  @javax.annotation.Nullable
  private BatchOperationTypeEnum batchOperationType;

  public BatchOperationCreatedResult() {
  }

  public BatchOperationCreatedResult batchOperationKey(@javax.annotation.Nullable String batchOperationKey) {
    
    this.batchOperationKey = batchOperationKey;
    return this;
  }

  /**
   * Key of the batch operation.
   * @return batchOperationKey
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_BATCH_OPERATION_KEY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getBatchOperationKey() {
    return batchOperationKey;
  }


  @JsonProperty(JSON_PROPERTY_BATCH_OPERATION_KEY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBatchOperationKey(@javax.annotation.Nullable String batchOperationKey) {
    this.batchOperationKey = batchOperationKey;
  }

  public BatchOperationCreatedResult batchOperationType(@javax.annotation.Nullable BatchOperationTypeEnum batchOperationType) {
    
    this.batchOperationType = batchOperationType;
    return this;
  }

  /**
   * Get batchOperationType
   * @return batchOperationType
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_BATCH_OPERATION_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BatchOperationTypeEnum getBatchOperationType() {
    return batchOperationType;
  }


  @JsonProperty(JSON_PROPERTY_BATCH_OPERATION_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBatchOperationType(@javax.annotation.Nullable BatchOperationTypeEnum batchOperationType) {
    this.batchOperationType = batchOperationType;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BatchOperationCreatedResult batchOperationCreatedResult = (BatchOperationCreatedResult) o;
    return Objects.equals(this.batchOperationKey, batchOperationCreatedResult.batchOperationKey) &&
        Objects.equals(this.batchOperationType, batchOperationCreatedResult.batchOperationType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(batchOperationKey, batchOperationType);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BatchOperationCreatedResult {\n");
    sb.append("    batchOperationKey: ").append(toIndentedString(batchOperationKey)).append("\n");
    sb.append("    batchOperationType: ").append(toIndentedString(batchOperationType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `batchOperationKey` to the URL query string
    if (getBatchOperationKey() != null) {
      try {
        joiner.add(String.format("%sbatchOperationKey%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getBatchOperationKey()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `batchOperationType` to the URL query string
    if (getBatchOperationType() != null) {
      try {
        joiner.add(String.format("%sbatchOperationType%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getBatchOperationType()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    return joiner.toString();
  }

}

