/*
 * Orchestration Cluster REST API
 * API for communicating with a Camunda 8 cluster.
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.camunda.client.protocol.rest;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.camunda.client.protocol.rest.DeploymentMetadataResult;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.io.UnsupportedEncodingException;
import java.net.URLEncoder;
import java.util.StringJoiner;

/**
 * DeploymentResult
 */
@JsonPropertyOrder({
  DeploymentResult.JSON_PROPERTY_TENANT_ID,
  DeploymentResult.JSON_PROPERTY_DEPLOYMENT_KEY,
  DeploymentResult.JSON_PROPERTY_DEPLOYMENTS
})
@com.fasterxml.jackson.annotation.JsonInclude(com.fasterxml.jackson.annotation.JsonInclude.Include.NON_NULL)
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-07-24T12:02:12.602366536Z[Etc/UTC]", comments = "Generator version: 7.12.0")
public class DeploymentResult {
  public static final String JSON_PROPERTY_TENANT_ID = "tenantId";
  @javax.annotation.Nullable
  private String tenantId;

  public static final String JSON_PROPERTY_DEPLOYMENT_KEY = "deploymentKey";
  @javax.annotation.Nullable
  private String deploymentKey;

  public static final String JSON_PROPERTY_DEPLOYMENTS = "deployments";
  @javax.annotation.Nullable
  private List<DeploymentMetadataResult> deployments = new ArrayList<>();

  public DeploymentResult() {
  }

  public DeploymentResult tenantId(@javax.annotation.Nullable String tenantId) {
    
    this.tenantId = tenantId;
    return this;
  }

  /**
   * The tenant ID associated with the deployment.
   * @return tenantId
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TENANT_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTenantId() {
    return tenantId;
  }


  @JsonProperty(JSON_PROPERTY_TENANT_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTenantId(@javax.annotation.Nullable String tenantId) {
    this.tenantId = tenantId;
  }

  public DeploymentResult deploymentKey(@javax.annotation.Nullable String deploymentKey) {
    
    this.deploymentKey = deploymentKey;
    return this;
  }

  /**
   * The unique key identifying the deployment.
   * @return deploymentKey
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DEPLOYMENT_KEY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDeploymentKey() {
    return deploymentKey;
  }


  @JsonProperty(JSON_PROPERTY_DEPLOYMENT_KEY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDeploymentKey(@javax.annotation.Nullable String deploymentKey) {
    this.deploymentKey = deploymentKey;
  }

  public DeploymentResult deployments(@javax.annotation.Nullable List<DeploymentMetadataResult> deployments) {
    
    this.deployments = deployments;
    return this;
  }

  public DeploymentResult addDeploymentsItem(DeploymentMetadataResult deploymentsItem) {
    if (this.deployments == null) {
      this.deployments = new ArrayList<>();
    }
    this.deployments.add(deploymentsItem);
    return this;
  }

  /**
   * Items deployed by the request.
   * @return deployments
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DEPLOYMENTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<DeploymentMetadataResult> getDeployments() {
    return deployments;
  }


  @JsonProperty(JSON_PROPERTY_DEPLOYMENTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDeployments(@javax.annotation.Nullable List<DeploymentMetadataResult> deployments) {
    this.deployments = deployments;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DeploymentResult deploymentResult = (DeploymentResult) o;
    return Objects.equals(this.tenantId, deploymentResult.tenantId) &&
        Objects.equals(this.deploymentKey, deploymentResult.deploymentKey) &&
        Objects.equals(this.deployments, deploymentResult.deployments);
  }

  @Override
  public int hashCode() {
    return Objects.hash(tenantId, deploymentKey, deployments);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DeploymentResult {\n");
    sb.append("    tenantId: ").append(toIndentedString(tenantId)).append("\n");
    sb.append("    deploymentKey: ").append(toIndentedString(deploymentKey)).append("\n");
    sb.append("    deployments: ").append(toIndentedString(deployments)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `tenantId` to the URL query string
    if (getTenantId() != null) {
      try {
        joiner.add(String.format("%stenantId%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getTenantId()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `deploymentKey` to the URL query string
    if (getDeploymentKey() != null) {
      try {
        joiner.add(String.format("%sdeploymentKey%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getDeploymentKey()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `deployments` to the URL query string
    if (getDeployments() != null) {
      for (int i = 0; i < getDeployments().size(); i++) {
        if (getDeployments().get(i) != null) {
          joiner.add(getDeployments().get(i).toUrlQueryString(String.format("%sdeployments%s%s", prefix, suffix,
              "".equals(suffix) ? "" : String.format("%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    return joiner.toString();
  }

}

