/*
 * Copyright Camunda Services GmbH and/or licensed to Camunda Services GmbH under
 * one or more contributor license agreements. See the NOTICE file distributed
 * with this work for additional information regarding copyright ownership.
 * Licensed under the Camunda License 1.0. You may not use this file
 * except in compliance with the Camunda License 1.0.
 */
package io.camunda.zeebe.engine.state;

import static org.assertj.core.api.Assertions.assertThat;

import io.camunda.zeebe.engine.util.EngineRule;
import io.camunda.zeebe.model.bpmn.Bpmn;
import io.camunda.zeebe.protocol.Protocol;
import io.camunda.zeebe.protocol.record.Assertions;
import io.camunda.zeebe.protocol.record.Record;
import io.camunda.zeebe.protocol.record.RecordType;
import io.camunda.zeebe.protocol.record.RejectionType;
import io.camunda.zeebe.protocol.record.value.JobRecordValue;
import io.camunda.zeebe.test.util.record.RecordingExporter;
import org.junit.Rule;
import org.junit.Test;

/**
 * Tests the key generator's behaviour after broker restart and log replay when the log contains a
 * rejected command whose log-entry header key is anomalously large.
 *
 * <p>Root cause: ReplayStateMachine.onRecordReplayed calls setKeyIfHigher(record.getKey())
 * unconditionally for every record in the log — commands, rejections, and events alike. A
 * CompleteJob command submitted with an arbitrarily large job key writes that key into the
 * log-entry header. On replay after restart, setKeyIfHigher advances the key counter to that large
 * value, so all subsequent nextKey() calls start from largeKey + 1.
 */
public final class KeyGeneratorAfterRestartTest {

  private static final String PROCESS_ID = "process";
  private static final String JOB_TYPE = "type";

  @Rule public final EngineRule engine = EngineRule.singlePartition();

  @Test
  public void shouldNotAdvanceKeyCounterWhenReplayingRejectedCommandWithLargeKey() {
    // given: deploy a process and create an instance to establish a baseline key
    engine
        .deployment()
        .withXmlResource(
            Bpmn.createExecutableProcess(PROCESS_ID)
                .startEvent()
                .serviceTask("task", t -> t.zeebeJobType(JOB_TYPE))
                .endEvent()
                .done())
        .deploy();

    final long baselineKey = engine.processInstance().ofBpmnProcessId(PROCESS_ID).create();

    // a large key with valid partition bits (partition 1) but a sequence number far ahead of
    // anything the engine has generated — simulating a misbehaving client or corrupt request
    final long anomalouslyLargeKey =
        Protocol.encodePartitionId(Protocol.DEPLOYMENT_PARTITION, 1_000_000_000L);

    assertThat(anomalouslyLargeKey)
        .as("precondition: anomalous key is much larger than the baseline key")
        .isGreaterThan(baselineKey);
    assertThat(Protocol.decodePartitionId(anomalouslyLargeKey))
        .as("precondition: anomalous key encodes partition 1 and will pass the partition check")
        .isEqualTo(Protocol.DEPLOYMENT_PARTITION);

    // when: complete a non-existent job using the anomalously large key
    // the command is written to the log with key=anomalouslyLargeKey in the log-entry header
    // the engine rejects it (job not found) and the rejection is written with the same header key
    final Record<JobRecordValue> rejection =
        engine.job().withKey(anomalouslyLargeKey).expectRejection().complete();
    Assertions.assertThat(rejection).hasRejectionType(RejectionType.NOT_FOUND);
    assertThat(rejection.getKey())
        .as("the rejection record header key must equal the submitted key")
        .isEqualTo(anomalouslyLargeKey);

    // when: restart the broker, forcing replay of every log record
    // during replay, ReplayStateMachine.onRecordReplayed calls setKeyIfHigher(record.getKey())
    // for all record types — the rejection and its originating command both have
    // key=anomalouslyLargeKey
    engine.reprocess();

    // guard: confirm the rejection record was actually replayed (re-exported) after restart
    // if this assertion fails the test did not exercise the path under investigation
    assertThat(
            RecordingExporter.records()
                .withRecordType(RecordType.COMMAND_REJECTION)
                .filter(r -> r.getKey() == anomalouslyLargeKey)
                .findFirst())
        .as("rejection record with key=%d must be re-exported after restart", anomalouslyLargeKey)
        .isPresent();

    // then: create a new process instance — its key is generated by nextKey() after replay
    final long keyAfterRestart = engine.processInstance().ofBpmnProcessId(PROCESS_ID).create();

    // the key must be sequential from the baseline, NOT jumped to anomalouslyLargeKey + 1
    // if this assertion fails, setKeyIfHigher advanced the counter to anomalouslyLargeKey
    // during replay of the rejection record, confirming the key-corruption bug
    assertThat(keyAfterRestart)
        .as(
            "key after restart (%d) must not have jumped to anomalouslyLargeKey + 1 = %d. "
                + "If it did, setKeyIfHigher advanced the counter from the rejection record header.",
            keyAfterRestart, anomalouslyLargeKey + 1)
        .isLessThan(anomalouslyLargeKey);
  }
}
