services:
  elasticsearch:
    environment:
      - 'ES_JAVA_OPTS=-Xms2g -Xmx2g'
  camunda:
    environment:
      - 'JAVA_TOOL_OPTIONS=-Xms1g -Xmx2g'
    ports: !override
      - "8088:8080"
      - "26555:26500"
      - "9666:9600"
