/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(project(":tasklist-common"))
    api(project(":webapps-schema"))
    api(project(":camunda-security-core"))
    api(project(":camunda-schema-manager"))
    api(project(":camunda-search-client-connect"))
    api(project(":zeebe-util"))
    api(project(":camunda-spring-utils"))
    api(libs.org.springframework.boot.spring.boot.actuator)
    api(libs.org.springframework.spring.context)
    api(libs.org.springframework.spring.core)
    api(libs.org.springframework.spring.beans)
    api(libs.co.elastic.clients.elasticsearch.java)
    api(libs.org.opensearch.client.opensearch.java)
    api(libs.jakarta.json.jakarta.json.api)
    implementation(libs.org.apache.commons.commons.lang3)
    api(libs.com.fasterxml.jackson.core.jackson.annotations)
    api(libs.com.fasterxml.jackson.core.jackson.databind)
    implementation(libs.org.slf4j.slf4j.api)
    api(libs.org.apache.lucene.lucene.core)
    api(libs.org.apache.commons.commons.collections4)
    testImplementation(libs.org.mockito.mockito.core)
    testImplementation(libs.org.mockito.mockito.junit.jupiter)
    testImplementation(libs.org.assertj.assertj.core)
    testImplementation(libs.org.junit.jupiter.junit.jupiter.api)
    testImplementation(libs.org.junit.jupiter.junit.jupiter.params)
    testImplementation(libs.org.junit.platform.junit.platform.suite.api)
    testImplementation(libs.org.junit.platform.junit.platform.suite.engine)
}

description = "Tasklist ELS schema"
