---
# Source: camunda-platform/charts/elasticsearch/templates/master/pdb.yaml
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: elastic
  namespace: "c8-ck-test-realistic"
  labels:
    app.kubernetes.io/instance: c8-ck-test-realistic
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: elasticsearch
    app.kubernetes.io/version: 8.18.0
    helm.sh/chart: elasticsearch-21.6.3
    app.kubernetes.io/component: master
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app.kubernetes.io/instance: c8-ck-test-realistic
      app.kubernetes.io/name: elasticsearch
      app.kubernetes.io/component: master
