---
# Source: camunda-platform/charts/elasticsearch/templates/master/svc-headless.yaml
apiVersion: v1
kind: Service
metadata:
  name: elastic-hl
  namespace: "c8-ck-test-realistic"
  labels:
    app.kubernetes.io/instance: c8-ck-test-realistic
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: elasticsearch
    app.kubernetes.io/version: 8.18.0
    helm.sh/chart: elasticsearch-21.6.3
    app.kubernetes.io/component: master
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - name: tcp-rest-api
      port: 9200
      targetPort: rest-api
    - name: tcp-transport
      port: 9300
      targetPort: transport
  selector:
    app.kubernetes.io/instance: c8-ck-test-realistic
    app.kubernetes.io/name: elasticsearch
    app.kubernetes.io/component: master
