/*
 * Copyright Camunda Services GmbH and/or licensed to Camunda Services GmbH under
 * one or more contributor license agreements. See the NOTICE file distributed
 * with this work for additional information regarding copyright ownership.
 * Licensed under the Camunda License 1.0. You may not use this file
 * except in compliance with the Camunda License 1.0.
 */

import {getCurrentUser} from './authentication';
import {activateAdHocSubProcessActivities} from './ad-hoc-sub-process';
import {
	createAuthorization,
	updateAuthorization,
	getAuthorization,
	deleteAuthorization,
	queryAuthorizations,
} from './authorization';
import {
	getBatchOperation,
	queryBatchOperations,
	cancelBatchOperation,
	suspendBatchOperation,
	resumeBatchOperation,
	queryBatchOperationItems,
} from './batch-operation';
import {pinClock, resetClock} from './clock';
import {getTopology} from './cluster';
import {
	queryDecisionDefinitions,
	getDecisionDefinition,
	getDecisionDefinitionXml,
	evaluateDecision,
} from './decision-definition';
import {queryDecisionInstances, getDecisionInstance} from './decision-instance';
import {queryDecisionRequirements, getDecisionRequirements, getDecisionRequirementsXml} from './decision-requirements';
import {createDocument, createDocuments, getDocument, deleteDocument, createDocumentLink} from './document';
import {
	queryElementInstances,
	getElementInstance,
	updateElementInstanceVariables,
	queryElementInstanceIncidents,
} from './element-instance';
import {
	createGroup,
	getGroup,
	updateGroup,
	deleteGroup,
	queryGroups,
	queryUsersByGroup,
	queryClientsByGroup,
	queryRolesByGroup,
	queryMappingRulesByGroup,
	assignUserToGroup,
	unassignUserFromGroup,
	assignClientToGroup,
	unassignClientFromGroup,
	assignMappingToGroup,
	unassignMappingFromGroup,
} from './group';
import {resolveIncident, getIncident, queryIncidents} from './incident';
import {getLicense} from './license';
import {
	createMappingRule,
	updateMappingRule,
	deleteMappingRule,
	getMappingRule,
	queryMappingRules,
} from './mapping-rule';
import {publishMessage, correlateMessage} from './message';
import {queryMessageSubscriptions, queryCorrelatedMessageSubscriptions} from './message-subscriptions';
import {
	createProcessInstance,
	getProcessInstance,
	queryProcessInstances,
	cancelProcessInstance,
	queryProcessInstanceIncidents,
	getProcessInstanceCallHierarchy,
	getProcessInstanceStatistics,
	getProcessInstanceSequenceFlows,
	createIncidentResolutionBatchOperation,
	createCancellationBatchOperation,
	createMigrationBatchOperation,
	createModificationBatchOperation,
	resolveProcessInstanceIncidents,
} from './process-instance';
import {
	getUserTask,
	queryUserTasks,
	getUserTaskForm,
	getTask,
	assignTask,
	unassignTask,
	completeTask,
	queryVariablesByUserTask,
	updateUserTask,
} from './user-task';
import {getVariable, queryVariables} from './variable';
import {queryJobs, activateJobs, failJob, throwJobError, completeJob, updateJob} from './job';
import {
	getProcessDefinition,
	getProcessDefinitionXml,
	getProcessStartForm,
	getProcessDefinitionStatistics,
	queryProcessDefinitions,
	getProcessDefinitionInstanceStatistics,
	getProcessDefinitionInstanceVersionStatistics,
} from './process-definition';
import {createDeployment, deleteResource, getResource, getResourceContent} from './resource';
import {
	createRole,
	getRole,
	updateRole,
	deleteRole,
	queryRoles,
	queryUsersByRole,
	queryClientsByRole,
	assignUserToRole,
	unassignUserFromRole,
	assignClientToRole,
	unassignClientFromRole,
	assignGroupToRole,
	unassignGroupFromRole,
	queryGroupsByRole,
	assignMappingToRole,
	unassignMappingFromRole,
	queryMappingRulesByRole,
} from './role';
import {broadcastSignal} from './signal';
import {
	createTenant,
	getTenant,
	updateTenant,
	deleteTenant,
	queryTenants,
	assignUserToTenant,
	unassignUserFromTenant,
	queryUsersByTenant,
	queryClientsByTenant,
	queryGroupsByTenant,
	queryRolesByTenant,
	assignClientToTenant,
	unassignClientFromTenant,
	assignMappingRuleToTenant,
	unassignMappingRuleFromTenant,
	queryMappingRulesByTenant,
	assignGroupToTenant,
	unassignGroupFromTenant,
	assignRoleToTenant,
	unassignRoleFromTenant,
} from './tenant';
import {createUser, queryUsers, getUser, deleteUser, updateUser} from './user';
import {getUsageMetrics} from './usage-metrics';
import {getAuditLog, queryAuditLogs} from './audit-log';
import {queryUserTaskAuditLogs} from './user-task-audit-log';
import {
	deleteProcessInstance,
	modifyProcessInstance as modifyProcessInstanceCommand,
} from './process-instance-commands';
import {
	getIncidentProcessInstanceStatisticsByError,
	getIncidentProcessInstanceStatisticsByDefinition,
} from './incident-statistics';

const endpoints = {
	getCurrentUser,

	activateAdHocSubProcessActivities,
	createAuthorization,
	updateAuthorization,
	getAuthorization,
	deleteAuthorization,
	queryAuthorizations,
	getBatchOperation,
	queryBatchOperations,
	cancelBatchOperation,
	suspendBatchOperation,
	resumeBatchOperation,
	queryBatchOperationItems,
	pinClock,
	resetClock,
	getTopology,
	queryDecisionDefinitions,
	getDecisionDefinition,
	getDecisionDefinitionXml,
	evaluateDecision,
	queryDecisionInstances,
	getDecisionInstance,
	queryDecisionRequirements,
	getDecisionRequirements,
	getDecisionRequirementsXml,
	createDocument,
	createDocuments,
	getDocument,
	deleteDocument,
	createDocumentLink,
	queryElementInstances,
	queryElementInstanceIncidents,
	getElementInstance,
	updateElementInstanceVariables,
	createGroup,
	getGroup,
	updateGroup,
	deleteGroup,
	queryGroups,
	queryUsersByGroup,
	queryClientsByGroup,
	queryRolesByGroup,
	queryMappingRulesByGroup,
	assignUserToGroup,
	unassignUserFromGroup,
	assignClientToGroup,
	unassignClientFromGroup,
	assignMappingToGroup,
	unassignMappingFromGroup,
	resolveIncident,
	getIncident,
	queryIncidents,
	getLicense,
	createMappingRule,
	updateMappingRule,
	deleteMappingRule,
	getMappingRule,
	queryMappingRules,
	publishMessage,
	correlateMessage,
	queryMessageSubscriptions,
	queryCorrelatedMessageSubscriptions,
	getUserTask,
	queryUserTasks,
	getUserTaskForm,
	getTask,
	assignTask,
	unassignTask,
	completeTask,
	queryVariablesByUserTask,
	updateUserTask,
	createProcessInstance,
	getVariable,
	queryVariables,
	queryJobs,
	activateJobs,
	failJob,
	throwJobError,
	completeJob,
	updateJob,
	getProcessDefinition,
	getProcessDefinitionXml,
	getProcessStartForm,
	getProcessDefinitionStatistics,
	queryProcessDefinitions,
	getProcessDefinitionInstanceStatistics,
	getProcessDefinitionInstanceVersionStatistics,
	getProcessInstance,
	queryProcessInstances,
	cancelProcessInstance,
	queryProcessInstanceIncidents,
	getProcessInstanceCallHierarchy,
	getProcessInstanceStatistics,
	getProcessInstanceSequenceFlows,
	createDeployment,
	deleteResource,
	getResource,
	getResourceContent,
	createRole,
	getRole,
	updateRole,
	deleteRole,
	queryRoles,
	queryUsersByRole,
	queryClientsByRole,
	assignUserToRole,
	unassignUserFromRole,
	assignClientToRole,
	unassignClientFromRole,
	assignGroupToRole,
	unassignGroupFromRole,
	queryGroupsByRole,
	assignMappingToRole,
	unassignMappingFromRole,
	queryMappingRulesByRole,
	broadcastSignal,
	createTenant,
	getTenant,
	updateTenant,
	deleteTenant,
	queryTenants,
	assignUserToTenant,
	unassignUserFromTenant,
	queryUsersByTenant,
	queryClientsByTenant,
	queryGroupsByTenant,
	queryRolesByTenant,
	assignClientToTenant,
	unassignClientFromTenant,
	assignMappingRuleToTenant,
	unassignMappingRuleFromTenant,
	queryMappingRulesByTenant,
	assignGroupToTenant,
	unassignGroupFromTenant,
	assignRoleToTenant,
	unassignRoleFromTenant,
	createUser,
	queryUsers,
	getUser,
	deleteUser,
	updateUser,
	getUsageMetrics,
	createIncidentResolutionBatchOperation,
	createCancellationBatchOperation,
	createMigrationBatchOperation,
	createModificationBatchOperation,
	modifyProcessInstance: modifyProcessInstanceCommand,
	deleteProcessInstance,
	resolveProcessInstanceIncidents,
	queryAuditLogs,
	getAuditLog,
	queryUserTaskAuditLogs,
	getIncidentProcessInstanceStatisticsByError,
	getIncidentProcessInstanceStatisticsByDefinition,
} as const;

export {
	auditLogEntityTypeSchema,
	auditLogOperationTypeSchema,
	auditLogActorTypeSchema,
	auditLogResultSchema,
	auditLogCategorySchema,
	auditLogSchema,
	auditLogFilterSchema,
	auditLogSortFieldEnum,
	queryAuditLogsRequestBodySchema,
	queryAuditLogsResponseBodySchema,
	getAuditLogResponseBodySchema,
	type AuditLog,
	type AuditLogEntityType,
	type AuditLogOperationType,
	type AuditLogActorType,
	type AuditLogResult,
	type AuditLogCategory,
	type AuditLogSortField,
	type QueryAuditLogsRequestBody,
	type QueryAuditLogsResponseBody,
	type GetAuditLogResponseBody,
} from './audit-log';
export {
	userTaskAuditLogFilterSchema,
	queryUserTaskAuditLogsRequestBodySchema,
	queryUserTaskAuditLogsResponseBodySchema,
	type UserTaskAuditLogFilter,
	type QueryUserTaskAuditLogsRequestBody,
	type QueryUserTaskAuditLogsResponseBody,
} from './user-task-audit-log';
export {
	deleteProcessInstanceRequestBodySchema,
	modifyProcessInstanceRequestBodySchema,
	type DeleteProcessInstanceRequestBody,
	type ModifyProcessInstanceRequestBody,
} from './process-instance-commands';
export {
	getIncidentProcessInstanceStatisticsByErrorRequestBodySchema,
	getIncidentProcessInstanceStatisticsByErrorResponseBodySchema,
	incidentProcessInstanceStatisticsByErrorSchema,
	getIncidentProcessInstanceStatisticsByDefinitionRequestBodySchema,
	getIncidentProcessInstanceStatisticsByDefinitionResponseBodySchema,
	incidentProcessInstanceStatisticsByDefinitionSchema,
	type IncidentProcessInstanceStatisticsByError,
	type GetIncidentProcessInstanceStatisticsByErrorRequestBody,
	type GetIncidentProcessInstanceStatisticsByErrorResponseBody,
	type IncidentProcessInstanceStatisticsByDefinition,
	type GetIncidentProcessInstanceStatisticsByDefinitionRequestBody,
	type GetIncidentProcessInstanceStatisticsByDefinitionResponseBody,
} from './incident-statistics';
export {currentUserSchema, getCurrentUser, type CurrentUser} from './authentication';
export {
	activityTypeSchema,
	queryActivatableActivitiesRequestBodySchema,
	queryActivatableActivitiesResponseBodySchema,
	activateActivityWithinAdHocSubProcessRequestBodySchema,
	activateActivityWithinAdHocSubProcessResponseBodySchema,
	type ActivityType,
	type QueryActivatableActivitiesRequestBody,
	type ActivatableActivity,
	type QueryActivatableActivitiesResponseBody,
	type ActivateActivityWithinAdHocSubProcessRequestBody,
	type ActivateActivityWithinAdHocSubProcessResponseBody,
} from './ad-hoc-sub-process';
export {
	permissionTypeSchema,
	resourceTypeSchema,
	ownerTypeSchema,
	authorizationResultSchema,
	createAuthorizationRequestBodySchema,
	createAuthorizationResponseBodySchema,
	updateAuthorizationRequestBodySchema,
	getAuthorizationResponseBodySchema,
	queryAuthorizationsRequestBodySchema,
	queryAuthorizationsResponseBodySchema,
	authorizationSchema,
	type Authorization,
	type AuthorizationResult,
	type PermissionType,
	type ResourceType,
	type OwnerType,
	type CreateAuthorizationResponseBody,
	type GetAuthorizationResponseBody,
	type QueryAuthorizationsRequestBody,
	type QueryAuthorizationsResponseBody,
	type CreateAuthorizationRequestBody,
	type UpdateAuthorizationRequestBody,
} from './authorization';
export {
	batchOperationTypeSchema,
	batchOperationStateSchema,
	batchOperationItemStateSchema,
	batchOperationSchema,
	batchOperationItemSchema,
	queryBatchOperationsRequestBodySchema,
	queryBatchOperationsResponseBodySchema,
	queryBatchOperationItemsRequestBodySchema,
	queryBatchOperationItemsResponseBodySchema,
	type BatchOperationType,
	type BatchOperationState,
	type BatchOperationItemState,
	type BatchOperation,
	type BatchOperationItem,
	type QueryBatchOperationsRequestBody,
	type QueryBatchOperationsResponseBody,
	type QueryBatchOperationItemsRequestBody,
	type QueryBatchOperationItemsResponseBody,
} from './batch-operation';
export {pinClockRequestBodySchema, type PinClockRequestBody} from './clock';
export {
	partitionRoleSchema,
	partitionHealthSchema,
	partitionSchema,
	brokerInfoSchema,
	getTopologyResponseBodySchema,
	type PartitionRole,
	type PartitionHealth,
	type Partition,
	type BrokerInfo,
	type GetTopologyResponseBody,
} from './cluster';
export {
	decisionDefinitionSchema,
	queryDecisionDefinitionsRequestBodySchema,
	queryDecisionDefinitionsResponseBodySchema,
	getDecisionDefinitionXmlResponseBodySchema,
	evaluatedDecisionInputItemSchema,
	evaluatedDecisionOutputItemSchema,
	matchedDecisionRuleItemSchema,
	evaluatedDecisionResultSchema,
	evaluateDecisionRequestBodySchema,
	evaluateDecisionResponseBodySchema,
	type DecisionDefinition,
	type QueryDecisionDefinitionsRequestBody,
	type QueryDecisionDefinitionsResponseBody,
	type GetDecisionDefinitionXmlResponseBody,
	type EvaluatedDecisionInputItem,
	type EvaluatedDecisionOutputItem,
	type MatchedDecisionRuleItem,
	type EvaluatedDecisionResult,
	type EvaluateDecisionRequestBody,
	type EvaluateDecisionResponseBody,
} from './decision-definition';
export {
	decisionDefinitionTypeSchema,
	decisionInstanceStateSchema,
	decisionInstanceSchema,
	queryDecisionInstancesRequestBodySchema,
	queryDecisionInstancesResponseBodySchema,
	getDecisionInstanceResponseBodySchema,
	type DecisionDefinitionType,
	type DecisionInstanceState,
	type DecisionInstance,
	type QueryDecisionInstancesRequestBody,
	type QueryDecisionInstancesResponseBody,
	type GetDecisionInstanceResponseBody,
} from './decision-instance';
export {
	decisionRequirementsSchema,
	queryDecisionRequirementsRequestBodySchema,
	queryDecisionRequirementsResponseBodySchema,
	getDecisionRequirementsXmlResponseBodySchema,
	type DecisionRequirements,
	type QueryDecisionRequirementsRequestBody,
	type QueryDecisionRequirementsResponseBody,
	type GetDecisionRequirementsXmlResponseBody,
} from './decision-requirements';
export {
	documentMetadataSchema,
	documentReferenceSchema,
	documentCreationFailureDetailSchema,
	createDocumentsResponseBodySchema,
	documentLinkRequestBodySchema,
	documentLinkSchema,
	getDocumentResponseBodySchema,
	type DocumentMetadata,
	type DocumentReference,
	type DocumentCreationFailureDetail,
	type CreateDocumentsResponseBody,
	type DocumentLinkRequestBody,
	type DocumentLink,
	type GetDocumentResponseBody,
} from './document';
export {
	queryElementInstancesRequestBodySchema,
	queryElementInstancesResponseBodySchema,
	getElementInstanceResponseBodySchema,
	updateElementInstanceVariablesRequestBodySchema,
	elementInstanceStateSchema,
	elementInstanceTypeSchema,
	elementInstanceSchema,
	elementInstanceFilterSchema,
	queryElementInstanceIncidentsRequestBodySchema,
	queryElementInstanceIncidentsResponseBodySchema,
	type ElementInstanceState,
	type ElementInstanceType,
	type ElementInstance,
	type QueryElementInstancesRequestBody,
	type QueryElementInstancesResponseBody,
	type GetElementInstanceResponseBody,
	type UpdateElementInstanceVariablesRequestBody,
	type QueryElementInstanceIncidentsRequestBody,
	type QueryElementInstanceIncidentsResponseBody,
} from './element-instance';
export {
	createGroupRequestBodySchema,
	createGroupResponseBodySchema,
	getGroupResponseBodySchema,
	updateGroupRequestBodySchema,
	updateGroupResponseBodySchema,
	queryGroupsRequestBodySchema,
	queryGroupsResponseBodySchema,
	queryUsersByGroupRequestBodySchema,
	queryUsersByGroupResponseBodySchema,
	queryClientsByGroupRequestBodySchema,
	queryClientsByGroupResponseBodySchema,
	queryRolesByGroupRequestBodySchema,
	queryRolesByGroupResponseBodySchema,
	queryMappingRulesByGroupRequestBodySchema,
	queryMappingRulesByGroupResponseBodySchema,
	groupSchema,
	type Group,
	type CreateGroupRequestBody,
	type CreateGroupResponseBody,
	type GetGroupResponseBody,
	type UpdateGroupRequestBody,
	type UpdateGroupResponseBody,
	type QueryGroupsRequestBody,
	type QueryGroupsResponseBody,
	type QueryUsersByGroupRequestBody,
	type QueryUsersByGroupResponseBody,
	type QueryClientsByGroupRequestBody,
	type QueryClientsByGroupResponseBody,
	type QueryRolesByGroupRequestBody,
	type QueryRolesByGroupResponseBody,
	type QueryMappingRulesByGroupRequestBody,
	type QueryMappingRulesByGroupResponseBody,
} from './group';
export {
	getIncidentResponseBodySchema,
	queryIncidentsRequestBodySchema,
	queryIncidentsResponseBodySchema,
	incidentErrorTypeSchema,
	incidentStateSchema,
	incidentSchema,
	type IncidentErrorType,
	type IncidentState,
	type Incident,
	type GetIncidentResponseBody,
	type QueryIncidentsRequestBody,
	type QueryIncidentsResponseBody,
} from './incident';
export {
	queryJobsRequestBodySchema,
	queryJobsResponseBodySchema,
	activateJobsRequestBodySchema,
	activateJobsResponseBodySchema,
	failJobRequestBodySchema,
	throwJobErrorRequestBodySchema,
	completeJobRequestBodySchema,
	updateJobRequestBodySchema,
	jobSchema,
	activatedJobSchema,
	jobResultSchema,
	jobChangesetSchema,
	jobStateSchema,
	jobKindSchema,
	listenerEventTypeSchema,
	jobStateFilterSchema,
	jobKindFilterSchema,
	listenerEventTypeFilterSchema,
	type QueryJobsRequestBody,
	type QueryJobsResponseBody,
	type ActivateJobsRequestBody,
	type ActivateJobsResponseBody,
	type FailJobRequestBody,
	type ThrowJobErrorRequestBody,
	type CompleteJobRequestBody,
	type UpdateJobRequestBody,
	type Job,
	type ActivatedJob,
	type JobResult,
	type JobResultCorrections,
	type JobChangeset,
	type JobState,
	type JobKind,
	type ListenerEventType,
} from './job';
export {licenseSchema, type License} from './license';
export {
	publishMessageRequestBodySchema,
	publishMessageResponseBodySchema,
	correlateMessageRequestBodySchema,
	correlateMessageResponseBodySchema,
	type PublishMessageRequestBody,
	type PublishMessageResponseBody,
	type CorrelateMessageRequestBody,
	type CorrelateMessageResponseBody,
} from './message';
export {
	messageSubscriptionSchema,
	queryMessageSubscriptionRequestBodySchema,
	queryMessageSubscriptionsResponseBodySchema,
	correlatedMessageSubscriptionSchema,
	queryCorrelatedMessageSubscriptionRequestBodySchema,
	queryCorrelatedMessageSubscriptionsResponseBodySchema,
	type MessageSubscriptionState,
	type MessageSubscription,
	type QueryMessageSubscriptionsRequestBody,
	type QueryMessageSubscriptionsResponseBody,
	type CorrelatedMessageSubscription,
	type QueryCorrelatedMessageSubscriptionsRequestBody,
	type QueryCorrelatedMessageSubscriptionsResponseBody,
} from './message-subscriptions';
export {
	createMappingRuleRequestBodySchema,
	createMappingRuleResponseBodySchema,
	updateMappingRuleRequestBodySchema,
	updateMappingRuleResponseBodySchema,
	queryMappingRulesRequestBodySchema,
	queryMappingRulesResponseBodySchema,
	mappingRuleSchema,
	type CreateMappingRuleRequestBody,
	type CreateMappingRuleResponseBody,
	type UpdateMappingRuleRequestBody,
	type UpdateMappingRuleResponseBody,
	type QueryMappingRulesRequestBody,
	type QueryMappingRulesResponseBody,
	type MappingRule,
} from './mapping-rule';
export {
	createProcessInstanceRequestBodySchema,
	createProcessInstanceResponseBodySchema,
	queryProcessInstancesRequestBodySchema,
	queryProcessInstancesResponseBodySchema,
	cancelProcessInstanceRequestBodySchema,
	queryProcessInstanceIncidentsRequestBodySchema,
	queryProcessInstanceIncidentsResponseBodySchema,
	getProcessInstanceCallHierarchyResponseBodySchema,
	getProcessInstanceStatisticsResponseBodySchema,
	getProcessInstanceSequenceFlowsResponseBodySchema,
	createIncidentResolutionBatchOperationResponseBodySchema,
	createCancellationBatchOperationResponseBodySchema,
	createMigrationBatchOperationResponseBodySchema,
	createModificationBatchOperationResponseBodySchema,
	resolveProcessInstanceIncidentsResponseBodySchema,
	processInstanceStateSchema,
	processInstanceSchema,
	sequenceFlowSchema,
	callHierarchySchema,
	type CreateProcessInstanceRequestBody,
	type CreateProcessInstanceResponseBody,
	type QueryProcessInstancesRequestBody,
	type QueryProcessInstancesResponseBody,
	type CancelProcessInstanceRequestBody,
	type QueryProcessInstanceIncidentsRequestBody,
	type QueryProcessInstanceIncidentsResponseBody,
	type CallHierarchy,
	type GetProcessInstanceCallHierarchyResponseBody,
	type SequenceFlow,
	type GetProcessInstanceSequenceFlowsResponseBody,
	type ProcessInstanceState,
	type StatisticName,
	type ProcessInstance,
	type GetProcessInstanceStatisticsResponseBody,
	type CreateIncidentResolutionBatchOperationRequestBody,
	type CreateIncidentResolutionBatchOperationResponseBody,
	type CreateCancellationBatchOperationRequestBody,
	type CreateCancellationBatchOperationResponseBody,
	type CreateMigrationBatchOperationRequestBody,
	type CreateMigrationBatchOperationResponseBody,
	type CreateModificationBatchOperationRequestBody,
	type CreateModificationBatchOperationResponseBody,
	type ResolveProcessInstanceIncidentsResponseBody,
} from './process-instance';
export {
	userTaskSchema,
	queryUserTasksResponseBodySchema,
	queryUserTasksRequestBodySchema,
	formSchema,
	assignTaskRequestBodySchema,
	unassignTaskRequestBodySchema,
	completeTaskRequestBodySchema,
	queryVariablesByUserTaskRequestBodySchema,
	queryVariablesByUserTaskResponseBodySchema,
	updateUserTaskRequestBodySchema,
	type UserTask,
	type QueryUserTasksResponseBody,
	type QueryUserTasksRequestBody,
	type Form,
	type AssignTaskRequestBody,
	type UnassignTaskRequestBody,
	type CompleteTaskRequestBody,
	type QueryVariablesByUserTaskRequestBody,
	type QueryVariablesByUserTaskResponseBody,
	type UpdateUserTaskRequestBody,
} from './user-task';
export {
	variableSchema,
	queryVariablesRequestBodySchema,
	queryVariablesResponseBodySchema,
	type Variable,
	type QueryVariablesResponseBody,
	type QueryVariablesRequestBody,
} from './variable';
export {
	processDefinitionStatisticSchema,
	getProcessDefinitionResponseBodySchema,
	getProcessDefinitionXmlResponseBodySchema,
	getProcessStartFormResponseBodySchema,
	processDefinitionResponseSchema,
	getProcessDefinitionStatisticsRequestBodySchema,
	getProcessDefinitionStatisticsResponseBodySchema,
	queryProcessDefinitionsRequestBodySchema,
	queryProcessDefinitionsResponseBodySchema,
	processDefinitionSchema,
	getProcessDefinitionInstanceStatisticsRequestBodySchema,
	getProcessDefinitionInstanceStatisticsResponseBodySchema,
	processDefinitionInstanceStatisticsSchema,
	getProcessDefinitionInstanceVersionStatisticsRequestBodySchema,
	getProcessDefinitionInstanceVersionStatisticsResponseBodySchema,
	processDefinitionInstanceVersionStatisticsSchema,
	type ProcessDefinition,
	type ProcessDefinitionStatistic,
	type GetProcessDefinitionResponseBody,
	type GetProcessDefinitionXmlResponseBody,
	type GetProcessStartFormResponseBody,
	type GetProcessDefinitionStatisticsRequestBody,
	type GetProcessDefinitionStatisticsResponseBody,
	type QueryProcessDefinitionsRequestBody,
	type QueryProcessDefinitionsResponseBody,
	type GetProcessDefinitionInstanceStatisticsRequestBody,
	type GetProcessDefinitionInstanceStatisticsResponseBody,
	type ProcessDefinitionInstanceStatistics,
	type GetProcessDefinitionInstanceVersionStatisticsRequestBody,
	type GetProcessDefinitionInstanceVersionStatisticsResponseBody,
	type ProcessDefinitionInstanceVersionStatistics,
} from './process-definition';
export {
	problemDetailsSchema,
	queryPageSchema,
	querySortOrderSchema,
	problemDetailResponseSchema,
	type ProblemDetails,
	type QueryPage,
	type QuerySortOrder,
	type ProblemDetailsResponse,
} from './common';
export {
	createDeploymentResponseBodySchema,
	deleteResourceRequestBodySchema,
	deleteResourceResponseBodySchema,
	batchOperationCreatedResultSchema,
	resourceSchema,
	getResourceContentResponseBodySchema,
	processDeploymentSchema,
	decisionDeploymentSchema,
	decisionRequirementsDeploymentSchema,
	formDeploymentSchema,
	resourceDeploymentSchema,
	deploymentSchema,
	type CreateDeploymentResponseBody,
	type DeleteResourceRequestBody,
	type DeleteResourceResponseBody,
	type BatchOperationCreatedResult,
	type Resource,
	type GetResourceContentResponseBody,
	type ProcessDeployment,
	type DecisionDeployment,
	type DecisionRequirementsDeployment,
	type FormDeployment,
	type ResourceDeployment,
	type Deployment,
} from './resource';
export {
	roleSchema,
	createRoleRequestBodySchema,
	createRoleResponseBodySchema,
	updateRoleRequestBodySchema,
	updateRoleResponseBodySchema,
	queryRolesRequestBodySchema,
	queryRolesResponseBodySchema,
	queryUsersByRoleRequestBodySchema,
	queryUsersByRoleResponseBodySchema,
	queryClientsByRoleRequestBodySchema,
	queryClientsByRoleResponseBodySchema,
	queryGroupsByRoleRequestBodySchema,
	queryGroupsByRoleResponseBodySchema,
	queryMappingRulesByRoleRequestBodySchema,
	queryMappingRulesByRoleResponseBodySchema,
	type Role,
	type CreateRoleRequestBody,
	type CreateRoleResponseBody,
	type UpdateRoleRequestBody,
	type UpdateRoleResponseBody,
	type QueryRolesRequestBody,
	type QueryRolesResponseBody,
	type QueryUsersByRoleRequestBody,
	type QueryUsersByRoleResponseBody,
	type QueryClientsByRoleRequestBody,
	type QueryClientsByRoleResponseBody,
	type QueryGroupsByRoleRequestBody,
	type QueryGroupsByRoleResponseBody,
	type QueryMappingRulesByRoleRequestBody,
	type QueryMappingRulesByRoleResponseBody,
} from './role';
export {
	broadcastSignalRequestBodySchema,
	broadcastSignalResponseBodySchema,
	type BroadcastSignalRequestBody,
	type BroadcastSignalResponseBody,
} from './signal';
export {
	tenantSchema,
	createTenantRequestBodySchema,
	createTenantResponseBodySchema,
	updateTenantRequestBodySchema,
	updateTenantResponseBodySchema,
	queryTenantsRequestBodySchema,
	queryTenantsResponseBodySchema,
	tenantUserSchema,
	queryUsersByTenantRequestBodySchema,
	queryUsersByTenantResponseBodySchema,
	tenantClientSchema,
	queryClientsByTenantRequestBodySchema,
	queryClientsByTenantResponseBodySchema,
	queryGroupsByTenantRequestBodySchema,
	queryGroupsByTenantResponseBodySchema,
	queryRolesByTenantRequestBodySchema,
	queryRolesByTenantResponseBodySchema,
	queryMappingRulesByTenantRequestBodySchema,
	queryMappingRulesByTenantResponseBodySchema,
	type Tenant,
	type CreateTenantRequestBody,
	type CreateTenantResponseBody,
	type UpdateTenantRequestBody,
	type UpdateTenantResponseBody,
	type QueryTenantsRequestBody,
	type QueryTenantsResponseBody,
	type TenantUser,
	type QueryUsersByTenantRequestBody,
	type QueryUsersByTenantResponseBody,
	type TenantClient,
	type QueryClientsByTenantRequestBody,
	type QueryClientsByTenantResponseBody,
	type QueryGroupsByTenantRequestBody,
	type QueryGroupsByTenantResponseBody,
	type QueryRolesByTenantRequestBody,
	type QueryRolesByTenantResponseBody,
	type QueryMappingRulesByTenantRequestBody,
	type QueryMappingRulesByTenantResponseBody,
} from './tenant';
export {
	userSchema,
	createUserRequestBodySchema,
	createUserResponseBodySchema,
	updateUserRequestBodySchema,
	queryUsersRequestBodySchema,
	queryUsersResponseBodySchema,
	type User,
	type CreateUserRequestBody,
	type CreateUserResponseBody,
	type UpdateUserRequestBody,
	type QueryUsersRequestBody,
	type QueryUsersResponseBody,
} from './user';
export {
	usageMetricsSchema,
	getUsageMetricsResponseBodySchema,
	type UsageMetrics,
	type GetUsageMetricsResponseBody,
	type GetUsageMetricsParams,
} from './usage-metrics';
export {endpoints};
