---
name: Adjust POM for license analysis
description: |
  Adjusts pom.xml files so that Maven analysis tools (FOSSA, depgraph, etc.)
  can correctly resolve the full module hierarchy from bom/pom.xml as the root.

# owner: @camunda/monorepo-devops-team

runs:
  using: composite
  steps:
    - name: Adjust pom.xml files for analysis
      shell: bash
      run: |
        # The bom/pom.xml must be the actual root, otherwise, analysis tools won't detect the hierarchy correctly
        yq -i \
          '.project.modules.module += "./.."' \
          parent/pom.xml
        yq -i \
          '.project.modules.module += "./../parent"' \
          bom/pom.xml
        # Remove bom and parent from the list of modules of ./pom.xml
        yq -i \
          'del(.project.modules.module[] | select(. == "bom" or . == "parent"))' \
          pom.xml
        # Remove optimize/qa module as a bug in FOSSA prevents scope filtering
        # TODO remove this workaround once FOSSA is fixed
        yq -i \
          'del(.project.modules.module[] | select(. == "qa"))' \
          optimize/pom.xml
