/*
 * Copyright Camunda Services GmbH and/or licensed to Camunda Services GmbH under
 * one or more contributor license agreements. See the NOTICE file distributed
 * with this work for additional information regarding copyright ownership.
 * Licensed under the Camunda License 1.0. You may not use this file
 * except in compliance with the Camunda License 1.0.
 */
package io.camunda.configuration.physicaltenants;

import static org.assertj.core.api.Assertions.assertThat;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import io.camunda.configuration.Camunda;
import java.beans.IntrospectionException;
import java.beans.Introspector;
import java.beans.PropertyDescriptor;
import java.io.IOException;
import java.io.InputStream;
import java.io.UncheckedIOException;
import java.net.URL;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Arrays;
import java.util.Enumeration;
import java.util.List;
import java.util.Set;
import java.util.TreeSet;
import java.util.stream.Collectors;
import org.junit.jupiter.api.Test;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.boot.context.properties.source.ConfigurationPropertyName;

/**
 * Golden-file guard over the physical-tenant override surface.
 *
 * <p>Enumerates every {@code camunda.*} property in the {@link Camunda} configuration tree (the
 * exact surface a physical tenant can override — see {@link PhysicalTenantResolver}), classifies
 * each through the real {@link PhysicalTenantOverridePolicyValidation} policy, and compares the two
 * resulting sets against checked-in golden files:
 *
 * <ul>
 *   <li>{@code overridable-properties.golden.txt}
 *   <li>{@code non-overridable-properties.golden.txt}
 * </ul>
 *
 * <p>The property list is sourced from Spring Boot's generated {@code
 * spring-configuration-metadata.json}, so <strong>any new configuration property automatically
 * appears here</strong>. When a property is added or removed the golden files no longer match and
 * this test fails — forcing a deliberate decision about whether the new property is overridable per
 * tenant or belongs in the deny-list of {@link PhysicalTenantOverridePolicyValidation}. To resolve
 * the failure, update the deny-list if needed and regenerate the golden files (the failure message
 * prints the expected content).
 */
class PhysicalTenantOverridablePropertiesGoldenTest {

  private static final Logger LOGGER =
      LoggerFactory.getLogger(PhysicalTenantOverridablePropertiesGoldenTest.class);

  private static final String GOLDEN_OVERRIDABLE = "overridable-properties.golden.txt";
  private static final String GOLDEN_NON_OVERRIDABLE = "non-overridable-properties.golden.txt";
  private static final String METADATA_RESOURCE = "META-INF/spring-configuration-metadata.json";

  /**
   * System property that switches the test from <em>assert</em> to <em>update</em>: when {@code
   * true}, the test (re)writes the golden files from the live configuration surface instead of
   * comparing against them. This keeps regeneration routed through the real override policy — no
   * duplicated classification logic.
   */
  private static final String UPDATE_PROPERTY = "golden.update";

  private static final String UPDATE_COMMAND =
      "./mvnw test -pl configuration -Dtest=PhysicalTenantOverridablePropertiesGoldenTest "
          + "-Dgolden.update=true -DskipTests=false -Dquickly";

  private static final String OVERRIDABLE_HEADER =
      """
      # GOLDEN FILE — overridable physical-tenant properties
      # Every camunda.* property in the Camunda configuration tree that MAY be overridden
      # per physical tenant. Generated by PhysicalTenantOverridablePropertiesGoldenTest.
      # Do not edit by hand — regenerate with:
      #   %s
      # Adding a new property forces a deliberate decision: keep it overridable (here) or add it
      # to the deny-list in PhysicalTenantOverridePolicyValidation (moves it to the non-overridable file).
      """
          .formatted(UPDATE_COMMAND);

  private static final String NON_OVERRIDABLE_HEADER =
      """
      # GOLDEN FILE — non-overridable physical-tenant properties
      # Every camunda.* property in the Camunda configuration tree that may NOT be overridden per
      # physical tenant (cluster identity / system / license). Driven by the deny-list in
      # PhysicalTenantOverridePolicyValidation. Generated by
      # PhysicalTenantOverridablePropertiesGoldenTest. Do not edit by hand — regenerate with:
      #   %s
      """
          .formatted(UPDATE_COMMAND);

  @Test
  void overridablePropertiesMatchGoldenFile() {
    final Classification classification = classifyConfigurationSurface();

    if (updateRequested()) {
      writeGolden(GOLDEN_OVERRIDABLE, OVERRIDABLE_HEADER, classification.overridable());
      return;
    }

    assertThat(classification.overridable())
        .as(
            "Overridable physical-tenant properties drifted from the golden file. "
                + "A property was added, removed, or moved between the deny-list and the "
                + "overridable set. Decide whether it should be overridable per physical tenant, "
                + "adjust PhysicalTenantOverridePolicyValidation if needed, then regenerate the "
                + "golden files with:%n  %s",
            UPDATE_COMMAND)
        .containsExactlyElementsOf(readGolden(GOLDEN_OVERRIDABLE));
  }

  @Test
  void nonOverridablePropertiesMatchGoldenFile() {
    final Classification classification = classifyConfigurationSurface();

    if (updateRequested()) {
      writeGolden(GOLDEN_NON_OVERRIDABLE, NON_OVERRIDABLE_HEADER, classification.nonOverridable());
      return;
    }

    assertThat(classification.nonOverridable())
        .as(
            "Non-overridable physical-tenant properties drifted from the golden file. "
                + "A property was added, removed, or moved between the deny-list and the "
                + "overridable set. Decide whether it should be non-overridable per physical "
                + "tenant, adjust PhysicalTenantOverridePolicyValidation if needed, then "
                + "regenerate the golden files with:%n  %s",
            UPDATE_COMMAND)
        .containsExactlyElementsOf(readGolden(GOLDEN_NON_OVERRIDABLE));
  }

  /**
   * Reads every {@code camunda.*} property from the generated configuration metadata, restricts it
   * to the {@link Camunda} tree (the per-tenant override surface), and partitions it through the
   * real override policy. Property names are <em>relative to {@code camunda.}</em> (e.g. {@code
   * cluster.size}).
   */
  private static Classification classifyConfigurationSurface() {
    final Set<String> rootSections = camundaTopLevelSections();
    final Set<String> overridable = new TreeSet<>();
    final Set<String> nonOverridable = new TreeSet<>();

    for (final String fullName : readMetadataPropertyNames()) {
      final ConfigurationPropertyName name = ConfigurationPropertyName.of(fullName);
      // skip 'camunda' itself and the physical-tenants override map
      if (name.getNumberOfElements() < 2
          || !"camunda".equals(name.getElement(0, ConfigurationPropertyName.Form.DASHED))) {
        continue;
      }
      final String section = name.getElement(1, ConfigurationPropertyName.Form.DASHED);
      if ("physical-tenants".equals(section) || !rootSections.contains(section)) {
        // outside the Camunda override surface (e.g. legacy camunda.operate.*, camunda.tasklist.*)
        continue;
      }
      final ConfigurationPropertyName relative = name.subName(1);
      final String relativeName = relative.toString();
      if (PhysicalTenantOverridePolicyValidation.isNonOverridable(relative)) {
        nonOverridable.add(relativeName);
      } else {
        overridable.add(relativeName);
      }
    }

    assertThat(overridable).as("expected to discover overridable properties").isNotEmpty();
    assertThat(nonOverridable).as("expected to discover non-overridable properties").isNotEmpty();
    return new Classification(List.copyOf(overridable), List.copyOf(nonOverridable));
  }

  /**
   * Top-level configuration sections of {@link Camunda}, in kebab-case (e.g. {@code cluster},
   * {@code process-instance-creation}). Read reflectively so a new section added to {@code Camunda}
   * is picked up automatically.
   */
  private static Set<String> camundaTopLevelSections() {
    try {
      return Arrays.stream(Introspector.getBeanInfo(Camunda.class).getPropertyDescriptors())
          .map(PropertyDescriptor::getName)
          .filter(name -> !"class".equals(name))
          .map(PhysicalTenantOverridablePropertiesGoldenTest::camelToKebab)
          .collect(Collectors.toUnmodifiableSet());
    } catch (final IntrospectionException e) {
      throw new IllegalStateException("Failed to introspect " + Camunda.class, e);
    }
  }

  private static String camelToKebab(final String camel) {
    return camel.replaceAll("([a-z0-9])([A-Z])", "$1-$2").toLowerCase();
  }

  /**
   * All {@code camunda.*} property names declared in any {@code spring-configuration-metadata.json}
   * on the classpath. Only this module declares {@code camunda.*} configuration metadata, so
   * merging across resources is safe and avoids depending on classpath ordering.
   */
  private static Set<String> readMetadataPropertyNames() {
    final Set<String> names = new TreeSet<>();
    final ObjectMapper mapper = new ObjectMapper();
    try {
      final Enumeration<URL> resources =
          PhysicalTenantOverridablePropertiesGoldenTest.class
              .getClassLoader()
              .getResources(METADATA_RESOURCE);
      while (resources.hasMoreElements()) {
        final URL url = resources.nextElement();
        try (final InputStream in = url.openStream()) {
          final JsonNode properties = mapper.readTree(in).path("properties");
          for (final JsonNode property : properties) {
            final String name = property.path("name").asText("");
            if (name.startsWith("camunda.")) {
              names.add(name);
            }
          }
        }
      }
    } catch (final IOException e) {
      throw new UncheckedIOException("Failed to read " + METADATA_RESOURCE, e);
    }
    assertThat(names)
        .as(
            "No camunda.* configuration metadata found on the classpath (%s). "
                + "Ensure the configuration module is compiled with the "
                + "spring-boot-configuration-processor before running this test.",
            METADATA_RESOURCE)
        .isNotEmpty();
    return names;
  }

  private static List<String> readGolden(final String fileName) {
    final URL url = PhysicalTenantOverridablePropertiesGoldenTest.class.getResource(fileName);
    assertThat(url).as("missing golden file '%s'", fileName).isNotNull();
    try {
      return Files.readAllLines(Path.of(url.toURI()), StandardCharsets.UTF_8).stream()
          .map(String::strip)
          .filter(line -> !line.isEmpty() && !line.startsWith("#"))
          .toList();
    } catch (final Exception e) {
      throw new IllegalStateException("Failed to read golden file " + fileName, e);
    }
  }

  private static boolean updateRequested() {
    return Boolean.getBoolean(UPDATE_PROPERTY);
  }

  /**
   * Writes a golden file (header + one property per line, trailing newline) back into {@code
   * src/test/resources}. Used only in update mode; the content is produced by the same
   * classification the assertions check, so the policy stays the single source of truth.
   */
  private static void writeGolden(
      final String fileName, final String header, final List<String> properties) {
    final Path target = goldenSourcePath(fileName);
    final String content = header + String.join("\n", properties) + "\n";
    try {
      Files.writeString(target, content, StandardCharsets.UTF_8);
    } catch (final IOException e) {
      throw new UncheckedIOException("Failed to write golden file " + target, e);
    }
    LOGGER.info("[golden.update] wrote {} entries to {}", properties.size(), target);
  }

  /**
   * Resolves the source-tree location of a golden resource: {@code
   * src/test/resources/<package>/<fileName>}. Surefire runs tests with the module directory as the
   * working directory, so a module-relative path is sufficient. Used only in update mode.
   */
  private static Path goldenSourcePath(final String fileName) {
    Path dir = Path.of("src", "test", "resources");
    for (final String segment :
        PhysicalTenantOverridablePropertiesGoldenTest.class.getPackageName().split("\\.")) {
      dir = dir.resolve(segment);
    }
    return dir.resolve(fileName);
  }

  private record Classification(List<String> overridable, List<String> nonOverridable) {}
}
