/*
 * Copyright Camunda Services GmbH and/or licensed to Camunda Services GmbH
 * under one or more contributor license agreements. Licensed under a proprietary license.
 * See the License.txt file for more information. You may not use this file
 * except in compliance with the proprietary license.
 */

const mockStatistics = {
  running: 891,
  active: 277,
  withIncidents: 614,
};

const mockIncidentsByError = [
  {
    errorMessage: 'No more retries left.',
    instancesWithErrorCount: 170,
    processes: [
      {
        processId: '2251799813687201',
        version: 2,
        name: null,
        bpmnProcessId: 'complexProcess',
        errorMessage: 'No more retries left.',
        instancesWithActiveIncidentsCount: 20,
        activeInstancesCount: 0,
      },
      {
        processId: '2251799813686137',
        version: 1,
        name: 'Nested subprocesses',
        bpmnProcessId: 'prWithSubprocess',
        errorMessage: 'No more retries left.',
        instancesWithActiveIncidentsCount: 19,
        activeInstancesCount: 0,
      },
      {
        processId: '2251799813687192',
        version: 2,
        name: 'Multi-Instance Process',
        bpmnProcessId: 'multiInstanceProcess',
        errorMessage: 'No more retries left.',
        instancesWithActiveIncidentsCount: 17,
        activeInstancesCount: 0,
      },
      {
        processId: '2251799813687208',
        version: 2,
        name: null,
        bpmnProcessId: 'nonInterruptingBoundaryEvent',
        errorMessage: 'No more retries left.',
        instancesWithActiveIncidentsCount: 16,
        activeInstancesCount: 0,
      },
      {
        processId: '2251799813687210',
        version: 1,
        name: 'Called Process',
        bpmnProcessId: 'called-process',
        errorMessage: 'No more retries left.',
        instancesWithActiveIncidentsCount: 14,
        activeInstancesCount: 0,
      },
      {
        processId: '2251799813686132',
        version: 1,
        name: null,
        bpmnProcessId: 'complexProcess',
        errorMessage: 'No more retries left.',
        instancesWithActiveIncidentsCount: 14,
        activeInstancesCount: 0,
      },
      {
        processId: '2251799813687190',
        version: 2,
        name: 'Flight registration',
        bpmnProcessId: 'flightRegistration',
        errorMessage: 'No more retries left.',
        instancesWithActiveIncidentsCount: 13,
        activeInstancesCount: 0,
      },
      {
        processId: '2251799813686118',
        version: 1,
        name: 'Flight registration',
        bpmnProcessId: 'flightRegistration',
        errorMessage: 'No more retries left.',
        instancesWithActiveIncidentsCount: 10,
        activeInstancesCount: 0,
      },
      {
        processId: '2251799813686147',
        version: 1,
        name: 'Event Subprocess Process',
        bpmnProcessId: 'eventSubprocessProcess',
        errorMessage: 'No more retries left.',
        instancesWithActiveIncidentsCount: 9,
        activeInstancesCount: 0,
      },
      {
        processId: '2251799813687206',
        version: 2,
        name: null,
        bpmnProcessId: 'interruptingBoundaryEvent',
        errorMessage: 'No more retries left.',
        instancesWithActiveIncidentsCount: 8,
        activeInstancesCount: 0,
      },
      {
        processId: '2251799813687188',
        version: 2,
        name: 'Order process',
        bpmnProcessId: 'orderProcess',
        errorMessage: 'No more retries left.',
        instancesWithActiveIncidentsCount: 8,
        activeInstancesCount: 0,
      },
      {
        processId: '2251799813686134',
        version: 1,
        name: 'Event based gateway with message start',
        bpmnProcessId: 'eventBasedGatewayProcess',
        errorMessage: 'No more retries left.',
        instancesWithActiveIncidentsCount: 6,
        activeInstancesCount: 0,
      },
      {
        processId: '2251799813686161',
        version: 1,
        name: 'Link events process',
        bpmnProcessId: 'linkEventProcess',
        errorMessage: 'No more retries left.',
        instancesWithActiveIncidentsCount: 6,
        activeInstancesCount: 0,
      },
      {
        processId: '2251799813686116',
        version: 1,
        name: null,
        bpmnProcessId: 'loanProcess',
        errorMessage: 'No more retries left.',
        instancesWithActiveIncidentsCount: 3,
        activeInstancesCount: 0,
      },
      {
        processId: '2251799813686141',
        version: 1,
        name: null,
        bpmnProcessId: 'nonInterruptingBoundaryEvent',
        errorMessage: 'No more retries left.',
        instancesWithActiveIncidentsCount: 3,
        activeInstancesCount: 0,
      },
      {
        processId: '2251799813686114',
        version: 1,
        name: 'Order process',
        bpmnProcessId: 'orderProcess',
        errorMessage: 'No more retries left.',
        instancesWithActiveIncidentsCount: 2,
        activeInstancesCount: 0,
      },
      {
        processId: '2251799813686149',
        version: 1,
        name: null,
        bpmnProcessId: 'bigProcess',
        errorMessage: 'No more retries left.',
        instancesWithActiveIncidentsCount: 1,
        activeInstancesCount: 0,
      },
      {
        processId: '2251799813686139',
        version: 1,
        name: null,
        bpmnProcessId: 'interruptingBoundaryEvent',
        errorMessage: 'No more retries left.',
        instancesWithActiveIncidentsCount: 1,
        activeInstancesCount: 0,
      },
    ],
  },
  {
    errorMessage:
      "failed to evaluate expression '{orderId:orderNo,amountToPay:total}': no variable found for name 'total'",
    instancesWithErrorCount: 112,
    processes: [
      {
        processId: '2251799813687188',
        version: 2,
        name: 'Order process',
        bpmnProcessId: 'orderProcess',
        errorMessage:
          "failed to evaluate expression '{orderId:orderNo,amountToPay:total}': no variable found for name 'total'",
        instancesWithActiveIncidentsCount: 112,
        activeInstancesCount: 0,
      },
    ],
  },
  {
    errorMessage:
      "failed to evaluate expression 'clientId': no variable found for name 'clientId'",
    instancesWithErrorCount: 76,
    processes: [
      {
        processId: '2251799813687889',
        version: 3,
        name: null,
        bpmnProcessId: 'complexProcess',
        errorMessage:
          "failed to evaluate expression 'clientId': no variable found for name 'clientId'",
        instancesWithActiveIncidentsCount: 56,
        activeInstancesCount: 0,
      },
      {
        processId: '2251799813687203',
        version: 2,
        name: 'Event based gateway with timer start',
        bpmnProcessId: 'eventBasedGatewayProcess',
        errorMessage:
          "failed to evaluate expression 'clientId': no variable found for name 'clientId'",
        instancesWithActiveIncidentsCount: 20,
        activeInstancesCount: 0,
      },
    ],
  },
  {
    errorMessage:
      'Expected at least one condition to evaluate to true, or to have a default flow',
    instancesWithErrorCount: 63,
    processes: [
      {
        processId: '2251799813687889',
        version: 3,
        name: null,
        bpmnProcessId: 'complexProcess',
        errorMessage:
          'Expected at least one condition to evaluate to true, or to have a default flow',
        instancesWithActiveIncidentsCount: 56,
        activeInstancesCount: 0,
      },
      {
        processId: '2251799813686168',
        version: 1,
        name: 'Inclusive gateway',
        bpmnProcessId: 'inclusiveGatewayProcess',
        errorMessage:
          'Expected at least one condition to evaluate to true, or to have a default flow',
        instancesWithActiveIncidentsCount: 7,
        activeInstancesCount: 0,
      },
    ],
  },
  {
    errorMessage:
      "Expected result of the expression ' list contains(flows,\"2\")' to be 'BOOLEAN', but was 'NULL'.",
    instancesWithErrorCount: 56,
    processes: [
      {
        processId: '2251799813687889',
        version: 3,
        name: null,
        bpmnProcessId: 'complexProcess',
        errorMessage:
          "Expected result of the expression ' list contains(flows,\"2\")' to be 'BOOLEAN', but was 'NULL'.",
        instancesWithActiveIncidentsCount: 56,
        activeInstancesCount: 0,
      },
    ],
  },
  {
    errorMessage:
      "failed to evaluate expression '{taskOrderId:orderId}': no variable found for name 'orderId'",
    instancesWithErrorCount: 56,
    processes: [
      {
        processId: '2251799813687889',
        version: 3,
        name: null,
        bpmnProcessId: 'complexProcess',
        errorMessage:
          "failed to evaluate expression '{taskOrderId:orderId}': no variable found for name 'orderId'",
        instancesWithActiveIncidentsCount: 56,
        activeInstancesCount: 0,
      },
    ],
  },
  {
    errorMessage:
      'Something went wrong. \njava.lang.Throwable\n\tat io.camunda.operate.data.usertest.UserTestDataGenerator.lambda$progressAlwaysFailingTask$3(UserTestDataGenerator.java:359)\n\tat io.camunda.zeebe.client.impl.worker.JobRunnableFactory.executeJob(JobRunnableFactory.java:44)\n\tat io.camunda.zeebe.client.impl.worker.JobRunnableFactory.lambda$create$0(JobRunnableFactory.java:39)\n\tat java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577)\n\tat java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)\n\tat java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)\n\tat java.base/java.lang.Thread.run(Thread.java:1589)',
    instancesWithErrorCount: 55,
    processes: [
      {
        processId: '2251799813687889',
        version: 3,
        name: null,
        bpmnProcessId: 'complexProcess',
        errorMessage:
          'Something went wrong. \njava.lang.Throwable\n\tat io.camunda.operate.data.usertest.UserTestDataGenerator.lambda$progressAlwaysFailingTask$3(UserTestDataGenerator.java:359)\n\tat io.camunda.zeebe.client.impl.worker.JobRunnableFactory.executeJob(JobRunnableFactory.java:44)\n\tat io.camunda.zeebe.client.impl.worker.JobRunnableFactory.lambda$create$0(JobRunnableFactory.java:39)\n\tat java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577)\n\tat java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)\n\tat java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)\n\tat java.base/java.lang.Thread.run(Thread.java:1589)',
        instancesWithActiveIncidentsCount: 55,
        activeInstancesCount: 0,
      },
    ],
  },
  {
    errorMessage:
      "Expected process with BPMN process id 'called-process' to be deployed, but not found.",
    instancesWithErrorCount: 20,
    processes: [
      {
        processId: '2251799813686145',
        version: 1,
        name: 'Call Activity Process',
        bpmnProcessId: 'call-activity-process',
        errorMessage:
          "Expected process with BPMN process id 'called-process' to be deployed, but not found.",
        instancesWithActiveIncidentsCount: 20,
        activeInstancesCount: 0,
      },
    ],
  },
  {
    errorMessage:
      "Expected to throw an error event with the code 'end', but it was not caught. No error events are available in the scope.",
    instancesWithErrorCount: 20,
    processes: [
      {
        processId: '2251799813686153',
        version: 1,
        name: null,
        bpmnProcessId: 'error-end-process',
        errorMessage:
          "Expected to throw an error event with the code 'end', but it was not caught. No error events are available in the scope.",
        instancesWithActiveIncidentsCount: 20,
        activeInstancesCount: 0,
      },
    ],
  },
  {
    errorMessage:
      "Expected to evaluate decision 'invoiceAssignApprover', but failed to evaluate expression 'amount': no variable found for name 'amount'",
    instancesWithErrorCount: 17,
    processes: [
      {
        processId: '2251799813686130',
        version: 1,
        name: 'DMN invoice',
        bpmnProcessId: 'invoice',
        errorMessage:
          "Expected to evaluate decision 'invoiceAssignApprover', but failed to evaluate expression 'amount': no variable found for name 'amount'",
        instancesWithActiveIncidentsCount: 17,
        activeInstancesCount: 0,
      },
    ],
  },
  {
    errorMessage:
      "Expected to throw an error event with the code 'unknown' with message 'Job worker throw error with error code: unknown', but it was not caught. Available error events are [boundary, subProcess]",
    instancesWithErrorCount: 17,
    processes: [
      {
        processId: '2251799813686151',
        version: 1,
        name: 'Error Process',
        bpmnProcessId: 'errorProcess',
        errorMessage:
          "Expected to throw an error event with the code 'unknown' with message 'Job worker throw error with error code: unknown', but it was not caught. Available error events are [boundary, subProcess]",
        instancesWithActiveIncidentsCount: 17,
        activeInstancesCount: 0,
      },
    ],
  },
  {
    errorMessage:
      "Expected to evaluate decision 'invoiceAssignApprover', but no decision found for id 'invoiceAssignApprover'",
    instancesWithErrorCount: 16,
    processes: [
      {
        processId: '2251799813686130',
        version: 1,
        name: 'DMN invoice',
        bpmnProcessId: 'invoice',
        errorMessage:
          "Expected to evaluate decision 'invoiceAssignApprover', but no decision found for id 'invoiceAssignApprover'",
        instancesWithActiveIncidentsCount: 16,
        activeInstancesCount: 0,
      },
    ],
  },
  {
    errorMessage: 'Loan request does not contain all the required data',
    instancesWithErrorCount: 10,
    processes: [
      {
        processId: '2251799813686116',
        version: 1,
        name: null,
        bpmnProcessId: 'loanProcess',
        errorMessage: 'Loan request does not contain all the required data',
        instancesWithActiveIncidentsCount: 10,
        activeInstancesCount: 0,
      },
    ],
  },
  {
    errorMessage: 'Cannot connect to server delivery05',
    instancesWithErrorCount: 9,
    processes: [
      {
        processId: '2251799813687188',
        version: 2,
        name: 'Order process',
        bpmnProcessId: 'orderProcess',
        errorMessage: 'Cannot connect to server delivery05',
        instancesWithActiveIncidentsCount: 6,
        activeInstancesCount: 0,
      },
      {
        processId: '2251799813686114',
        version: 1,
        name: 'Order process',
        bpmnProcessId: 'orderProcess',
        errorMessage: 'Cannot connect to server delivery05',
        instancesWithActiveIncidentsCount: 3,
        activeInstancesCount: 0,
      },
    ],
  },
  {
    errorMessage:
      "failed to evaluate expression 'paid = false': no variable found for name 'paid'",
    instancesWithErrorCount: 4,
    processes: [
      {
        processId: '2251799813687188',
        version: 2,
        name: 'Order process',
        bpmnProcessId: 'orderProcess',
        errorMessage:
          "failed to evaluate expression 'paid = false': no variable found for name 'paid'",
        instancesWithActiveIncidentsCount: 4,
        activeInstancesCount: 0,
      },
    ],
  },
  {
    errorMessage:
      "failed to evaluate expression 'paid = true': no variable found for name 'paid'",
    instancesWithErrorCount: 4,
    processes: [
      {
        processId: '2251799813686114',
        version: 1,
        name: 'Order process',
        bpmnProcessId: 'orderProcess',
        errorMessage:
          "failed to evaluate expression 'paid = true': no variable found for name 'paid'",
        instancesWithActiveIncidentsCount: 4,
        activeInstancesCount: 0,
      },
    ],
  },
  {
    errorMessage: 'Schufa system is not accessible',
    instancesWithErrorCount: 2,
    processes: [
      {
        processId: '2251799813686116',
        version: 1,
        name: null,
        bpmnProcessId: 'loanProcess',
        errorMessage: 'Schufa system is not accessible',
        instancesWithActiveIncidentsCount: 2,
        activeInstancesCount: 0,
      },
    ],
  },
  {
    errorMessage: 'No memory left.',
    instancesWithErrorCount: 1,
    processes: [
      {
        processId: '2251799813685257',
        version: 1,
        name: 'Only Incidents Process',
        bpmnProcessId: 'onlyIncidentsProcess',
        errorMessage: 'No memory left.',
        instancesWithActiveIncidentsCount: 1,
        activeInstancesCount: 0,
      },
    ],
  },
  {
    errorMessage: 'No space left on device.',
    instancesWithErrorCount: 1,
    processes: [
      {
        processId: '2251799813685301',
        version: 2,
        name: 'Only Incidents Process',
        bpmnProcessId: 'onlyIncidentsProcess',
        errorMessage: 'No space left on device.',
        instancesWithActiveIncidentsCount: 1,
        activeInstancesCount: 0,
      },
    ],
  },
  {
    errorMessage: 'error',
    instancesWithErrorCount: 1,
    processes: [
      {
        processId: '2251799813686141',
        version: 1,
        name: null,
        bpmnProcessId: 'nonInterruptingBoundaryEvent',
        errorMessage: 'error',
        instancesWithActiveIncidentsCount: 1,
        activeInstancesCount: 0,
      },
    ],
  },
  {
    errorMessage:
      "failed to evaluate expression 'smthIsMissing = true': no variable found for name 'smthIsMissing'",
    instancesWithErrorCount: 1,
    processes: [
      {
        processId: '2251799813687188',
        version: 2,
        name: 'Order process',
        bpmnProcessId: 'orderProcess',
        errorMessage:
          "failed to evaluate expression 'smthIsMissing = true': no variable found for name 'smthIsMissing'",
        instancesWithActiveIncidentsCount: 1,
        activeInstancesCount: 0,
      },
    ],
  },
  {
    errorMessage:
      'java.lang.RuntimeException: Payment system not available.\n\tat io.camunda.operate.data.develop.DevelopDataGenerator.lambda$progressOrderProcessCheckPayment$0(DevelopDataGenerator.java:233)\n\tat io.camunda.zeebe.client.impl.worker.JobRunnableFactory.executeJob(JobRunnableFactory.java:44)\n\tat io.camunda.zeebe.client.impl.worker.JobRunnableFactory.lambda$create$0(JobRunnableFactory.java:39)\n\tat java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577)\n\tat java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)\n\tat java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)\n\tat java.base/java.lang.Thread.run(Thread.java:1589)',
    instancesWithErrorCount: 1,
    processes: [
      {
        processId: '2251799813686114',
        version: 1,
        name: 'Order process',
        bpmnProcessId: 'orderProcess',
        errorMessage:
          'java.lang.RuntimeException: Payment system not available.\n\tat io.camunda.operate.data.develop.DevelopDataGenerator.lambda$progressOrderProcessCheckPayment$0(DevelopDataGenerator.java:233)\n\tat io.camunda.zeebe.client.impl.worker.JobRunnableFactory.executeJob(JobRunnableFactory.java:44)\n\tat io.camunda.zeebe.client.impl.worker.JobRunnableFactory.lambda$create$0(JobRunnableFactory.java:39)\n\tat java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577)\n\tat java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)\n\tat java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)\n\tat java.base/java.lang.Thread.run(Thread.java:1589)',
        instancesWithActiveIncidentsCount: 1,
        activeInstancesCount: 0,
      },
    ],
  },
];

const mockIncidentsByProcess = [
  {
    bpmnProcessId: 'orderProcess',
    processName: 'Order process',
    instancesWithActiveIncidentsCount: 141,
    activeInstancesCount: 5,
    processes: [
      {
        processId: '2251799813687188',
        version: 2,
        name: 'Order process',
        bpmnProcessId: 'orderProcess',
        errorMessage: null,
        instancesWithActiveIncidentsCount: 131,
        activeInstancesCount: 5,
      },
      {
        processId: '2251799813686114',
        version: 1,
        name: 'Order process',
        bpmnProcessId: 'orderProcess',
        errorMessage: null,
        instancesWithActiveIncidentsCount: 10,
        activeInstancesCount: 0,
      },
    ],
  },
  {
    bpmnProcessId: 'call-activity-process',
    processName: 'Call Activity Process',
    instancesWithActiveIncidentsCount: 90,
    activeInstancesCount: 15,
    processes: [
      {
        processId: '2251799813686145',
        version: 1,
        name: 'Call Activity Process',
        bpmnProcessId: 'call-activity-process',
        errorMessage: null,
        instancesWithActiveIncidentsCount: 90,
        activeInstancesCount: 15,
      },
    ],
  },
  {
    bpmnProcessId: 'complexProcess',
    processName: null,
    instancesWithActiveIncidentsCount: 90,
    activeInstancesCount: 13,
    processes: [
      {
        processId: '2251799813687889',
        version: 3,
        name: null,
        bpmnProcessId: 'complexProcess',
        errorMessage: null,
        instancesWithActiveIncidentsCount: 56,
        activeInstancesCount: 0,
      },
      {
        processId: '2251799813687201',
        version: 2,
        name: null,
        bpmnProcessId: 'complexProcess',
        errorMessage: null,
        instancesWithActiveIncidentsCount: 20,
        activeInstancesCount: 9,
      },
      {
        processId: '2251799813686132',
        version: 1,
        name: null,
        bpmnProcessId: 'complexProcess',
        errorMessage: null,
        instancesWithActiveIncidentsCount: 14,
        activeInstancesCount: 4,
      },
    ],
  },
  {
    bpmnProcessId: 'called-process',
    processName: null,
    instancesWithActiveIncidentsCount: 70,
    activeInstancesCount: 0,
    processes: [
      {
        processId: '2251799813687891',
        version: 2,
        name: null,
        bpmnProcessId: 'called-process',
        errorMessage: null,
        instancesWithActiveIncidentsCount: 56,
        activeInstancesCount: 0,
      },
      {
        processId: '2251799813687210',
        version: 1,
        name: 'Called Process',
        bpmnProcessId: 'called-process',
        errorMessage: null,
        instancesWithActiveIncidentsCount: 14,
        activeInstancesCount: 0,
      },
    ],
  },
  {
    bpmnProcessId: 'invoice',
    processName: 'DMN invoice',
    instancesWithActiveIncidentsCount: 33,
    activeInstancesCount: 35,
    processes: [
      {
        processId: '2251799813686130',
        version: 1,
        name: 'DMN invoice',
        bpmnProcessId: 'invoice',
        errorMessage: null,
        instancesWithActiveIncidentsCount: 33,
        activeInstancesCount: 35,
      },
    ],
  },
  {
    bpmnProcessId: 'eventBasedGatewayProcess',
    processName: 'Event based gateway with timer start',
    instancesWithActiveIncidentsCount: 26,
    activeInstancesCount: 0,
    processes: [
      {
        processId: '2251799813687203',
        version: 2,
        name: 'Event based gateway with timer start',
        bpmnProcessId: 'eventBasedGatewayProcess',
        errorMessage: null,
        instancesWithActiveIncidentsCount: 20,
        activeInstancesCount: 0,
      },
      {
        processId: '2251799813686134',
        version: 1,
        name: 'Event based gateway with message start',
        bpmnProcessId: 'eventBasedGatewayProcess',
        errorMessage: null,
        instancesWithActiveIncidentsCount: 6,
        activeInstancesCount: 0,
      },
    ],
  },
  {
    bpmnProcessId: 'flightRegistration',
    processName: 'Flight registration',
    instancesWithActiveIncidentsCount: 23,
    activeInstancesCount: 4,
    processes: [
      {
        processId: '2251799813687190',
        version: 2,
        name: 'Flight registration',
        bpmnProcessId: 'flightRegistration',
        errorMessage: null,
        instancesWithActiveIncidentsCount: 13,
        activeInstancesCount: 4,
      },
      {
        processId: '2251799813686118',
        version: 1,
        name: 'Flight registration',
        bpmnProcessId: 'flightRegistration',
        errorMessage: null,
        instancesWithActiveIncidentsCount: 10,
        activeInstancesCount: 0,
      },
    ],
  },
  {
    bpmnProcessId: 'error-end-process',
    processName: null,
    instancesWithActiveIncidentsCount: 20,
    activeInstancesCount: 0,
    processes: [
      {
        processId: '2251799813686153',
        version: 1,
        name: null,
        bpmnProcessId: 'error-end-process',
        errorMessage: null,
        instancesWithActiveIncidentsCount: 20,
        activeInstancesCount: 0,
      },
    ],
  },
  {
    bpmnProcessId: 'nonInterruptingBoundaryEvent',
    processName: null,
    instancesWithActiveIncidentsCount: 19,
    activeInstancesCount: 0,
    processes: [
      {
        processId: '2251799813687208',
        version: 2,
        name: null,
        bpmnProcessId: 'nonInterruptingBoundaryEvent',
        errorMessage: null,
        instancesWithActiveIncidentsCount: 16,
        activeInstancesCount: 0,
      },
      {
        processId: '2251799813686141',
        version: 1,
        name: null,
        bpmnProcessId: 'nonInterruptingBoundaryEvent',
        errorMessage: null,
        instancesWithActiveIncidentsCount: 3,
        activeInstancesCount: 0,
      },
    ],
  },
  {
    bpmnProcessId: 'prWithSubprocess',
    processName: 'Nested subprocesses',
    instancesWithActiveIncidentsCount: 19,
    activeInstancesCount: 0,
    processes: [
      {
        processId: '2251799813686137',
        version: 1,
        name: 'Nested subprocesses',
        bpmnProcessId: 'prWithSubprocess',
        errorMessage: null,
        instancesWithActiveIncidentsCount: 19,
        activeInstancesCount: 0,
      },
    ],
  },
  {
    bpmnProcessId: 'multiInstanceProcess',
    processName: 'Multi-Instance Process',
    instancesWithActiveIncidentsCount: 17,
    activeInstancesCount: 15,
    processes: [
      {
        processId: '2251799813687192',
        version: 2,
        name: 'Multi-Instance Process',
        bpmnProcessId: 'multiInstanceProcess',
        errorMessage: null,
        instancesWithActiveIncidentsCount: 17,
        activeInstancesCount: 0,
      },
      {
        processId: '2251799813686120',
        version: 1,
        name: 'Sequential Multi-Instance Process',
        bpmnProcessId: 'multiInstanceProcess',
        errorMessage: null,
        instancesWithActiveIncidentsCount: 0,
        activeInstancesCount: 15,
      },
    ],
  },
  {
    bpmnProcessId: 'errorProcess',
    processName: 'Error Process',
    instancesWithActiveIncidentsCount: 17,
    activeInstancesCount: 0,
    processes: [
      {
        processId: '2251799813686151',
        version: 1,
        name: 'Error Process',
        bpmnProcessId: 'errorProcess',
        errorMessage: null,
        instancesWithActiveIncidentsCount: 17,
        activeInstancesCount: 0,
      },
    ],
  },
  {
    bpmnProcessId: 'loanProcess',
    processName: null,
    instancesWithActiveIncidentsCount: 15,
    activeInstancesCount: 0,
    processes: [
      {
        processId: '2251799813686116',
        version: 1,
        name: null,
        bpmnProcessId: 'loanProcess',
        errorMessage: null,
        instancesWithActiveIncidentsCount: 15,
        activeInstancesCount: 0,
      },
    ],
  },
  {
    bpmnProcessId: 'eventSubprocessProcess',
    processName: 'Event Subprocess Process',
    instancesWithActiveIncidentsCount: 9,
    activeInstancesCount: 0,
    processes: [
      {
        processId: '2251799813686147',
        version: 1,
        name: 'Event Subprocess Process',
        bpmnProcessId: 'eventSubprocessProcess',
        errorMessage: null,
        instancesWithActiveIncidentsCount: 9,
        activeInstancesCount: 0,
      },
    ],
  },
  {
    bpmnProcessId: 'interruptingBoundaryEvent',
    processName: null,
    instancesWithActiveIncidentsCount: 9,
    activeInstancesCount: 0,
    processes: [
      {
        processId: '2251799813687206',
        version: 2,
        name: null,
        bpmnProcessId: 'interruptingBoundaryEvent',
        errorMessage: null,
        instancesWithActiveIncidentsCount: 8,
        activeInstancesCount: 0,
      },
      {
        processId: '2251799813686139',
        version: 1,
        name: null,
        bpmnProcessId: 'interruptingBoundaryEvent',
        errorMessage: null,
        instancesWithActiveIncidentsCount: 1,
        activeInstancesCount: 0,
      },
    ],
  },
  {
    bpmnProcessId: 'inclusiveGatewayProcess',
    processName: 'Inclusive gateway',
    instancesWithActiveIncidentsCount: 7,
    activeInstancesCount: 12,
    processes: [
      {
        processId: '2251799813686168',
        version: 1,
        name: 'Inclusive gateway',
        bpmnProcessId: 'inclusiveGatewayProcess',
        errorMessage: null,
        instancesWithActiveIncidentsCount: 7,
        activeInstancesCount: 12,
      },
    ],
  },
  {
    bpmnProcessId: 'linkEventProcess',
    processName: 'Link events process',
    instancesWithActiveIncidentsCount: 6,
    activeInstancesCount: 0,
    processes: [
      {
        processId: '2251799813686161',
        version: 1,
        name: 'Link events process',
        bpmnProcessId: 'linkEventProcess',
        errorMessage: null,
        instancesWithActiveIncidentsCount: 6,
        activeInstancesCount: 0,
      },
    ],
  },
  {
    bpmnProcessId: 'onlyIncidentsProcess',
    processName: 'Only Incidents Process',
    instancesWithActiveIncidentsCount: 2,
    activeInstancesCount: 20,
    processes: [
      {
        processId: '2251799813685257',
        version: 1,
        name: 'Only Incidents Process',
        bpmnProcessId: 'onlyIncidentsProcess',
        errorMessage: null,
        instancesWithActiveIncidentsCount: 1,
        activeInstancesCount: 10,
      },
      {
        processId: '2251799813685301',
        version: 2,
        name: 'Only Incidents Process',
        bpmnProcessId: 'onlyIncidentsProcess',
        errorMessage: null,
        instancesWithActiveIncidentsCount: 1,
        activeInstancesCount: 10,
      },
    ],
  },
  {
    bpmnProcessId: 'bigProcess',
    processName: null,
    instancesWithActiveIncidentsCount: 1,
    activeInstancesCount: 0,
    processes: [
      {
        processId: '2251799813686149',
        version: 1,
        name: null,
        bpmnProcessId: 'bigProcess',
        errorMessage: null,
        instancesWithActiveIncidentsCount: 1,
        activeInstancesCount: 0,
      },
    ],
  },
  {
    bpmnProcessId: 'escalationEvents',
    processName: 'Escalation events',
    instancesWithActiveIncidentsCount: 0,
    activeInstancesCount: 46,
    processes: [
      {
        processId: '2251799813687212',
        version: 2,
        name: 'Escalation events',
        bpmnProcessId: 'escalationEvents',
        errorMessage: null,
        instancesWithActiveIncidentsCount: 0,
        activeInstancesCount: 29,
      },
      {
        processId: '2251799813686163',
        version: 1,
        name: 'Escalation events',
        bpmnProcessId: 'escalationEvents',
        errorMessage: null,
        instancesWithActiveIncidentsCount: 0,
        activeInstancesCount: 17,
      },
    ],
  },
  {
    bpmnProcessId: 'withoutIncidentsProcess',
    processName: 'Without Incidents Process',
    instancesWithActiveIncidentsCount: 0,
    activeInstancesCount: 26,
    processes: [
      {
        processId: '2251799813685364',
        version: 2,
        name: 'Without Incidents Process',
        bpmnProcessId: 'withoutIncidentsProcess',
        errorMessage: null,
        instancesWithActiveIncidentsCount: 0,
        activeInstancesCount: 17,
      },
      {
        processId: '2251799813685350',
        version: 1,
        name: 'Without Incidents Process',
        bpmnProcessId: 'withoutIncidentsProcess',
        errorMessage: null,
        instancesWithActiveIncidentsCount: 0,
        activeInstancesCount: 9,
      },
    ],
  },
  {
    bpmnProcessId: 'signalEventProcess',
    processName: 'Signal event',
    instancesWithActiveIncidentsCount: 0,
    activeInstancesCount: 20,
    processes: [
      {
        processId: '2251799813686165',
        version: 1,
        name: 'Signal event',
        bpmnProcessId: 'signalEventProcess',
        errorMessage: null,
        instancesWithActiveIncidentsCount: 0,
        activeInstancesCount: 20,
      },
    ],
  },
  {
    bpmnProcessId: 'intermediate-message-throw-event-process',
    processName: null,
    instancesWithActiveIncidentsCount: 0,
    activeInstancesCount: 17,
    processes: [
      {
        processId: '2251799813686124',
        version: 1,
        name: null,
        bpmnProcessId: 'intermediate-message-throw-event-process',
        errorMessage: null,
        instancesWithActiveIncidentsCount: 0,
        activeInstancesCount: 17,
      },
    ],
  },
  {
    bpmnProcessId: 'terminateEndEvent',
    processName: 'Terminate End Event',
    instancesWithActiveIncidentsCount: 0,
    activeInstancesCount: 16,
    processes: [
      {
        processId: '2251799813686155',
        version: 1,
        name: 'Terminate End Event',
        bpmnProcessId: 'terminateEndEvent',
        errorMessage: null,
        instancesWithActiveIncidentsCount: 0,
        activeInstancesCount: 16,
      },
    ],
  },
  {
    bpmnProcessId: 'dataStoreProcess',
    processName: 'Data store process',
    instancesWithActiveIncidentsCount: 0,
    activeInstancesCount: 14,
    processes: [
      {
        processId: '2251799813686159',
        version: 1,
        name: 'Data store process',
        bpmnProcessId: 'dataStoreProcess',
        errorMessage: null,
        instancesWithActiveIncidentsCount: 0,
        activeInstancesCount: 14,
      },
    ],
  },
  {
    bpmnProcessId: 'message-end-event-process',
    processName: null,
    instancesWithActiveIncidentsCount: 0,
    activeInstancesCount: 14,
    processes: [
      {
        processId: '2251799813686128',
        version: 1,
        name: null,
        bpmnProcessId: 'message-end-event-process',
        errorMessage: null,
        instancesWithActiveIncidentsCount: 0,
        activeInstancesCount: 14,
      },
    ],
  },
  {
    bpmnProcessId: 'timerProcess',
    processName: 'Timer process',
    instancesWithActiveIncidentsCount: 0,
    activeInstancesCount: 3,
    processes: [
      {
        processId: '2251799813687198',
        version: 2,
        name: 'Timer process',
        bpmnProcessId: 'timerProcess',
        errorMessage: null,
        instancesWithActiveIncidentsCount: 0,
        activeInstancesCount: 2,
      },
      {
        processId: '2251799813686143',
        version: 1,
        name: 'Timer process',
        bpmnProcessId: 'timerProcess',
        errorMessage: null,
        instancesWithActiveIncidentsCount: 0,
        activeInstancesCount: 1,
      },
    ],
  },
  {
    bpmnProcessId: 'bigVarProcess',
    processName: 'Big variable process',
    instancesWithActiveIncidentsCount: 0,
    activeInstancesCount: 2,
    processes: [
      {
        processId: '2251799813685430',
        version: 1,
        name: 'Big variable process',
        bpmnProcessId: 'bigVarProcess',
        errorMessage: null,
        instancesWithActiveIncidentsCount: 0,
        activeInstancesCount: 2,
      },
    ],
  },
  {
    bpmnProcessId: 'Process_b1711b2e-ec8e-4dad-908c-8c12e028f32f',
    processName: 'Input Output Mapping Test',
    instancesWithActiveIncidentsCount: 0,
    activeInstancesCount: 1,
    processes: [
      {
        processId: '2251799813685251',
        version: 1,
        name: 'Input Output Mapping Test',
        bpmnProcessId: 'Process_b1711b2e-ec8e-4dad-908c-8c12e028f32f',
        errorMessage: null,
        instancesWithActiveIncidentsCount: 0,
        activeInstancesCount: 1,
      },
    ],
  },
  {
    bpmnProcessId: 'always-completing-process',
    processName: 'Always completing process',
    instancesWithActiveIncidentsCount: 0,
    activeInstancesCount: 0,
    processes: [
      {
        processId: '2251799813685249',
        version: 1,
        name: 'Always completing process',
        bpmnProcessId: 'always-completing-process',
        errorMessage: null,
        instancesWithActiveIncidentsCount: 0,
        activeInstancesCount: 0,
      },
    ],
  },
  {
    bpmnProcessId: 'intermediate-none-event-process',
    processName: null,
    instancesWithActiveIncidentsCount: 0,
    activeInstancesCount: 0,
    processes: [
      {
        processId: '2251799813686126',
        version: 1,
        name: null,
        bpmnProcessId: 'intermediate-none-event-process',
        errorMessage: null,
        instancesWithActiveIncidentsCount: 0,
        activeInstancesCount: 0,
      },
    ],
  },
  {
    bpmnProcessId: 'manual-task-process',
    processName: null,
    instancesWithActiveIncidentsCount: 0,
    activeInstancesCount: 0,
    processes: [
      {
        processId: '2251799813686122',
        version: 1,
        name: null,
        bpmnProcessId: 'manual-task-process',
        errorMessage: null,
        instancesWithActiveIncidentsCount: 0,
        activeInstancesCount: 0,
      },
    ],
  },
  {
    bpmnProcessId: 'noInstancesProcess',
    processName: 'Without Instances Process',
    instancesWithActiveIncidentsCount: 0,
    activeInstancesCount: 0,
    processes: [
      {
        processId: '2251799813685253',
        version: 1,
        name: 'Without Instances Process',
        bpmnProcessId: 'noInstancesProcess',
        errorMessage: null,
        instancesWithActiveIncidentsCount: 0,
        activeInstancesCount: 0,
      },
      {
        processId: '2251799813685255',
        version: 2,
        name: 'Without Instances Process',
        bpmnProcessId: 'noInstancesProcess',
        errorMessage: null,
        instancesWithActiveIncidentsCount: 0,
        activeInstancesCount: 0,
      },
    ],
  },
  {
    bpmnProcessId: 'undefined-task-process',
    processName: 'undefined-task',
    instancesWithActiveIncidentsCount: 0,
    activeInstancesCount: 0,
    processes: [
      {
        processId: '2251799813686157',
        version: 1,
        name: 'undefined-task',
        bpmnProcessId: 'undefined-task-process',
        errorMessage: null,
        instancesWithActiveIncidentsCount: 0,
        activeInstancesCount: 0,
      },
    ],
  },
];

export {mockStatistics, mockIncidentsByError, mockIncidentsByProcess};
