/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.frontend-webjar-conventions")
}

layout.buildDirectory.set(layout.projectDirectory.dir("target/gradle-build"))

frontendWebjar {
    frontendBuildDirectory.set(layout.projectDirectory.dir("build"))
    resourceTargetPath.set("META-INF/resources/tasklist")
}

description = "Tasklist Webjar"
