/*
 * This file was generated by the Gradle 'init' task.
 */

plugins { id("buildlogic.server-conventions") }

dependencies {
  implementation(project(":operate-common"))
  implementation(project(":camunda-cluster"))
  implementation(project(":webapps-schema"))
  implementation(project(":camunda-schema-manager"))
  implementation(libs.io.camunda.security.library.spring.boot.starter)
  implementation(libs.io.camunda.security.library.api)
  implementation(libs.io.camunda.security.library.core)
  implementation(libs.io.camunda.security.library.spring.boot.starter)
  implementation(project(":camunda-spring-utils"))
  api(libs.org.springframework.spring.context)
  api(libs.org.springframework.spring.web)
  api(libs.org.springframework.spring.beans)
  api(libs.org.springframework.boot.spring.boot.autoconfigure)
  implementation(project(":camunda-client-java"))
  implementation(project(":camunda-search-client"))
  implementation(project(":camunda-search-domain"))
  implementation(libs.org.slf4j.slf4j.api)
  implementation(project(":camunda-service"))
  implementation(project(":zeebe-protocol-impl"))
  implementation(project(":zeebe-protocol"))
  implementation(libs.com.fasterxml.jackson.core.jackson.core)
  api(libs.jakarta.annotation.jakarta.annotation.api)
  api(libs.com.fasterxml.jackson.core.jackson.databind)
  testImplementation(libs.org.mockito.mockito.core)
  testImplementation(libs.org.assertj.assertj.core)
  testImplementation(libs.org.junit.jupiter.junit.jupiter.api)
  testRuntimeOnly(libs.org.junit.jupiter.junit.jupiter.engine)
}

description = "Operate Data Generator"
