/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(project(":zeebe-exporter-api"))
    api(project(":zeebe-protocol"))
    api(project(":zeebe-util"))
    api(libs.org.apache.httpcomponents.httpclient)
    api(libs.org.apache.httpcomponents.httpcore)
    api(libs.com.fasterxml.jackson.core.jackson.databind)
    api(libs.com.fasterxml.jackson.core.jackson.core)
    api(libs.com.fasterxml.jackson.core.jackson.annotations)
    api(libs.com.fasterxml.jackson.datatype.jackson.datatype.jsr310)
    implementation("dev.failsafe:failsafe:3.3.2")
    implementation(libs.org.slf4j.slf4j.api)

    testImplementation(libs.org.assertj.assertj.core)
    testImplementation(libs.org.mockito.mockito.core)
    testImplementation(libs.org.junit.jupiter.junit.jupiter.api)
    testImplementation(project(":zeebe-exporter-test"))
    testImplementation(project(":zeebe-protocol-test-util"))
    testImplementation(libs.org.awaitility.awaitility)
    testImplementation(libs.org.wiremock.wiremock.standalone)
}

description = "Camunda App Integrations Exporter"
