/*
 * Copyright Camunda Services GmbH and/or licensed to Camunda Services GmbH under
 * one or more contributor license agreements. See the NOTICE file distributed
 * with this work for additional information regarding copyright ownership.
 * Licensed under the Camunda License 1.0. You may not use this file
 * except in compliance with the Camunda License 1.0.
 */

import type {ThemeTokens, TokenMap} from './buildThemeTokens';
import type {ThemeConfig} from './presets';

/** Marks the preview frame and every portal (popover, tooltip, select) opened from it. */
const PREVIEW_SCOPE_ATTRIBUTE = 'data-tasklist-theme-preview';

function toDeclarations(tokens: TokenMap, indent: string) {
	return Object.entries(tokens)
		.map(([name, value]) => `${indent}${name}: ${value};`)
		.join('\n');
}

function toRule(selector: string, tokens: TokenMap, indent = '') {
	if (Object.keys(tokens).length === 0) {
		return '';
	}

	return `${indent}${selector} {\n${toDeclarations(tokens, `${indent}  `)}\n${indent}}`;
}

/**
 * The `custom.css` file to deploy. The `html` prefix makes the selectors more specific than the
 * design system defaults, which load after `custom.css`.
 */
function toCustomCss({light, dark}: ThemeTokens, config: ThemeConfig) {
	const header = [
		'/*',
		' * Tasklist custom theme, generated by the Tasklist theme editor.',
		` * Base: ${config.base}, primary: ${config.primary}, accent: ${config.accent}, radius: ${config.radius}.`,
		' *',
		' * Place this file at /usr/local/camunda/config/custom.css (Docker) or',
		' * camunda-zeebe-<version>/config/custom.css (distribution archive), then restart Camunda.',
		' */',
	].join('\n');
	const rules = [
		toRule('/* Light theme */\nhtml .c4-ui', light),
		toRule('/* Dark theme */\nhtml .c4-ui.dark,\nhtml .dark .c4-ui', dark),
	].filter((rule) => rule !== '');

	if (rules.length === 0) {
		return `${header}\n\n/* No changes from the default theme. */\n`;
	}

	return `${header}\n\n${rules.join('\n\n')}\n`;
}

/**
 * The same tokens, limited to the preview frame and its portals with `@scope`. Scoped rules win
 * over the unscoped design system rules with the same specificity, because of scope proximity.
 */
function toPreviewCss({light, dark}: ThemeTokens) {
	const rules = [toRule('.c4-ui', light, '  '), toRule('.c4-ui.dark,\n  .dark .c4-ui', dark, '  ')].filter(
		(rule) => rule !== '',
	);

	if (rules.length === 0) {
		return '';
	}

	return `@scope ([${PREVIEW_SCOPE_ATTRIBUTE}]) {\n${rules.join('\n\n')}\n}\n`;
}

export {PREVIEW_SCOPE_ATTRIBUTE, toCustomCss, toPreviewCss};
