/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(project(":zeebe-util"))
    api(libs.com.google.guava.guava)
    api(libs.org.apache.commons.commons.lang3)
    api(libs.com.esotericsoftware.kryo)
    api(libs.org.objenesis.objenesis)
    api(libs.org.slf4j.slf4j.api)
    api(libs.com.esotericsoftware.minlog)
    api(libs.io.netty.netty.common)
    testImplementation(libs.junit.junit)
    testImplementation(libs.org.junit.jupiter.junit.jupiter.api)
    testImplementation(libs.org.assertj.assertj.core)
    testImplementation(libs.org.awaitility.awaitility)
}

description = "Zeebe Atomix Utilities"
