/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    implementation(project(":camunda-process-test-spring"))
}

description = "Camunda Process Test Spring Boot 4"
