@startuml
actor User as user
participant "Front-End" as fe
participant "BE: Services" as serv
participant "BE: Reader/Writer" as re
database "Elasticsearch" as els

user -> fe: Request via browser
activate fe

fe -> serv: REST call to Services
note right: Services are @RESTControllers\nin the spring context
activate serv

serv -> serv: Apply validations, if write operation

serv -> re: Request data to reader
note right: Readers (or Writers to write operations)\nare accessing our data.\nTherefore, acting as repositories
activate re

re -> els: Make a query to Elasticsearch (via ES library)
activate els

els -> re: Return raw index data
deactivate els

re -> serv: Parse data and return DTO
deactivate re

serv -> fe: Return DTO as JSON
deactivate serv

fe -> user: Render data on screen
deactivate fe
@enduml
