/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    implementation(libs.org.slf4j.slf4j.api)
    api(libs.com.fasterxml.jackson.core.jackson.annotations)
    api(project(":zeebe-protocol"))
    api(project(":camunda-security-protocol"))
    testImplementation(libs.org.junit.jupiter.junit.jupiter.engine)
    testImplementation(libs.org.junit.jupiter.junit.jupiter.api)
    testImplementation(libs.org.junit.jupiter.junit.jupiter.params)
    testImplementation(libs.org.junit.platform.junit.platform.commons.x1)
    testImplementation(libs.org.assertj.assertj.core)
    testImplementation(libs.org.reflections.reflections)
    testImplementation(libs.com.fasterxml.jackson.core.jackson.databind)
}

description = "Webapps Schema"
