/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    implementation(project(":zeebe-backup"))
    implementation(project(":zeebe-atomix-cluster"))
    implementation(project(":zeebe-db"))
    implementation(project(":zeebe-snapshots"))
    implementation(project(":zeebe-util"))
    implementation(project(":zeebe-journal"))
    implementation(project(":zeebe-cluster-config"))
    implementation(project(":zeebe-scheduler"))
    implementation(project(":zeebe-broker"))
    implementation(project(":camunda-db-rdbms"))
    implementation(libs.org.slf4j.slf4j.api)
    implementation(libs.org.agrona.agrona)
    implementation(libs.io.micrometer.micrometer.core)
    testImplementation(project(":zeebe-protocol"))
    testImplementation(project(":zeebe-logstreams", configuration = "tests"))
    testImplementation(libs.org.assertj.assertj.core)
    testImplementation(libs.org.junit.jupiter.junit.jupiter.api)
    testImplementation(libs.org.mockito.mockito.core)
}

description = "Zeebe Backup Restore"
