---
# Source: camunda-platform/templates/optimize/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: optimize
  labels:
    app: camunda-platform
    app.kubernetes.io/name: camunda-platform
    app.kubernetes.io/instance: c8-ck-test-realistic
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: camunda-platform
    camunda.io/created-by: ck-claude-test
    camunda.io/purpose: load-test
    helm.sh/chart: camunda-platform-15.0.0-alpha0
    app.kubernetes.io/component: optimize
    app.kubernetes.io/version: "8.9.0"
automountServiceAccountToken: false
