{{- if .Values.keycloak.postgresql.enabled -}}
---
# The PostgreSQL database to host Keycloak data
# Reference: https://cloudnative-pg.io/docs/1.30/cloudnative-pg.v1#database
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: {{ .Values.keycloak.postgresql.databaseName }}
spec:
  # The CNPG Cluster to manage the database in.
  cluster:
    name: {{ .Values.keycloak.postgresql.clusterName }}

  # The name of the PostgreSQL database to create.
  name: {{ .Values.keycloak.postgresql.databaseName }}

  # The name of the PostgreSQL user who will be the owner of the database.
  # This should match the "DatabaseRole" configured in this folder.
  owner: {{ .Values.keycloak.postgresql.databaseUser }}
{{- end -}}
