/*
 * Copyright Camunda Services GmbH and/or licensed to Camunda Services GmbH under
 * one or more contributor license agreements. See the NOTICE file distributed
 * with this work for additional information regarding copyright ownership.
 * Licensed under the Camunda License 1.0. You may not use this file
 * except in compliance with the Camunda License 1.0.
 */
package physicaltenants

import (
	"bytes"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"runtime"
	"strings"

	"github.com/camunda/camunda/c8run/internal/types"
	"gopkg.in/yaml.v3"
)

// GeneratedConfigName is written into the c8run configuration directory. Spring only
// auto-loads application.yaml from that directory, so c8run adds this file explicitly.
const GeneratedConfigName = "physical-tenants.generated.yaml"

func isWindows() bool { return runtime.GOOS == "windows" }

// StoragePrefix returns the secondary-storage namespace a tenant gets for a storage type,
// and the camunda.data.secondary-storage sub-key it lives under.
func StoragePrefix(id, storageType string) (key, value string) {
	switch strings.ToLower(storageType) {
	case "elasticsearch", "opensearch":
		return strings.ToLower(storageType) + ".index-prefix", id
	case "none":
		return "", ""
	default: // rdbms (bundled H2 included) and unset
		return "rdbms.prefix", strings.ToUpper(id) + "_"
	}
}

// Render produces the Spring config declaring every tenant's storage isolation. Logins are
// passed through the environment (see CredentialEnv) so passwords never touch disk here.
func Render(tenants []types.PhysicalTenant, storageType string) ([]byte, error) {
	perTenant := map[string]any{}
	for _, t := range tenants {
		tenant := map[string]any{}
		key, value := StoragePrefix(t.ID, storageType)
		if key != "" {
			storage := map[string]any{}
			parts := strings.SplitN(key, ".", 2)
			inner := map[string]any{parts[1]: value}
			if parts[0] != "rdbms" {
				inner["history"] = map[string]any{
					"policy-name":               t.ID + "-camunda-retention-policy",
					"usage-metrics-policy-name": t.ID + "-camunda-usage-metrics-retention-policy",
				}
			}
			storage[parts[0]] = inner
			tenant["data"] = map[string]any{"secondary-storage": storage}
		}
		perTenant[t.ID] = tenant
	}
	var buf bytes.Buffer
	buf.WriteString("# Generated by c8run from `c8run tenants` / --physical-tenants. Do not edit:\n")
	buf.WriteString("# it is rewritten on every start. Put custom tenant settings in your --config file.\n")
	enc := yaml.NewEncoder(&buf)
	enc.SetIndent(2)
	if err := enc.Encode(map[string]any{"camunda": map[string]any{"physical-tenants": perTenant}}); err != nil {
		return nil, err
	}
	if err := enc.Close(); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

// CredentialEnv returns the environment that seeds each tenant's login and admin role.
// Lists are not merged across Spring property sources, so the whole block goes here.
func CredentialEnv(tenants []types.PhysicalTenant) map[string]string {
	env := map[string]string{}
	for _, t := range tenants {
		prefix := "CAMUNDA_PHYSICALTENANTS_" + strings.ToUpper(t.ID) + "_SECURITY_INITIALIZATION_"
		env[prefix+"USERS_0_USERNAME"] = t.Username
		env[prefix+"USERS_0_PASSWORD"] = t.Password
		env[prefix+"USERS_0_NAME"] = t.Username
		env[prefix+"USERS_0_EMAIL"] = t.Username + "@example.com"
		env[prefix+"DEFAULTROLES_ADMIN_USERS_0"] = t.Username
	}
	return env
}

// WriteGeneratedConfig writes (or, with no tenants, removes) the generated config file.
func WriteGeneratedConfig(baseDir string, tenants []types.PhysicalTenant, storageType string) (string, error) {
	return WriteGeneratedConfigForPort(baseDir, tenants, storageType, 0)
}

// portMarker records the port c8run was started on so `c8run tenants` prints matching URLs.
const portMarker = "# c8run-port: "

// WriteGeneratedConfigForPort is WriteGeneratedConfig that also records the Camunda port.
func WriteGeneratedConfigForPort(baseDir string, tenants []types.PhysicalTenant, storageType string, port int) (string, error) {
	path := filepath.Join(baseDir, "configuration", GeneratedConfigName)
	if len(tenants) == 0 {
		if err := os.Remove(path); err != nil && !errors.Is(err, os.ErrNotExist) {
			return "", err
		}
		return "", nil
	}
	content, err := Render(tenants, storageType)
	if err != nil {
		return "", err
	}
	if port > 0 {
		content = append([]byte(fmt.Sprintf("%s%d\n", portMarker, port)), content...)
	}
	if err := atomicWrite(path, content, 0o644); err != nil {
		return "", fmt.Errorf("failed to write %s: %w", path, err)
	}
	return path, nil
}

// ConfigDeclaresTenants reports whether a Spring YAML file declares camunda.physical-tenants.
func ConfigDeclaresTenants(path string) bool {
	content, err := os.ReadFile(path)
	if err != nil {
		return false
	}
	var root map[string]any
	if yaml.Unmarshal(content, &root) != nil {
		return strings.Contains(string(content), "physical-tenants")
	}
	if camunda, ok := root["camunda"].(map[string]any); ok {
		if _, ok := camunda["physical-tenants"]; ok {
			return true
		}
		if _, ok := camunda["physicalTenants"]; ok {
			return true
		}
	}
	for key := range root {
		if strings.HasPrefix(key, "camunda.physical-tenants.") {
			return true
		}
	}
	return false
}

// ResolveInput is everything Resolve needs; it keeps the function free of globals for tests.
type ResolveInput struct {
	Store           *Store
	FlagIDs         []string
	DefaultUsername string
	DefaultPassword string
	// UserConfigs are the user-provided --config files (not the bundled default).
	UserConfigs         []string
	ConnectorsEnabled   bool
	FirstConnectorsPort int
	PortFree            func(int) bool
}

// Resolution is the outcome of Resolve, including user-facing notices.
type Resolution struct {
	Tenants []types.PhysicalTenant
	Notices []string
}

// Resolve decides which tenants this run starts: --physical-tenants wins for this run only,
// otherwise the persisted tenants. A user --config declaring tenants takes over completely.
func Resolve(in ResolveInput) (Resolution, error) {
	var res Resolution
	mode, err := Mode()
	if err != nil {
		return res, err
	}
	for _, path := range in.UserConfigs {
		if ConfigDeclaresTenants(path) {
			if len(in.FlagIDs) > 0 {
				return res, fmt.Errorf("--physical-tenants cannot be combined with a --config that declares camunda.physical-tenants (%s); use one or the other", path)
			}
			res.Notices = append(res.Notices, fmt.Sprintf("Physical tenants are declared in %s; tenants managed with `c8run tenants` are not applied.", path))
			return res, nil
		}
	}

	var stored []Tenant
	if len(in.FlagIDs) > 0 {
		for _, id := range in.FlagIDs {
			stored = append(stored, Tenant{ID: id})
		}
	} else if mode == "local" && in.Store != nil {
		if stored, err = in.Store.List(); err != nil {
			return res, err
		}
	}

	port := in.FirstConnectorsPort
	for _, st := range stored {
		t := types.PhysicalTenant{ID: st.ID, Username: in.DefaultUsername, Password: in.DefaultPassword}
		if st.Username != "" {
			pw, ok, err := in.Store.Password(st.ID)
			if err != nil {
				return res, err
			}
			if !ok {
				return res, fmt.Errorf("physical tenant %q has user %q but no stored password; run `c8run tenants remove %s` and add it again", st.ID, st.Username, st.ID)
			}
			t.Username, t.Password = st.Username, pw
		}
		if in.ConnectorsEnabled && !st.NoConnectors {
			for in.PortFree != nil && !in.PortFree(port) && port < 65535 {
				port++
			}
			t.Connectors, t.ConnectorsPort = true, port
			port++
		}
		res.Tenants = append(res.Tenants, t)
	}
	return res, nil
}

// LastStartPort returns the port recorded by the last start with physical tenants, or 0.
func LastStartPort(baseDir string) int {
	content, err := os.ReadFile(filepath.Join(baseDir, "configuration", GeneratedConfigName))
	if err != nil {
		return 0
	}
	for _, line := range strings.Split(string(content), "\n") {
		if strings.HasPrefix(line, portMarker) {
			var port int
			if _, err := fmt.Sscanf(strings.TrimPrefix(line, portMarker), "%d", &port); err == nil {
				return port
			}
		}
	}
	return 0
}
