/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.server-conventions")
}

// Maven surefire excludes *Test classes; failsafe runs them as ITs (require Docker/Testcontainers).
tasks.named<Test>("test") {
    exclude("**/*Test.class", "**/*Test\$*.class")
}

val it by tasks.registering(Test::class) {
    group = "verification"
    description = "Runs integration tests (require Docker)"
    testClassesDirs = tasks.named<Test>("test").get().testClassesDirs
    classpath = tasks.named<Test>("test").get().classpath
    include("**/*Test.class", "**/*Test\$*.class")
    shouldRunAfter(tasks.named("test"))
}

dependencies {
    implementation(project(":camunda-spring-boot-starter"))
    testImplementation(project(":camunda-process-test-spring"))
    testImplementation(project(":camunda-process-test-java"))
    testImplementation(project(":camunda-process-test-json-test-cases"))
    testImplementation(libs.org.springframework.boot.spring.boot.starter.test)
    testImplementation(libs.org.springframework.boot.spring.boot.test)
    testImplementation(libs.org.mockito.mockito.core)
    testImplementation(libs.org.awaitility.awaitility)
    testImplementation(libs.org.springframework.spring.test)
    testImplementation(libs.org.wiremock.integrations.wiremock.spring.boot)
}

description = "Camunda Process Test Example"
