/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.server-conventions")
    id("buildlogic.netty-tcnative-runtime-conventions")
}

dependencies {
    implementation(project(":zeebe-auth"))
    implementation(project(":zeebe-gateway-protocol-impl"))
    implementation(project(":zeebe-util"))
    implementation(project(":zeebe-atomix-utils"))
    implementation(project(":zeebe-scheduler"))
    implementation(project(":zeebe-auth"))
    implementation(project(":zeebe-protocol"))
    implementation(project(":zeebe-protocol-impl"))
    implementation(project(":camunda-security-core"))
    implementation(project(":camunda-security-protocol"))
    implementation(libs.io.camunda.security.library.api)
    implementation(project(":zeebe-msgpack-value"))
    implementation(project(":zeebe-broker-client"))
    implementation(project(":zeebe-cluster-config"))
    implementation(project(":camunda-search-domain"))
    api(libs.org.agrona.agrona)
    implementation(libs.org.slf4j.slf4j.api)
    implementation(project(":zeebe-atomix-cluster"))
    api(libs.com.fasterxml.jackson.core.jackson.core)
    api(libs.org.springframework.spring.core)
    api(libs.io.micrometer.micrometer.commons)
    api(libs.io.micrometer.micrometer.core)
    runtimeOnly(libs.io.netty.netty.tcnative.boringssl.static)
    testImplementation(project(":zeebe-test-util"))
    testImplementation(project(":zeebe-scheduler", configuration = "tests"))
    testImplementation(libs.junit.junit)
    testRuntimeOnly(libs.org.junit.vintage.junit.vintage.engine.x1)
    testImplementation(libs.org.mockito.mockito.core)
}

description = "Zeebe Gateway"

val testsJar by tasks.registering(Jar::class) {
    archiveClassifier = "tests"
    from(sourceSets["test"].output)
}

val tests by configurations.creating {
    isCanBeConsumed = true
    isCanBeResolved = false
    extendsFrom(configurations["testRuntimeClasspath"])
}

artifacts {
    add("tests", testsJar)
}

(publishing.publications["maven"] as MavenPublication).artifact(testsJar)
