      - CAMUNDA_SECURITY_AUTHENTICATION_METHOD=basic
      - CAMUNDA_SECURITY_AUTHORIZATIONS_ENABLED=true
      - CAMUNDA_SECURITY_INITIALIZATION_USERS_0__USERNAME=demo
      - CAMUNDA_SECURITY_INITIALIZATION_USERS_0__PASSWORD=demo
      - CAMUNDA_SECURITY_INITIALIZATION_USERS_0__NAME=Demo
      - CAMUNDA_SECURITY_INITIALIZATION_USERS_0__EMAIL=demo@example.com
      - CAMUNDA_SECURITY_INITIALIZATION_USERS_1__USERNAME=connectors
      - CAMUNDA_SECURITY_INITIALIZATION_USERS_1__PASSWORD=connectors
      - CAMUNDA_SECURITY_INITIALIZATION_USERS_1__NAME=Connectors
      - CAMUNDA_SECURITY_INITIALIZATION_DEFAULTROLES_ADMIN_USERS_0_=demo
      - CAMUNDA_SECURITY_INITIALIZATION_DEFAULTROLES_ADMIN_USERS_1_=connectors
