      - CAMUNDA_SECURITY_AUTHENTICATION_METHOD=oidc
      - CAMUNDA_SECURITY_AUTHENTICATION_OIDC_ISSUERURI=http://{{ENV_NAME}}-keycloak:8080/realms/camunda-platform
      - CAMUNDA_SECURITY_AUTHENTICATION_OIDC_CLIENTID=camunda
      - CAMUNDA_SECURITY_AUTHENTICATION_OIDC_CLIENTSECRET=camunda-secret
      - CAMUNDA_SECURITY_AUTHENTICATION_OIDC_USERNAMECLAIM=preferred_username
      - CAMUNDA_SECURITY_AUTHORIZATIONS_ENABLED=false
