      - CAMUNDA_DATA_SECONDARYSTORAGE_TYPE=rdbms
      - CAMUNDA_DATA_SECONDARYSTORAGE_RDBMS_URL=jdbc:{{DB_TYPE}}://{{ENV_NAME}}-{{DB_TYPE}}:3306/camunda
      - CAMUNDA_DATA_SECONDARYSTORAGE_RDBMS_USERNAME=camunda
      - CAMUNDA_DATA_SECONDARYSTORAGE_RDBMS_PASSWORD=camunda
