      - CAMUNDA_DATA_SECONDARYSTORAGE_TYPE=rdbms
      - CAMUNDA_DATA_SECONDARYSTORAGE_RDBMS_URL=jdbc:sqlserver://{{ENV_NAME}}-mssql:1433;encrypt=false
      - CAMUNDA_DATA_SECONDARYSTORAGE_RDBMS_USERNAME=sa
      - CAMUNDA_DATA_SECONDARYSTORAGE_RDBMS_PASSWORD=Camunda#8_demo
