      - CAMUNDA_DATA_SECONDARYSTORAGE_TYPE=rdbms
      - CAMUNDA_DATA_SECONDARYSTORAGE_RDBMS_URL=jdbc:oracle:thin:@{{ENV_NAME}}-oracle:1521/FREEPDB1
      - CAMUNDA_DATA_SECONDARYSTORAGE_RDBMS_USERNAME=camunda
      - CAMUNDA_DATA_SECONDARYSTORAGE_RDBMS_PASSWORD=camunda
