      - ZEEBE_BROKER_EXPORTERS_CAMUNDAEXPORTER_CLASSNAME=io.camunda.exporter.CamundaExporter
      - ZEEBE_BROKER_EXPORTERS_CAMUNDAEXPORTER_ARGS_CONNECT_URL=http://{{ENV_NAME}}-opensearch:9200
      - CAMUNDA_DATA_SECONDARYSTORAGE_TYPE=opensearch
