      - CAMUNDA_DATA_SECONDARYSTORAGE_TYPE=rdbms
      - CAMUNDA_DATA_SECONDARYSTORAGE_RDBMS_URL=jdbc:postgresql://{{ENV_NAME}}-postgres:5432/camunda
      - CAMUNDA_DATA_SECONDARYSTORAGE_RDBMS_USERNAME=camunda
      - CAMUNDA_DATA_SECONDARYSTORAGE_RDBMS_PASSWORD=camunda
