/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(libs.org.agrona.agrona)
    api(libs.org.slf4j.slf4j.api)
    api(project(":zeebe-atomix-cluster"))
    api(project(":zeebe-atomix-utils"))
    api(project(":zeebe-cluster-config"))
    api(project(":zeebe-protocol"))
    api(project(":zeebe-protocol-impl"))
    api(project(":zeebe-scheduler"))
    api(project(":zeebe-transport"))
    api(project(":zeebe-util"))
    api(libs.io.micrometer.micrometer.commons)
    api(libs.io.micrometer.micrometer.core)
    testImplementation(project(":zeebe-test-util"))
    testImplementation(project(":zeebe-scheduler"))
    testImplementation(libs.org.junit.jupiter.junit.jupiter.api)
    testImplementation(libs.org.assertj.assertj.core)
    testImplementation(project(":zeebe-protocol-test-util"))
    testImplementation(libs.org.awaitility.awaitility)
    testImplementation(libs.org.hamcrest.hamcrest)
}

description = "Zeebe Broker Client"
