/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.server-conventions")
}

dependencies {
    implementation(libs.org.apache.commons.commons.lang3)
    api(libs.com.fasterxml.jackson.core.jackson.annotations)
    implementation(libs.org.slf4j.slf4j.api)
    implementation(libs.io.camunda.security.library.api)
    implementation(libs.io.camunda.security.library.core)
    implementation(project(":camunda-security-core"))
    implementation(project(":camunda-security-protocol"))
    implementation(project(":zeebe-protocol"))
    implementation(project(":camunda-spring-utils"))
}

description = "Camunda Search Domain"
