/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    implementation(libs.org.apache.commons.commons.lang3)
    api(libs.com.fasterxml.jackson.core.jackson.annotations)
    implementation(libs.org.slf4j.slf4j.api)
    api(project(":camunda-security-core"))
    api(project(":camunda-security-protocol"))
    api(project(":zeebe-protocol"))
    api(project(":camunda-spring-utils"))
    testImplementation(libs.org.junit.jupiter.junit.jupiter.api)
    testImplementation(libs.org.junit.jupiter.junit.jupiter.params)
    testImplementation(libs.org.assertj.assertj.core)
}

description = "Camunda Search Domain"
