# Additional values file to run Zeebe on preemptible/spot VMs
zeebe:
  # Require n2-standard-4 to ensure the broker is the only application running on its node
  nodeSelector:
    component: benchmark-n2-standard-4
    topology.kubernetes.io/zone: __AVAILABILITY_ZONE__

  tolerations:
  - key: nodepool
    operator: Equal
    value: n2-standard-4
    effect: NoSchedule
