# Additional values file to run Zeebe on preemptible/spot VMs
zeebe:
  # Require n2-standard-2 to ensure the broker is the only application running on its node
  nodeSelector:
    cloud.google.com/gke-nodepool: n2-standard-2

  tolerations:
  - key: nodepool
    operator: Equal
    value: n2-standard-2
    effect: NoSchedule
