apiVersion: v1
kind: Namespace
metadata:
  name: __NAMESPACE__
  labels:
    camunda.io/purpose: load-test
    camunda.io/created-by: __AUTHOR__
    deadline-date: "__DEADLINE_DATE__"
    registry: harbor
  annotations:
    topology.kubernetes.io/zone: __AVAILABILITY_ZONE__
