/*
 * Copyright Camunda Services GmbH and/or licensed to Camunda Services GmbH under
 * one or more contributor license agreements. See the NOTICE file distributed
 * with this work for additional information regarding copyright ownership.
 * Licensed under the Camunda License 1.0. You may not use this file
 * except in compliance with the Camunda License 1.0.
 */

import type {
  ProcessInstance,
  ProcessDefinition,
  Variable,
  ElementInstance,
  Job,
} from '@camunda/camunda-api-zod-schemas/8.10';

import {
  MOCK_LOAN_INSTANCE_KEY,
  MOCK_LOAN_DEFINITION_KEY,
  MOCK_LOAN_DEFINITION_ID,
  MOCK_LOAN_AGENT_TASK_KEY,
  MOCK_LOAN_AGENT_ITERATION_1_KEY,
  MOCK_LOAN_AGENT_ITERATION_2_KEY,
  MOCK_LOAN_AGENT_ITERATION_3_KEY,
  MOCK_LOAN_TOOLS_ITERATION_1_KEY,
  MOCK_LOAN_TOOLS_ITERATION_2_KEY,
} from './constants';

// Extended type for mock data — flowScopeKey is not in the API type but needed for scope filtering
type MockElementInstance = ElementInstance & {flowScopeKey: string};

export const MOCK_LOAN_PROCESS_INSTANCE: ProcessInstance = {
  processInstanceKey: MOCK_LOAN_INSTANCE_KEY,
  processDefinitionName: 'Loan Evaluation',
  processDefinitionId: MOCK_LOAN_DEFINITION_ID,
  processDefinitionKey: MOCK_LOAN_DEFINITION_KEY,
  processDefinitionVersion: 1,
  processDefinitionVersionTag: null,
  tenantId: '<default>',
  state: 'COMPLETED',
  startDate: '2026-04-10T09:15:00.000Z',
  endDate: '2026-04-10T09:15:07.800Z',
  hasIncident: false,
  parentProcessInstanceKey: null,
  parentElementInstanceKey: null,
  rootProcessInstanceKey: null,
  tags: [],
};

export const MOCK_LOAN_PROCESS_DEFINITION: ProcessDefinition = {
  name: 'Loan Evaluation',
  processDefinitionId: MOCK_LOAN_DEFINITION_ID,
  processDefinitionKey: MOCK_LOAN_DEFINITION_KEY,
  resourceName: 'loan-evaluation.bpmn',
  version: 1,
  versionTag: null,
  tenantId: '<default>',
  hasStartForm: false,
};

export const MOCK_LOAN_ELEMENT_INSTANCES: MockElementInstance[] = [
  // Process root
  {
    elementInstanceKey: MOCK_LOAN_INSTANCE_KEY,
    processInstanceKey: MOCK_LOAN_INSTANCE_KEY,
    processDefinitionKey: MOCK_LOAN_DEFINITION_KEY,
    processDefinitionId: MOCK_LOAN_DEFINITION_ID,
    elementId: MOCK_LOAN_DEFINITION_ID,
    elementName: 'Loan Evaluation',
    type: 'PROCESS',
    state: 'COMPLETED',
    hasIncident: false,
    flowScopeKey: MOCK_LOAN_INSTANCE_KEY,
    rootProcessInstanceKey: null,
    tenantId: '<default>',
    startDate: '2026-04-10T09:15:00.000Z',
    endDate: '2026-04-10T09:15:07.800Z',
    incidentKey: null,
  },
  // Start event
  {
    elementInstanceKey: '5551799813685001',
    processInstanceKey: MOCK_LOAN_INSTANCE_KEY,
    processDefinitionKey: MOCK_LOAN_DEFINITION_KEY,
    processDefinitionId: MOCK_LOAN_DEFINITION_ID,
    elementId: 'start',
    elementName: 'Loan application received',
    type: 'START_EVENT',
    state: 'COMPLETED',
    hasIncident: false,
    flowScopeKey: MOCK_LOAN_INSTANCE_KEY,
    rootProcessInstanceKey: null,
    tenantId: '<default>',
    startDate: '2026-04-10T09:15:00.050Z',
    endDate: '2026-04-10T09:15:00.080Z',
    incidentKey: null,
  },
  // Create prompt
  {
    elementInstanceKey: '5551799813685002',
    processInstanceKey: MOCK_LOAN_INSTANCE_KEY,
    processDefinitionKey: MOCK_LOAN_DEFINITION_KEY,
    processDefinitionId: MOCK_LOAN_DEFINITION_ID,
    elementId: 'create_prompt',
    elementName: 'Create prompt',
    type: 'SCRIPT_TASK',
    state: 'COMPLETED',
    hasIncident: false,
    flowScopeKey: MOCK_LOAN_INSTANCE_KEY,
    rootProcessInstanceKey: null,
    tenantId: '<default>',
    startDate: '2026-04-10T09:15:00.100Z',
    endDate: '2026-04-10T09:15:00.150Z',
    incidentKey: null,
  },
  // Merge gateway — executed 3 times (initial + 2 loops)
  {
    elementInstanceKey: '5551799813685003',
    processInstanceKey: MOCK_LOAN_INSTANCE_KEY,
    processDefinitionKey: MOCK_LOAN_DEFINITION_KEY,
    processDefinitionId: MOCK_LOAN_DEFINITION_ID,
    elementId: 'merge_gateway',
    elementName: null,
    type: 'EXCLUSIVE_GATEWAY',
    state: 'COMPLETED',
    hasIncident: false,
    flowScopeKey: MOCK_LOAN_INSTANCE_KEY,
    rootProcessInstanceKey: null,
    tenantId: '<default>',
    startDate: '2026-04-10T09:15:00.160Z',
    endDate: '2026-04-10T09:15:00.180Z',
    incidentKey: null,
  },
  // Agent task — iteration 1
  {
    elementInstanceKey: MOCK_LOAN_AGENT_ITERATION_1_KEY,
    processInstanceKey: MOCK_LOAN_INSTANCE_KEY,
    processDefinitionKey: MOCK_LOAN_DEFINITION_KEY,
    processDefinitionId: MOCK_LOAN_DEFINITION_ID,
    elementId: 'ai_task_agent',
    elementName: 'Risk Assessment Agent',
    type: 'SERVICE_TASK',
    state: 'COMPLETED',
    hasIncident: false,
    flowScopeKey: MOCK_LOAN_INSTANCE_KEY,
    rootProcessInstanceKey: null,
    tenantId: '<default>',
    startDate: '2026-04-10T09:15:00.200Z',
    endDate: '2026-04-10T09:15:02.800Z',
    incidentKey: null,
  },
  // Tool check gateway — iteration 1 (Yes -> tools)
  {
    elementInstanceKey: '5551799813685014',
    processInstanceKey: MOCK_LOAN_INSTANCE_KEY,
    processDefinitionKey: MOCK_LOAN_DEFINITION_KEY,
    processDefinitionId: MOCK_LOAN_DEFINITION_ID,
    elementId: 'tool_check',
    elementName: 'Run more tools?',
    type: 'EXCLUSIVE_GATEWAY',
    state: 'COMPLETED',
    hasIncident: false,
    flowScopeKey: MOCK_LOAN_INSTANCE_KEY,
    rootProcessInstanceKey: null,
    tenantId: '<default>',
    startDate: '2026-04-10T09:15:02.820Z',
    endDate: '2026-04-10T09:15:02.850Z',
    incidentKey: null,
  },
  // Tools subprocess — iteration 1
  {
    elementInstanceKey: MOCK_LOAN_TOOLS_ITERATION_1_KEY,
    processInstanceKey: MOCK_LOAN_INSTANCE_KEY,
    processDefinitionKey: MOCK_LOAN_DEFINITION_KEY,
    processDefinitionId: MOCK_LOAN_DEFINITION_ID,
    elementId: 'tools',
    elementName: 'Tools',
    type: 'AD_HOC_SUB_PROCESS',
    state: 'COMPLETED',
    hasIncident: false,
    flowScopeKey: MOCK_LOAN_INSTANCE_KEY,
    rootProcessInstanceKey: null,
    tenantId: '<default>',
    startDate: '2026-04-10T09:15:02.860Z',
    endDate: '2026-04-10T09:15:02.890Z',
    incidentKey: null,
  },
  // Tools from iteration 1: credit score + income
  {
    elementInstanceKey: '5551799813685030',
    processInstanceKey: MOCK_LOAN_INSTANCE_KEY,
    processDefinitionKey: MOCK_LOAN_DEFINITION_KEY,
    processDefinitionId: MOCK_LOAN_DEFINITION_ID,
    elementId: 'get_credit_score',
    elementName: 'Get credit score',
    type: 'SERVICE_TASK',
    state: 'COMPLETED',
    hasIncident: false,
    flowScopeKey: MOCK_LOAN_TOOLS_ITERATION_1_KEY,
    rootProcessInstanceKey: null,
    tenantId: '<default>',
    startDate: '2026-04-10T09:15:00.400Z',
    endDate: '2026-04-10T09:15:01.600Z',
    incidentKey: null,
  },
  {
    elementInstanceKey: '5551799813685031',
    processInstanceKey: MOCK_LOAN_INSTANCE_KEY,
    processDefinitionKey: MOCK_LOAN_DEFINITION_KEY,
    processDefinitionId: MOCK_LOAN_DEFINITION_ID,
    elementId: 'verify_income',
    elementName: 'Verify income',
    type: 'SERVICE_TASK',
    state: 'COMPLETED',
    hasIncident: false,
    flowScopeKey: MOCK_LOAN_TOOLS_ITERATION_1_KEY,
    rootProcessInstanceKey: null,
    tenantId: '<default>',
    startDate: '2026-04-10T09:15:00.400Z',
    endDate: '2026-04-10T09:15:02.200Z',
    incidentKey: null,
  },
  // Merge gateway — loop back (iteration 2)
  {
    elementInstanceKey: '5551799813685040',
    processInstanceKey: MOCK_LOAN_INSTANCE_KEY,
    processDefinitionKey: MOCK_LOAN_DEFINITION_KEY,
    processDefinitionId: MOCK_LOAN_DEFINITION_ID,
    elementId: 'merge_gateway',
    elementName: null,
    type: 'EXCLUSIVE_GATEWAY',
    state: 'COMPLETED',
    hasIncident: false,
    flowScopeKey: MOCK_LOAN_INSTANCE_KEY,
    rootProcessInstanceKey: null,
    tenantId: '<default>',
    startDate: '2026-04-10T09:15:02.900Z',
    endDate: '2026-04-10T09:15:02.910Z',
    incidentKey: null,
  },
  // Agent task — iteration 2
  {
    elementInstanceKey: MOCK_LOAN_AGENT_ITERATION_2_KEY,
    processInstanceKey: MOCK_LOAN_INSTANCE_KEY,
    processDefinitionKey: MOCK_LOAN_DEFINITION_KEY,
    processDefinitionId: MOCK_LOAN_DEFINITION_ID,
    elementId: 'ai_task_agent',
    elementName: 'Risk Assessment Agent',
    type: 'SERVICE_TASK',
    state: 'COMPLETED',
    hasIncident: false,
    flowScopeKey: MOCK_LOAN_INSTANCE_KEY,
    rootProcessInstanceKey: null,
    tenantId: '<default>',
    startDate: '2026-04-10T09:15:02.900Z',
    endDate: '2026-04-10T09:15:05.100Z',
    incidentKey: null,
  },
  // Tool check gateway — iteration 2 (Yes -> tools)
  {
    elementInstanceKey: '5551799813685041',
    processInstanceKey: MOCK_LOAN_INSTANCE_KEY,
    processDefinitionKey: MOCK_LOAN_DEFINITION_KEY,
    processDefinitionId: MOCK_LOAN_DEFINITION_ID,
    elementId: 'tool_check',
    elementName: 'Run more tools?',
    type: 'EXCLUSIVE_GATEWAY',
    state: 'COMPLETED',
    hasIncident: false,
    flowScopeKey: MOCK_LOAN_INSTANCE_KEY,
    rootProcessInstanceKey: null,
    tenantId: '<default>',
    startDate: '2026-04-10T09:15:05.120Z',
    endDate: '2026-04-10T09:15:05.140Z',
    incidentKey: null,
  },
  // Tools subprocess — iteration 2
  {
    elementInstanceKey: MOCK_LOAN_TOOLS_ITERATION_2_KEY,
    processInstanceKey: MOCK_LOAN_INSTANCE_KEY,
    processDefinitionKey: MOCK_LOAN_DEFINITION_KEY,
    processDefinitionId: MOCK_LOAN_DEFINITION_ID,
    elementId: 'tools',
    elementName: 'Tools',
    type: 'AD_HOC_SUB_PROCESS',
    state: 'COMPLETED',
    hasIncident: false,
    flowScopeKey: MOCK_LOAN_INSTANCE_KEY,
    rootProcessInstanceKey: null,
    tenantId: '<default>',
    startDate: '2026-04-10T09:15:05.150Z',
    endDate: '2026-04-10T09:15:05.180Z',
    incidentKey: null,
  },
  // Tools from iteration 2: risk profile + fraud check
  {
    elementInstanceKey: '5551799813685050',
    processInstanceKey: MOCK_LOAN_INSTANCE_KEY,
    processDefinitionKey: MOCK_LOAN_DEFINITION_KEY,
    processDefinitionId: MOCK_LOAN_DEFINITION_ID,
    elementId: 'check_risk_profile',
    elementName: 'Check risk profile',
    type: 'SERVICE_TASK',
    state: 'COMPLETED',
    hasIncident: false,
    flowScopeKey: MOCK_LOAN_TOOLS_ITERATION_2_KEY,
    rootProcessInstanceKey: null,
    tenantId: '<default>',
    startDate: '2026-04-10T09:15:03.000Z',
    endDate: '2026-04-10T09:15:03.900Z',
    incidentKey: null,
  },
  {
    elementInstanceKey: '5551799813685051',
    processInstanceKey: MOCK_LOAN_INSTANCE_KEY,
    processDefinitionKey: MOCK_LOAN_DEFINITION_KEY,
    processDefinitionId: MOCK_LOAN_DEFINITION_ID,
    elementId: 'check_fraud',
    elementName: 'Check fraud database',
    type: 'SERVICE_TASK',
    state: 'COMPLETED',
    hasIncident: false,
    flowScopeKey: MOCK_LOAN_TOOLS_ITERATION_2_KEY,
    rootProcessInstanceKey: null,
    tenantId: '<default>',
    startDate: '2026-04-10T09:15:03.000Z',
    endDate: '2026-04-10T09:15:04.400Z',
    incidentKey: null,
  },
  // Merge gateway — loop back (iteration 3)
  {
    elementInstanceKey: '5551799813685060',
    processInstanceKey: MOCK_LOAN_INSTANCE_KEY,
    processDefinitionKey: MOCK_LOAN_DEFINITION_KEY,
    processDefinitionId: MOCK_LOAN_DEFINITION_ID,
    elementId: 'merge_gateway',
    elementName: null,
    type: 'EXCLUSIVE_GATEWAY',
    state: 'COMPLETED',
    hasIncident: false,
    flowScopeKey: MOCK_LOAN_INSTANCE_KEY,
    rootProcessInstanceKey: null,
    tenantId: '<default>',
    startDate: '2026-04-10T09:15:05.200Z',
    endDate: '2026-04-10T09:15:05.210Z',
    incidentKey: null,
  },
  // Agent task — iteration 3 (final, with Slack notification tool)
  {
    elementInstanceKey: MOCK_LOAN_AGENT_ITERATION_3_KEY,
    processInstanceKey: MOCK_LOAN_INSTANCE_KEY,
    processDefinitionKey: MOCK_LOAN_DEFINITION_KEY,
    processDefinitionId: MOCK_LOAN_DEFINITION_ID,
    elementId: 'ai_task_agent',
    elementName: 'Risk Assessment Agent',
    type: 'SERVICE_TASK',
    state: 'COMPLETED',
    hasIncident: false,
    flowScopeKey: MOCK_LOAN_INSTANCE_KEY,
    rootProcessInstanceKey: null,
    tenantId: '<default>',
    startDate: '2026-04-10T09:15:05.200Z',
    endDate: '2026-04-10T09:15:07.500Z',
    incidentKey: null,
  },
  // Tool check gateway — iteration 3 (No -> end)
  {
    elementInstanceKey: '5551799813685061',
    processInstanceKey: MOCK_LOAN_INSTANCE_KEY,
    processDefinitionKey: MOCK_LOAN_DEFINITION_KEY,
    processDefinitionId: MOCK_LOAN_DEFINITION_ID,
    elementId: 'tool_check',
    elementName: 'Run more tools?',
    type: 'EXCLUSIVE_GATEWAY',
    state: 'COMPLETED',
    hasIncident: false,
    flowScopeKey: MOCK_LOAN_INSTANCE_KEY,
    rootProcessInstanceKey: null,
    tenantId: '<default>',
    startDate: '2026-04-10T09:15:07.520Z',
    endDate: '2026-04-10T09:15:07.540Z',
    incidentKey: null,
  },
  // End event
  {
    elementInstanceKey: '5551799813685070',
    processInstanceKey: MOCK_LOAN_INSTANCE_KEY,
    processDefinitionKey: MOCK_LOAN_DEFINITION_KEY,
    processDefinitionId: MOCK_LOAN_DEFINITION_ID,
    elementId: 'end',
    elementName: 'Assessment complete',
    type: 'END_EVENT',
    state: 'COMPLETED',
    hasIncident: false,
    flowScopeKey: MOCK_LOAN_INSTANCE_KEY,
    rootProcessInstanceKey: null,
    tenantId: '<default>',
    startDate: '2026-04-10T09:15:07.560Z',
    endDate: '2026-04-10T09:15:07.580Z',
    incidentKey: null,
  },
];

export const MOCK_LOAN_ELEMENT_STATISTICS = {
  items: [
    {elementId: 'start', active: 0, canceled: 0, incidents: 0, completed: 1},
    {
      elementId: 'create_prompt',
      active: 0,
      canceled: 0,
      incidents: 0,
      completed: 1,
    },
    {
      elementId: 'merge_gateway',
      active: 0,
      canceled: 0,
      incidents: 0,
      completed: 3,
    },
    {
      elementId: 'ai_task_agent',
      active: 0,
      canceled: 0,
      incidents: 0,
      completed: 3,
    },
    {
      elementId: 'tool_check',
      active: 0,
      canceled: 0,
      incidents: 0,
      completed: 3,
    },
    {elementId: 'tools', active: 0, canceled: 0, incidents: 0, completed: 2},
    {
      elementId: 'get_credit_score',
      active: 0,
      canceled: 0,
      incidents: 0,
      completed: 1,
    },
    {
      elementId: 'verify_income',
      active: 0,
      canceled: 0,
      incidents: 0,
      completed: 1,
    },
    {
      elementId: 'check_risk_profile',
      active: 0,
      canceled: 0,
      incidents: 0,
      completed: 1,
    },
    {
      elementId: 'check_fraud',
      active: 0,
      canceled: 0,
      incidents: 0,
      completed: 1,
    },
    {elementId: 'end', active: 0, canceled: 0, incidents: 0, completed: 1},
  ],
};

export const MOCK_LOAN_SEQUENCE_FLOWS = {
  items: [
    {
      processInstanceKey: MOCK_LOAN_INSTANCE_KEY,
      elementId: 'flow_start_to_prompt',
    },
    {
      processInstanceKey: MOCK_LOAN_INSTANCE_KEY,
      elementId: 'flow_prompt_to_merge',
    },
    {
      processInstanceKey: MOCK_LOAN_INSTANCE_KEY,
      elementId: 'flow_merge_to_agent',
    },
    {
      processInstanceKey: MOCK_LOAN_INSTANCE_KEY,
      elementId: 'flow_agent_to_check',
    },
    {processInstanceKey: MOCK_LOAN_INSTANCE_KEY, elementId: 'flow_yes_tools'},
    {
      processInstanceKey: MOCK_LOAN_INSTANCE_KEY,
      elementId: 'flow_tools_to_merge',
    },
    {processInstanceKey: MOCK_LOAN_INSTANCE_KEY, elementId: 'flow_no_tools'},
  ],
};

export const MOCK_LOAN_VARIABLES: Variable[] = [
  {
    variableKey: `${MOCK_LOAN_INSTANCE_KEY}-applicationId`,
    name: 'applicationId',
    value: '"APP-2026-4821"',
    isTruncated: false,
    tenantId: '<default>',
    processInstanceKey: MOCK_LOAN_INSTANCE_KEY,
    scopeKey: MOCK_LOAN_INSTANCE_KEY,
    rootProcessInstanceKey: null,
  },
  {
    variableKey: `${MOCK_LOAN_INSTANCE_KEY}-applicantName`,
    name: 'applicantName',
    value: '"Maria Santos"',
    isTruncated: false,
    tenantId: '<default>',
    processInstanceKey: MOCK_LOAN_INSTANCE_KEY,
    scopeKey: MOCK_LOAN_INSTANCE_KEY,
    rootProcessInstanceKey: null,
  },
  {
    variableKey: `${MOCK_LOAN_INSTANCE_KEY}-applicantId`,
    name: 'applicantId',
    value: '"78432"',
    isTruncated: false,
    tenantId: '<default>',
    processInstanceKey: MOCK_LOAN_INSTANCE_KEY,
    scopeKey: MOCK_LOAN_INSTANCE_KEY,
    rootProcessInstanceKey: null,
  },
  {
    variableKey: `${MOCK_LOAN_INSTANCE_KEY}-loanAmount`,
    name: 'loanAmount',
    value: '250000',
    isTruncated: false,
    tenantId: '<default>',
    processInstanceKey: MOCK_LOAN_INSTANCE_KEY,
    scopeKey: MOCK_LOAN_INSTANCE_KEY,
    rootProcessInstanceKey: null,
  },
  {
    variableKey: `${MOCK_LOAN_INSTANCE_KEY}-purpose`,
    name: 'purpose',
    value: '"Home purchase"',
    isTruncated: false,
    tenantId: '<default>',
    processInstanceKey: MOCK_LOAN_INSTANCE_KEY,
    scopeKey: MOCK_LOAN_INSTANCE_KEY,
    rootProcessInstanceKey: null,
  },
  {
    variableKey: `${MOCK_LOAN_INSTANCE_KEY}-termMonths`,
    name: 'termMonths',
    value: '360',
    isTruncated: false,
    tenantId: '<default>',
    processInstanceKey: MOCK_LOAN_INSTANCE_KEY,
    scopeKey: MOCK_LOAN_INSTANCE_KEY,
    rootProcessInstanceKey: null,
  },
  {
    variableKey: `${MOCK_LOAN_INSTANCE_KEY}-prompt`,
    name: 'prompt',
    value:
      '"Evaluate loan application APP-2026-4821 for applicant Maria Santos (ID: 78432). Requested amount: \\u20AC250,000. Purpose: Home purchase. Term: 360 months."',
    isTruncated: false,
    tenantId: '<default>',
    processInstanceKey: MOCK_LOAN_INSTANCE_KEY,
    scopeKey: MOCK_LOAN_INSTANCE_KEY,
    rootProcessInstanceKey: null,
  },
  {
    variableKey: `${MOCK_LOAN_AGENT_TASK_KEY}-agent`,
    name: 'agent',
    value: JSON.stringify({
      context: {
        state: 'COMPLETED',
        metrics: {
          modelCalls: 3,
          tokenUsage: {inputTokenCount: 2750, outputTokenCount: 393},
        },
      },
      text: 'Loan evaluation complete. Recommending approval with standard mortgage insurance for Maria Santos.',
    }),
    isTruncated: true,
    tenantId: '<default>',
    processInstanceKey: MOCK_LOAN_INSTANCE_KEY,
    scopeKey: MOCK_LOAN_AGENT_TASK_KEY,
    rootProcessInstanceKey: null,
  },
];

export const MOCK_LOAN_JOBS: Job[] = [];
