{
 "title": "Zeebe Medic Load Tests",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Not maintained",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<center>\n\n⚠️ **This dashboard is not maintained anymore.** Use the dashboards in the [camunda-observability](https://github.com/camunda/camunda-observability) repository instead.\n\n</center>"
   }
  },
  { "title": "Realistic Load Tests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Overall FNI  per s",
   "type": "stat",
   "description": "Flow node instances completed or terminated per second over all partitions.",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(zeebe_element_instance_events_total{namespace=~\"((c8-)?medic.*(mixed|realistic)|(c8-)?release-rolling)\", type!=\"PROCESS\", action!=\"activated\"}[$__rate_interval])) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Completed processes per s",
   "type": "stat",
   "description": "Process instances completed or terminated per second over all partitions.",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(zeebe_element_instance_events_total{namespace=~\"((c8-)?medic.*(mixed|realistic)|(c8-)?release-rolling)\", action=\"completed\", type=\"PROCESS\"}[$__rate_interval])) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Completed tasks per s",
   "type": "stat",
   "description": "Tasks completed or terminated per second over all partitions.",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(zeebe_element_instance_events_total{namespace=~\"((c8-)?medic.*(mixed|realistic)|(c8-)?release-rolling)\", action=\"completed\", type=\"SERVICE_TASK\"}[$__rate_interval])) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  { "title": "Daily Max Load Tests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Overall FNI  per s",
   "type": "stat",
   "description": "Flow node instances completed or terminated per second over all partitions.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(zeebe_element_instance_events_total{namespace=~\"(c8-)?medic-daily.*\", type!=\"PROCESS\", action!=\"activated\"}[$__rate_interval])) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Completed processes per s",
   "type": "stat",
   "description": "Process instances completed or terminated per second over all partitions.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(zeebe_element_instance_events_total{namespace=~\"(c8-)?medic-daily.*\",action=\"completed\", type=\"PROCESS\"}[$__rate_interval])) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Completed tasks per s",
   "type": "stat",
   "description": "Tasks completed or terminated per second over all partitions.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(zeebe_element_instance_events_total{namespace=~\"(c8-)?medic-daily.*\", action=\"completed\", type=\"SERVICE_TASK\"}[$__rate_interval])) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  { "title": "ECS Weekly Load Tests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Overall FNI  per s",
   "type": "stat",
   "description": "Flow node instances completed or terminated per second over all partitions.",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(zeebe_element_instance_events_total{namespace=~\"ecs-weekly.*\", type!=\"PROCESS\", action!=\"activated\"}[$__rate_interval])) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Completed processes per s",
   "type": "stat",
   "description": "Process instances completed or terminated per second over all partitions.",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(zeebe_element_instance_events_total{namespace=~\"ecs-weekly.*\", action=\"completed\", type=\"PROCESS\"}[$__rate_interval])) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Completed tasks per s",
   "type": "stat",
   "description": "Tasks completed or terminated per second over all partitions.",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(zeebe_element_instance_events_total{namespace=~\"ecs-weekly.*\", action=\"completed\", type=\"SERVICE_TASK\"}[$__rate_interval])) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  { "title": "Medic Load Tests Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Health",
   "type": "table",
   "description": "Shows health per partition and pod",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "zeebe_health{namespace=~\"(c8-)?medic.*|ecs-weekly.*\"} ",
     "legendFormat": "Partition {{pod}} {{partition}}"
    },
    {
     "expr": "atomix_role{namespace=~\"(c8-)?medic.*|ecs-weekly.*\"} "
    }
   ]
  },
  {
   "title": "Pod Last Terminated Reason",
   "type": "table",
   "description": "Shows the reason for the last pod restart",
   "gridPos": { "h": 5, "w": 13, "x": 11, "y": 23 },
   "targets": [
    {
     "expr": "kube_pod_container_status_last_terminated_reason{namespace=~\"(c8-)?medic.*|ecs-weekly.*\", container=~\"zeebe|camunda\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Namespace max disk usage",
   "type": "stat",
   "description": "Shows how much disk is used at max by a broker per namespace",
   "gridPos": { "h": 5, "w": 13, "x": 11, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(kubelet_volume_stats_used_bytes{namespace=~\"(c8-)?medic.*|ecs-weekly.*\", persistentvolumeclaim=~\".*zeebe.*|.*camunda.*\"} / kubelet_volume_stats_capacity_bytes{namespace=~\"(c8-)?medic.*|ecs-weekly.*\", persistentvolumeclaim=~\".*zeebe.*|.*camunda.*\"}) by (namespace)",
     "legendFormat": "{{persistentvolumeclaim}}"
    }
   ]
  },
  { "title": "Release Load Tests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Overall FNI  per s",
   "type": "stat",
   "description": "Flow node instances completed or terminated per second over all partitions.",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(zeebe_element_instance_events_total{namespace=~\"(c8-)?release-8.*\",type!=\"PROCESS\", action!=\"activated\"}[$__rate_interval])) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Completed processes per s",
   "type": "stat",
   "description": "Process instances completed or terminated per second over all partitions.",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(zeebe_element_instance_events_total{namespace=~\"(c8-)?release-8.*\", action=\"completed\", type=\"PROCESS\"}[$__rate_interval])) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Completed tasks per s",
   "type": "stat",
   "description": "Tasks completed or terminated per second over all partitions.",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(zeebe_element_instance_events_total{namespace=~\"(c8-)?release-8.*\",action=\"completed\", type=\"SERVICE_TASK\"}[$__rate_interval])) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "p50 Latency",
   "type": "stat",
   "description": "Average process instance execution latency",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(zeebe_process_instance_execution_time_bucket{namespace=~\"(c8-)?release-8.*\"}[$__rate_interval])) by (le, namespace))",
     "legendFormat": "{{namespace}}"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(zeebe_process_instance_execution_time_seconds_bucket{namespace=~\"(c8-)?release-8.*\"}[$__rate_interval])) by (le, namespace))",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "p90 Latency",
   "type": "stat",
   "description": "90th percentile process instance execution latency",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(zeebe_process_instance_execution_time_bucket{namespace=~\"(c8-)?release-8.*\"}[$__rate_interval])) by (le, namespace))",
     "legendFormat": "{{namespace}}"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(zeebe_process_instance_execution_time_seconds_bucket{namespace=~\"(c8-)?release-8.*\"}[$__rate_interval])) by (le, namespace))",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "p99 Latency",
   "type": "stat",
   "description": "99th percentile process instance execution latency",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(zeebe_process_instance_execution_time_bucket{namespace=~\"(c8-)?release-8.*\"}[$__rate_interval])) by (le, namespace))",
     "legendFormat": "{{namespace}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(zeebe_process_instance_execution_time_seconds_bucket{namespace=~\"(c8-)?release-8.*\"}[$__rate_interval])) by (le, namespace))",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Health",
   "type": "table",
   "description": "Shows health per partition and pod",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "zeebe_health{namespace=~\"(c8-)?release.*\"} ",
     "legendFormat": "Partition {{pod}} {{partition}}"
    },
    {
     "expr": "atomix_role{namespace=~\"(c8-)?release.*\"} "
    }
   ]
  },
  {
   "title": "Namespace disk usage (max)",
   "type": "stat",
   "description": "Shows how much disk at max is used by brokers per namespace",
   "gridPos": { "h": 9, "w": 13, "x": 11, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(kubelet_volume_stats_used_bytes{namespace=~\"(c8-)?release.*\", persistentvolumeclaim=~\".*zeebe.*|.*camunda.*\"} / kubelet_volume_stats_capacity_bytes{namespace=~\"(c8-)?release.*\", persistentvolumeclaim=~\".*zeebe.*|.*camunda.*\"}) by (namespace)",
     "legendFormat": "{{persistentvolumeclaim}} {{namespace}}"
    }
   ]
  }
 ]
}