-- create_process_deployment_table
CREATE TABLE C8_PROCESS_DEFINITION (
  PROCESS_DEFINITION_KEY BIGINT NOT NULL,
  PROCESS_DEFINITION_ID VARCHAR(200),
  NAME VARCHAR(200),
  RESOURCE_NAME VARCHAR(4000),
  BPMN_XML CLOB,
  TENANT_ID VARCHAR(200),
  VERSION SMALLINT,
  VERSION_TAG VARCHAR(200),
  FORM_ID VARCHAR(200),
  CONSTRAINT PK_C8_PROCESS_DEFINITION PRIMARY KEY (PROCESS_DEFINITION_KEY)
);

CREATE INDEX C8_IDX_PROCESS_DEFINITION_ID ON C8_PROCESS_DEFINITION(PROCESS_DEFINITION_ID);

-- create_process_instance_table
CREATE TABLE C8_PROCESS_INSTANCE (
  PROCESS_INSTANCE_KEY BIGINT NOT NULL,
  PROCESS_DEFINITION_ID VARCHAR(200),
  PROCESS_DEFINITION_KEY BIGINT,
  STATE VARCHAR(20),
  START_DATE TIMESTAMP(3) WITH TIME ZONE,
  END_DATE TIMESTAMP(3) WITH TIME ZONE,
  TENANT_ID VARCHAR(200),
  PARENT_PROCESS_INSTANCE_KEY BIGINT,
  PARENT_ELEMENT_INSTANCE_KEY BIGINT,
  ELEMENT_ID VARCHAR(255),
  VERSION SMALLINT,
  CONSTRAINT PK_C8_PROCESS_INSTANCE PRIMARY KEY (PROCESS_INSTANCE_KEY)
);

