-- create_process_deployment_table
CREATE TABLE PROCESS_DEFINITION
(
    PROCESS_DEFINITION_KEY BIGINT        NOT NULL,
    PROCESS_DEFINITION_ID  VARCHAR(4000) NULL,
    NAME                   VARCHAR(4000) NULL,
    RESOURCE_NAME          VARCHAR(4000) NULL,
    BPMN_XML               LONGTEXT      NULL,
    TENANT_ID              VARCHAR(4000) NULL,
    VERSION                SMALLINT      NULL,
    VERSION_TAG            VARCHAR(4000) NULL,
    FORM_ID                VARCHAR(4000) NULL,
    CONSTRAINT PK_PROCESS_DEFINITION PRIMARY KEY (PROCESS_DEFINITION_KEY)
);

CREATE INDEX IDX_PROCESS_DEFINITION_ID ON PROCESS_DEFINITION (PROCESS_DEFINITION_ID);

CREATE INDEX PROCESS_DEFINITION_TENANT ON PROCESS_DEFINITION (TENANT_ID);

-- create_process_instance_table
CREATE TABLE PROCESS_INSTANCE
(
    PROCESS_INSTANCE_KEY        BIGINT        NOT NULL,
    PROCESS_DEFINITION_ID       VARCHAR(4000) NULL,
    PROCESS_DEFINITION_KEY      BIGINT        NULL,
    STATE                       VARCHAR(20)   NULL,
    START_DATE                  TIMESTAMP(3)  NULL,
    END_DATE                    TIMESTAMP(3)  NULL,
    TENANT_ID                   VARCHAR(4000) NULL,
    PARENT_PROCESS_INSTANCE_KEY BIGINT        NULL,
    PARENT_ELEMENT_INSTANCE_KEY BIGINT        NULL,
    ELEMENT_ID                  VARCHAR(4000) NULL,
    VERSION                     SMALLINT      NULL,
    `DESCRIPTION`                 VARCHAR(4000) NULL,
    TREE_PATH                   VARCHAR(4000) NULL,
    ERROR_MESSAGE               VARCHAR(4000) NULL,
    CONSTRAINT PK_PROCESS_INSTANCE PRIMARY KEY (PROCESS_INSTANCE_KEY)
);

