/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(project(":zeebe-util"))
    api(project(":zeebe-protocol"))
    api(project(":camunda-security-protocol"))
    api(project(":zeebe-exporter-api"))
    api(project(":camunda-client-java"))
    api(libs.org.slf4j.slf4j.api)
    api(libs.org.apache.logging.log4j.log4j.core)
    api(libs.org.msgpack.msgpack.core)
    api(libs.org.apache.commons.commons.lang3)
    api(project(":zeebe-bpmn-model"))
    api(libs.com.fasterxml.jackson.core.jackson.core)
    api(libs.com.fasterxml.jackson.core.jackson.databind)
    api(libs.org.msgpack.jackson.dataformat.msgpack)
    api(libs.org.agrona.agrona)
    api(libs.junit.junit)
    api(libs.org.assertj.assertj.core)
    api(libs.org.springframework.spring.beans)
    api(libs.org.springframework.spring.core)
    api(libs.org.springframework.boot.spring.boot)
    api(libs.org.yaml.snakeyaml)
    api(libs.io.grpc.grpc.api)
    api(libs.io.netty.netty.handler)
    api(libs.io.netty.netty.transport)
    api(libs.io.netty.netty.common)
    api(libs.io.netty.netty.buffer)
    api(libs.org.awaitility.awaitility)
    api(libs.org.junit.jupiter.junit.jupiter.api)
    api(libs.org.junit.platform.junit.platform.commons.x1)
    api(libs.org.testcontainers.testcontainers)
    api(libs.org.testcontainers.testcontainers.elasticsearch)
    api(libs.org.testcontainers.testcontainers.jdbc)
    api(libs.org.testcontainers.testcontainers.postgresql)
    api(libs.org.testcontainers.testcontainers.oracle.free)
    api(libs.org.testcontainers.testcontainers.mariadb)
    api(libs.org.testcontainers.testcontainers.mysql)
    api(libs.org.testcontainers.testcontainers.mssqlserver)
    api(libs.com.github.dasniko.testcontainers.keycloak)
    api(libs.com.github.docker.java.docker.java.api)
    api(libs.org.elasticsearch.client.elasticsearch.rest.client)
    api(libs.org.opensearch.opensearch.testcontainers)
    api(libs.org.opensearch.client.opensearch.rest.client)
    api(libs.org.openjdk.jmh.jmh.core)
    testImplementation(libs.org.junit.jupiter.junit.jupiter.params)
}

description = "Zeebe Test Util"
