/*
 * Copyright Camunda Services GmbH and/or licensed to Camunda Services GmbH under
 * one or more contributor license agreements. See the NOTICE file distributed
 * with this work for additional information regarding copyright ownership.
 * Licensed under the Camunda License 1.0. You may not use this file
 * except in compliance with the Camunda License 1.0.
 */
package io.camunda.zeebe.dynamic.config;

import static org.assertj.core.api.Assertions.assertThat;

import io.atomix.cluster.AtomixCluster;
import io.atomix.cluster.MemberId;
import io.atomix.cluster.Node;
import io.atomix.cluster.discovery.BootstrapDiscoveryProvider;
import io.atomix.cluster.impl.DiscoveryMembershipProtocol;
import io.atomix.primitive.partition.PartitionMetadata;
import io.camunda.cluster.PartitionId;
import io.camunda.cluster.PhysicalTenantIds;
import io.camunda.zeebe.dynamic.config.changes.ClusterChangeExecutor.NoopClusterChangeExecutor;
import io.camunda.zeebe.dynamic.config.changes.ConfigurationChangeCoordinator;
import io.camunda.zeebe.dynamic.config.changes.ModeChangeExecutor.NoopModeChangeExecutor;
import io.camunda.zeebe.dynamic.config.changes.NoopPartitionChangeExecutor;
import io.camunda.zeebe.dynamic.config.changes.PartitionScalingChangeExecutor.NoopPartitionScalingChangeExecutor;
import io.camunda.zeebe.dynamic.config.gossip.ClusterConfigurationGossiperConfig;
import io.camunda.zeebe.dynamic.config.state.CurrentClusterConfiguration;
import io.camunda.zeebe.dynamic.config.state.DynamicPartitionConfig;
import io.camunda.zeebe.dynamic.config.state.Mode;
import io.camunda.zeebe.dynamic.config.state.PartitionGroupConfiguration;
import io.camunda.zeebe.dynamic.config.state.PartitionGroupOperation.ModeChangeOperation;
import io.camunda.zeebe.dynamic.config.state.PartitionGroupOperation.PartitionChangeOperation.PartitionJoinOperation;
import io.camunda.zeebe.dynamic.config.state.PartitionGroupOperation.PartitionChangeOperation.PartitionLeaveOperation;
import io.camunda.zeebe.scheduler.ActorScheduler;
import io.camunda.zeebe.scheduler.ActorSchedulingService;
import io.camunda.zeebe.scheduler.future.ActorFuture;
import io.camunda.zeebe.test.util.socket.SocketUtil;
import io.camunda.zeebe.util.Either;
import io.camunda.zeebe.util.FileUtil;
import io.micrometer.core.instrument.MeterRegistry;
import io.micrometer.core.instrument.simple.SimpleMeterRegistry;
import java.io.IOException;
import java.nio.file.Path;
import java.time.Duration;
import java.util.Collection;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.stream.Collectors;
import org.awaitility.Awaitility;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.AutoClose;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

/**
 * Exercises {@link ClusterConfigurationManagerService} end-to-end. Assertions read the {@link
 * CurrentClusterConfiguration} directly (via {@link
 * ClusterConfigurationManagerService#getClusterConfiguration()}) rather than the legacy compat
 * projection ({@code toLegacyDefault()}), since that projection cannot distinguish "uninitialized"
 * from "initialized but empty" for the new model.
 */
class ClusterConfigurationManagementIntegrationTest {

  private static final Duration INITIALIZATION_TIMEOUT = Duration.ofSeconds(30);
  private static final MemberId MEMBER_0 = MemberId.from("0");
  private static final MemberId MEMBER_1 = MemberId.from("1");
  private static final MemberId MEMBER_2 = MemberId.from("2");

  @TempDir Path rootDir;

  private final ActorScheduler actorScheduler = ActorScheduler.newActorScheduler().build();

  private final List<Node> clusterNodes =
      List.of(createNode("0"), createNode("1"), createNode("2"));
  private final Map<Integer, TestNode> nodes = new HashMap<>();
  private Set<MemberId> clusterMemberIds;
  @AutoClose private final MeterRegistry meterRegistry = new SimpleMeterRegistry();

  @BeforeEach
  void setup() {
    actorScheduler.start();

    clusterMemberIds =
        clusterNodes.stream()
            .map(Node::id)
            .map(id -> MemberId.from(id.id()))
            .collect(Collectors.toSet());

    // start 3 clusterNodes
    createClusterNodes();
  }

  @AfterEach
  void tearDown() {
    nodes.values().forEach(TestNode::close);
    actorScheduler.stop();
  }

  private void createClusterNodes() {
    clusterNodes.forEach(
        node ->
            nodes.put(
                Integer.parseInt(node.id().id()),
                createClusterTopologyManagerService(
                    rootDir, createClusterNode(node, clusterNodes))));
  }

  @Test
  void shouldInitializeTopologyFromCoordinator() {
    // when - start node 1 and 2 with incorrect partition distribution
    nodes.values().forEach(this::startNode);

    // then - all nodes should have the correct topology generated by node 0
    nodes
        .values()
        .forEach(
            node ->
                Awaitility.await(
                        "The cluster should initialize topology with correct configuration")
                    .timeout(INITIALIZATION_TIMEOUT)
                    .untilAsserted(
                        () ->
                            assertThat(node.service().getClusterConfiguration())
                                .succeedsWithin(INITIALIZATION_TIMEOUT)
                                .satisfies(this::assertInitializedWithAllMembers)));
  }

  @Test
  void shouldUseExistingTopologyAfterRestart() {
    // given
    nodes.values().forEach(this::startNode);
    awaitAllInitialized();

    // when
    nodes.values().forEach(TestNode::close);
    // restart with incorrect topology
    createClusterNodes();

    nodes
        .values()
        .forEach(node -> node.start(actorScheduler, Set.of(), getIncorrectPartitionDistribution()));

    // then - all nodes should have the correct topology generated from the first bootstrap
    nodes
        .values()
        .forEach(
            node ->
                Awaitility.await("The cluster should use the correct topology")
                    .timeout(INITIALIZATION_TIMEOUT)
                    .untilAsserted(
                        () ->
                            assertInitializedWithAllMembers(
                                node.service().getClusterConfiguration().join())));
  }

  @Test
  void shouldInitializeCoordinatorFromPeers() throws IOException {
    // given
    nodes.values().forEach(this::startNode);
    awaitAllInitialized();

    // when
    nodes.get(0).close();

    // recreate node 0 with empty topology file to simulate data loss
    final Path emptyTopologyFile = rootDir.resolve("new");
    FileUtil.ensureDirectoryExists(emptyTopologyFile);
    final TestNode restartedNode0 =
        createClusterTopologyManagerService(
            emptyTopologyFile, createClusterNode(clusterNodes.get(0), clusterNodes));
    nodes.put(0, restartedNode0);

    restartedNode0.start(actorScheduler, clusterMemberIds, getIncorrectPartitionDistribution());

    // then - all nodes should have the correct topology generated before restart of node 0
    nodes
        .values()
        .forEach(
            node ->
                Awaitility.await("The cluster should use the correct topology")
                    .timeout(INITIALIZATION_TIMEOUT)
                    .untilAsserted(
                        () ->
                            assertInitializedWithAllMembers(
                                node.service().getClusterConfiguration().join())));
  }

  @Test
  void shouldApplyTopologyChange() {
    // given - all members have partition 1
    nodes.values().forEach(this::startNode);
    awaitAllInitialized();

    // when
    final ClusterConfigurationManagerService service = nodes.get(0).service();
    final ConfigurationChangeCoordinator coordinator =
        service.getTopologyChangeCoordinator().orElseThrow();
    coordinator
        .applyOperations(
            ignore ->
                Either.right(
                    CurrentClusterConfiguration.toPhases(
                        List.of(
                            new PartitionJoinOperation(MEMBER_0, 2, 1, true),
                            new PartitionLeaveOperation(MEMBER_1, 1, 1)))))
        .join();

    // then
    Awaitility.await("The topology change should complete.")
        .untilAsserted(() -> assertThat(defaultGroupOf(service).hasPendingChanges()).isFalse());
    final var defaultGroup = defaultGroupOf(service);
    assertThat(defaultGroup.getMember(MEMBER_0).partitions().keySet())
        .describedAs("Member 0 must replicate both partitions after the change.")
        .containsExactlyInAnyOrder(1, 2);
    assertThat(defaultGroup.hasMember(MEMBER_1))
        .describedAs("Member 1 replicates no partitions of the group anymore, so it is removed.")
        .isFalse();
  }

  @Test
  void shouldTransitionMemberToRecoveringState() {
    // given
    final var startFutures = nodes.values().stream().map(this::startNode).toList();
    startFutures.forEach(ActorFuture::join);

    final ClusterConfigurationManagerService service = nodes.get(0).service();
    final ConfigurationChangeCoordinator coordinator =
        service.getTopologyChangeCoordinator().orElseThrow();

    // when
    coordinator
        .applyOperations(
            ignore ->
                Either.right(
                    CurrentClusterConfiguration.toPhases(
                        List.of(
                            new ModeChangeOperation(MEMBER_0, Mode.RECOVERING),
                            new ModeChangeOperation(MEMBER_1, Mode.RECOVERING),
                            new ModeChangeOperation(MEMBER_2, Mode.RECOVERING)))))
        .join();

    // then
    Awaitility.await("The enter-recovery operation should complete.")
        .untilAsserted(() -> assertThat(defaultGroupOf(service).hasPendingChanges()).isFalse());
    final var defaultGroup = defaultGroupOf(service);
    assertThat(defaultGroup.getMember(MEMBER_0).mode()).isEqualTo(Mode.RECOVERING);
    assertThat(defaultGroup.getMember(MEMBER_1).mode()).isEqualTo(Mode.RECOVERING);
    assertThat(defaultGroup.getMember(MEMBER_2).mode()).isEqualTo(Mode.RECOVERING);
  }

  @Test
  void shouldApplyConsecutiveTopologyChangeOnSameMember() {
    // given - all members have partition 1
    nodes.values().forEach(this::startNode);
    awaitAllInitialized();

    // when
    final ClusterConfigurationManagerService service = nodes.get(0).service();
    final ConfigurationChangeCoordinator coordinator =
        service.getTopologyChangeCoordinator().orElseThrow();
    coordinator
        .applyOperations(
            ignore ->
                Either.right(
                    CurrentClusterConfiguration.toPhases(
                        List.of(
                            new PartitionJoinOperation(MEMBER_0, 2, 1, true),
                            new PartitionLeaveOperation(MEMBER_1, 1, 1),
                            new PartitionJoinOperation(MEMBER_1, 1, 1, true)))))
        .join();

    // then
    Awaitility.await("The topology change should complete.")
        .untilAsserted(() -> assertThat(defaultGroupOf(service).hasPendingChanges()).isFalse());
    final var defaultGroup = defaultGroupOf(service);
    assertThat(defaultGroup.getMember(MEMBER_0).partitions().keySet())
        .describedAs("Member 0 must replicate both partitions after the change.")
        .containsExactlyInAnyOrder(1, 2);
    assertThat(defaultGroup.getMember(MEMBER_1).partitions().keySet())
        .describedAs("Member 1 left and rejoined partition 1.")
        .containsExactlyInAnyOrder(1);
  }

  /**
   * Asserts that the configuration is initialized and every static cluster member is visible in
   * {@link CurrentClusterConfiguration#globalConfiguration()}. Checking {@code
   * globalConfiguration().members()} directly (rather than the legacy {@code toLegacyDefault()}
   * projection) is required because that projection's derived {@code version} can never equal the
   * legacy uninitialized sentinel, so {@code isUninitialized()} on the projection is always {@code
   * false} — it cannot be used to detect that initialization hasn't happened yet.
   */
  private void assertInitializedWithAllMembers(final CurrentClusterConfiguration configuration) {
    assertThat(configuration.isUninitialized()).isFalse();
    assertThat(configuration.globalConfiguration().members().keySet())
        .containsExactlyInAnyOrderElementsOf(clusterMemberIds);
  }

  private PartitionGroupConfiguration defaultGroupOf(
      final ClusterConfigurationManagerService service) {
    return service
        .getClusterConfiguration()
        .join()
        .partitionGroup(PhysicalTenantIds.DEFAULT_PHYSICAL_TENANT_ID);
  }

  private void awaitAllInitialized() {
    Awaitility.await("All nodes should initialize")
        .timeout(INITIALIZATION_TIMEOUT)
        .untilAsserted(
            () ->
                assertThat(nodes.values())
                    .allSatisfy(
                        node ->
                            assertThat(node.service().getClusterConfiguration())
                                .succeedsWithin(INITIALIZATION_TIMEOUT)
                                .returns(false, CurrentClusterConfiguration::isUninitialized)));
  }

  private Node createNode(final String id) {
    return Node.builder().withId(id).withPort(SocketUtil.getNextAddress().getPort()).build();
  }

  private AtomixCluster createClusterNode(final Node localNode, final Collection<Node> nodes) {
    return AtomixCluster.builder(meterRegistry)
        .withAddress(localNode.address())
        .withMemberId(localNode.id().id())
        .withMembershipProvider(new BootstrapDiscoveryProvider(nodes))
        .withMembershipProtocol(new DiscoveryMembershipProtocol())
        .build();
  }

  private TestNode createClusterTopologyManagerService(
      final Path tempDir, final AtomixCluster cluster) {
    final var service =
        new ClusterConfigurationManagerService(
            tempDir.resolve(cluster.getMembershipService().getLocalMember().id().id()),
            cluster.getCommunicationService(),
            cluster.getMembershipService(),
            new ClusterConfigurationGossiperConfig(
                Duration.ofSeconds(1),
                Duration.ofMillis(100),
                2,
                Duration.ofSeconds(1),
                Duration.ofSeconds(5)),
            new NoopClusterChangeExecutor(),
            meterRegistry);
    return new TestNode(cluster, service);
  }

  private ActorFuture<Void> startNode(final TestNode node) {
    if (node.cluster.getMembershipService().getLocalMember().id().id().equals("0")) {
      return node.start(actorScheduler, clusterMemberIds, getExpectedPartitionDistribution());
    } else {
      return node.start(actorScheduler, clusterMemberIds, getIncorrectPartitionDistribution());
    }
  }

  private Set<PartitionMetadata> getExpectedPartitionDistribution() {
    return Set.of(
        new PartitionMetadata(
            new PartitionId(PhysicalTenantIds.DEFAULT_PHYSICAL_TENANT_ID, 1),
            Set.of(MemberId.from("0"), MemberId.from("1"), MemberId.from("2")),
            Map.of(MemberId.from("0"), 1, MemberId.from("1"), 2, MemberId.from("2"), 3),
            3,
            MemberId.from("2")),
        new PartitionMetadata(
            new PartitionId(PhysicalTenantIds.DEFAULT_PHYSICAL_TENANT_ID, 2),
            Set.of(MemberId.from("2")),
            Map.of(MemberId.from("2"), 1),
            1,
            MemberId.from("2")));
  }

  private Set<PartitionMetadata> getIncorrectPartitionDistribution() {
    return Set.of(
        new PartitionMetadata(
            new PartitionId("test", 1),
            Set.of(MemberId.from("10"), MemberId.from("11"), MemberId.from("12")),
            Map.of(MemberId.from("10"), 1, MemberId.from("11"), 2, MemberId.from("12"), 3),
            3,
            MemberId.from("12")));
  }

  private record TestNode(AtomixCluster cluster, ClusterConfigurationManagerService service) {

    ActorFuture<Void> start(
        final ActorSchedulingService actorScheduler,
        final Set<MemberId> clusterMembers,
        final Set<PartitionMetadata> partitions) {
      cluster.start().join();
      final var startFuture =
          service.start(
              actorScheduler,
              new StaticConfiguration(
                  new ControllablePartitionDistributor().withPartitions(partitions),
                  clusterMembers,
                  cluster.getMembershipService().getLocalMember().id(),
                  List.of(),
                  3,
                  Map.of(
                      PhysicalTenantIds.DEFAULT_PHYSICAL_TENANT_ID, DynamicPartitionConfig.init()),
                  "clusterId"),
              Map.of());
      startFuture.onComplete(
          (ignore, error) -> {
            if (error == null) {
              service.registerModeChangeExecutor(
                  PhysicalTenantIds.DEFAULT_PHYSICAL_TENANT_ID, new NoopModeChangeExecutor());
              service.registerPartitionChangeExecutors(
                  PhysicalTenantIds.DEFAULT_PHYSICAL_TENANT_ID,
                  new NoopPartitionChangeExecutor(),
                  new NoopPartitionScalingChangeExecutor());
            }
          },
          Runnable::run);
      return startFuture;
    }

    void close() {
      service.closeAsync().join();
      cluster.stop().join();
    }
  }
}
