/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    implementation(project(":tasklist-common"))
    implementation(project(":webapps-schema"))
    implementation(project(":camunda-spring-utils"))
    implementation(project(":camunda-service"))
    implementation(project(":camunda-security-core"))
    implementation(libs.io.camunda.security.library.api)
    implementation(project(":camunda-client-java"))
    implementation(project(":zeebe-protocol"))
    implementation(project(":zeebe-protocol-impl"))
    api(libs.org.springframework.spring.context)
    api(libs.org.springframework.spring.beans)
    api(libs.org.springframework.boot.spring.boot.autoconfigure)
    api(libs.co.elastic.clients.elasticsearch.java)
    api(libs.org.opensearch.client.opensearch.java)
    api(libs.jakarta.annotation.jakarta.annotation.api)
    implementation(libs.org.slf4j.slf4j.api)
}

description = "Tasklist Data Generator"
