---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - testrun.yaml

configMapGenerator:
  - name: k6-scripts
    files:
      - test1.js

generatorOptions:
  # Needed to have the expected ConfigMap name in the TestRun resource.
  disableNameSuffixHash: true
