apiVersion: v1
kind: Secret
metadata:
  name: load-test-credentials
type: Opaque
stringData:
  clientId: orchestration
  {{- $secretName := dict
            "namespace" $.Release.Namespace
            "user" (include "oc-secret-name" .)
  }}
  clientSecret: "{{ include "generate-secret" $secretName }}"
  zeebeRestAddress: http://camunda:8080
  authServer: http://keycloak/auth/realms/camunda-platform/protocol/openid-connect/token
  authType: OAUTH
  zeebeGrpcAddress: http://camunda:26500
  authorizationAudience: orchestration-api
