---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: metrics-exporter
  labels:
    app: metrics-exporter
spec:
  progressDeadlineSeconds: 60
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: metrics-exporter
  template:
    metadata:
      labels:
        app: metrics-exporter
    spec:
      containers:
      - name: metrics-exporter
        image: {{ include "metrics-exporter.image" . }}
        args:
          - --es.addresses={{ .Values.metricsExporter.database.url }}
        ports:
        - containerPort: 9600
          name: metrics
        readinessProbe:
          httpGet:
            path: /metrics
            port: metrics
          periodSeconds: 10
          timeoutSeconds: 5
        resources:
          limits:
            cpu: 100m
            memory: 50Mi
          requests:
            cpu: 100m
            memory: 50Mi
      imagePullSecrets:
      - name: harbor-registry

      restartPolicy: Always

      # Node scheduling
      nodeSelector:
        {{- if .Values.topologyZone }}
        topology.kubernetes.io/zone: "{{ .Values.topologyZone }}"
        {{- end }}
      tolerations:
      - effect: NoSchedule
        key: nodepool
        operator: Equal
        value: n2-standard-4
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: metrics-exporter
  labels:
    app: metrics-exporter
    release: monitoring # needed to be detected by Prometheus Operator
spec:
  podMetricsEndpoints:
  - interval: 30s
    path: /metrics
    port: metrics
    scrapeTimeout: 20s
  selector:
    matchLabels:
      app: metrics-exporter
