package org.camunda.optimize.test.util;

public enum DecisionReportDataType {
  RAW_DATA,
  COUNT_DEC_INST_FREQ_GROUP_BY_NONE,
  COUNT_DEC_INST_FREQ_GROUP_BY_EVALUATION_DATE_TIME,
  COUNT_DEC_INST_FREQ_GROUP_BY_INPUT_VARIABLE,
  COUNT_DEC_INST_FREQ_GROUP_BY_OUTPUT_VARIABLE,
  COUNT_DEC_INST_FREQ_GROUP_BY_MATCHED_RULE,
  ;
}
