package org.camunda.optimize.test.util;

public enum ProcessReportDataType {

  RAW_DATA,

  AVG_PROC_INST_DUR_GROUP_BY_NONE,
  AVG_PROC_INST_DUR_GROUP_BY_NONE_WITH_PART,
  AVG_PROC_INST_DUR_GROUP_BY_START_DATE,
  AVG_PROC_INST_DUR_GROUP_BY_START_DATE_WITH_PART,
  AVG_PROC_INST_DUR_GROUP_BY_VARIABLE,
  AVG_PROC_INST_DUR_GROUP_BY_VARIABLE_WITH_PART,

  MIN_PROC_INST_DUR_GROUP_BY_NONE,
  MIN_PROC_INST_DUR_GROUP_BY_NONE_WITH_PART,
  MIN_PROC_INST_DUR_GROUP_BY_START_DATE,
  MIN_PROC_INST_DUR_GROUP_BY_START_DATE_WITH_PART,
  MIN_PROC_INST_DUR_GROUP_BY_VARIABLE,
  MIN_PROC_INST_DUR_GROUP_BY_VARIABLE_WITH_PART,

  MAX_PROC_INST_DUR_GROUP_BY_NONE,
  MAX_PROC_INST_DUR_GROUP_BY_NONE_WITH_PART,
  MAX_PROC_INST_DUR_GROUP_BY_START_DATE,
  MAX_PROC_INST_DUR_GROUP_BY_START_DATE_WITH_PART,
  MAX_PROC_INST_DUR_GROUP_BY_VARIABLE,
  MAX_PROC_INST_DUR_GROUP_BY_VARIABLE_WITH_PART,

  MEDIAN_PROC_INST_DUR_GROUP_BY_NONE,
  MEDIAN_PROC_INST_DUR_GROUP_BY_NONE_WITH_PART,
  MEDIAN_PROC_INST_DUR_GROUP_BY_START_DATE,
  MEDIAN_PROC_INST_DUR_GROUP_BY_START_DATE_WITH_PART,
  MEDIAN_PROC_INST_DUR_GROUP_BY_VARIABLE,
  MEDIAN_PROC_INST_DUR_GROUP_BY_VARIABLE_WITH_PART,

  COUNT_PROC_INST_FREQ_GROUP_BY_NONE,
  COUNT_PROC_INST_FREQ_GROUP_BY_START_DATE,
  COUNT_PROC_INST_FREQ_GROUP_BY_VARIABLE,

  COUNT_FLOW_NODE_FREQ_GROUP_BY_FLOW_NODE,

  AVG_FLOW_NODE_DUR_GROUP_BY_FLOW_NODE,
  MIN_FLOW_NODE_DUR_GROUP_BY_FLOW_NODE,
  MAX_FLOW_NODE_DUR_GROUP_BY_FLOW_NODE,
  MEDIAN_FLOW_NODE_DUR_GROUP_BY_FLOW_NODE,

}
