/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(project(":zeebe-backup"))
    api(libs.com.fasterxml.jackson.core.jackson.databind)
    testImplementation(project(":zeebe-protocol"))
    testImplementation(libs.org.junit.jupiter.junit.jupiter.api)
    testImplementation(libs.org.assertj.assertj.core)
    testImplementation(libs.net.jqwik.jqwik)
    testImplementation(libs.org.junit.jupiter.junit.jupiter.engine)
}

description = "Zeebe Backup Store Common"
