/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    testImplementation(libs.org.testcontainers.testcontainers)
    testImplementation(libs.com.github.docker.java.docker.java.api)
    testImplementation(project(":zeebe-test-util"))
    testImplementation(project(":camunda-zeebe"))
    testImplementation(project(":zeebe-qa-util"))
    testImplementation(libs.org.slf4j.slf4j.api)
    testImplementation(libs.io.zeebe.zeebe.test.container)
    testImplementation(project(":camunda-client-java"))
    testImplementation(project(":zeebe-bpmn-model"))
    testImplementation(project(":camunda-authentication"))
    testImplementation(libs.org.junit.jupiter.junit.jupiter.api)
    testImplementation(libs.org.junit.jupiter.junit.jupiter.params)
    testImplementation(libs.org.assertj.assertj.core)
    testImplementation(libs.org.mockito.mockito.core)
    testImplementation(project(":zeebe-util"))
    testImplementation(libs.org.awaitility.awaitility)
    testImplementation(libs.net.jodah.failsafe)
    testImplementation(libs.org.agrona.agrona)
    testImplementation(libs.com.fasterxml.jackson.core.jackson.databind)
    testImplementation(libs.com.fasterxml.jackson.core.jackson.annotations)
    testImplementation(libs.io.github.resilience4j.resilience4j.retry)
    testImplementation(libs.io.github.resilience4j.resilience4j.core)
    testImplementation(project(":zeebe-protocol"))
}

description = "Zeebe QA Update Tests"
