#
# copyright camunda services gmbh and/or licensed to camunda services gmbh under one or more contributor license agreements.
# licensed under a proprietary license. see the license.txt file for more information.
# you may not use this file except in compliance with the proprietary license.
#
# Jackson 2 compatibility mode for Spring Boot 4.0
# See: https://docs.spring.io/spring-boot/4.0-SNAPSHOT/reference/features/json.html#features.json.jackson2
spring.http.converters.preferred-json-mapper=jackson2
# Actuator Config
management.endpoints.web.base-path=/actuator
management.endpoint.metrics.enabled=true
management.endpoints.web.exposure.include=metrics,health,info,prometheus,backups
management.metrics.distribution.percentiles-histogram.http.server.requests=true
management.metrics.distribution.percentiles.http.server.requests=0.5,0.95,0.99
management.metrics.distribution.slo.optimize.import.overallImportTime=1s,5s,15s,30s,1m,2m,5m,10m,15m,20m,30m,45m,1h,2h,4h
management.metrics.distribution.slo.optimize.import.newPageFetchTime=10ms,50ms,100ms,250ms,500ms,1s,2500ms,5s,10s,30s
management.metrics.distribution.slo.optimize.import.indexingDuration=10ms,50ms,100ms,250ms,500ms,1s,2500ms,5s,10s,30s,1m,5m
management.metrics.distribution.slo.optimize.import.cycleDuration=10ms,50ms,100ms,250ms,500ms,1s,2500ms,5s,10s,30s,1m,5m
#Report Instrumentation Config
optimize.metrics.report-latency.enabled=true
