# Elasticsearch values for Camunda Platform Chart.
# https://github.com/camunda/camunda-platform-helm
#
# This configures Elasticsearch when it's used for Optimize AND as the Camunda secondary storage.
#
# If you want to configure Elasticsearch only for Optimize and use another
# secondary storage option for Camunda, see
# the "camunda-platform-values-optimize-elasticsearch.yaml" file.
# If you make changes to this file or the
# "camunda-platform-values-optimize-elasticsearch.yaml" file, make sure to keep
# the other file in sync (minus the secondary storage-only options).

########################################################################################
################################################### Global cluster configuration
########################################################################################
global:
  elasticsearch:
    url:
      # The Elasticsearch host value is derived from the ECK Elasticsearch custom resource name.
      # The ECK operator creates a service named "<resource-name>-es-http" for HTTP access.
      # See resources/elasticsearch.yaml for the resource definition.
      host: elasticsearch-es-http

########################################################################################
################################################### Orchestration cluster configuration
########################################################################################
orchestration:
  # We need to explicitly set the secondary storage type to ELS
  # THIS GETS OVERRIDDEN IN THE OTHER VALUES FILES, e.g. for OpenSearch and RDBMS
  data:
    secondaryStorage:
      type: elasticsearch
      enabled: true
