# Elasticsearch values for Camunda Platform Chart.
# https://github.com/camunda/camunda-platform-helm
#
# This configures Elasticsearch when it's used for Optimize, but NOT as the Camunda secondary storage.
#
# For the Elasticsearch as secondary storage configuration, see the
# "camunda-platform-values-elasticsearch.yaml" file.
# If you make changes to this file or the "camunda-platform-values-elasticsearch.yaml" file, make
# sure to keep the other file in sync (minus the secondary storage-only options).
#
##########################################################################
################################################### Optimize configuration
##########################################################################
optimize:
  database:
    elasticsearch:
      enabled: true
      url:
        # The Elasticsearch host value is derived from the ECK Elasticsearch custom resource name.
        # The ECK operator creates a service named "<resource-name>-es-http" for HTTP access.
        # See load-tests/setup/default/resources/elasticsearch.yaml for the resource definition.
        host: elasticsearch-es-http
