/*
 * Copyright Camunda Services GmbH and/or licensed to Camunda Services GmbH under
 * one or more contributor license agreements. See the NOTICE file distributed
 * with this work for additional information regarding copyright ownership.
 * Licensed under the Camunda License 1.0. You may not use this file
 * except in compliance with the Camunda License 1.0.
 */
package io.camunda.zeebe.db.impl.rocksdb;

import io.micrometer.core.instrument.Counter;
import io.micrometer.core.instrument.MeterRegistry;
import java.util.Arrays;
import java.util.Map;
import java.util.stream.Collectors;
import org.rocksdb.AbstractEventListener;
import org.rocksdb.FlushJobInfo;
import org.rocksdb.FlushReason;
import org.rocksdb.MemTableInfo;
import org.rocksdb.RocksDB;
import org.slf4j.Logger;

/**
 * Logs RocksDB flush and memtable lifecycle events to help diagnose optimistic transaction
 * conflict-check failures. When a memtable is flushed, its sequence-number history is discarded (if
 * max_write_buffer_size_to_maintain is 0), which causes conflict checks to fail for any transaction
 * that started before the flushed range.
 *
 * <h2>Flush reasons</h2>
 *
 * RocksDB reports a {@link FlushReason} for every flush. The reasons relevant to Zeebe:
 *
 * <p>PS: Generated by claude - Did not yet verify if the explanations are valid.
 *
 * <dl>
 *   <dt>{@link FlushReason#WRITE_BUFFER_FULL}
 *   <dd>Most common trigger in production. The memtable reached its configured size limit ({@code
 *       write_buffer_size}). When {@code max_write_buffer_size_to_maintain=0} (Zeebe's default),
 *       this discards sequence-number history and is the primary cause of optimistic-transaction
 *       conflict-check failures.
 *   <dt>{@link FlushReason#WRITE_BUFFER_MANAGER}
 *   <dd>The global {@code WriteBufferManager} limit (shared across all column families and
 *       databases) was exceeded, forcing this column family to flush to release shared memory.
 *   <dt>{@link FlushReason#WAL_FULL}
 *   <dd>The write-ahead log reached its size limit. RocksDB must flush memtables to free WAL space
 *       before it can accept new writes.
 *   <dt>{@link FlushReason#MANUAL_FLUSH}
 *   <dd>An explicit {@code DB::Flush()} call — triggered by the application or an operator.
 *   <dt>{@link FlushReason#MANUAL_COMPACTION}
 *   <dd>A manual compaction was requested; RocksDB flushes the memtable first to ensure all live
 *       data is in SST files.
 *   <dt>{@link FlushReason#AUTO_COMPACTION}
 *   <dd>A background compaction needed the memtable to be flushed first.
 *   <dt>{@link FlushReason#SHUTDOWN}
 *   <dd>The database is closing; all memtables are flushed before the DB is fully shut down.
 *   <dt>{@link FlushReason#EXTERNAL_FILE_INGESTION}
 *   <dd>An external SST file is being bulk-ingested via {@code IngestExternalFile()}, which
 *       requires a prior memtable flush.
 *   <dt>{@link FlushReason#GET_LIVE_FILES}
 *   <dd>{@code GetLiveFiles()} was called — typically by a backup or checkpoint operation.
 *   <dt>{@link FlushReason#DELETE_FILES}
 *   <dd>{@code DeleteFile()} was called; requires a flush to ensure no live memtable data overlaps
 *       the file being deleted.
 *   <dt>{@link FlushReason#ERROR_RECOVERY}
 *   <dd>Flush triggered as part of an error-recovery sequence.
 *   <dt>{@link FlushReason#ERROR_RECOVERY_RETRY_FLUSH}
 *   <dd>A retry flush during error recovery after a previous flush attempt failed.
 *   <dt>{@link FlushReason#CATCH_UP_AFTER_ERROR_RECOVERY}
 *   <dd>A catch-up flush after error recovery completes, to sync state.
 *   <dt>{@link FlushReason#TEST}
 *   <dd>Triggered only in tests.
 *   <dt>{@link FlushReason#OTHERS}
 *   <dd>Unclassified reason; may indicate a RocksDB version mismatch.
 * </dl>
 */
public final class ZeebeRocksDbEventListener extends AbstractEventListener {

  private static final Logger LOG = Loggers.DB_LOGGER;

  /**
   * Counter metric {@code zeebe.rocksdb.memtable.flush} tagged by {@code reason}, incremented on
   * every completed flush. Use this to track how frequently each {@link FlushReason} fires, and to
   * correlate flush activity with transaction conflict failures.
   */
  private final Map<FlushReason, Counter> flushCounters;

  public ZeebeRocksDbEventListener(final MeterRegistry meterRegistry) {
    super(
        EnabledEventCallback.ON_FLUSH_BEGIN,
        EnabledEventCallback.ON_FLUSH_COMPLETED,
        EnabledEventCallback.ON_MEMTABLE_SEALED);
    flushCounters =
        Arrays.stream(FlushReason.values())
            .collect(
                Collectors.toUnmodifiableMap(
                    r -> r,
                    r ->
                        Counter.builder("zeebe.rocksdb.memtable.flush")
                            .description("Number of memtable flushes completed, by trigger reason")
                            .tag("reason", r.name())
                            .register(meterRegistry)));
  }

  @Override
  public void onFlushCompleted(final RocksDB db, final FlushJobInfo flushJobInfo) {
    flushCounters.get(flushJobInfo.getFlushReason()).increment();
    LOG.trace(
        "RocksDB memtable flush completed: columnFamily={}, reason={}, smallestSeqno={}, largestSeqno={}",
        flushJobInfo.getColumnFamilyName(),
        flushJobInfo.getFlushReason(),
        flushJobInfo.getSmallestSeqno(),
        flushJobInfo.getLargestSeqno());
  }

  @Override
  public void onFlushBegin(final RocksDB db, final FlushJobInfo flushJobInfo) {
    LOG.trace(
        "RocksDB memtable flush started: columnFamily={}, reason={}",
        flushJobInfo.getColumnFamilyName(),
        flushJobInfo.getFlushReason());
  }

  /**
   * Called when a memtable becomes immutable (write buffer full). The sequence range logged here
   * ({@code firstSeqno} to the next flush's {@code largestSeqno}) is the range that will be lost
   * from in-memory conflict history once the flush completes.
   */
  @Override
  public void onMemTableSealed(final MemTableInfo memTableInfo) {
    LOG.trace(
        "RocksDB memtable sealed (now immutable): columnFamily={}, firstSeqno={}, earliestSeqno={}, numEntries={}",
        memTableInfo.getColumnFamilyName(),
        memTableInfo.getFirstSeqno(),
        memTableInfo.getEarliestSeqno(),
        memTableInfo.getNumEntries());
  }
}
