---
name: Setup AWS OpenSearch env

# owner: @camunda/data-layer

description: |
  Imports OpenSearch endpoints from Vault, resolves OS URL for a selected 
  version, and configures AWS credentials.

inputs:
  vault-address:
    description: Vault URL to retrieve secrets from
    required: true
  vault-role-id:
    description: Vault Role ID to use
    required: true
  vault-secret-id:
    description: Vault Secret ID to use
    required: true
  opensearch-version:
    description: OpenSearch version to configure (2.19 or 3.3)
    required: true

outputs:
  opensearch-url:
    description: Resolved OpenSearch endpoint URL for the selected version
    value: ${{ steps.resolve-os-url.outputs.opensearch-url }}

runs:
  using: composite
  steps:
    - name: Import secrets from Vault
      id: secrets
      uses: hashicorp/vault-action@4c06c5ccf5c0761b6029f56cfb1dcf5565918a3b # v3.4.0
      with:
        url: ${{ inputs.vault-address }}
        method: approle
        roleId: ${{ inputs.vault-role-id }}
        secretId: ${{ inputs.vault-secret-id }}
        secrets: |
          secret/data/products/camunda/ci/github-actions CAMUNDA_CI_OPENSEARCH_2_19_URL;
          secret/data/products/camunda/ci/github-actions CAMUNDA_CI_OPENSEARCH_3_3_URL;

    - name: Resolve OpenSearch URL and export env
      id: resolve-os-url
      shell: bash
      run: |
        {
          echo "AWS_REGION=$AWS_REGION"
          echo "AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION"
          echo "AWS_ROLE_ARN=$AWS_ROLE_ARN"
          echo "AWS_WEB_IDENTITY_TOKEN_FILE=$AWS_WEB_IDENTITY_TOKEN_FILE"
          echo "AWS_STS_REGIONAL_ENDPOINTS=$AWS_STS_REGIONAL_ENDPOINTS"
        } >> "$GITHUB_ENV"

        if [[ "${{ inputs.opensearch-version }}" = "2.19" ]]
        then
          echo "Using OS 2.19"
          OS_URL="https://${{ steps.secrets.outputs.CAMUNDA_CI_OPENSEARCH_2_19_URL }}"
        elif [[ "${{ inputs.opensearch-version }}" = "3.3" ]]
        then
          echo "Using OS 3.3"
          OS_URL="https://${{ steps.secrets.outputs.CAMUNDA_CI_OPENSEARCH_3_3_URL }}"
        else
          echo "Unsupported OpenSearch version"
          exit 1
        fi

        echo "OPENSEARCH_URL=$OS_URL" >> "$GITHUB_ENV"
        echo "opensearch-url=$OS_URL" >> "$GITHUB_OUTPUT"

    - name: Pre-login to AWS
      uses: aws-actions/configure-aws-credentials@ec61189d14ec14c8efccab744f656cffd0e33f37 # v6.1.0
      with:
        aws-region: ${{ env.AWS_REGION }}
        web-identity-token-file: ${{ env.AWS_WEB_IDENTITY_TOKEN_FILE }}
        role-to-assume: ${{ env.AWS_ROLE_ARN }}
