services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.1
    command: start-dev --import-realm
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    ports:
      - "18080:8080"
    volumes:
      - ./realm-camunda.json:/opt/keycloak/data/import/realm-camunda.json:ro
