// Code generated by protoc-gen-go. DO NOT EDIT.
// source: gateway.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import empty "github.com/golang/protobuf/ptypes/empty"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Partition_PartitionBrokerRole int32

const (
	Partition_LEADER Partition_PartitionBrokerRole = 0
	Partition_FOLLOW Partition_PartitionBrokerRole = 1
)

var Partition_PartitionBrokerRole_name = map[int32]string{
	0: "LEADER",
	1: "FOLLOW",
}
var Partition_PartitionBrokerRole_value = map[string]int32{
	"LEADER": 0,
	"FOLLOW": 1,
}

func (x Partition_PartitionBrokerRole) String() string {
	return proto.EnumName(Partition_PartitionBrokerRole_name, int32(x))
}
func (Partition_PartitionBrokerRole) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_gateway_5f4d0dd5a4502bd1, []int{1, 0}
}

type WorkflowRequestObject_ResourceType int32

const (
	WorkflowRequestObject_BPMN WorkflowRequestObject_ResourceType = 0
	WorkflowRequestObject_YAML WorkflowRequestObject_ResourceType = 1
)

var WorkflowRequestObject_ResourceType_name = map[int32]string{
	0: "BPMN",
	1: "YAML",
}
var WorkflowRequestObject_ResourceType_value = map[string]int32{
	"BPMN": 0,
	"YAML": 1,
}

func (x WorkflowRequestObject_ResourceType) String() string {
	return proto.EnumName(WorkflowRequestObject_ResourceType_name, int32(x))
}
func (WorkflowRequestObject_ResourceType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_gateway_5f4d0dd5a4502bd1, []int{4, 0}
}

type HealthRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HealthRequest) Reset()         { *m = HealthRequest{} }
func (m *HealthRequest) String() string { return proto.CompactTextString(m) }
func (*HealthRequest) ProtoMessage()    {}
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_gateway_5f4d0dd5a4502bd1, []int{0}
}
func (m *HealthRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HealthRequest.Unmarshal(m, b)
}
func (m *HealthRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HealthRequest.Marshal(b, m, deterministic)
}
func (dst *HealthRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HealthRequest.Merge(dst, src)
}
func (m *HealthRequest) XXX_Size() int {
	return xxx_messageInfo_HealthRequest.Size(m)
}
func (m *HealthRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HealthRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HealthRequest proto.InternalMessageInfo

type Partition struct {
	PartitionId          int32                         `protobuf:"varint,1,opt,name=partitionId,proto3" json:"partitionId,omitempty"`
	Role                 Partition_PartitionBrokerRole `protobuf:"varint,3,opt,name=role,proto3,enum=gateway_protocol.Partition_PartitionBrokerRole" json:"role,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *Partition) Reset()         { *m = Partition{} }
func (m *Partition) String() string { return proto.CompactTextString(m) }
func (*Partition) ProtoMessage()    {}
func (*Partition) Descriptor() ([]byte, []int) {
	return fileDescriptor_gateway_5f4d0dd5a4502bd1, []int{1}
}
func (m *Partition) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Partition.Unmarshal(m, b)
}
func (m *Partition) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Partition.Marshal(b, m, deterministic)
}
func (dst *Partition) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Partition.Merge(dst, src)
}
func (m *Partition) XXX_Size() int {
	return xxx_messageInfo_Partition.Size(m)
}
func (m *Partition) XXX_DiscardUnknown() {
	xxx_messageInfo_Partition.DiscardUnknown(m)
}

var xxx_messageInfo_Partition proto.InternalMessageInfo

func (m *Partition) GetPartitionId() int32 {
	if m != nil {
		return m.PartitionId
	}
	return 0
}

func (m *Partition) GetRole() Partition_PartitionBrokerRole {
	if m != nil {
		return m.Role
	}
	return Partition_LEADER
}

type BrokerInfo struct {
	Host                 string       `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Port                 int32        `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Partitions           []*Partition `protobuf:"bytes,3,rep,name=partitions,proto3" json:"partitions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *BrokerInfo) Reset()         { *m = BrokerInfo{} }
func (m *BrokerInfo) String() string { return proto.CompactTextString(m) }
func (*BrokerInfo) ProtoMessage()    {}
func (*BrokerInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_gateway_5f4d0dd5a4502bd1, []int{2}
}
func (m *BrokerInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BrokerInfo.Unmarshal(m, b)
}
func (m *BrokerInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BrokerInfo.Marshal(b, m, deterministic)
}
func (dst *BrokerInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BrokerInfo.Merge(dst, src)
}
func (m *BrokerInfo) XXX_Size() int {
	return xxx_messageInfo_BrokerInfo.Size(m)
}
func (m *BrokerInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_BrokerInfo.DiscardUnknown(m)
}

var xxx_messageInfo_BrokerInfo proto.InternalMessageInfo

func (m *BrokerInfo) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *BrokerInfo) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *BrokerInfo) GetPartitions() []*Partition {
	if m != nil {
		return m.Partitions
	}
	return nil
}

type HealthResponse struct {
	Brokers              []*BrokerInfo `protobuf:"bytes,1,rep,name=brokers,proto3" json:"brokers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *HealthResponse) Reset()         { *m = HealthResponse{} }
func (m *HealthResponse) String() string { return proto.CompactTextString(m) }
func (*HealthResponse) ProtoMessage()    {}
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_gateway_5f4d0dd5a4502bd1, []int{3}
}
func (m *HealthResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HealthResponse.Unmarshal(m, b)
}
func (m *HealthResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HealthResponse.Marshal(b, m, deterministic)
}
func (dst *HealthResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HealthResponse.Merge(dst, src)
}
func (m *HealthResponse) XXX_Size() int {
	return xxx_messageInfo_HealthResponse.Size(m)
}
func (m *HealthResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HealthResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HealthResponse proto.InternalMessageInfo

func (m *HealthResponse) GetBrokers() []*BrokerInfo {
	if m != nil {
		return m.Brokers
	}
	return nil
}

type WorkflowRequestObject struct {
	Name                 string                             `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type                 WorkflowRequestObject_ResourceType `protobuf:"varint,2,opt,name=type,proto3,enum=gateway_protocol.WorkflowRequestObject_ResourceType" json:"type,omitempty"`
	Definition           []byte                             `protobuf:"bytes,3,opt,name=definition,proto3" json:"definition,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                           `json:"-"`
	XXX_unrecognized     []byte                             `json:"-"`
	XXX_sizecache        int32                              `json:"-"`
}

func (m *WorkflowRequestObject) Reset()         { *m = WorkflowRequestObject{} }
func (m *WorkflowRequestObject) String() string { return proto.CompactTextString(m) }
func (*WorkflowRequestObject) ProtoMessage()    {}
func (*WorkflowRequestObject) Descriptor() ([]byte, []int) {
	return fileDescriptor_gateway_5f4d0dd5a4502bd1, []int{4}
}
func (m *WorkflowRequestObject) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WorkflowRequestObject.Unmarshal(m, b)
}
func (m *WorkflowRequestObject) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WorkflowRequestObject.Marshal(b, m, deterministic)
}
func (dst *WorkflowRequestObject) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WorkflowRequestObject.Merge(dst, src)
}
func (m *WorkflowRequestObject) XXX_Size() int {
	return xxx_messageInfo_WorkflowRequestObject.Size(m)
}
func (m *WorkflowRequestObject) XXX_DiscardUnknown() {
	xxx_messageInfo_WorkflowRequestObject.DiscardUnknown(m)
}

var xxx_messageInfo_WorkflowRequestObject proto.InternalMessageInfo

func (m *WorkflowRequestObject) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *WorkflowRequestObject) GetType() WorkflowRequestObject_ResourceType {
	if m != nil {
		return m.Type
	}
	return WorkflowRequestObject_BPMN
}

func (m *WorkflowRequestObject) GetDefinition() []byte {
	if m != nil {
		return m.Definition
	}
	return nil
}

type DeployWorkflowRequest struct {
	Workflows            []*WorkflowRequestObject `protobuf:"bytes,1,rep,name=workflows,proto3" json:"workflows,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *DeployWorkflowRequest) Reset()         { *m = DeployWorkflowRequest{} }
func (m *DeployWorkflowRequest) String() string { return proto.CompactTextString(m) }
func (*DeployWorkflowRequest) ProtoMessage()    {}
func (*DeployWorkflowRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_gateway_5f4d0dd5a4502bd1, []int{5}
}
func (m *DeployWorkflowRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeployWorkflowRequest.Unmarshal(m, b)
}
func (m *DeployWorkflowRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeployWorkflowRequest.Marshal(b, m, deterministic)
}
func (dst *DeployWorkflowRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeployWorkflowRequest.Merge(dst, src)
}
func (m *DeployWorkflowRequest) XXX_Size() int {
	return xxx_messageInfo_DeployWorkflowRequest.Size(m)
}
func (m *DeployWorkflowRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeployWorkflowRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeployWorkflowRequest proto.InternalMessageInfo

func (m *DeployWorkflowRequest) GetWorkflows() []*WorkflowRequestObject {
	if m != nil {
		return m.Workflows
	}
	return nil
}

type WorkflowMetadata struct {
	BpmnProcessId        string   `protobuf:"bytes,1,opt,name=bpmnProcessId,proto3" json:"bpmnProcessId,omitempty"`
	Version              int32    `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	WorkflowKey          int64    `protobuf:"varint,3,opt,name=workflowKey,proto3" json:"workflowKey,omitempty"`
	ResourceName         string   `protobuf:"bytes,4,opt,name=resourceName,proto3" json:"resourceName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WorkflowMetadata) Reset()         { *m = WorkflowMetadata{} }
func (m *WorkflowMetadata) String() string { return proto.CompactTextString(m) }
func (*WorkflowMetadata) ProtoMessage()    {}
func (*WorkflowMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_gateway_5f4d0dd5a4502bd1, []int{6}
}
func (m *WorkflowMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WorkflowMetadata.Unmarshal(m, b)
}
func (m *WorkflowMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WorkflowMetadata.Marshal(b, m, deterministic)
}
func (dst *WorkflowMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WorkflowMetadata.Merge(dst, src)
}
func (m *WorkflowMetadata) XXX_Size() int {
	return xxx_messageInfo_WorkflowMetadata.Size(m)
}
func (m *WorkflowMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_WorkflowMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_WorkflowMetadata proto.InternalMessageInfo

func (m *WorkflowMetadata) GetBpmnProcessId() string {
	if m != nil {
		return m.BpmnProcessId
	}
	return ""
}

func (m *WorkflowMetadata) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *WorkflowMetadata) GetWorkflowKey() int64 {
	if m != nil {
		return m.WorkflowKey
	}
	return 0
}

func (m *WorkflowMetadata) GetResourceName() string {
	if m != nil {
		return m.ResourceName
	}
	return ""
}

type DeployWorkflowResponse struct {
	Key                  int64               `protobuf:"varint,1,opt,name=key,proto3" json:"key,omitempty"`
	Workflows            []*WorkflowMetadata `protobuf:"bytes,2,rep,name=workflows,proto3" json:"workflows,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *DeployWorkflowResponse) Reset()         { *m = DeployWorkflowResponse{} }
func (m *DeployWorkflowResponse) String() string { return proto.CompactTextString(m) }
func (*DeployWorkflowResponse) ProtoMessage()    {}
func (*DeployWorkflowResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_gateway_5f4d0dd5a4502bd1, []int{7}
}
func (m *DeployWorkflowResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeployWorkflowResponse.Unmarshal(m, b)
}
func (m *DeployWorkflowResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeployWorkflowResponse.Marshal(b, m, deterministic)
}
func (dst *DeployWorkflowResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeployWorkflowResponse.Merge(dst, src)
}
func (m *DeployWorkflowResponse) XXX_Size() int {
	return xxx_messageInfo_DeployWorkflowResponse.Size(m)
}
func (m *DeployWorkflowResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeployWorkflowResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeployWorkflowResponse proto.InternalMessageInfo

func (m *DeployWorkflowResponse) GetKey() int64 {
	if m != nil {
		return m.Key
	}
	return 0
}

func (m *DeployWorkflowResponse) GetWorkflows() []*WorkflowMetadata {
	if m != nil {
		return m.Workflows
	}
	return nil
}

type PublishMessageRequest struct {
	Name           string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	CorrelationKey string `protobuf:"bytes,2,opt,name=correlationKey,proto3" json:"correlationKey,omitempty"`
	TimeToLive     int64  `protobuf:"varint,3,opt,name=timeToLive,proto3" json:"timeToLive,omitempty"`
	MessageId      string `protobuf:"bytes,4,opt,name=messageId,proto3" json:"messageId,omitempty"`
	// payload has to be a valid json object as string
	Payload              string   `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PublishMessageRequest) Reset()         { *m = PublishMessageRequest{} }
func (m *PublishMessageRequest) String() string { return proto.CompactTextString(m) }
func (*PublishMessageRequest) ProtoMessage()    {}
func (*PublishMessageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_gateway_5f4d0dd5a4502bd1, []int{8}
}
func (m *PublishMessageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PublishMessageRequest.Unmarshal(m, b)
}
func (m *PublishMessageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PublishMessageRequest.Marshal(b, m, deterministic)
}
func (dst *PublishMessageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PublishMessageRequest.Merge(dst, src)
}
func (m *PublishMessageRequest) XXX_Size() int {
	return xxx_messageInfo_PublishMessageRequest.Size(m)
}
func (m *PublishMessageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PublishMessageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PublishMessageRequest proto.InternalMessageInfo

func (m *PublishMessageRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PublishMessageRequest) GetCorrelationKey() string {
	if m != nil {
		return m.CorrelationKey
	}
	return ""
}

func (m *PublishMessageRequest) GetTimeToLive() int64 {
	if m != nil {
		return m.TimeToLive
	}
	return 0
}

func (m *PublishMessageRequest) GetMessageId() string {
	if m != nil {
		return m.MessageId
	}
	return ""
}

func (m *PublishMessageRequest) GetPayload() string {
	if m != nil {
		return m.Payload
	}
	return ""
}

type CreateJobRequest struct {
	JobType string `protobuf:"bytes,1,opt,name=jobType,proto3" json:"jobType,omitempty"`
	Retries int32  `protobuf:"varint,2,opt,name=retries,proto3" json:"retries,omitempty"`
	// custom headers has to be a valid json object as string
	CustomHeaders string `protobuf:"bytes,3,opt,name=customHeaders,proto3" json:"customHeaders,omitempty"`
	// payload has to be a valid json object as string
	Payload              string   `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateJobRequest) Reset()         { *m = CreateJobRequest{} }
func (m *CreateJobRequest) String() string { return proto.CompactTextString(m) }
func (*CreateJobRequest) ProtoMessage()    {}
func (*CreateJobRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_gateway_5f4d0dd5a4502bd1, []int{9}
}
func (m *CreateJobRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateJobRequest.Unmarshal(m, b)
}
func (m *CreateJobRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateJobRequest.Marshal(b, m, deterministic)
}
func (dst *CreateJobRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateJobRequest.Merge(dst, src)
}
func (m *CreateJobRequest) XXX_Size() int {
	return xxx_messageInfo_CreateJobRequest.Size(m)
}
func (m *CreateJobRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateJobRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateJobRequest proto.InternalMessageInfo

func (m *CreateJobRequest) GetJobType() string {
	if m != nil {
		return m.JobType
	}
	return ""
}

func (m *CreateJobRequest) GetRetries() int32 {
	if m != nil {
		return m.Retries
	}
	return 0
}

func (m *CreateJobRequest) GetCustomHeaders() string {
	if m != nil {
		return m.CustomHeaders
	}
	return ""
}

func (m *CreateJobRequest) GetPayload() string {
	if m != nil {
		return m.Payload
	}
	return ""
}

type CreateJobResponse struct {
	Key                  int64    `protobuf:"varint,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateJobResponse) Reset()         { *m = CreateJobResponse{} }
func (m *CreateJobResponse) String() string { return proto.CompactTextString(m) }
func (*CreateJobResponse) ProtoMessage()    {}
func (*CreateJobResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_gateway_5f4d0dd5a4502bd1, []int{10}
}
func (m *CreateJobResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateJobResponse.Unmarshal(m, b)
}
func (m *CreateJobResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateJobResponse.Marshal(b, m, deterministic)
}
func (dst *CreateJobResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateJobResponse.Merge(dst, src)
}
func (m *CreateJobResponse) XXX_Size() int {
	return xxx_messageInfo_CreateJobResponse.Size(m)
}
func (m *CreateJobResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateJobResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateJobResponse proto.InternalMessageInfo

func (m *CreateJobResponse) GetKey() int64 {
	if m != nil {
		return m.Key
	}
	return 0
}

type UpdateJobRetriesRequest struct {
	JobKey               int64    `protobuf:"varint,1,opt,name=jobKey,proto3" json:"jobKey,omitempty"`
	Retries              int32    `protobuf:"varint,2,opt,name=retries,proto3" json:"retries,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateJobRetriesRequest) Reset()         { *m = UpdateJobRetriesRequest{} }
func (m *UpdateJobRetriesRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateJobRetriesRequest) ProtoMessage()    {}
func (*UpdateJobRetriesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_gateway_5f4d0dd5a4502bd1, []int{11}
}
func (m *UpdateJobRetriesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateJobRetriesRequest.Unmarshal(m, b)
}
func (m *UpdateJobRetriesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateJobRetriesRequest.Marshal(b, m, deterministic)
}
func (dst *UpdateJobRetriesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateJobRetriesRequest.Merge(dst, src)
}
func (m *UpdateJobRetriesRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateJobRetriesRequest.Size(m)
}
func (m *UpdateJobRetriesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateJobRetriesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateJobRetriesRequest proto.InternalMessageInfo

func (m *UpdateJobRetriesRequest) GetJobKey() int64 {
	if m != nil {
		return m.JobKey
	}
	return 0
}

func (m *UpdateJobRetriesRequest) GetRetries() int32 {
	if m != nil {
		return m.Retries
	}
	return 0
}

type UpdateJobRetriesResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateJobRetriesResponse) Reset()         { *m = UpdateJobRetriesResponse{} }
func (m *UpdateJobRetriesResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateJobRetriesResponse) ProtoMessage()    {}
func (*UpdateJobRetriesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_gateway_5f4d0dd5a4502bd1, []int{12}
}
func (m *UpdateJobRetriesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateJobRetriesResponse.Unmarshal(m, b)
}
func (m *UpdateJobRetriesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateJobRetriesResponse.Marshal(b, m, deterministic)
}
func (dst *UpdateJobRetriesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateJobRetriesResponse.Merge(dst, src)
}
func (m *UpdateJobRetriesResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateJobRetriesResponse.Size(m)
}
func (m *UpdateJobRetriesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateJobRetriesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateJobRetriesResponse proto.InternalMessageInfo

type FailJobRequest struct {
	JobKey               int64    `protobuf:"varint,1,opt,name=jobKey,proto3" json:"jobKey,omitempty"`
	Retries              int32    `protobuf:"varint,2,opt,name=retries,proto3" json:"retries,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FailJobRequest) Reset()         { *m = FailJobRequest{} }
func (m *FailJobRequest) String() string { return proto.CompactTextString(m) }
func (*FailJobRequest) ProtoMessage()    {}
func (*FailJobRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_gateway_5f4d0dd5a4502bd1, []int{13}
}
func (m *FailJobRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FailJobRequest.Unmarshal(m, b)
}
func (m *FailJobRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FailJobRequest.Marshal(b, m, deterministic)
}
func (dst *FailJobRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FailJobRequest.Merge(dst, src)
}
func (m *FailJobRequest) XXX_Size() int {
	return xxx_messageInfo_FailJobRequest.Size(m)
}
func (m *FailJobRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FailJobRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FailJobRequest proto.InternalMessageInfo

func (m *FailJobRequest) GetJobKey() int64 {
	if m != nil {
		return m.JobKey
	}
	return 0
}

func (m *FailJobRequest) GetRetries() int32 {
	if m != nil {
		return m.Retries
	}
	return 0
}

type FailJobResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FailJobResponse) Reset()         { *m = FailJobResponse{} }
func (m *FailJobResponse) String() string { return proto.CompactTextString(m) }
func (*FailJobResponse) ProtoMessage()    {}
func (*FailJobResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_gateway_5f4d0dd5a4502bd1, []int{14}
}
func (m *FailJobResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FailJobResponse.Unmarshal(m, b)
}
func (m *FailJobResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FailJobResponse.Marshal(b, m, deterministic)
}
func (dst *FailJobResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FailJobResponse.Merge(dst, src)
}
func (m *FailJobResponse) XXX_Size() int {
	return xxx_messageInfo_FailJobResponse.Size(m)
}
func (m *FailJobResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FailJobResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FailJobResponse proto.InternalMessageInfo

type CompleteJobRequest struct {
	JobKey int64 `protobuf:"varint,1,opt,name=jobKey,proto3" json:"jobKey,omitempty"`
	// payload has to be a valid json object as string
	Payload              string   `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CompleteJobRequest) Reset()         { *m = CompleteJobRequest{} }
func (m *CompleteJobRequest) String() string { return proto.CompactTextString(m) }
func (*CompleteJobRequest) ProtoMessage()    {}
func (*CompleteJobRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_gateway_5f4d0dd5a4502bd1, []int{15}
}
func (m *CompleteJobRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CompleteJobRequest.Unmarshal(m, b)
}
func (m *CompleteJobRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CompleteJobRequest.Marshal(b, m, deterministic)
}
func (dst *CompleteJobRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CompleteJobRequest.Merge(dst, src)
}
func (m *CompleteJobRequest) XXX_Size() int {
	return xxx_messageInfo_CompleteJobRequest.Size(m)
}
func (m *CompleteJobRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CompleteJobRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CompleteJobRequest proto.InternalMessageInfo

func (m *CompleteJobRequest) GetJobKey() int64 {
	if m != nil {
		return m.JobKey
	}
	return 0
}

func (m *CompleteJobRequest) GetPayload() string {
	if m != nil {
		return m.Payload
	}
	return ""
}

type CompleteJobResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CompleteJobResponse) Reset()         { *m = CompleteJobResponse{} }
func (m *CompleteJobResponse) String() string { return proto.CompactTextString(m) }
func (*CompleteJobResponse) ProtoMessage()    {}
func (*CompleteJobResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_gateway_5f4d0dd5a4502bd1, []int{16}
}
func (m *CompleteJobResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CompleteJobResponse.Unmarshal(m, b)
}
func (m *CompleteJobResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CompleteJobResponse.Marshal(b, m, deterministic)
}
func (dst *CompleteJobResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CompleteJobResponse.Merge(dst, src)
}
func (m *CompleteJobResponse) XXX_Size() int {
	return xxx_messageInfo_CompleteJobResponse.Size(m)
}
func (m *CompleteJobResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CompleteJobResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CompleteJobResponse proto.InternalMessageInfo

type CreateWorkflowInstanceRequest struct {
	WorkflowKey   int64  `protobuf:"varint,1,opt,name=workflowKey,proto3" json:"workflowKey,omitempty"`
	BpmnProcessId string `protobuf:"bytes,2,opt,name=bpmnProcessId,proto3" json:"bpmnProcessId,omitempty"`
	// if bpmnProcessId is set version = -1 indicates to use the latest version
	Version int32 `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	// payload has to be a valid json object as string
	Payload              string   `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateWorkflowInstanceRequest) Reset()         { *m = CreateWorkflowInstanceRequest{} }
func (m *CreateWorkflowInstanceRequest) String() string { return proto.CompactTextString(m) }
func (*CreateWorkflowInstanceRequest) ProtoMessage()    {}
func (*CreateWorkflowInstanceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_gateway_5f4d0dd5a4502bd1, []int{17}
}
func (m *CreateWorkflowInstanceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateWorkflowInstanceRequest.Unmarshal(m, b)
}
func (m *CreateWorkflowInstanceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateWorkflowInstanceRequest.Marshal(b, m, deterministic)
}
func (dst *CreateWorkflowInstanceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateWorkflowInstanceRequest.Merge(dst, src)
}
func (m *CreateWorkflowInstanceRequest) XXX_Size() int {
	return xxx_messageInfo_CreateWorkflowInstanceRequest.Size(m)
}
func (m *CreateWorkflowInstanceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateWorkflowInstanceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateWorkflowInstanceRequest proto.InternalMessageInfo

func (m *CreateWorkflowInstanceRequest) GetWorkflowKey() int64 {
	if m != nil {
		return m.WorkflowKey
	}
	return 0
}

func (m *CreateWorkflowInstanceRequest) GetBpmnProcessId() string {
	if m != nil {
		return m.BpmnProcessId
	}
	return ""
}

func (m *CreateWorkflowInstanceRequest) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *CreateWorkflowInstanceRequest) GetPayload() string {
	if m != nil {
		return m.Payload
	}
	return ""
}

type CreateWorkflowInstanceResponse struct {
	WorkflowKey          int64    `protobuf:"varint,1,opt,name=workflowKey,proto3" json:"workflowKey,omitempty"`
	BpmnProcessId        string   `protobuf:"bytes,2,opt,name=bpmnProcessId,proto3" json:"bpmnProcessId,omitempty"`
	Version              int32    `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	WorkflowInstanceKey  int64    `protobuf:"varint,5,opt,name=workflowInstanceKey,proto3" json:"workflowInstanceKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateWorkflowInstanceResponse) Reset()         { *m = CreateWorkflowInstanceResponse{} }
func (m *CreateWorkflowInstanceResponse) String() string { return proto.CompactTextString(m) }
func (*CreateWorkflowInstanceResponse) ProtoMessage()    {}
func (*CreateWorkflowInstanceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_gateway_5f4d0dd5a4502bd1, []int{18}
}
func (m *CreateWorkflowInstanceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateWorkflowInstanceResponse.Unmarshal(m, b)
}
func (m *CreateWorkflowInstanceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateWorkflowInstanceResponse.Marshal(b, m, deterministic)
}
func (dst *CreateWorkflowInstanceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateWorkflowInstanceResponse.Merge(dst, src)
}
func (m *CreateWorkflowInstanceResponse) XXX_Size() int {
	return xxx_messageInfo_CreateWorkflowInstanceResponse.Size(m)
}
func (m *CreateWorkflowInstanceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateWorkflowInstanceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateWorkflowInstanceResponse proto.InternalMessageInfo

func (m *CreateWorkflowInstanceResponse) GetWorkflowKey() int64 {
	if m != nil {
		return m.WorkflowKey
	}
	return 0
}

func (m *CreateWorkflowInstanceResponse) GetBpmnProcessId() string {
	if m != nil {
		return m.BpmnProcessId
	}
	return ""
}

func (m *CreateWorkflowInstanceResponse) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *CreateWorkflowInstanceResponse) GetWorkflowInstanceKey() int64 {
	if m != nil {
		return m.WorkflowInstanceKey
	}
	return 0
}

type CancelWorkflowInstanceRequest struct {
	WorkflowInstanceKey  int64    `protobuf:"varint,1,opt,name=workflowInstanceKey,proto3" json:"workflowInstanceKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CancelWorkflowInstanceRequest) Reset()         { *m = CancelWorkflowInstanceRequest{} }
func (m *CancelWorkflowInstanceRequest) String() string { return proto.CompactTextString(m) }
func (*CancelWorkflowInstanceRequest) ProtoMessage()    {}
func (*CancelWorkflowInstanceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_gateway_5f4d0dd5a4502bd1, []int{19}
}
func (m *CancelWorkflowInstanceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CancelWorkflowInstanceRequest.Unmarshal(m, b)
}
func (m *CancelWorkflowInstanceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CancelWorkflowInstanceRequest.Marshal(b, m, deterministic)
}
func (dst *CancelWorkflowInstanceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CancelWorkflowInstanceRequest.Merge(dst, src)
}
func (m *CancelWorkflowInstanceRequest) XXX_Size() int {
	return xxx_messageInfo_CancelWorkflowInstanceRequest.Size(m)
}
func (m *CancelWorkflowInstanceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CancelWorkflowInstanceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CancelWorkflowInstanceRequest proto.InternalMessageInfo

func (m *CancelWorkflowInstanceRequest) GetWorkflowInstanceKey() int64 {
	if m != nil {
		return m.WorkflowInstanceKey
	}
	return 0
}

type CancelWorkflowInstanceResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CancelWorkflowInstanceResponse) Reset()         { *m = CancelWorkflowInstanceResponse{} }
func (m *CancelWorkflowInstanceResponse) String() string { return proto.CompactTextString(m) }
func (*CancelWorkflowInstanceResponse) ProtoMessage()    {}
func (*CancelWorkflowInstanceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_gateway_5f4d0dd5a4502bd1, []int{20}
}
func (m *CancelWorkflowInstanceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CancelWorkflowInstanceResponse.Unmarshal(m, b)
}
func (m *CancelWorkflowInstanceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CancelWorkflowInstanceResponse.Marshal(b, m, deterministic)
}
func (dst *CancelWorkflowInstanceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CancelWorkflowInstanceResponse.Merge(dst, src)
}
func (m *CancelWorkflowInstanceResponse) XXX_Size() int {
	return xxx_messageInfo_CancelWorkflowInstanceResponse.Size(m)
}
func (m *CancelWorkflowInstanceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CancelWorkflowInstanceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CancelWorkflowInstanceResponse proto.InternalMessageInfo

type UpdateWorkflowInstancePayloadRequest struct {
	ActivityInstanceKey int64 `protobuf:"varint,1,opt,name=activityInstanceKey,proto3" json:"activityInstanceKey,omitempty"`
	// payload has to be a valid json object as string
	Payload              string   `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateWorkflowInstancePayloadRequest) Reset()         { *m = UpdateWorkflowInstancePayloadRequest{} }
func (m *UpdateWorkflowInstancePayloadRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateWorkflowInstancePayloadRequest) ProtoMessage()    {}
func (*UpdateWorkflowInstancePayloadRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_gateway_5f4d0dd5a4502bd1, []int{21}
}
func (m *UpdateWorkflowInstancePayloadRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateWorkflowInstancePayloadRequest.Unmarshal(m, b)
}
func (m *UpdateWorkflowInstancePayloadRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateWorkflowInstancePayloadRequest.Marshal(b, m, deterministic)
}
func (dst *UpdateWorkflowInstancePayloadRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateWorkflowInstancePayloadRequest.Merge(dst, src)
}
func (m *UpdateWorkflowInstancePayloadRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateWorkflowInstancePayloadRequest.Size(m)
}
func (m *UpdateWorkflowInstancePayloadRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateWorkflowInstancePayloadRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateWorkflowInstancePayloadRequest proto.InternalMessageInfo

func (m *UpdateWorkflowInstancePayloadRequest) GetActivityInstanceKey() int64 {
	if m != nil {
		return m.ActivityInstanceKey
	}
	return 0
}

func (m *UpdateWorkflowInstancePayloadRequest) GetPayload() string {
	if m != nil {
		return m.Payload
	}
	return ""
}

type UpdateWorkflowInstancePayloadResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateWorkflowInstancePayloadResponse) Reset()         { *m = UpdateWorkflowInstancePayloadResponse{} }
func (m *UpdateWorkflowInstancePayloadResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateWorkflowInstancePayloadResponse) ProtoMessage()    {}
func (*UpdateWorkflowInstancePayloadResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_gateway_5f4d0dd5a4502bd1, []int{22}
}
func (m *UpdateWorkflowInstancePayloadResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateWorkflowInstancePayloadResponse.Unmarshal(m, b)
}
func (m *UpdateWorkflowInstancePayloadResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateWorkflowInstancePayloadResponse.Marshal(b, m, deterministic)
}
func (dst *UpdateWorkflowInstancePayloadResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateWorkflowInstancePayloadResponse.Merge(dst, src)
}
func (m *UpdateWorkflowInstancePayloadResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateWorkflowInstancePayloadResponse.Size(m)
}
func (m *UpdateWorkflowInstancePayloadResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateWorkflowInstancePayloadResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateWorkflowInstancePayloadResponse proto.InternalMessageInfo

type ListWorkflowsRequest struct {
	// optional filter by BPMN process id, if empty all workflows are returned
	BpmnProcessId        string   `protobuf:"bytes,1,opt,name=bpmnProcessId,proto3" json:"bpmnProcessId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListWorkflowsRequest) Reset()         { *m = ListWorkflowsRequest{} }
func (m *ListWorkflowsRequest) String() string { return proto.CompactTextString(m) }
func (*ListWorkflowsRequest) ProtoMessage()    {}
func (*ListWorkflowsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_gateway_5f4d0dd5a4502bd1, []int{23}
}
func (m *ListWorkflowsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListWorkflowsRequest.Unmarshal(m, b)
}
func (m *ListWorkflowsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListWorkflowsRequest.Marshal(b, m, deterministic)
}
func (dst *ListWorkflowsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListWorkflowsRequest.Merge(dst, src)
}
func (m *ListWorkflowsRequest) XXX_Size() int {
	return xxx_messageInfo_ListWorkflowsRequest.Size(m)
}
func (m *ListWorkflowsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListWorkflowsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListWorkflowsRequest proto.InternalMessageInfo

func (m *ListWorkflowsRequest) GetBpmnProcessId() string {
	if m != nil {
		return m.BpmnProcessId
	}
	return ""
}

type ListWorkflowsResponse struct {
	Workflows            []*WorkflowMetadata `protobuf:"bytes,1,rep,name=workflows,proto3" json:"workflows,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *ListWorkflowsResponse) Reset()         { *m = ListWorkflowsResponse{} }
func (m *ListWorkflowsResponse) String() string { return proto.CompactTextString(m) }
func (*ListWorkflowsResponse) ProtoMessage()    {}
func (*ListWorkflowsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_gateway_5f4d0dd5a4502bd1, []int{24}
}
func (m *ListWorkflowsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListWorkflowsResponse.Unmarshal(m, b)
}
func (m *ListWorkflowsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListWorkflowsResponse.Marshal(b, m, deterministic)
}
func (dst *ListWorkflowsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListWorkflowsResponse.Merge(dst, src)
}
func (m *ListWorkflowsResponse) XXX_Size() int {
	return xxx_messageInfo_ListWorkflowsResponse.Size(m)
}
func (m *ListWorkflowsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListWorkflowsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListWorkflowsResponse proto.InternalMessageInfo

func (m *ListWorkflowsResponse) GetWorkflows() []*WorkflowMetadata {
	if m != nil {
		return m.Workflows
	}
	return nil
}

// either workflow key or bpmn process id and version has to be specified
type GetWorkflowRequest struct {
	WorkflowKey int64 `protobuf:"varint,1,opt,name=workflowKey,proto3" json:"workflowKey,omitempty"`
	// if bpmnProcessId is set version = -1 indicates to use the latest version
	Version              int32    `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	BpmnProcessId        string   `protobuf:"bytes,3,opt,name=bpmnProcessId,proto3" json:"bpmnProcessId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetWorkflowRequest) Reset()         { *m = GetWorkflowRequest{} }
func (m *GetWorkflowRequest) String() string { return proto.CompactTextString(m) }
func (*GetWorkflowRequest) ProtoMessage()    {}
func (*GetWorkflowRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_gateway_5f4d0dd5a4502bd1, []int{25}
}
func (m *GetWorkflowRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetWorkflowRequest.Unmarshal(m, b)
}
func (m *GetWorkflowRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetWorkflowRequest.Marshal(b, m, deterministic)
}
func (dst *GetWorkflowRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetWorkflowRequest.Merge(dst, src)
}
func (m *GetWorkflowRequest) XXX_Size() int {
	return xxx_messageInfo_GetWorkflowRequest.Size(m)
}
func (m *GetWorkflowRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetWorkflowRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetWorkflowRequest proto.InternalMessageInfo

func (m *GetWorkflowRequest) GetWorkflowKey() int64 {
	if m != nil {
		return m.WorkflowKey
	}
	return 0
}

func (m *GetWorkflowRequest) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *GetWorkflowRequest) GetBpmnProcessId() string {
	if m != nil {
		return m.BpmnProcessId
	}
	return ""
}

type GetWorkflowResponse struct {
	WorkflowKey          int64    `protobuf:"varint,1,opt,name=workflowKey,proto3" json:"workflowKey,omitempty"`
	Version              int32    `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	BpmnProcessId        string   `protobuf:"bytes,3,opt,name=bpmnProcessId,proto3" json:"bpmnProcessId,omitempty"`
	ResourceName         string   `protobuf:"bytes,4,opt,name=resourceName,proto3" json:"resourceName,omitempty"`
	BpmnXml              string   `protobuf:"bytes,5,opt,name=bpmnXml,proto3" json:"bpmnXml,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetWorkflowResponse) Reset()         { *m = GetWorkflowResponse{} }
func (m *GetWorkflowResponse) String() string { return proto.CompactTextString(m) }
func (*GetWorkflowResponse) ProtoMessage()    {}
func (*GetWorkflowResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_gateway_5f4d0dd5a4502bd1, []int{26}
}
func (m *GetWorkflowResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetWorkflowResponse.Unmarshal(m, b)
}
func (m *GetWorkflowResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetWorkflowResponse.Marshal(b, m, deterministic)
}
func (dst *GetWorkflowResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetWorkflowResponse.Merge(dst, src)
}
func (m *GetWorkflowResponse) XXX_Size() int {
	return xxx_messageInfo_GetWorkflowResponse.Size(m)
}
func (m *GetWorkflowResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetWorkflowResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetWorkflowResponse proto.InternalMessageInfo

func (m *GetWorkflowResponse) GetWorkflowKey() int64 {
	if m != nil {
		return m.WorkflowKey
	}
	return 0
}

func (m *GetWorkflowResponse) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *GetWorkflowResponse) GetBpmnProcessId() string {
	if m != nil {
		return m.BpmnProcessId
	}
	return ""
}

func (m *GetWorkflowResponse) GetResourceName() string {
	if m != nil {
		return m.ResourceName
	}
	return ""
}

func (m *GetWorkflowResponse) GetBpmnXml() string {
	if m != nil {
		return m.BpmnXml
	}
	return ""
}

func init() {
	proto.RegisterType((*HealthRequest)(nil), "gateway_protocol.HealthRequest")
	proto.RegisterType((*Partition)(nil), "gateway_protocol.Partition")
	proto.RegisterType((*BrokerInfo)(nil), "gateway_protocol.BrokerInfo")
	proto.RegisterType((*HealthResponse)(nil), "gateway_protocol.HealthResponse")
	proto.RegisterType((*WorkflowRequestObject)(nil), "gateway_protocol.WorkflowRequestObject")
	proto.RegisterType((*DeployWorkflowRequest)(nil), "gateway_protocol.DeployWorkflowRequest")
	proto.RegisterType((*WorkflowMetadata)(nil), "gateway_protocol.WorkflowMetadata")
	proto.RegisterType((*DeployWorkflowResponse)(nil), "gateway_protocol.DeployWorkflowResponse")
	proto.RegisterType((*PublishMessageRequest)(nil), "gateway_protocol.PublishMessageRequest")
	proto.RegisterType((*CreateJobRequest)(nil), "gateway_protocol.CreateJobRequest")
	proto.RegisterType((*CreateJobResponse)(nil), "gateway_protocol.CreateJobResponse")
	proto.RegisterType((*UpdateJobRetriesRequest)(nil), "gateway_protocol.UpdateJobRetriesRequest")
	proto.RegisterType((*UpdateJobRetriesResponse)(nil), "gateway_protocol.UpdateJobRetriesResponse")
	proto.RegisterType((*FailJobRequest)(nil), "gateway_protocol.FailJobRequest")
	proto.RegisterType((*FailJobResponse)(nil), "gateway_protocol.FailJobResponse")
	proto.RegisterType((*CompleteJobRequest)(nil), "gateway_protocol.CompleteJobRequest")
	proto.RegisterType((*CompleteJobResponse)(nil), "gateway_protocol.CompleteJobResponse")
	proto.RegisterType((*CreateWorkflowInstanceRequest)(nil), "gateway_protocol.CreateWorkflowInstanceRequest")
	proto.RegisterType((*CreateWorkflowInstanceResponse)(nil), "gateway_protocol.CreateWorkflowInstanceResponse")
	proto.RegisterType((*CancelWorkflowInstanceRequest)(nil), "gateway_protocol.CancelWorkflowInstanceRequest")
	proto.RegisterType((*CancelWorkflowInstanceResponse)(nil), "gateway_protocol.CancelWorkflowInstanceResponse")
	proto.RegisterType((*UpdateWorkflowInstancePayloadRequest)(nil), "gateway_protocol.UpdateWorkflowInstancePayloadRequest")
	proto.RegisterType((*UpdateWorkflowInstancePayloadResponse)(nil), "gateway_protocol.UpdateWorkflowInstancePayloadResponse")
	proto.RegisterType((*ListWorkflowsRequest)(nil), "gateway_protocol.ListWorkflowsRequest")
	proto.RegisterType((*ListWorkflowsResponse)(nil), "gateway_protocol.ListWorkflowsResponse")
	proto.RegisterType((*GetWorkflowRequest)(nil), "gateway_protocol.GetWorkflowRequest")
	proto.RegisterType((*GetWorkflowResponse)(nil), "gateway_protocol.GetWorkflowResponse")
	proto.RegisterEnum("gateway_protocol.Partition_PartitionBrokerRole", Partition_PartitionBrokerRole_name, Partition_PartitionBrokerRole_value)
	proto.RegisterEnum("gateway_protocol.WorkflowRequestObject_ResourceType", WorkflowRequestObject_ResourceType_name, WorkflowRequestObject_ResourceType_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GatewayClient is the client API for Gateway service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GatewayClient interface {
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
	DeployWorkflow(ctx context.Context, in *DeployWorkflowRequest, opts ...grpc.CallOption) (*DeployWorkflowResponse, error)
	PublishMessage(ctx context.Context, in *PublishMessageRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	CreateJob(ctx context.Context, in *CreateJobRequest, opts ...grpc.CallOption) (*CreateJobResponse, error)
	UpdateJobRetries(ctx context.Context, in *UpdateJobRetriesRequest, opts ...grpc.CallOption) (*UpdateJobRetriesResponse, error)
	FailJob(ctx context.Context, in *FailJobRequest, opts ...grpc.CallOption) (*FailJobResponse, error)
	CompleteJob(ctx context.Context, in *CompleteJobRequest, opts ...grpc.CallOption) (*CompleteJobResponse, error)
	CreateWorkflowInstance(ctx context.Context, in *CreateWorkflowInstanceRequest, opts ...grpc.CallOption) (*CreateWorkflowInstanceResponse, error)
	CancelWorkflowInstance(ctx context.Context, in *CancelWorkflowInstanceRequest, opts ...grpc.CallOption) (*CancelWorkflowInstanceResponse, error)
	UpdateWorkflowInstancePayload(ctx context.Context, in *UpdateWorkflowInstancePayloadRequest, opts ...grpc.CallOption) (*UpdateWorkflowInstancePayloadResponse, error)
	ListWorkflows(ctx context.Context, in *ListWorkflowsRequest, opts ...grpc.CallOption) (*ListWorkflowsResponse, error)
	GetWorkflow(ctx context.Context, in *GetWorkflowRequest, opts ...grpc.CallOption) (*GetWorkflowResponse, error)
}

type gatewayClient struct {
	cc *grpc.ClientConn
}

func NewGatewayClient(cc *grpc.ClientConn) GatewayClient {
	return &gatewayClient{cc}
}

func (c *gatewayClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, "/gateway_protocol.Gateway/Health", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayClient) DeployWorkflow(ctx context.Context, in *DeployWorkflowRequest, opts ...grpc.CallOption) (*DeployWorkflowResponse, error) {
	out := new(DeployWorkflowResponse)
	err := c.cc.Invoke(ctx, "/gateway_protocol.Gateway/DeployWorkflow", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayClient) PublishMessage(ctx context.Context, in *PublishMessageRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/gateway_protocol.Gateway/PublishMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayClient) CreateJob(ctx context.Context, in *CreateJobRequest, opts ...grpc.CallOption) (*CreateJobResponse, error) {
	out := new(CreateJobResponse)
	err := c.cc.Invoke(ctx, "/gateway_protocol.Gateway/CreateJob", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayClient) UpdateJobRetries(ctx context.Context, in *UpdateJobRetriesRequest, opts ...grpc.CallOption) (*UpdateJobRetriesResponse, error) {
	out := new(UpdateJobRetriesResponse)
	err := c.cc.Invoke(ctx, "/gateway_protocol.Gateway/UpdateJobRetries", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayClient) FailJob(ctx context.Context, in *FailJobRequest, opts ...grpc.CallOption) (*FailJobResponse, error) {
	out := new(FailJobResponse)
	err := c.cc.Invoke(ctx, "/gateway_protocol.Gateway/FailJob", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayClient) CompleteJob(ctx context.Context, in *CompleteJobRequest, opts ...grpc.CallOption) (*CompleteJobResponse, error) {
	out := new(CompleteJobResponse)
	err := c.cc.Invoke(ctx, "/gateway_protocol.Gateway/CompleteJob", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayClient) CreateWorkflowInstance(ctx context.Context, in *CreateWorkflowInstanceRequest, opts ...grpc.CallOption) (*CreateWorkflowInstanceResponse, error) {
	out := new(CreateWorkflowInstanceResponse)
	err := c.cc.Invoke(ctx, "/gateway_protocol.Gateway/CreateWorkflowInstance", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayClient) CancelWorkflowInstance(ctx context.Context, in *CancelWorkflowInstanceRequest, opts ...grpc.CallOption) (*CancelWorkflowInstanceResponse, error) {
	out := new(CancelWorkflowInstanceResponse)
	err := c.cc.Invoke(ctx, "/gateway_protocol.Gateway/CancelWorkflowInstance", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayClient) UpdateWorkflowInstancePayload(ctx context.Context, in *UpdateWorkflowInstancePayloadRequest, opts ...grpc.CallOption) (*UpdateWorkflowInstancePayloadResponse, error) {
	out := new(UpdateWorkflowInstancePayloadResponse)
	err := c.cc.Invoke(ctx, "/gateway_protocol.Gateway/UpdateWorkflowInstancePayload", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayClient) ListWorkflows(ctx context.Context, in *ListWorkflowsRequest, opts ...grpc.CallOption) (*ListWorkflowsResponse, error) {
	out := new(ListWorkflowsResponse)
	err := c.cc.Invoke(ctx, "/gateway_protocol.Gateway/ListWorkflows", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayClient) GetWorkflow(ctx context.Context, in *GetWorkflowRequest, opts ...grpc.CallOption) (*GetWorkflowResponse, error) {
	out := new(GetWorkflowResponse)
	err := c.cc.Invoke(ctx, "/gateway_protocol.Gateway/GetWorkflow", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GatewayServer is the server API for Gateway service.
type GatewayServer interface {
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	DeployWorkflow(context.Context, *DeployWorkflowRequest) (*DeployWorkflowResponse, error)
	PublishMessage(context.Context, *PublishMessageRequest) (*empty.Empty, error)
	CreateJob(context.Context, *CreateJobRequest) (*CreateJobResponse, error)
	UpdateJobRetries(context.Context, *UpdateJobRetriesRequest) (*UpdateJobRetriesResponse, error)
	FailJob(context.Context, *FailJobRequest) (*FailJobResponse, error)
	CompleteJob(context.Context, *CompleteJobRequest) (*CompleteJobResponse, error)
	CreateWorkflowInstance(context.Context, *CreateWorkflowInstanceRequest) (*CreateWorkflowInstanceResponse, error)
	CancelWorkflowInstance(context.Context, *CancelWorkflowInstanceRequest) (*CancelWorkflowInstanceResponse, error)
	UpdateWorkflowInstancePayload(context.Context, *UpdateWorkflowInstancePayloadRequest) (*UpdateWorkflowInstancePayloadResponse, error)
	ListWorkflows(context.Context, *ListWorkflowsRequest) (*ListWorkflowsResponse, error)
	GetWorkflow(context.Context, *GetWorkflowRequest) (*GetWorkflowResponse, error)
}

func RegisterGatewayServer(s *grpc.Server, srv GatewayServer) {
	s.RegisterService(&_Gateway_serviceDesc, srv)
}

func _Gateway_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gateway_protocol.Gateway/Health",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gateway_DeployWorkflow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeployWorkflowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServer).DeployWorkflow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gateway_protocol.Gateway/DeployWorkflow",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServer).DeployWorkflow(ctx, req.(*DeployWorkflowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gateway_PublishMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServer).PublishMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gateway_protocol.Gateway/PublishMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServer).PublishMessage(ctx, req.(*PublishMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gateway_CreateJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServer).CreateJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gateway_protocol.Gateway/CreateJob",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServer).CreateJob(ctx, req.(*CreateJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gateway_UpdateJobRetries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateJobRetriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServer).UpdateJobRetries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gateway_protocol.Gateway/UpdateJobRetries",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServer).UpdateJobRetries(ctx, req.(*UpdateJobRetriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gateway_FailJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FailJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServer).FailJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gateway_protocol.Gateway/FailJob",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServer).FailJob(ctx, req.(*FailJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gateway_CompleteJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompleteJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServer).CompleteJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gateway_protocol.Gateway/CompleteJob",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServer).CompleteJob(ctx, req.(*CompleteJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gateway_CreateWorkflowInstance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateWorkflowInstanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServer).CreateWorkflowInstance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gateway_protocol.Gateway/CreateWorkflowInstance",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServer).CreateWorkflowInstance(ctx, req.(*CreateWorkflowInstanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gateway_CancelWorkflowInstance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelWorkflowInstanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServer).CancelWorkflowInstance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gateway_protocol.Gateway/CancelWorkflowInstance",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServer).CancelWorkflowInstance(ctx, req.(*CancelWorkflowInstanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gateway_UpdateWorkflowInstancePayload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateWorkflowInstancePayloadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServer).UpdateWorkflowInstancePayload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gateway_protocol.Gateway/UpdateWorkflowInstancePayload",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServer).UpdateWorkflowInstancePayload(ctx, req.(*UpdateWorkflowInstancePayloadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gateway_ListWorkflows_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListWorkflowsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServer).ListWorkflows(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gateway_protocol.Gateway/ListWorkflows",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServer).ListWorkflows(ctx, req.(*ListWorkflowsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gateway_GetWorkflow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWorkflowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServer).GetWorkflow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gateway_protocol.Gateway/GetWorkflow",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServer).GetWorkflow(ctx, req.(*GetWorkflowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Gateway_serviceDesc = grpc.ServiceDesc{
	ServiceName: "gateway_protocol.Gateway",
	HandlerType: (*GatewayServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Health",
			Handler:    _Gateway_Health_Handler,
		},
		{
			MethodName: "DeployWorkflow",
			Handler:    _Gateway_DeployWorkflow_Handler,
		},
		{
			MethodName: "PublishMessage",
			Handler:    _Gateway_PublishMessage_Handler,
		},
		{
			MethodName: "CreateJob",
			Handler:    _Gateway_CreateJob_Handler,
		},
		{
			MethodName: "UpdateJobRetries",
			Handler:    _Gateway_UpdateJobRetries_Handler,
		},
		{
			MethodName: "FailJob",
			Handler:    _Gateway_FailJob_Handler,
		},
		{
			MethodName: "CompleteJob",
			Handler:    _Gateway_CompleteJob_Handler,
		},
		{
			MethodName: "CreateWorkflowInstance",
			Handler:    _Gateway_CreateWorkflowInstance_Handler,
		},
		{
			MethodName: "CancelWorkflowInstance",
			Handler:    _Gateway_CancelWorkflowInstance_Handler,
		},
		{
			MethodName: "UpdateWorkflowInstancePayload",
			Handler:    _Gateway_UpdateWorkflowInstancePayload_Handler,
		},
		{
			MethodName: "ListWorkflows",
			Handler:    _Gateway_ListWorkflows_Handler,
		},
		{
			MethodName: "GetWorkflow",
			Handler:    _Gateway_GetWorkflow_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gateway.proto",
}

func init() { proto.RegisterFile("gateway.proto", fileDescriptor_gateway_5f4d0dd5a4502bd1) }

var fileDescriptor_gateway_5f4d0dd5a4502bd1 = []byte{
	// 1146 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x57, 0xdf, 0x53, 0x23, 0xc5,
	0x13, 0xcf, 0x26, 0x01, 0xbe, 0x69, 0x20, 0x97, 0x1b, 0xbe, 0x60, 0xdc, 0x3b, 0x30, 0x37, 0xc2,
	0x81, 0x56, 0x19, 0xae, 0xd0, 0x3a, 0x1f, 0xf4, 0xe1, 0x0e, 0x0e, 0x0e, 0x24, 0x1c, 0x71, 0x3d,
	0x3d, 0xcf, 0xb2, 0xb4, 0x76, 0x93, 0x01, 0x16, 0x36, 0x99, 0xbd, 0xdd, 0x01, 0x2a, 0x56, 0xf9,
	0xea, 0x1f, 0xe0, 0x93, 0x55, 0x3e, 0xf9, 0xec, 0xab, 0x3e, 0xf8, 0xcf, 0xf8, 0xb7, 0x58, 0x33,
	0x99, 0x59, 0xf6, 0xc7, 0x6c, 0x12, 0xca, 0xf2, 0x6d, 0xa6, 0xb7, 0xa7, 0x3f, 0xdd, 0x9f, 0xee,
	0xe9, 0x9e, 0x85, 0xf9, 0x53, 0x9b, 0x91, 0x6b, 0x7b, 0xd0, 0xf4, 0x03, 0xca, 0x28, 0xaa, 0xc9,
	0xed, 0xf7, 0x62, 0xdb, 0xa1, 0x9e, 0x79, 0xef, 0x94, 0xd2, 0x53, 0x8f, 0x6c, 0x0a, 0x81, 0x73,
	0x79, 0xb2, 0x49, 0x7a, 0x3e, 0x93, 0xea, 0xf8, 0x0e, 0xcc, 0xef, 0x13, 0xdb, 0x63, 0x67, 0x16,
	0x79, 0x73, 0x49, 0x42, 0x86, 0x7f, 0x33, 0xa0, 0xd2, 0xb6, 0x03, 0xe6, 0x32, 0x97, 0xf6, 0x51,
	0x03, 0x66, 0x7d, 0xb5, 0x39, 0xe8, 0xd6, 0x8d, 0x86, 0xb1, 0x31, 0x65, 0xc5, 0x45, 0x68, 0x07,
	0xca, 0x01, 0xf5, 0x48, 0xbd, 0xd4, 0x30, 0x36, 0xaa, 0x5b, 0x9b, 0xcd, 0x34, 0x7c, 0x33, 0x32,
	0x76, 0xb3, 0xda, 0x0e, 0xe8, 0x05, 0x09, 0x2c, 0xea, 0x11, 0x4b, 0x1c, 0xc6, 0x1f, 0xc0, 0x82,
	0xe6, 0x23, 0x02, 0x98, 0x6e, 0xed, 0x3e, 0x7d, 0xb6, 0x6b, 0xd5, 0x0a, 0x7c, 0xbd, 0x77, 0xdc,
	0x6a, 0x1d, 0xbf, 0xaa, 0x19, 0xf8, 0x0d, 0xc0, 0x50, 0xeb, 0xa0, 0x7f, 0x42, 0x11, 0x82, 0xf2,
	0x19, 0x0d, 0x99, 0x70, 0xae, 0x62, 0x89, 0x35, 0x97, 0xf9, 0x34, 0x60, 0xf5, 0xa2, 0x70, 0x58,
	0xac, 0xd1, 0x27, 0x00, 0x91, 0xe3, 0x61, 0xbd, 0xd4, 0x28, 0x6d, 0xcc, 0x6e, 0xdd, 0x1b, 0xe1,
	0xaf, 0x15, 0x53, 0xc7, 0xfb, 0x50, 0x55, 0x3c, 0x85, 0x3e, 0xed, 0x87, 0x04, 0x3d, 0x86, 0x19,
	0x47, 0x38, 0x11, 0xd6, 0x0d, 0x61, 0xeb, 0x7e, 0xd6, 0xd6, 0x8d, 0x97, 0x96, 0x52, 0xc6, 0x7f,
	0x19, 0xb0, 0xf8, 0x8a, 0x06, 0x17, 0x27, 0x1e, 0xbd, 0x96, 0xa4, 0x1f, 0x3b, 0xe7, 0xa4, 0x23,
	0x9c, 0xee, 0xdb, 0x3d, 0xa2, 0x02, 0xe1, 0x6b, 0xb4, 0x0f, 0x65, 0x36, 0xf0, 0x89, 0x08, 0xa4,
	0xba, 0xf5, 0x51, 0x16, 0x42, 0x6b, 0xaa, 0x69, 0x91, 0x90, 0x5e, 0x06, 0x1d, 0xf2, 0x72, 0xe0,
	0x13, 0x4b, 0x58, 0x40, 0x2b, 0x00, 0x5d, 0x72, 0xe2, 0xf6, 0x45, 0x40, 0x22, 0x5d, 0x73, 0x56,
	0x4c, 0x82, 0x31, 0xcc, 0xc5, 0x4f, 0xa1, 0xff, 0x41, 0x79, 0xbb, 0x7d, 0xf4, 0xa2, 0x56, 0xe0,
	0xab, 0xd7, 0x4f, 0x8f, 0x5a, 0x35, 0x03, 0x7f, 0x07, 0x8b, 0xcf, 0x88, 0xef, 0xd1, 0x41, 0x0a,
	0x15, 0xed, 0x42, 0xe5, 0x5a, 0x8a, 0x14, 0x1d, 0xeb, 0x13, 0xfa, 0x6a, 0xdd, 0x9c, 0xc4, 0xbf,
	0x18, 0x50, 0x53, 0x4a, 0x47, 0x84, 0xd9, 0x5d, 0x9b, 0xd9, 0x68, 0x15, 0xe6, 0x1d, 0xbf, 0xd7,
	0x6f, 0x07, 0xb4, 0x43, 0xc2, 0x50, 0x56, 0x61, 0xc5, 0x4a, 0x0a, 0x51, 0x1d, 0x66, 0xae, 0x48,
	0x10, 0xf2, 0xd8, 0x86, 0x49, 0x57, 0x5b, 0x5e, 0xc3, 0x0a, 0xe1, 0x90, 0x0c, 0x44, 0xe4, 0x25,
	0x2b, 0x2e, 0x42, 0x18, 0xe6, 0x02, 0x19, 0xfa, 0x0b, 0x9e, 0x80, 0xb2, 0x00, 0x48, 0xc8, 0xb0,
	0x07, 0x4b, 0xe9, 0xd0, 0x65, 0x21, 0xd4, 0xa0, 0x74, 0x41, 0x06, 0xc2, 0xab, 0x92, 0xc5, 0x97,
	0xe8, 0x49, 0x9c, 0x8d, 0xa2, 0x60, 0x03, 0xe7, 0xb3, 0xa1, 0x02, 0x8d, 0x13, 0xf1, 0xbb, 0x01,
	0x8b, 0xed, 0x4b, 0xc7, 0x73, 0xc3, 0xb3, 0x23, 0x12, 0x86, 0xf6, 0x29, 0x51, 0x4c, 0xeb, 0x8a,
	0xe4, 0x21, 0x54, 0x3b, 0x34, 0x08, 0x88, 0x67, 0xf3, 0x4c, 0xf2, 0x20, 0x8b, 0xe2, 0x6b, 0x4a,
	0xca, 0x4b, 0x80, 0xb9, 0x3d, 0xf2, 0x92, 0xb6, 0xdc, 0x2b, 0x22, 0x89, 0x88, 0x49, 0xd0, 0x7d,
	0xa8, 0xf4, 0x86, 0x68, 0x07, 0x5d, 0x49, 0xc2, 0x8d, 0x80, 0x33, 0xec, 0xdb, 0x03, 0x8f, 0xda,
	0xdd, 0xfa, 0x94, 0xf8, 0xa6, 0xb6, 0xf8, 0x27, 0x03, 0x6a, 0x3b, 0x01, 0xb1, 0x19, 0xf9, 0x8c,
	0x3a, 0xca, 0xd1, 0x3a, 0xcc, 0x9c, 0x53, 0x87, 0x97, 0x92, 0xf4, 0x55, 0x6d, 0xf9, 0x97, 0x80,
	0xb0, 0xc0, 0x25, 0xa1, 0x4a, 0x95, 0xdc, 0xf2, 0x54, 0x77, 0x2e, 0x43, 0x46, 0x7b, 0xfb, 0xc4,
	0xee, 0xf2, 0x9b, 0x55, 0x1a, 0xa6, 0x3a, 0x21, 0x8c, 0x3b, 0x52, 0x4e, 0x3a, 0xb2, 0x06, 0x77,
	0x63, 0x7e, 0xe4, 0xe5, 0x07, 0x1f, 0xc2, 0x5b, 0x5f, 0xfa, 0x5d, 0xa5, 0x26, 0xa0, 0x95, 0xd7,
	0x4b, 0x30, 0x7d, 0x4e, 0x9d, 0xc3, 0x48, 0x5f, 0xee, 0xf2, 0x7d, 0xc6, 0x26, 0xd4, 0xb3, 0xc6,
	0x86, 0xd0, 0x78, 0x1b, 0xaa, 0x7b, 0xb6, 0xeb, 0xc5, 0x58, 0xb9, 0xbd, 0xfd, 0xbb, 0x70, 0x27,
	0xb2, 0x21, 0xcd, 0xee, 0x01, 0xda, 0xa1, 0x3d, 0xdf, 0x23, 0x09, 0xc2, 0x47, 0x98, 0x56, 0x74,
	0x15, 0x93, 0x74, 0x2d, 0xc2, 0x42, 0xc2, 0x8e, 0x34, 0xff, 0xab, 0x01, 0xcb, 0x43, 0x1a, 0x55,
	0x89, 0x1e, 0xf4, 0x43, 0x66, 0xf7, 0x3b, 0x51, 0x11, 0xa6, 0xae, 0x94, 0x91, 0xbd, 0x52, 0x99,
	0x4b, 0x5b, 0x1c, 0x73, 0x69, 0x4b, 0xc9, 0x4b, 0x9b, 0x9f, 0xe3, 0x3f, 0x0c, 0x58, 0xc9, 0xf3,
	0x4e, 0x66, 0xfc, 0xbf, 0x77, 0xef, 0x11, 0x2c, 0x5c, 0xa7, 0xd0, 0x39, 0xd2, 0x94, 0x40, 0xd2,
	0x7d, 0xc2, 0x9f, 0xc3, 0xf2, 0x0e, 0x5f, 0x7b, 0x79, 0x9c, 0xe6, 0x98, 0x34, 0xf2, 0x4d, 0x36,
	0x60, 0x25, 0xcf, 0xa4, 0xcc, 0x64, 0x00, 0xab, 0xc3, 0xda, 0x4c, 0x6b, 0xb4, 0x87, 0x64, 0xc6,
	0xb0, 0xed, 0x0e, 0x73, 0xaf, 0x5c, 0x36, 0xd0, 0x60, 0x6b, 0x3e, 0x8d, 0x28, 0xaa, 0x75, 0x58,
	0x1b, 0x83, 0x29, 0x9d, 0xfb, 0x14, 0xfe, 0xdf, 0x72, 0x43, 0xa6, 0xd4, 0xa2, 0x2b, 0x38, 0x51,
	0xbf, 0xc7, 0xaf, 0x61, 0x31, 0x75, 0x5a, 0x26, 0xff, 0x49, 0x76, 0x14, 0xdd, 0xb2, 0xf9, 0x5e,
	0x01, 0x7a, 0x4e, 0x58, 0x7a, 0xc4, 0x8d, 0x2f, 0xaa, 0xfc, 0x11, 0x94, 0x09, 0xa9, 0xa4, 0x0b,
	0xe9, 0x4f, 0x03, 0x16, 0x12, 0xc0, 0x13, 0x97, 0xf3, 0xbf, 0x44, 0x9e, 0x64, 0x00, 0x72, 0x0c,
	0x7e, 0xe8, 0xeb, 0x9e, 0xa7, 0xda, 0xbf, 0xdc, 0x6e, 0xfd, 0x5d, 0x81, 0x99, 0xe7, 0x43, 0x82,
	0xd1, 0x11, 0x4c, 0x0f, 0xdf, 0x49, 0xe8, 0x9d, 0x2c, 0xe9, 0x89, 0x97, 0xa6, 0xd9, 0xc8, 0x57,
	0x90, 0x15, 0x52, 0x40, 0x04, 0xaa, 0xc9, 0xa9, 0x8b, 0x34, 0xcf, 0x0a, 0xed, 0x93, 0xc4, 0xdc,
	0x18, 0xaf, 0x18, 0xc1, 0x7c, 0x01, 0xd5, 0xe4, 0xb4, 0xd5, 0xc1, 0x68, 0xe7, 0xb1, 0xb9, 0xd4,
	0x1c, 0x3e, 0xaf, 0x9b, 0xea, 0x79, 0xdd, 0xdc, 0xe5, 0xcf, 0x6b, 0x5c, 0x40, 0x5f, 0x41, 0x25,
	0x1a, 0x46, 0x48, 0x53, 0x82, 0xe9, 0x89, 0x69, 0xbe, 0x3b, 0x52, 0x27, 0x72, 0xf6, 0x02, 0x6a,
	0xe9, 0x81, 0x83, 0xde, 0xcb, 0x1e, 0xcd, 0x99, 0x70, 0xe6, 0xfb, 0x93, 0xa8, 0x46, 0x60, 0x6d,
	0x98, 0x91, 0xd3, 0x07, 0x69, 0xf2, 0x95, 0x1c, 0x6e, 0xe6, 0x83, 0x11, 0x1a, 0x91, 0xc5, 0x6f,
	0x61, 0x36, 0x36, 0x74, 0xd0, 0xaa, 0x26, 0xe8, 0xcc, 0x6c, 0x33, 0xd7, 0xc6, 0x68, 0x45, 0xd6,
	0x7f, 0x84, 0x25, 0xfd, 0x70, 0x40, 0x9b, 0x79, 0xec, 0xe6, 0x34, 0x64, 0xf3, 0xd1, 0xe4, 0x07,
	0x12, 0xf0, 0xda, 0x96, 0xac, 0x85, 0x1f, 0x35, 0x0f, 0xb4, 0xf0, 0xa3, 0xbb, 0x7d, 0x01, 0xfd,
	0x6c, 0xc0, 0xf2, 0xc8, 0xe6, 0x8b, 0x1e, 0xe7, 0x65, 0x7f, 0xf4, 0x84, 0x30, 0x3f, 0xbe, 0xf5,
	0xb9, 0xc8, 0x29, 0x07, 0xe6, 0x13, 0x9d, 0x1a, 0x3d, 0xcc, 0xda, 0xd2, 0x0d, 0x02, 0x73, 0x7d,
	0xac, 0x5e, 0xbc, 0xa8, 0x62, 0x9d, 0x53, 0x57, 0x54, 0xd9, 0x8e, 0xae, 0x2b, 0x2a, 0x4d, 0xfb,
	0xc5, 0x85, 0xed, 0x07, 0xf0, 0xb6, 0x4b, 0x9b, 0x3f, 0x10, 0xe2, 0x90, 0x66, 0xe2, 0x6f, 0xbb,
	0x43, 0xbd, 0x76, 0xe1, 0x9b, 0xa2, 0xef, 0x38, 0xd3, 0x62, 0xff, 0xe1, 0x3f, 0x01, 0x00, 0x00,
	0xff, 0xff, 0x8d, 0x6f, 0x1f, 0x24, 0x8e, 0x0f, 0x00, 0x00,
}
