#!/usr/bin/env bash
# owner: @camunda/reliability-testing
#
# Generates camunda-platform-physical-tenants.yaml: the orchestration.extraConfiguration
# overlay that declares pt1..ptN physical tenants on top of whichever secondary_storage
# the namespace is using. Invoked by common.mk at `make install`/`make template` time
# (not by newLoadTest.sh at scaffold time), so an existing namespace can change
# physical_tenant_count across re-installs without re-scaffolding.
#
# orchestration.extraConfiguration is a list, and Helm replaces (rather than merges) list
# values from later -f files. So rather than declaring extraConfiguration fresh (which
# would silently drop the base application.yml settings), this script re-reads the content
# already carried by whichever file is last in the platform_values chain to set it
# (camunda-platform-values-rdbms.yaml for rdbms storages, camunda-platform-values-none.yaml
# for "none", camunda-platform-values-defaults.yaml otherwise — mirrors the ifs in
# common.mk's "Add secondary storage values" section) and appends the per-tenant properties
# after it.
#
# Usage: generate-physical-tenant-values.sh <secondary_storage> <physical_tenant_count> <rdbms_storages>
#   secondary_storage      One of newLoadTest.sh's allowed_storage values.
#   physical_tenant_count  Non-negative integer. 0 removes any previously generated file.
#   rdbms_storages         Space-separated rdbms-backed secondary_storage values (common.mk's rdbms_storages).
#
# Writes ./camunda-platform-physical-tenants.yaml, relative to CWD (the namespace folder).

set -euo pipefail

secondary_storage="$1"
physical_tenant_count="$2"
rdbms_storages="$3"

output_file="camunda-platform-physical-tenants.yaml"

if [[ ! "$physical_tenant_count" =~ ^[0-9]+$ ]]; then
  echo "Error: physical_tenant_count must be a non-negative integer, got '$physical_tenant_count'" >&2
  exit 1
fi

if [[ "$physical_tenant_count" -eq 0 ]]; then
  rm -f "$output_file"
  exit 0
fi

is_rdbms=false
for storage in $rdbms_storages; do
  [[ "$storage" == "$secondary_storage" ]] && is_rdbms=true
done

if [[ "$is_rdbms" == "true" ]]; then
  base_file="camunda-platform-values-rdbms.yaml"
elif [[ "$secondary_storage" == "none" ]]; then
  base_file="camunda-platform-values-none.yaml"
else
  base_file="camunda-platform-values-defaults.yaml"
fi

if [[ ! -f "$base_file" ]]; then
  echo "Error: expected base values file '$base_file' in $(pwd) (namespace folder) — was it staged by newLoadTest.sh?" >&2
  exit 1
fi

# document_store_key: "elasticsearch"/"opensearch", empty for rdbms/none. Doubles as the
# camunda.data.secondary-storage.<key> segment for both the index-prefix override below and
# the ILM/ISM lifecycle-policy names (history.policy-name, history.usage-metrics-policy-name)
# — rdbms/none have neither, so there's nothing to isolate for them either way.
case "$secondary_storage" in
  elasticsearch) document_store_key="elasticsearch" ;;
  opensearch) document_store_key="opensearch" ;;
  *) document_store_key="" ;;
esac

# storage_prefix_key: the camunda.data.secondary-storage.<key> suffix used to isolate the
# storage layer by prefix. Empty for "none" — there's no storage layer to isolate, only
# broker/engine/REST-routing-level isolation (authorizations below still apply).
if [[ -n "$document_store_key" ]]; then
  storage_prefix_key="${document_store_key}.index-prefix"
elif [[ "$is_rdbms" == "true" ]]; then
  storage_prefix_key="rdbms.prefix"
else
  storage_prefix_key=""
fi

lines=("# Physical tenants pt1..pt${physical_tenant_count}, generated by generate-physical-tenant-values.sh.")

if [[ -n "$storage_prefix_key" ]]; then
  if [[ "$storage_prefix_key" == "rdbms.prefix" ]]; then
    default_prefix="DEFAULT_"
  else
    default_prefix="default-"
  fi
  lines+=("camunda.data.secondary-storage.${storage_prefix_key}: ${default_prefix}")
fi

for ((i = 1; i <= physical_tenant_count; i++)); do
  tenant="pt${i}"

  if [[ -n "$storage_prefix_key" ]]; then
    if [[ "$storage_prefix_key" == "rdbms.prefix" ]]; then
      tenant_prefix="PT${i}_"
    else
      tenant_prefix="pt${i}-"
    fi
    lines+=("camunda.physical-tenants.${tenant}.data.secondary-storage.${storage_prefix_key}: ${tenant_prefix}")
  fi

  if [[ -n "$document_store_key" ]]; then
    lines+=(
      "camunda.physical-tenants.${tenant}.data.secondary-storage.${document_store_key}.history.policy-name: ${tenant}-camunda-retention-policy"
      "camunda.physical-tenants.${tenant}.data.secondary-storage.${document_store_key}.history.usage-metrics-policy-name: ${tenant}-camunda-usage-metrics-retention-policy"
    )
  fi

  lines+=(
    "# ${tenant}: grant the orchestration client the same permissions as the default tenant"
    "camunda.physical-tenants.${tenant}.security.initialization.authorizations[0].ownerType: CLIENT"
    "camunda.physical-tenants.${tenant}.security.initialization.authorizations[0].ownerId: orchestration"
    "camunda.physical-tenants.${tenant}.security.initialization.authorizations[0].resourceType: RESOURCE"
    "camunda.physical-tenants.${tenant}.security.initialization.authorizations[0].resourceId: \"*\""
    "camunda.physical-tenants.${tenant}.security.initialization.authorizations[0].permissions[0]: CREATE"
    "camunda.physical-tenants.${tenant}.security.initialization.authorizations[1].ownerType: CLIENT"
    "camunda.physical-tenants.${tenant}.security.initialization.authorizations[1].ownerId: orchestration"
    "camunda.physical-tenants.${tenant}.security.initialization.authorizations[1].resourceType: PROCESS_DEFINITION"
    "camunda.physical-tenants.${tenant}.security.initialization.authorizations[1].resourceId: \"*\""
    "camunda.physical-tenants.${tenant}.security.initialization.authorizations[1].permissions[0]: CREATE_PROCESS_INSTANCE"
    "camunda.physical-tenants.${tenant}.security.initialization.authorizations[1].permissions[1]: UPDATE_PROCESS_INSTANCE"
    "camunda.physical-tenants.${tenant}.security.initialization.authorizations[1].permissions[2]: READ_PROCESS_INSTANCE"
    "camunda.physical-tenants.${tenant}.security.initialization.authorizations[1].permissions[3]: READ_PROCESS_DEFINITION"
    "camunda.physical-tenants.${tenant}.security.initialization.authorizations[2].ownerType: CLIENT"
    "camunda.physical-tenants.${tenant}.security.initialization.authorizations[2].ownerId: orchestration"
    "camunda.physical-tenants.${tenant}.security.initialization.authorizations[2].resourceType: MESSAGE"
    "camunda.physical-tenants.${tenant}.security.initialization.authorizations[2].resourceId: \"*\""
    "camunda.physical-tenants.${tenant}.security.initialization.authorizations[2].permissions[0]: CREATE"
    "# ${tenant}: assign the default OIDC provider (Keycloak) so this tenant can authenticate"
    "camunda.physical-tenants.${tenant}.security.authentication.providers.assigned[0]: oidc"
  )
done

PT_LINES="$(printf '%s\n' "${lines[@]}")"
export PT_LINES

{
  echo "########################################################################################"
  echo "################################################### Orchestration cluster configuration"
  echo "########################################################################################"
  echo "# Physical-tenant overlay: pt1..pt${physical_tenant_count} over secondary_storage=${secondary_storage}."
  echo "# Generated by generate-physical-tenant-values.sh at make time from ${base_file}'s"
  echo "# application.yml content plus the per-tenant properties below — regenerated on every"
  echo "# \`make install\`/\`make template\`, not meant to be hand-edited."
  # .content already ends in exactly one trailing newline (YAML clip-mode "|" block
  # scalar), so no extra separator is needed here — one would insert a blank line.
  yq eval '{"orchestration": {"extraConfiguration": [{"file": .orchestration.extraConfiguration[0].file, "content": (.orchestration.extraConfiguration[0].content + strenv(PT_LINES))}, .orchestration.extraConfiguration[1]]}}' "$base_file"
} > "$output_file"

echo "Generated ${output_file} (physical_tenant_count=${physical_tenant_count}, secondary_storage=${secondary_storage})."
