apiVersion: v1
kind: Secret
metadata:
  name: camunda-credentials
type: Opaque
stringData:
  identity-firstuser-password: "__IDENTITY_FIRSTUSER_PASSWORD__"
  identity-keycloak-admin-password: "__IDENTITY_KEYCLOAK_ADMIN_PASSWORD__"
  identity-keycloak-postgresql-admin-password: "__IDENTITY_KEYCLOAK_POSTGRESQL_ADMIN_PASSWORD__"
  identity-keycloak-postgresql-user-password: "__IDENTITY_KEYCLOAK_POSTGRESQL_USER_PASSWORD__"
  identity-postgresql-admin-password: "__IDENTITY_POSTGRESQL_ADMIN_PASSWORD__"
  identity-postgresql-user-password: "__IDENTITY_POSTGRESQL_USER_PASSWORD__"
  identity-admin-client-token: "__IDENTITY_ADMIN_CLIENT_TOKEN__"
  identity-optimize-client-token: "__IDENTITY_OPTIMIZE_CLIENT_TOKEN__"
  identity-zeebe-client-token: "__IDENTITY_ZEEBE_CLIENT_TOKEN__"
