{
 "title": "REST",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "region", "query": { "query": "label_values(camunda_region)" } },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(http_server_requests_seconds_count{camunda_region=~\"$region\"},namespace)"
    }
   },
   {
    "name": "container",
    "query": {
     "query": "label_values(http_server_requests_seconds_count,container)"
    }
   },
   {
    "name": "uri",
    "query": {
     "query": "label_values(http_server_requests_seconds_count{container=~\"$container\"},uri)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Not maintained",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<center>\n\n⚠️ **This dashboard is not maintained anymore.** Use the dashboards in the [camunda-observability](https://github.com/camunda/camunda-observability) repository instead.\n\n</center>"
   }
  },
  {
   "title": "Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "sum by(status) (rate(http_server_requests_seconds_count{camunda_region=~\"$region\", namespace=~\"$namespace\", container=~\"$container\", uri=~\"$uri\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency (avg)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
   "targets": [
    {
     "expr": "sum by(uri) (rate(http_server_requests_seconds_sum{camunda_region=~\"$region\", namespace=~\"$namespace\", container=~\"$container\", uri=~\"$uri\"}[$__rate_interval])) / sum by(uri) (rate(http_server_requests_seconds_count{camunda_region=~\"$region\", namespace=~\"$namespace\", container=~\"$container\", uri=~\"$uri\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Server error rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "sum by(status) (\n  rate(http_server_requests_seconds_count{\n    outcome=~\"SERVER_ERROR\",\n    camunda_region=~\"$region\",\n    namespace=~\"$namespace\",\n    container=~\"$container\"\n  }[$__rate_interval])\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Client error rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "sum by(status) (\n  rate(http_server_requests_seconds_count{\n    outcome=~\"CLIENT_ERROR\",\n    camunda_region=~\"$region\",\n    namespace=~\"$namespace\",\n    container=~\"$container\"\n  }[$__rate_interval])\n)\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}