---
name: Validate flattened POM metadata
description: Installs xmllint and validates flattened Maven POM metadata

inputs:
  search-root:
    description: Directory root to scan for .flattened-pom.xml files
    default: "."
    required: false

runs:
  using: composite
  steps:
    - name: Install xmllint
      uses: nick-fields/retry@ad984534de44a9489a53aefd81eb77f87c70dc60 # v4.0.0
      with:
        max_attempts: 3
        retry_wait_seconds: 10
        timeout_minutes: 2
        shell: bash
        command: sudo apt-get update && sudo apt-get install -y --no-install-recommends libxml2-utils

    - name: Validate flattened POM metadata
      shell: bash
      run: bash .github/scripts/validate-flattened-poms.sh "${{ inputs.search-root }}"
