/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(project(":zeebe-protocol"))
    api(project(":zeebe-protocol-impl"))
    api(project(":zeebe-transport"))
    api(project(":zeebe-util"))
    api(project(":zeebe-scheduler"))
    api(project(":zeebe-msgpack-value"))
    api(project(":zeebe-msgpack-core"))
    api(libs.com.fasterxml.jackson.core.jackson.databind)
    api(libs.org.agrona.agrona)
    api(project(":zeebe-test-util"))
    api(project(":zeebe-bpmn-model"))
    api(libs.org.msgpack.jackson.dataformat.msgpack)
    api(libs.junit.junit)
    api(libs.org.assertj.assertj.core)
    api(libs.org.slf4j.slf4j.api)
    api(project(":zeebe-atomix-cluster"))
    api(libs.com.fasterxml.jackson.core.jackson.core)
    api(project(":zeebe-atomix-utils"))
    api(libs.io.micrometer.micrometer.core)
    api(libs.org.jeasy.easy.random.core)
    api(libs.io.github.classgraph.classgraph)
    testImplementation(libs.org.junit.jupiter.junit.jupiter.api)
    testImplementation(libs.org.junit.jupiter.junit.jupiter.params)
    testImplementation(project(":zeebe-protocol-asserts"))
}

description = "Zeebe Protocol Test Util"
