/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(project(":zeebe-util"))
    api(project(":zeebe-scheduler"))
    api(libs.io.micrometer.micrometer.core)
    api(libs.io.micrometer.micrometer.commons)
    api(project(":zeebe-protocol"))
    api(libs.org.agrona.agrona)
    implementation(libs.org.slf4j.slf4j.api)
    api(libs.com.fasterxml.jackson.core.jackson.databind)
    api(libs.com.fasterxml.jackson.core.jackson.annotations)
    testImplementation(libs.org.awaitility.awaitility)
    testImplementation(project(":zeebe-scheduler"))
    testImplementation(libs.org.assertj.assertj.core)
    testImplementation(libs.junit.junit)
    testImplementation(libs.org.junit.jupiter.junit.jupiter.api)
    testImplementation(project(":zeebe-test-util"))
    testImplementation(libs.org.mockito.mockito.core)
}

description = "Zeebe Snapshots"

val testsJar by tasks.registering(Jar::class) {
    archiveClassifier = "tests"
    from(sourceSets["test"].output)
}

(publishing.publications["maven"] as MavenPublication).artifact(testsJar)
