package io.camunda.gradle.catalog

import org.gradle.api.initialization.dsl.VersionCatalogBuilder

/** Spring Boot, Spring AI, springdoc and Hibernate Validator libraries. */
internal fun VersionCatalogBuilder.catalogSpringBootLibraries() {
  library(
      "org-springdoc-springdoc-openapi-starter-common",
      "org.springdoc",
      "springdoc-openapi-starter-common",
    )
    .versionRef("springdoc")
  library(
      "org-springdoc-springdoc-openapi-starter-webmvc-ui",
      "org.springdoc",
      "springdoc-openapi-starter-webmvc-ui",
    )
    .versionRef("springdoc")
  library(
      "org-springframework-ai-mcp-spring-webmvc",
      "org.springframework.ai",
      "mcp-spring-webmvc",
    )
    .withoutVersion()
  library(
      "org-springframework-ai-spring-ai-autoconfigure-mcp-server-common",
      "org.springframework.ai",
      "spring-ai-autoconfigure-mcp-server-common",
    )
    .withoutVersion()
  library(
      "org-springframework-ai-spring-ai-mcp-annotations",
      "org.springframework.ai",
      "spring-ai-mcp-annotations",
    )
    .withoutVersion()
  library("org-springframework-ai-spring-ai-model", "org.springframework.ai", "spring-ai-model")
    .withoutVersion()
  library(
      "org-springframework-ai-spring-ai-starter-mcp-server-webmvc",
      "org.springframework.ai",
      "spring-ai-starter-mcp-server-webmvc",
    )
    .withoutVersion()
  library("org-springframework-ai-spring-ai-bom", "org.springframework.ai", "spring-ai-bom")
    .versionRef("spring-ai")
  library("org-springframework-boot-spring-boot", "org.springframework.boot", "spring-boot")
    .versionRef("spring-boot")
  library(
      "org-springframework-boot-spring-boot-dependencies",
      "org.springframework.boot",
      "spring-boot-dependencies",
    )
    .versionRef("spring-boot")
  library(
      "org-springframework-boot-spring-boot-configuration-processor",
      "org.springframework.boot",
      "spring-boot-configuration-processor",
    )
    .versionRef("spring-boot")
  library(
      "org-springframework-boot-spring-boot-actuator",
      "org.springframework.boot",
      "spring-boot-actuator",
    )
    .versionRef("spring-boot")
  library(
      "org-springframework-boot-spring-boot-actuator-autoconfigure",
      "org.springframework.boot",
      "spring-boot-actuator-autoconfigure",
    )
    .versionRef("spring-boot")
  library(
      "org-springframework-boot-spring-boot-micrometer-metrics",
      "org.springframework.boot",
      "spring-boot-micrometer-metrics",
    )
    .versionRef("spring-boot")
  library(
      "org-springframework-boot-spring-boot-micrometer-observation",
      "org.springframework.boot",
      "spring-boot-micrometer-observation",
    )
    .versionRef("spring-boot")
  library(
      "org-springframework-boot-spring-boot-autoconfigure",
      "org.springframework.boot",
      "spring-boot-autoconfigure",
    )
    .versionRef("spring-boot")
  library(
      "org-springframework-boot-spring-boot-freemarker",
      "org.springframework.boot",
      "spring-boot-freemarker",
    )
    .versionRef("spring-boot")
  library(
      "org-springframework-boot-spring-boot-health",
      "org.springframework.boot",
      "spring-boot-health",
    )
    .versionRef("spring-boot")
  library(
      "org-springframework-boot-spring-boot-tomcat",
      "org.springframework.boot",
      "spring-boot-tomcat",
    )
    .versionRef("spring-boot")
  library(
      "org-springframework-boot-spring-boot-micrometer-metrics-test",
      "org.springframework.boot",
      "spring-boot-micrometer-metrics-test",
    )
    .versionRef("spring-boot")
  library(
      "org-springframework-boot-spring-boot-jackson",
      "org.springframework.boot",
      "spring-boot-jackson",
    )
    .versionRef("spring-boot")
  library(
      "org-springframework-boot-spring-boot-jackson2",
      "org.springframework.boot",
      "spring-boot-jackson2",
    )
    .versionRef("spring-boot")
  library(
      "org-springframework-boot-spring-boot-starter-actuator",
      "org.springframework.boot",
      "spring-boot-starter-actuator",
    )
    .versionRef("spring-boot")
  library(
      "org-springframework-boot-spring-boot-starter-data-jdbc",
      "org.springframework.boot",
      "spring-boot-starter-data-jdbc",
    )
    .versionRef("spring-boot")
  library(
      "org-springframework-boot-spring-boot-starter-log4j2",
      "org.springframework.boot",
      "spring-boot-starter-log4j2",
    )
    .versionRef("spring-boot")
  library(
      "org-springframework-boot-spring-boot-starter-oauth2-resource-server",
      "org.springframework.boot",
      "spring-boot-starter-oauth2-resource-server",
    )
    .versionRef("spring-boot")
  library(
      "org-springframework-boot-spring-boot-starter-security",
      "org.springframework.boot",
      "spring-boot-starter-security",
    )
    .versionRef("spring-boot")
  library(
      "org-springframework-boot-spring-boot-security",
      "org.springframework.boot",
      "spring-boot-security",
    )
    .versionRef("spring-boot")
  library(
      "org-springframework-boot-spring-boot-starter-test",
      "org.springframework.boot",
      "spring-boot-starter-test",
    )
    .versionRef("spring-boot")
  library(
      "org-springframework-boot-spring-boot-starter-thymeleaf",
      "org.springframework.boot",
      "spring-boot-starter-thymeleaf",
    )
    .versionRef("spring-boot")
  library(
      "org-springframework-boot-spring-boot-starter-tomcat",
      "org.springframework.boot",
      "spring-boot-starter-tomcat",
    )
    .versionRef("spring-boot")
  library(
      "org-springframework-boot-spring-boot-starter-validation",
      "org.springframework.boot",
      "spring-boot-starter-validation",
    )
    .versionRef("spring-boot")
  library(
      "org-springframework-boot-spring-boot-starter-web",
      "org.springframework.boot",
      "spring-boot-starter-web",
    )
    .versionRef("spring-boot")
  library(
      "org-springframework-boot-spring-boot-starter-webflux",
      "org.springframework.boot",
      "spring-boot-starter-webflux",
    )
    .versionRef("spring-boot")
  library(
      "org-springframework-boot-spring-boot-test",
      "org.springframework.boot",
      "spring-boot-test",
    )
    .versionRef("spring-boot")
  library(
      "org-springframework-boot-spring-boot-test-autoconfigure",
      "org.springframework.boot",
      "spring-boot-test-autoconfigure",
    )
    .versionRef("spring-boot")
  library(
      "org-springframework-boot-spring-boot-restclient",
      "org.springframework.boot",
      "spring-boot-restclient",
    )
    .versionRef("spring-boot")
  library(
      "org-springframework-boot-spring-boot-resttestclient",
      "org.springframework.boot",
      "spring-boot-resttestclient",
    )
    .versionRef("spring-boot")
  library(
      "org-springframework-boot-spring-boot-webmvc",
      "org.springframework.boot",
      "spring-boot-webmvc",
    )
    .versionRef("spring-boot")
  library(
      "org-springframework-boot-spring-boot-webmvc-test",
      "org.springframework.boot",
      "spring-boot-webmvc-test",
    )
    .versionRef("spring-boot")
  library(
      "org-springframework-boot-spring-boot-webtestclient",
      "org.springframework.boot",
      "spring-boot-webtestclient",
    )
    .versionRef("spring-boot")
  library(
      "org-springframework-boot-spring-boot-hibernate",
      "org.springframework.boot",
      "spring-boot-hibernate",
    )
    .versionRef("spring-boot")
  library(
      "org-hibernate-validator-hibernate-validator",
      "org.hibernate.validator",
      "hibernate-validator",
    )
    .withoutVersion()
  library(
      "org-springframework-boot-spring-boot-jdbc",
      "org.springframework.boot",
      "spring-boot-jdbc",
    )
    .versionRef("spring-boot")
}
