/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.server-conventions")
}

dependencies {
    api(libs.org.agrona.agrona)
    testImplementation(libs.org.msgpack.msgpack.core)
    testImplementation(libs.junit.junit)
    testRuntimeOnly(libs.org.junit.vintage.junit.vintage.engine.x1)
    testImplementation(project(":zeebe-test-util"))
    testImplementation(project(":zeebe-util"))
    testImplementation(libs.org.assertj.assertj.core)
    testImplementation(libs.org.apache.commons.commons.lang3)
}

description = "Zeebe Msgpack Core"
