include "application-local"   # inherit all local defaults

app.worker {
  sendMessage                = true
  messageName                = "dispute_process_receive_documents"
  correlationKeyVariableName = "correlationKey"
}
