---
# Source: camunda-platform/templates/connectors/service-headless.yaml
apiVersion: v1
kind: Service
metadata:
  name: connectors-headless
  labels:
    app: camunda-platform
    app.kubernetes.io/name: camunda-platform
    app.kubernetes.io/instance: c8-ck-test-realistic
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: camunda-platform
    camunda.io/created-by: ck-claude-test
    camunda.io/purpose: load-test
    helm.sh/chart: camunda-platform-15.0.0-alpha0
    app.kubernetes.io/component: connectors
    app.kubernetes.io/version: "8.9.0"
  annotations:
spec:
  clusterIP: None
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: camunda-platform
    app.kubernetes.io/name: camunda-platform
    app.kubernetes.io/instance: c8-ck-test-realistic
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: camunda-platform
    app.kubernetes.io/component: connectors
