/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    testImplementation(project(":camunda-process-test-spring"))
    testImplementation(project(":camunda-spring-boot-starter"))
    testImplementation(project(":camunda-process-test-java"))
    testImplementation(project(":camunda-client-java"))
    testImplementation(libs.org.springframework.spring.context)
    testImplementation(libs.org.springframework.spring.beans)
    testImplementation(libs.org.springframework.boot.spring.boot)
    testImplementation(libs.org.springframework.boot.spring.boot.autoconfigure)
    testImplementation(libs.org.springframework.boot.spring.boot.health)
    testImplementation(libs.org.springframework.boot.spring.boot.actuator.autoconfigure)
    testImplementation(libs.org.springframework.boot.spring.boot.actuator)
    testImplementation(libs.com.fasterxml.jackson.core.jackson.databind)
    testImplementation(libs.io.micrometer.micrometer.core)
    testImplementation(libs.org.springframework.boot.spring.boot.test)
    testImplementation(libs.org.junit.jupiter.junit.jupiter.api)
    testImplementation(libs.org.junit.jupiter.junit.jupiter.engine)
    testImplementation(libs.org.assertj.assertj.core)
}

description = "Camunda QA Compatibility Tests"
