/*
 * This file was generated by the Gradle 'init' task.
 */

plugins { id("buildlogic.server-conventions") }

dependencies {
  api(project(":camunda-cluster"))
  api(libs.org.springframework.spring.context)
  api(libs.org.springframework.spring.core)
  api(libs.org.slf4j.slf4j.api)
  compileOnly(libs.org.springframework.spring.web)
  compileOnly(libs.org.springframework.spring.webmvc)
  compileOnly(libs.jakarta.servlet.jakarta.servlet.api)
  testImplementation(libs.org.springframework.spring.web)
  testImplementation(libs.org.springframework.spring.webmvc)
  testImplementation(libs.jakarta.servlet.jakarta.servlet.api)
  testImplementation(libs.org.springframework.spring.test)
  testImplementation(libs.org.mockito.mockito.core)
  testImplementation(libs.org.junit.jupiter.junit.jupiter.api)
  testImplementation(libs.org.assertj.assertj.core)
}

description = "Camunda Spring Utils"
