/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.sbe-conventions")
}

// Configure resource filtering to replace Maven property placeholders
val protocolVersion = "6"
val projectVersionForFilter = version.toString()

tasks.named<ProcessResources>("processResources") {
    // Enable filtering for XML files to replace ${protocol.version} and ${project.version} placeholders
    val tokens = mapOf(
        "protocol.version" to protocolVersion,
        "project.version" to projectVersionForFilter
    )

    inputs.properties(tokens)

    filesMatching("*.xml") {
        filter { line ->
            var result = line
            tokens.forEach { (key, value) ->
                result = result.replace("\${$key}", value)
            }
            result
        }
    }
}

// Configure SBE input files for caching
sbe {
    inputFiles.from(
        layout.buildDirectory.file("resources/main/protocol.xml"),
        layout.buildDirectory.file("resources/main/cluster-management-protocol.xml")
    )
}

// Configure SBE generation with the XML schema files from resources
tasks.named<JavaExec>("generateSbe") {
    args(
        layout.buildDirectory.file("resources/main/protocol.xml").get().asFile.absolutePath,
        layout.buildDirectory.file("resources/main/cluster-management-protocol.xml").get().asFile.absolutePath
    )
    // Need to process resources first to get the XML files
    dependsOn(tasks.processResources)
}

// Configure compiler for Immutables annotation processor
tasks.named<JavaCompile>("compileJava") {
    options.isFork = true
    options.forkOptions.jvmArgs = listOf(
        "--add-opens=jdk.compiler/com.sun.tools.javac.code=ALL-UNNAMED"
    )
}

dependencies {
    api(project(":camunda-security-protocol"))
    api(libs.org.agrona.agrona)
    testImplementation(libs.org.junit.jupiter.junit.jupiter.api)
    testImplementation(libs.org.junit.jupiter.junit.jupiter.params)
    testImplementation(libs.org.junit.jupiter.junit.jupiter.engine)
    testImplementation(libs.org.assertj.assertj.core)
    testImplementation(libs.io.github.classgraph.classgraph)
    annotationProcessor(libs.org.immutables.value.processor)
    compileOnly(libs.org.immutables.value)
    compileOnly(libs.org.immutables.annotate)
    compileOnly(libs.com.github.spotbugs.spotbugs.annotations)
    compileOnly(libs.net.jcip.jcip.annotations)
}

description = "Zeebe Protocol"
