# description: Nightly E2E tests for stable/8.9 in both Tasklist V1 and V2 modes.
# test location: /qa/c8-orchestration-cluster-e2e-test-suite
# type: CI
# owner: @camunda/test-automation-team
---
name: C8 Orchestration Cluster Nightly 8.9 - E2E Tests

on:
  schedule:
    - cron: "15 1 * * *"
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  nightly-e2e-tests-v1:
    uses: ./.github/workflows/c8-orchestration-cluster-reusable-e2e-tests.yml
    with:
      branch: stable/8.9
      tasklist_mode: v1
    secrets: inherit

  nightly-e2e-tests-v2:
    uses: ./.github/workflows/c8-orchestration-cluster-reusable-e2e-tests.yml
    with:
      branch: stable/8.9
      tasklist_mode: v2
    secrets: inherit
