# description: Nightly Elasticsearch API tests for main
# test location: /qa/c8-orchestration-cluster-e2e-test-suite
# type: CI
# owner: @camunda/test-automation-team
---
name: C8 Orchestration Cluster Nightly main - API Tests (ES)

on:
  schedule:
    - cron: "30 1 * * *"
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  nightly-api-tests-es:
    uses: ./.github/workflows/c8-orchestration-cluster-reusable-api-tests.yml
    with:
      branch: main
    secrets: inherit

  nightly-api-tests-es-all-in-one:
    uses: ./.github/workflows/c8-orchestration-cluster-reusable-api-tests.yml
    with:
      branch: main
      camunda_mode: all-in-one
    secrets: inherit
