name: "C8Run: release"
on:
  workflow_dispatch:
    inputs:
      branch:
        description: "release branch of c8run to release (stable/8.7, main, etc.)"
        type: string
        required: true
        default: ""
      camundaRelease:
        description: "name of release in camunda"
        type: string
        required: true
        default: ""

permissions:
  actions: read
  attestations: none
  checks: read
  contents: write
  deployments: none
  id-token: none
  issues: none
  discussions: none
  packages: none
  pages: none
  pull-requests: none
  repository-projects: none
  security-events: none
  statuses: write

jobs:
  release:
    name: C8Run Release ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    strategy:
      matrix:
        # macos-latest is ARM, mac os 13 will execute on x86 runner.
        os: [ubuntu-latest, macos-latest, macos-13]
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}

      - name: Import Secrets
        id: secrets
        uses: hashicorp/vault-action@d1720f055e0635fd932a1d2a48f87a666a57906c # v3.0.0
        with:
          url: ${{ secrets.VAULT_ADDR }}
          method: approle
          roleId: ${{ secrets.VAULT_ROLE_ID }}
          secretId: ${{ secrets.VAULT_SECRET_ID }}
          secrets: |
            secret/data/products/distribution/ci NEXUS_USERNAME;
            secret/data/products/distribution/ci NEXUS_PASSWORD;
            secret/data/products/distribution/ci APPLE_CERTIFICATE;
            secret/data/products/distribution/ci APPLE_CERTIFICATE_PASSWORD;
            secret/data/products/distribution/ci APPLE_DEVELOPER_ID;
            secret/data/products/distribution/ci APPLE_DEVELOPER_PASSWORD;
            secret/data/products/distribution/ci APPLE_TEAM_ID;

      - uses: actions/setup-go@v5
        with:
          go-version: '>=1.23.1'
          cache: false  # disabling since not working anyways without a cache-dependency-path specified

      - name: Build c8run
        run: go build
        working-directory: ./c8run

      - name: sign the package
        if: matrix.os == 'macos-latest' || matrix.os == 'macos-13'
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/quill/main/install.sh | sh -s -- -b /usr/local/bin
          echo "$CERTIFICATE" > certificate.p12
          quill sign --p12 certificate.p12 c8run
          rm certificate.p12
        working-directory: ./c8run
        env:
          CERTIFICATE: ${{ steps.secrets.outputs.APPLE_CERTIFICATE }}
          QUILL_SIGN_P12: ./certificate.p12
          QUILL_SIGN_PASSWORD: ${{ steps.secrets.outputs.APPLE_CERTIFICATE_PASSWORD }}

      - name: make a package
        run: |
          ./c8run package
          mkdir tmp
          mv camunda8-run-*.tar.gz tmp
          cd tmp
          tar -xzvf camunda8-run-*.tar.gz
          zip -r $(basename camunda8-run-*).zip c8run
          rm camunda8-run-*.tar.gz
          mv $(basename camunda8-run-*).zip ../
        shell: bash
        working-directory: ./c8run
        env:
          JAVA_ARTIFACTS_USER: ${{ steps.secrets.outputs.NEXUS_USERNAME }}
          JAVA_ARTIFACTS_PASSWORD: ${{ steps.secrets.outputs.NEXUS_PASSWORD }}

      - name: verify the package
        if: matrix.os == 'macos-latest' || matrix.os == 'macos-13'
        run: codesign --verify -v c8run
        working-directory: ./c8run

      - name: notarize
        if: matrix.os == 'macos-latest' || matrix.os == 'macos-13'
        run: |
          xcrun notarytool submit ./camunda8-run-*.zip --apple-id "$APPLE_ID" --password "$APPLE_APP_PASSWORD" --team-id "$TEAM_ID" --wait
          xcrun stapler staple ./camunda8-run-*.zip
        working-directory: ./c8run
        env:
          APPLE_ID: ${{ steps.secrets.outputs.APPLE_DEVELOPER_ID }}
          APPLE_APP_PASSWORD: ${{ steps.secrets.outputs.APPLE_DEVELOPER_PASSWORD }}
          TEAM_ID: ${{ steps.secrets.outputs.APPLE_TEAM_ID }}

      - name: upload asset
        working-directory: ./c8run
        run: gh release upload "${{ env.CAMUNDA_RELEASE }}" camunda8-run-*
        env:
          GH_TOKEN: ${{ github.token }}
          CAMUNDA_RELEASE: ${{ inputs.camundaRelease }}

  release_windows:
    name: C8Run Release windows
    runs-on: windows-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}

      - name: Import Secrets
        id: secrets
        uses: hashicorp/vault-action@d1720f055e0635fd932a1d2a48f87a666a57906c # v3.0.0
        with:
          url: ${{ secrets.VAULT_ADDR }}
          method: approle
          roleId: ${{ secrets.VAULT_ROLE_ID }}
          secretId: ${{ secrets.VAULT_SECRET_ID }}
          secrets: |
            secret/data/products/distribution/ci NEXUS_USERNAME;
            secret/data/products/distribution/ci NEXUS_PASSWORD;

      - uses: actions/setup-go@v5
        with:
          go-version: '>=1.23.1'
          cache: false  # disabling since not working anyways without a cache-dependency-path specified

      - name: Build c8run
        run: go build
        working-directory: .\c8run

      - name: make a package
        run: .\c8run.exe package
        working-directory: .\c8run
        env:
          GH_TOKEN: ${{ github.token }}
          JAVA_ARTIFACTS_USER: ${{ steps.secrets.outputs.NEXUS_USERNAME }}
          JAVA_ARTIFACTS_PASSWORD: ${{ steps.secrets.outputs.NEXUS_PASSWORD }}

      - name: upload asset
        working-directory: .\c8run
        run: |
          gh release upload "${{ env.CAMUNDA_RELEASE }}" camunda8-run-${{ env.CAMUNDA_RELEASE }}-windows-x86_64.zip
        env:
          GH_TOKEN: ${{ github.token }}
          CAMUNDA_RELEASE: ${{ inputs.camundaRelease }}
