# description: CI for the load-tests/metrics-exporter Go module: runs unit tests, lints, and verifies the Docker image builds.
# type: CI
# owner: @camunda/reliability-testing
---
name: "Load test: metrics exporter: build/test"

on:
  push:
    branches:
      - main
    paths:
      - "load-tests/metrics-exporter/**"
      - ".github/workflows/camunda-load-test-metrics-exporter-ci.yaml"
  pull_request:
    paths:
      - "load-tests/metrics-exporter/**"
      - ".github/workflows/camunda-load-test-metrics-exporter-ci.yaml"

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    working-directory: ./load-tests/metrics-exporter

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: ./load-tests/metrics-exporter/go.mod
          cache-dependency-path: ./load-tests/metrics-exporter/go.sum

      - name: Download dependencies
        run: go mod download

      - name: Run tests
        run: make test

      - name: Run IT
        run: make integration-test

      - name: Observe build status
        if: always()
        continue-on-error: true
        uses: ./.github/actions/observe-build-status
        with:
          build_status: ${{ job.status }}
          secret_vault_address: ${{ secrets.VAULT_ADDR }}
          secret_vault_roleId: ${{ secrets.VAULT_ROLE_ID }}
          secret_vault_secretId: ${{ secrets.VAULT_SECRET_ID }}

  lint:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: ./load-tests/metrics-exporter/go.mod
          cache-dependency-path: ./load-tests/metrics-exporter/go.sum

      - name: Install golangci-lint
        run: go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@v2.1.6

      - name: Lint
        run: make lint

      - name: Observe build status
        if: always()
        continue-on-error: true
        uses: ./.github/actions/observe-build-status
        with:
          build_status: ${{ job.status }}
          secret_vault_address: ${{ secrets.VAULT_ADDR }}
          secret_vault_roleId: ${{ secrets.VAULT_ROLE_ID }}
          secret_vault_secretId: ${{ secrets.VAULT_SECRET_ID }}

  docker-build:
    name: Build Docker image
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Setup build environment
        uses: ./.github/actions/setup-build
        with:
          dockerhub-readonly: true
          harbor: true
          vault-address: ${{ secrets.VAULT_ADDR }}
          vault-role-id: ${{ secrets.VAULT_ROLE_ID }}
          vault-secret-id: ${{ secrets.VAULT_SECRET_ID }}

      - name: Setup Docker
        uses: docker/setup-buildx-action@bb05f3f5519dd87d3ba754cc423b652a5edd6d2c # v4.2.0

      - name: Build image
        run: make docker DOCKER_PUSH=${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}

      - name: Observe build status
        if: always()
        continue-on-error: true
        uses: ./.github/actions/observe-build-status
        with:
          build_status: ${{ job.status }}
          secret_vault_address: ${{ secrets.VAULT_ADDR }}
          secret_vault_roleId: ${{ secrets.VAULT_ROLE_ID }}
          secret_vault_secretId: ${{ secrets.VAULT_SECRET_ID }}
