# description: Create a Camunda load test for an individual PR. When a PR is closed, the test is cleaned up and removed
# type: CI
# owner @camunda/reliability-testing
name: Camunda Pull Request Benchmark
on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - closed

defaults:
  run:
    # use bash shell by default to ensure pipefail behavior is the default
    # see https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#exit-codes-and-error-action-preference
    shell: bash

env:
  CLUSTER: camunda-benchmark-prod
  TELEPORT_JOIN_TOKEN: infra-benchmark-prod-github-action-zeebe

jobs:
  sanitize-branch-name:
    name: Sanitize Branch Name
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions: {}
    outputs:
      sanitized-name: c8-${{ steps.sanitize.outputs.branch_name }}
      sanitized-name-rdbms: c8-${{ steps.sanitize.outputs.branch_name }}-rdbms
      cluster: ${{ env.CLUSTER }}
      teleport-join-token: ${{ env.TELEPORT_JOIN_TOKEN }}
    steps:
      - id: sanitize
        uses: camunda/infra-global-github-actions/sanitize-branch-name@main
        with:
          branch: ${{ github.event.pull_request.head.ref }}
          max_length: 44  # reduced to account for load-test prefix "c8-"" and potential suffixes for uniqueness
      - name: Observe build status
        if: always()
        continue-on-error: true
        uses: ./.github/actions/observe-build-status
        with:
          build_status: ${{ job.status }}
          secret_vault_address: ${{ secrets.VAULT_ADDR }}
          secret_vault_roleId: ${{ secrets.VAULT_ROLE_ID }}
          secret_vault_secretId: ${{ secrets.VAULT_SECRET_ID }}

  create-benchmark:
    name: Benchmark
    needs: sanitize-branch-name
    if: >
      (github.event.action == 'labeled' && github.event.label.name == 'benchmark') ||
      (github.event.action == 'synchronize' && contains(github.event.pull_request.labels.*.name, 'benchmark'))
    uses: ./.github/workflows/camunda-load-test.yml
    secrets: inherit
    with:
      name: ${{ needs.sanitize-branch-name.outputs.sanitized-name }}
      ref: ${{ github.event.pull_request.head.ref }}
      scenario: 'max'

  create-benchmark-rdbms:
    name: Benchmark RDBMS
    needs: sanitize-branch-name
    if: >
      (github.event.action == 'labeled' && github.event.label.name == 'benchmark-rdbms') ||
      (github.event.action == 'synchronize' && contains(github.event.pull_request.labels.*.name, 'benchmark-rdbms'))
    uses: ./.github/workflows/camunda-load-test.yml
    secrets: inherit
    with:
      name: ${{ needs.sanitize-branch-name.outputs.sanitized-name-rdbms }}
      ref: ${{ github.event.pull_request.head.ref }}
      scenario: 'max'
      secondary-storage-type: 'postgresql'

  profile-and-comment:
    name: Profile and Comment
    needs: [sanitize-branch-name, create-benchmark]
    if: >
      always() &&
      !(github.event.action == 'unlabeled' && github.event.label.name == 'benchmark') &&
      needs.create-benchmark.result == 'success'
    uses: ./.github/workflows/profile-benchmark.yml
    secrets: inherit
    with:
      name: ${{ needs.sanitize-branch-name.outputs.sanitized-name }}
      database: 'elasticsearch'
      cluster: ${{ needs.sanitize-branch-name.outputs.cluster }}
      teleport-join-token: ${{ needs.sanitize-branch-name.outputs.teleport-join-token }}

  profile-and-comment-rdbms:
    name: Profile and Comment RDBMS
    needs: [sanitize-branch-name, create-benchmark-rdbms]
    if: >
      always() &&
      !(github.event.action == 'unlabeled' && github.event.label.name == 'benchmark-rdbms') &&
      needs.create-benchmark-rdbms.result == 'success'
    uses: ./.github/workflows/profile-benchmark.yml
    secrets: inherit
    with:
      name: ${{ needs.sanitize-branch-name.outputs.sanitized-name-rdbms }}
      database: 'rdbms'
      cluster: ${{ needs.sanitize-branch-name.outputs.cluster }}
      teleport-join-token: ${{ needs.sanitize-branch-name.outputs.teleport-join-token }}

  delete-benchmark:
    name: Benchmark Cleanup
    needs: sanitize-branch-name
    if: >
      (github.event.action == 'unlabeled' && (github.event.label.name == 'benchmark' || github.event.label.name == 'benchmark-rdbms')) ||
      (github.event.action == 'closed' && (contains(github.event.pull_request.labels.*.name, 'benchmark') || contains(github.event.pull_request.labels.*.name, 'benchmark-rdbms')))
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Set up Teleport
        uses: teleport-actions/setup@v1
        with:
          version: 17.2.2
      - name: Authenticate to Cluster using Teleport
        uses: teleport-actions/auth-k8s@v2
        with:
          proxy: camunda.teleport.sh:443
          token: ${{ needs.sanitize-branch-name.outputs.teleport-join-token }}
          kubernetes-cluster: ${{ needs.sanitize-branch-name.outputs.cluster }}
      - name: Delete benchmark namespace
        if: >
          github.event.action == 'closed' ||
          (github.event.action == 'unlabeled' && github.event.label.name == 'benchmark' && contains(github.event.pull_request.labels.*.name, 'benchmark'))
        run: |
          kubectl delete ns "${{ needs.sanitize-branch-name.outputs.sanitized-name }}" --ignore-not-found
      - name: Delete RDBMS benchmark namespace
        if: >
          github.event.action == 'closed' ||
          (github.event.action == 'unlabeled' && github.event.label.name == 'benchmark-rdbms' && contains(github.event.pull_request.labels.*.name, 'benchmark-rdbms'))
        run: |
          kubectl delete ns "${{ needs.sanitize-branch-name.outputs.sanitized-name-rdbms }}" --ignore-not-found
      - name: Observe build status
        if: always()
        continue-on-error: true
        uses: ./.github/actions/observe-build-status
        with:
          build_status: ${{ job.status }}
          secret_vault_address: ${{ secrets.VAULT_ADDR }}
          secret_vault_roleId: ${{ secrets.VAULT_ROLE_ID }}
          secret_vault_secretId: ${{ secrets.VAULT_SECRET_ID }}

