# description: Verifies a load test deployment is healthy. Cleanup is delegated to
#              camunda-delete-load-test.yml and runs regardless of verify outcome.
# called-by: camunda-scheduled-release-load-tests.yml
# type: CI
# owner: @camunda/reliability-testing
name: Verify and cleanup load test
on:
  workflow_call:
    inputs:
      namespace:
        description: 'Kubernetes namespace where the load test is deployed'
        type: string
        required: true

env:
  CLUSTER: camunda-benchmark-prod
  TELEPORT_JOIN_TOKEN: infra-benchmark-prod-github-action-zeebe

jobs:
  verify:
    name: Verify
    permissions:
      contents: 'read'
      id-token: 'write'
    uses: ./.github/workflows/camunda-verify-load-test.yml
    secrets: inherit
    with:
      namespace: ${{ inputs.namespace }}

  cleanup:
    name: Cleanup
    needs: verify
    if: always()
    permissions:
      contents: read
      id-token: write
    uses: ./.github/workflows/camunda-delete-load-test.yml
    secrets: inherit
    with:
      namespace: ${{ inputs.namespace }}
