---
name: Camunda Platform Release Dry Run from main

# owner: @camunda/monorepo-devops-team

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Specifies the branch, for which the Release Dry Run should be executed'
        default: 'main'
        required: false
        type: string
  schedule:
    # Runs at 01:00 every week day; see this link for more: https://crontab.guru/#0_1_*_*_1-5
    - cron: '0 1 * * 1-5'

jobs:
  dry-run-release:
    name: "${{ matrix.version }} from ${{ inputs.branch || 'main' }}"
    uses: ./.github/workflows/camunda-platform-release.yml
    secrets: inherit
    strategy:
      fail-fast: false
      matrix:
        version: [ 1.0.2, 1.0.0-alpha1 ]
        include:
          - version: 1.0.2
            latest: true
          - version: 1.0.0-alpha1
            latest: false
    with:
      releaseBranch: ${{ inputs.branch || 'main' }}
      releaseVersion: ${{ matrix.version }}
      nextDevelopmentVersion: 0.0.0-SNAPSHOT
      isLatest: ${{ matrix.latest }}
      dryRun: true
