# type: CI
# owner: @camunda/reliability-testing
name: Camunda PR Benchmark (mysql)
on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - closed

defaults:
  run:
    shell: bash

jobs:
  benchmark:
    name: Benchmark (mysql)
    if: >
      (contains(fromJSON('["labeled", "unlabeled"]'), github.event.action) && github.event.label.name == 'benchmark-mysql') ||
      (contains(fromJSON('["synchronize", "closed"]'), github.event.action) && contains(github.event.pull_request.labels.*.name, 'benchmark-mysql'))
    uses: ./.github/workflows/pr-benchmark-pipeline.yml
    secrets: inherit
    with:
      label: 'benchmark-mysql'
      secondary-storage-type: 'mysql'
      ref: ${{ github.event.pull_request.head.ref }}
