# description: Deploys new Camunda load tests weekly. Multiple kinds of load tests are created - typical, realistic, latency
# type: CI
# owner: @camunda/reliability-testing
name: Camunda weekly medic load test
on:
  workflow_dispatch:
     inputs:
      reuse-tag:
        description: 'Docker image tag, that should be reused for the weekly load tests. Allows to skip the docker image build step, can be used for recreating previous weekly tests.'
        type: string
        default: ""
        required: false
      ttl:
        description: 'Specifies after how many days the weekly load test namespace should be deleted. Useful to adjust if we recreate the weekly tests.'
        type: number
        default: 28
        required: false
  schedule:
    # Runs at 1am every monday https://crontab.guru/#0_1_*_*_1
    - cron: 0 1 * * 1

defaults:
  run:
    # use bash shell by default to ensure pipefail behavior is the default
    # see https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#exit-codes-and-error-action-preference
    shell: bash

env:
  IMAGE_REPOSITORY: registry.camunda.cloud/team-zeebe

jobs:
  test-data:
    name: Collect test data
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions: { }
    outputs:
      image-tag: ${{ steps.data.outputs.image-tag }}
    steps:
      - uses: actions/checkout@v6
      - name: Collect test data
        id: data
        env:
          REUSE_TAG: ${{ inputs.reuse-tag }}
        run: |
          if [[ -z "$REUSE_TAG" ]]; then
            echo "Creating new weekly test tag"
            echo "image-tag=medic-$(date +%Y)-$(date +%V)-$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"
          else
            echo "Re-creating weekly test, with tag: $REUSE_TAG"
            echo "image-tag=$REUSE_TAG" >> "$GITHUB_OUTPUT"
          fi
      - name: Observe build status
        if: always()
        continue-on-error: true
        uses: ./.github/actions/observe-build-status
        with:
          build_status: ${{ job.status }}
          secret_vault_address: ${{ secrets.VAULT_ADDR }}
          secret_vault_roleId: ${{ secrets.VAULT_ROLE_ID }}
          secret_vault_secretId: ${{ secrets.VAULT_SECRET_ID }}

  build-camunda-image:
    name: Build Camunda Image
    needs: test-data
    if: ${{ inputs.reuse-tag == '' }}
    runs-on: ubuntu-latest
    timeout-minutes: 45
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-build
        with:
          dockerhub-readonly: true
          harbor: true
          vault-address: ${{ secrets.VAULT_ADDR }}
          vault-role-id: ${{ secrets.VAULT_ROLE_ID }}
          vault-secret-id: ${{ secrets.VAULT_SECRET_ID }}
          minimus: true
      - uses: ./.github/actions/build-frontend
        name: Build Operate Frontend
        with:
          directory: ./operate/client
          package-manager: "npm"
      - uses: ./.github/actions/build-frontend
        name: Build Tasklist Frontend
        with:
          directory: ./tasklist/client
          package-manager: "npm"
      - uses: ./.github/actions/build-frontend
        name: Build Identity Frontend
        with:
          directory: ./identity/client
          package-manager: "npm"
      - uses: ./.github/actions/build-frontend
        name: Build Optimize Frontend
        with:
          directory: ./optimize/client
          package-manager: "yarn"
      - uses: ./.github/actions/build-zeebe
        name: Build Camunda Platform
        id: build-camunda
        with:
          maven-extra-args: -PskipFrontendBuild -Pinclude-optimize
      - uses: ./.github/actions/build-platform-docker
        name: Build and Push Camunda Docker Image
        with:
          repository: '${{ env.IMAGE_REPOSITORY }}/camunda'
          push: true
          version: ${{ needs.test-data.outputs.image-tag }}
          distball: ${{ steps.build-camunda.outputs.distball }}
          dockerfile: 'camunda.Dockerfile'
      - uses: ./.github/actions/build-platform-docker
        name: Build Optimize Docker Image
        with:
          repository: '${{ env.IMAGE_REPOSITORY }}/optimize'
          push: true
          version: ${{ needs.test-data.outputs.image-tag }}
          distball: 'optimize-distro/target/camunda-optimize-*.tar.gz'
          dockerfile: 'optimize.Dockerfile'
      - name: Observe build status
        if: always()
        continue-on-error: true
        uses: ./.github/actions/observe-build-status
        with:
          build_status: ${{ job.status }}
          secret_vault_address: ${{ secrets.VAULT_ADDR }}
          secret_vault_roleId: ${{ secrets.VAULT_ROLE_ID }}
          secret_vault_secretId: ${{ secrets.VAULT_SECRET_ID }}

  build-load-test-images:
    name: Build Starter and Worker
    needs: test-data
    if: ${{ inputs.reuse-tag == '' }}
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-build
        with:
          dockerhub-readonly: true
          harbor: true
          vault-address: ${{ secrets.VAULT_ADDR }}
          vault-role-id: ${{ secrets.VAULT_ROLE_ID }}
          vault-secret-id: ${{ secrets.VAULT_SECRET_ID }}
      - run: ./mvnw -B -DskipTests -DskipChecks -P\!include-optimize -pl load-tests/load-tester -am install
      - name: Build Starter Image
        run: ./mvnw -pl load-tests/load-tester jib:build -P starter -P\!include-optimize -D image="${{ env.IMAGE_REPOSITORY }}/starter:${{ needs.test-data.outputs.image-tag }}"
      - name: Build Worker Image
        run: ./mvnw -pl load-tests/load-tester jib:build -P worker -P\!include-optimize -D image="${{ env.IMAGE_REPOSITORY }}/worker:${{ needs.test-data.outputs.image-tag }}"
      - name: Observe build status
        if: always()
        continue-on-error: true
        uses: ./.github/actions/observe-build-status
        with:
          build_status: ${{ job.status }}
          secret_vault_address: ${{ secrets.VAULT_ADDR }}
          secret_vault_roleId: ${{ secrets.VAULT_ROLE_ID }}
          secret_vault_secretId: ${{ secrets.VAULT_SECRET_ID }}

  setup-typical-load-test:
    name: Typical load test
    needs:
      - test-data
      - build-camunda-image
      - build-load-test-images
    if: |
      always() &&
      needs.test-data.result == 'success' &&
      (needs.build-camunda-image.result == 'success' || needs.build-camunda-image.result == 'skipped') &&
      (needs.build-load-test-images.result == 'success' || needs.build-load-test-images.result == 'skipped')
    uses: ./.github/workflows/camunda-load-test.yml
    secrets: inherit
    with:
      name: ${{ needs.test-data.outputs.image-tag }}-typical
      ttl: ${{ fromJSON(inputs.ttl || '28') }}
      reuse-tag: ${{ needs.test-data.outputs.image-tag }}
      scenario: typical

  setup-rdbms-realistic-load-test:
    name: Postgres realistic load test
    needs:
      - test-data
      - build-camunda-image
      - build-load-test-images
    if: |
      always() &&
      needs.test-data.result == 'success' &&
      (needs.build-camunda-image.result == 'success' || needs.build-camunda-image.result == 'skipped') &&
      (needs.build-load-test-images.result == 'success' || needs.build-load-test-images.result == 'skipped')
    uses: ./.github/workflows/camunda-load-test.yml
    secrets: inherit
    with:
      name: ${{ needs.test-data.outputs.image-tag }}-rdbms-realistic
      ttl: ${{ fromJSON(inputs.ttl || '28') }}
      reuse-tag: ${{ needs.test-data.outputs.image-tag }}
      secondary-storage-type: 'postgresql'
      scenario: realistic

  setup-realistic-test:
    name: Realistic load test
    uses: ./.github/workflows/camunda-load-test.yml
    secrets: inherit
    needs:
      - test-data
      - build-camunda-image
      - build-load-test-images
    if: |
      always() &&
      needs.test-data.result == 'success' &&
      (needs.build-camunda-image.result == 'success' || needs.build-camunda-image.result == 'skipped') &&
      (needs.build-load-test-images.result == 'success' || needs.build-load-test-images.result == 'skipped')
    with:
      name: ${{ needs.test-data.outputs.image-tag }}-realistic
      ttl: ${{ fromJSON(inputs.ttl || '28') }}
      reuse-tag: ${{ needs.test-data.outputs.image-tag }}
      scenario: realistic

  setup-latency-test:
    name: Latency test
    uses: ./.github/workflows/camunda-load-test.yml
    secrets: inherit
    needs:
      - test-data
      - build-camunda-image
      - build-load-test-images
    if: |
      always() &&
      needs.test-data.result == 'success' &&
      (needs.build-camunda-image.result == 'success' || needs.build-camunda-image.result == 'skipped') &&
      (needs.build-load-test-images.result == 'success' || needs.build-load-test-images.result == 'skipped')
    with:
      name: ${{ needs.test-data.outputs.image-tag }}-latency
      ttl: ${{ fromJSON(inputs.ttl || '28') }}
      reuse-tag: ${{ needs.test-data.outputs.image-tag }}
      scenario: latency

  notify:
    name: Notify on failure
    runs-on: ubuntu-latest
    needs: [ build-camunda-image, build-load-test-images, setup-typical-load-test, setup-rdbms-realistic-load-test, setup-realistic-test, setup-latency-test ]
    if: failure()
    timeout-minutes: 5
    permissions: { }
    steps:
      - uses: actions/checkout@v6
      - id: slack-notify
        uses: slackapi/slack-github-action@v3.0.1
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_RELIABILITY_TESTING_CH }}
          webhook-type: incoming-webhook
          payload: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": ":warning: *Weekly Medic load test creation failed:*"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "@reliability-testing-team Please check the related workflow execution: https://github.com/camunda/camunda/actions/runs/${{ github.run_id }}"
                  }
                }
              ]
            }
      - name: Observe build status
        if: always()
        continue-on-error: true
        uses: ./.github/actions/observe-build-status
        with:
          build_status: ${{ job.status }}
          secret_vault_address: ${{ secrets.VAULT_ADDR }}
          secret_vault_roleId: ${{ secrets.VAULT_ROLE_ID }}
          secret_vault_secretId: ${{ secrets.VAULT_SECRET_ID }}
