# type: Preview Environments
# owner: @camunda/engineering-operations
---
name: Check for PR conflicts

on:
  schedule:
  - cron: 23 1 * * 1-5
  workflow_dispatch:
  pull_request:

env:
  TEST_OWNER: '@camunda/engineering-operations'

jobs:
  check-all-pr-conflicts:
    if: ${{ github.event_name == 'schedule' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
    - name: Check all PRs for conflict
      uses: camunda/infra-global-github-actions/preview-env/conflicts@a362d3abeb1f550f0269d74adf2fe343e24517ef # preview-env: v1.0.8
  check-single-pr-conflict:
    # No check on label `deploy-preview` here, because it wouldn't run
    # if there's a remaining merge conflict. Thus, only a cleanup can happen here.
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    steps:
    - name: Check PR for merge conflicts
      uses: camunda/infra-global-github-actions/preview-env/conflicts@a362d3abeb1f550f0269d74adf2fe343e24517ef # preview-env: v1.0.8
      with:
        pull-request-id: ${{ github.event.pull_request.number }}
