# description: Workflow for running Client Components tests. Does linting and basic build validation for the JS/TS client library monorepo.
# test location: /client-components
# called by: ci.yml
# type: CI
# owner: @camunda/engineering-operations
name: Client Components Jobs

on:
  workflow_call: {}

env:
  GHA_BEST_PRACTICES_LINTER: enabled
  CLIENT_DIR: client-components

jobs:
  lint:
    name: "Lint"
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions: {} # GITHUB_TOKEN unused in this job
    defaults:
      run:
        working-directory: ${{ env.CLIENT_DIR }}
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: 24
      - name: Install dependencies
        uses: ./.github/actions/npm-ci-with-retry
        with:
          directory: ${{ env.CLIENT_DIR }}
      - name: Linting
        run: npm run lint
      - name: Observe build status
        if: always()
        continue-on-error: true
        uses: ./.github/actions/observe-build-status
        with:
          build_status: ${{ job.status }}
          secret_vault_secretId: ${{ secrets.VAULT_SECRET_ID }}
          secret_vault_address: ${{ secrets.VAULT_ADDR }}
          secret_vault_roleId: ${{ secrets.VAULT_ROLE_ID }}
