# description: Workflow for running Webapp Client tests. Does linting and basic build validation for the JS/TS client library monorepo.
# test location: /webapp/client
# called by: ci.yml
# type: CI
# owner: @camunda/monorepo-devops-team
name: Webapp Client Jobs

on:
  workflow_call: {}

env:
  GHA_BEST_PRACTICES_LINTER: enabled

jobs:
  typecheck:
    name: "Type check"
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions: {} # GITHUB_TOKEN unused in this job
    defaults:
      run:
        working-directory: webapp/client
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: 24
      - name: Install dependencies
        run: npm ci
      - name: Type check
        run: npm run typecheck
      - name: Observe build status
        if: always()
        continue-on-error: true
        uses: ./.github/actions/observe-build-status
        with:
          build_status: ${{ job.status }}
          secret_vault_secretId: ${{ secrets.VAULT_SECRET_ID }}
          secret_vault_address: ${{ secrets.VAULT_ADDR }}
          secret_vault_roleId: ${{ secrets.VAULT_ROLE_ID }}

  eslint:
    name: "ESLint"
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions: {} # GITHUB_TOKEN unused in this job
    defaults:
      run:
        working-directory: webapp/client
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: 24
      - name: Install dependencies
        run: npm ci
      - name: ESLint
        run: npm run lint:eslint
      - name: Observe build status
        if: always()
        continue-on-error: true
        uses: ./.github/actions/observe-build-status
        with:
          build_status: ${{ job.status }}
          secret_vault_secretId: ${{ secrets.VAULT_SECRET_ID }}
          secret_vault_address: ${{ secrets.VAULT_ADDR }}
          secret_vault_roleId: ${{ secrets.VAULT_ROLE_ID }}

  prettier:
    name: "Prettier"
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions: {} # GITHUB_TOKEN unused in this job
    defaults:
      run:
        working-directory: webapp/client
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: 24
      - name: Install dependencies
        run: npm ci
      - name: Prettier
        run: npm run lint:prettier
      - name: Observe build status
        if: always()
        continue-on-error: true
        uses: ./.github/actions/observe-build-status
        with:
          build_status: ${{ job.status }}
          secret_vault_secretId: ${{ secrets.VAULT_SECRET_ID }}
          secret_vault_address: ${{ secrets.VAULT_ADDR }}
          secret_vault_roleId: ${{ secrets.VAULT_ROLE_ID }}

  build:
    name: "Build"
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions: {} # GITHUB_TOKEN unused in this job
    defaults:
      run:
        working-directory: webapp/client
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: 24
      - name: Install dependencies
        run: npm ci
      - name: Build packages
        run: npm run build
      - name: Observe build status
        if: always()
        continue-on-error: true
        uses: ./.github/actions/observe-build-status
        with:
          build_status: ${{ job.status }}
          secret_vault_secretId: ${{ secrets.VAULT_SECRET_ID }}
          secret_vault_address: ${{ secrets.VAULT_ADDR }}
          secret_vault_roleId: ${{ secrets.VAULT_ROLE_ID }}
