# description: Instructions for GitHub co-pilot coding agent, ensuring the agent has an environment that it can work in.
# see_also: https://docs.github.com/en/enterprise-cloud@latest/copilot/how-tos/use-copilot-agents/coding-agent/customize-the-agent-environment
# test location: /
# type: AGENT_SETUP
# owner: @camunda/engineering-operations
---
name: "Copilot Setup Steps"

on:
  workflow_dispatch:
  pull_request:
    paths:
      - .github/workflows/copilot-setup-steps.yml

jobs:
  copilot-setup-steps:
    runs-on: ubuntu-latest
    timeout-minutes: 50

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Install gh-aw extension
        uses: github/gh-aw-actions/setup-cli@9271a1804551c0dc4fb0085a97979950aa2f8489 # v0.88.2
        with:
          version: v0.88.2
      # If we want to align Copilot and CI setups more in the future, consider using (parts of) .github/actions/setup-build here
      - uses: actions/setup-java@dd06d9cba3e5552c54d9f8ea23572deb30010f7c # v6.0.0
        with:
          distribution: 'temurin'
          java-version: '21'
