# description: Instructions for GitHub co-pilot coding agent, ensuring the agent has an environment that it can work in.
# see_also: https://docs.github.com/en/enterprise-cloud@latest/copilot/how-tos/use-copilot-agents/coding-agent/customize-the-agent-environment
# test location: /
# type: AGENT_SETUP
# owner: @camunda/monorepo-devops-team
---
name: "Copilot Setup Steps"

on:
  workflow_dispatch:
  pull_request:
    paths:
      - .github/workflows/copilot-setup-steps.yml

jobs:
  copilot-setup-steps:
    runs-on: ubuntu-latest
    timeout-minutes: 50

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Install gh-aw extension
        uses: github/gh-aw-actions/setup-cli@cba13b4e136caf371ffda4b9432f43841d6e5ec1 # v0.82.4
        with:
          version: v0.77.5
      # If we want to align Copilot and CI setups more in the future, consider using (parts of) .github/actions/setup-build here
      - uses: actions/setup-java@0f481fcb613427c0f801b606911222b5b6f3083a # v5.5.0
        with:
          distribution: 'temurin'
          java-version: '21'
