# type: Project Management
# owner: @camunda/engineering-operations
name: "Opened Issue Labeler"
on:
  issues:
    types: [opened]

permissions:
  issues: write
  contents: read

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
    - name: Generate GitHub token
      id: github-token
      uses: camunda/infra-global-github-actions/generate-github-app-token-from-vault-secrets@67d00e9260887361a31f6446252fffbecae4a02e # generate-github-app-token-from-vault-secrets-1.1.1
      with:
        github-app-id-vault-key: PROJECT_BOARD_AUTOMATION_APP_ID
        github-app-id-vault-path: secret/data/products/camunda/ci/camunda
        github-app-private-key-vault-key: PROJECT_BOARD_AUTOMATION_APP_PRIVATE_KEY
        github-app-private-key-vault-path: secret/data/products/camunda/ci/camunda
        vault-auth-method: approle
        vault-auth-role-id: ${{ secrets.VAULT_ROLE_ID }}
        vault-auth-secret-id: ${{ secrets.VAULT_SECRET_ID }}
        vault-url: ${{ secrets.VAULT_ADDR }}
    - uses: github/issue-labeler@ccca1e16fcb66762200e616fc29b57b940c1cb67 # v3.5
      with:
        configuration-path: .github/opened_issue_labeler.yml
        enable-versioned-regex: 0
        repo-token: ${{ steps.github-token.outputs.token }}
