name: Operate Frontend
on:
  push:
    branches:
      - 'main'
      - 'stable/**'
      - 'release**'
    paths:
      - '.github/workflows/operate-frontend.yml'
      - 'operate/client/**'
  pull_request:
    paths:
      - '.github/workflows/operate-frontend.yml'
      - 'operate/client/**'

# Limit workflow to 1 concurrent run per ref (branch): new commit -> old runs are canceled to save costs
# Exception for main branch: complete builds for every commit needed for confidenence
concurrency:
  cancel-in-progress: true
  group: ${{ format('{0}-{1}', github.workflow, github.ref == 'refs/heads/main' && github.sha || github.ref) }}

jobs:
  linting-and-testing:
    name: Linting & Testing
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: operate/client
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: "20"
      - uses: camunda/infra-global-github-actions/setup-yarn-cache@67d00e9260887361a31f6446252fffbecae4a02e # setup-yarn-cache-1.0.2
        with:
          directory: operate/client
      - run: yarn install --frozen-lockfile
        name: Install dependencies
      - run: yarn ts-check
        name: Type checks
      - run: yarn eslint
        name: ESLint
      - run: yarn test:ci
        name: Unit & Integration tests

      - name: Observe build status
        if: always()
        continue-on-error: true
        uses: ./.github/actions/observe-build-status
        with:
          build_status: ${{ job.status }}
          secret_vault_secretId: ${{ secrets.VAULT_SECRET_ID }}
          secret_vault_address: ${{ secrets.VAULT_ADDR }}
          secret_vault_roleId: ${{ secrets.VAULT_ROLE_ID }}
