# description: Runs Operate visual regression tests and updates baseline screenshots.
# test location: /operate/client/
# type: CI Helper
# owner: @camunda/fe-operate
name: Operate Update Visual Regression Snapshots

on:
  pull_request:
    types: [labeled]

# Limit workflow to 1 concurrent run per ref (branch): new commit -> old runs are canceled to save costs
concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  update-snapshots:
    if: github.event.pull_request.state != 'closed' && github.event.label.name == 'update-snapshots'
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: write
      pull-requests: write
    container:
      image: mcr.microsoft.com/playwright:v1.59.1
      options: --user 1001:1000

    steps:
      - name: Generate a GitHub token
        id: github-token
        uses: camunda/infra-global-github-actions/generate-github-app-token-from-vault-secrets@33a44f8dcb449fb8e08211afc03ae3c010195f75 # main
        with:
          github-app-id-vault-key: MONOREPO_DEVOPS_AUTOMATION_APP_ID
          github-app-id-vault-path: secret/data/products/camunda/ci/camunda
          github-app-private-key-vault-key: MONOREPO_DEVOPS_AUTOMATION_APP_PRIVATE_KEY
          github-app-private-key-vault-path: secret/data/products/camunda/ci/camunda
          vault-auth-method: approle
          vault-auth-role-id: ${{ secrets.VAULT_ROLE_ID }}
          vault-auth-secret-id: ${{ secrets.VAULT_SECRET_ID }}
          vault-url: ${{ secrets.VAULT_ADDR }}
      - name: Check out repository code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: ${{ github.head_ref }}
          token: ${{ steps.github-token.outputs.token }}
      - name: Setup NodeJS
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: 24
      - name: Install node dependencies
        working-directory: ./operate/client
        run: npm ci
      - name: Build frontend
        working-directory: ./operate/client
        run: npm run build:visual-regression
      - name: Start server
        working-directory: ./operate/client
        run: npm run start:visual-regression &
      - name: Update snapshots
        working-directory: ./operate/client
        run: npm run test:visual -- --update-snapshots
      - name: Commit screenshots
        uses: stefanzweifel/git-auto-commit-action@04702edda442b2e678b25b537cec683a1493fcb9 # v7.1.0
        with:
          commit_message: "test: updated operate snapshots"
          file_pattern: "operate/client/**/*.png"
          commit_user_name: operate-snapshot-bot
          commit_user_email: noreply@camunda.com
          commit_author: operate-snapshot-bot <noreply@camunda.com>
      - name: Remove update-snapshots label
        if: success()
        continue-on-error: true
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        with:
          github-token: ${{ steps.github-token.outputs.token }}
          script: |
            try {
              await github.rest.issues.removeLabel({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                name: 'update-snapshots',
              });
            } catch (error) {
              if (error.status === 404) {
                core.info('Label already removed.');
              } else {
                throw error;
              }
            }
      - name: Observe build status
        if: always()
        continue-on-error: true
        uses: ./.github/actions/observe-build-status
        with:
          build_status: ${{ job.status }}
          secret_vault_address: ${{ secrets.VAULT_ADDR }}
          secret_vault_roleId: ${{ secrets.VAULT_ROLE_ID }}
          secret_vault_secretId: ${{ secrets.VAULT_SECRET_ID }}
          user_description: "team-core-features"
