# This GitHub Actions workflow automates the CI build process for the 'operate' service.
# It triggers on a `workflow_call` event and accepts a branch name input.
#
# It consists of a several steps:
# 1. Setup: It checks out the specified branch, sets up Java and Maven with the provided inputs, and imports secrets from Vault.
# 2. Build: Then it builds the Maven artifacts.
#
# This workflow is designed to provide a comprehensive, automated CI process that ensures code quality, handles secrets securely,
# and enables detailed reporting of test results.
# description: Automates the build process for operate workflows
# called by: operate-ci.yml
# test location:
# type: CI
# owner: @camunda/core-features
---
name: Operate CI Reusable

on:
  workflow_call:
    inputs:
      branch:
        description: "The branch name to be used for the workflow"
        required: true
        type: string

defaults:
  run:
    # use bash shell by default to ensure pipefail behavior is the default
    # see https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#exit-codes-and-error-action-preference
    shell: bash

# Define environment variables
env:
  BRANCH_NAME: ${{ inputs.branch }}
  IS_DEFAULT_BRANCH: ${{ inputs.branch == 'main' }}
  IS_MAIN_OR_STABLE_BRANCH: ${{ inputs.branch == 'main' || startsWith(inputs.branch, 'stable/') }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      # Setup: checkout branch
      - name: Checkout '${{ inputs.branch }}' branch
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: refs/heads/${{ inputs.branch }}
          fetch-depth: 0 # fetches all history for all branches and tags

      #########################################################################
      # Setup: import secrets from vault
      - name: Import Secrets
        id: secrets # important to refer to it in later steps
        uses: hashicorp/vault-action@v3
        with:
          url: ${{ secrets.VAULT_ADDR }}
          method: approle
          roleId: ${{ secrets.VAULT_ROLE_ID }}
          secretId: ${{ secrets.VAULT_SECRET_ID }}
          exportEnv: false # we rely on step outputs, no need for environment variables
          secrets: |
            secret/data/products/operate/ci/github-actions OPERATE_CI_ALERT_WEBHOOK_URL;

      #########################################################################
      # Setup and configure Maven, Docker, and settings
      - uses: ./.github/actions/setup-build
        name: Build setup
        with:
          dockerhub: ${{ env.IS_MAIN_OR_STABLE_BRANCH == 'true' }}
          harbor: true
          java-distribution: adopt
          maven-cache-key-modifier: operate
          vault-address: ${{ secrets.VAULT_ADDR }}
          vault-role-id: ${{ secrets.VAULT_ROLE_ID }}
          vault-secret-id: ${{ secrets.VAULT_SECRET_ID }}
          minimus: true

      #########################################################################
      # Build Operate frontend
      - name: Build frontend
        uses: ./.github/actions/build-frontend
        with:
          directory: ./operate/client
          package-manager: "npm"

      #########################################################################
      # Build: maven artifacts
      - name: Build Maven
        run: |
          ./mvnw clean deploy -B -T1C -P -docker,skipFrontendBuild -DskipTests -DskipChecks -DaltStagingDirectory=${{ github.workspace }}/staging-${{ env.BRANCH_NAME }} -DskipRemoteStaging=true -Dmaven.deploy.skip=true

      #########################################################################
      # Collect information about build status for central statistics with CI Analytics
      - name: Observe build status
        if: always()
        continue-on-error: true
        uses: ./.github/actions/observe-build-status
        with:
          build_status: ${{ job.status }}
          secret_vault_secretId: ${{ secrets.VAULT_SECRET_ID }}
          secret_vault_address: ${{ secrets.VAULT_ADDR }}
          secret_vault_roleId: ${{ secrets.VAULT_ROLE_ID }}
