# description: Builds an Optimize docker image and a production .tar.gz, runs tests, and then deploys to artifactory and pushes to docker hub
# called by: optiimize-ci.yml
# type: CI
# owner: @camunda/core-features
name: Optimize Deploy Artifacts
on:
  workflow_call:

jobs:
  # Dynamically generate the Docker tag (e.g., SNAPSHOT or X.Y-SNAPSHOT) based on branch name
  utils-get-snapshot-docker-tag:
    uses: ./.github/workflows/generate-snapshot-docker-tag.yml
    secrets: inherit
    permissions:
      contents: read

  deploy-artifacts:
    name: Deploy Artifacts
    needs: [ utils-get-snapshot-docker-tag ]
    runs-on: gcp-core-4-default
    timeout-minutes: 30
    env:
      DOCKER_IMAGE_TEAM: registry.camunda.cloud/team-optimize/optimize
      DOCKER_IMAGE_DOCKER_HUB: camunda/optimize
      DOCKER_HUB_SNAPSHOT_TAG: ${{ needs.utils-get-snapshot-docker-tag.outputs.version_tag }}
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - name: Install common tooling (buildx)  # required on self-hosted runners
      uses: camunda/infra-global-github-actions/common-tooling@main
      with:
        buildx-enabled: true
        java-enabled: false
        node-enabled: false
        python-enabled: false
        yarn-enabled: false
    - name: Define common variables
      id: define-values
      uses: ./.github/actions/git-environment
    - name: "Read Java / Version Info"
      id: "pom-info"
      uses: YunaBraska/java-info-action@575e99f42f2915cc62410c7917fef5558257042c # 3.0.1
      with:
        work-dir: ./optimize
    - name: Read DB versions
      id: db-versions
      uses: ./.github/actions/read-db-versions
    - name: Expose common variables as Env
      run: |
        {
          echo "DOCKER_BRANCH_TAG=${{ steps.define-values.outputs.branch_slug }}"
          echo "DOCKER_LATEST_TAG=${{ steps.define-values.outputs.latest_tag }}"
          echo "DOCKER_TAG=${{ steps.define-values.outputs.image_tag }}"
          echo "VERSION=${{ steps.pom-info.outputs.project_version }}"
          echo "PUSH_LATEST_TAG=${{ steps.define-values.outputs.is_main_or_stable_branch }}"
          echo "IS_MAIN=${{ steps.define-values.outputs.is_main_branch }}"
          echo "REVISION=${{ steps.define-values.outputs.git_commit_hash }}"
          echo "DOCKER_HUB_SNAPSHOT_TAG=${DOCKER_HUB_SNAPSHOT_TAG}"
        } >> "$GITHUB_ENV"
    # Generating a production build
    - name: Setup Maven
      uses: ./.github/actions/setup-build
      with:
        dockerhub: true
        harbor: true
        maven-cache-key-modifier: optimize
        time-zone: Europe/Berlin
        vault-address: ${{ secrets.VAULT_ADDR }}
        vault-role-id: ${{ secrets.VAULT_ROLE_ID }}
        vault-secret-id: ${{ secrets.VAULT_SECRET_ID }}
        minimus: true
    - name: Build Optimize Backend
      uses: ./.github/actions/run-maven
      with:
        parameters: install -f optimize/pom.xml -pl backend -am -PrunAssembly -DskipTests -T1

    - name: Generate production .tar.gz
      uses: ./.github/actions/run-maven
      with:
        parameters: install -f optimize -DskipTests -Dskip.docker -PrunAssembly -T1
    - name: Build Docker Image
      run: ./.github/optimize/scripts/build-docker-image.sh
    # The SmokeTest is running as part of the "deploy-artifact" job to ensure we only push the artifact on success
    # It uses the previously created docker image before it was pushed
    - name: Set Smoketest versions for main branch
      if: github.ref_name == 'main'
      run: |
        {
          echo "ZEEBE_VERSION=latest"
          echo "IDENTITY_VERSION=latest"
        } >> "$GITHUB_ENV"
    - name: Set Smoketest versions for stable branch
      if: startsWith(github.ref_name, 'stable/')
      run: |
        {
          echo "ZEEBE_VERSION=${{ steps.pom-info.outputs.x_zeebe_version }}"
          echo "IDENTITY_VERSION=${{ steps.pom-info.outputs.x_identity_version }}"
        } >> "$GITHUB_ENV"
    - name: Start Smoketest
      uses: ./.github/actions/compose
      with:
        compose_file: .github/actions/compose/docker-compose.smoketest.yml
        project_name: smoketest
      env:
        OPTIMIZE_IMAGE_TAG: ${{ env.DOCKER_TAG }}
        ELASTIC_VERSION: ${{ steps.db-versions.outputs.elasticsearch-8 }}
        ZEEBE_VERSION: ${{ env.ZEEBE_VERSION }}
        IDENTITY_VERSION: ${{ env.IDENTITY_VERSION }}

    - name: Wait for Optimize to start
      run: ./.github/optimize/scripts/wait-for.sh http://localhost:8090/ready
    - name: Execute health check and push docker image
      uses: ./.github/actions/execute-healthcheck-and-push-image
      with:
        version: ${{ env.VERSION }}
        date: ${{ env.DATE }}
        revision: ${{ env.REVISION }}
    # We're running under the same condition of main / stable
    # We have all dependencies presents, therefore doesn't justify another job
    - name: Deploy to Artifactory
      uses: ./.github/actions/run-maven
      with:
        parameters: deploy -f optimize -Dskip.fe.build -DskipTests -Dskip.docker -PrunAssembly
        threads: 4C
    - name: Docker log dump
      uses: ./.github/actions/docker-logs
      if: always()
      with:
        archive_name: deploy-artifacts-docker
