# description: Publishes the C4 bundle for Optimize. This is abundle of react components which are imported and used in Optimize. They are published here: https://www.npmjs.com/package/@camunda/camunda-optimize-composite-components
# type: CI Helper - Manual
# owner: @camunda/core-features
name: Optimize publish c4 to npm

on:
  workflow_dispatch:

jobs:
  publish-optimize-c4:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./optimize/c4
    steps:
      - name: Checkout repository
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
      - name: "Parse pom.xml for versions"
        id: "pom_info"
        uses: YunaBraska/java-info-action@11a434ffbf6bb3357363d1933be71a4076a90a6b # 3.0.11
        with:
          work-dir: ./optimize
      - name: Enable Corepack
        run: corepack enable
      - name: Setup Node
        uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6
        with:
          node-version: ${{ steps.pom_info.outputs.x_version_node }}
      - uses: camunda/infra-global-github-actions/setup-yarn-cache@main
        with:
          directory: optimize/c4
      - name: Install
        run: yarn install --frozen-lockfile
      - name: Build
        run: yarn build
      - name: Publish to NPM
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ env.NPM_TOKEN }}" >> .npmrc
          npm publish --access=public
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
