# description: Nightly Optimize integration tests for ccsm-test group on Elasticsearch and OpenSearch
# test location: /optimize/backend
# type: CI
# owner: @camunda/core-features
name: Optimize CCSM Integration Tests (Nightly)

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

env:
  GHA_BEST_PRACTICES_LINTER: enabled

permissions:
  contents: read

jobs:
  integration-tests:
    name: "[IT] Run on Elasticsearch"
    runs-on: gcp-core-32-longrunning
    timeout-minutes: 120
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        includedGroups: ['ccsm-test']
        include:
          - includedGroups: 'ccsm-test'
            excludedGroups: ''
            profiles: 'ccsm-it'

    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Print metadata
        uses: ./.github/actions/print-metadata

      - name: Setup Maven
        uses: ./.github/actions/setup-build
        with:
          harbor: true
          maven-cache-key-modifier: optimize-tests
          time-zone: Europe/Berlin
          vault-address: ${{ secrets.VAULT_ADDR }}
          vault-role-id: ${{ secrets.VAULT_ROLE_ID }}
          vault-secret-id: ${{ secrets.VAULT_SECRET_ID }}

      - name: Read DB versions
        id: db-versions
        uses: ./.github/actions/read-db-versions

      - name: Start Elasticsearch
        uses: ./.github/actions/compose
        with:
          compose_file: .github/actions/compose/docker-compose.elasticsearch.yml
          project_name: elasticsearch
        env:
          ELASTIC_VERSION: ${{ steps.db-versions.outputs.elasticsearch-8 }}
          ELASTIC_JVM_MEMORY: 16
          ELASTIC_HTTP_PORT: 9200

      - uses: ./.github/actions/build-zeebe
        id: build-camunda
        with:
          maven-extra-args: -PskipFrontendBuild

      - name: Verify integration
        uses: ./.github/actions/run-maven
        env:
          LIMITS_CPU: 8
        with:
          threads: 8
          parameters: >
            verify -Dit.test.excludedGroups=${{ matrix.excludedGroups }}
            -Dit.test.includedGroups=${{ matrix.includedGroups }}
            -Dskip.docker -Dskip.fe.build -P${{ matrix.profiles }}
            -Dfailsafe.rerunFailingTestsCount=2
            -Ddatabase.type=elasticsearch -f optimize/pom.xml -pl backend -am

      - name: Upload Test Results
        if: always()
        uses: ./.github/actions/collect-test-artifacts
        with:
          name: integration-test-elasticsearch-${{ matrix.includedGroups }}-junit
          path: |
            **/failsafe-reports/**/*.xml

      - name: Docker log dump
        uses: ./.github/actions/docker-logs
        if: always()
        with:
          archive_name: integration-tests-elasticsearch-${{ matrix.includedGroups }}-docker

      - name: Observe build status
        if: always()
        continue-on-error: true
        uses: ./.github/actions/observe-build-status
        with:
          job_name: "integration-tests/${{ matrix.includedGroups }}"
          build_status: ${{ job.status }}
          secret_vault_secretId: ${{ secrets.VAULT_SECRET_ID }}
          secret_vault_address: ${{ secrets.VAULT_ADDR }}
          secret_vault_roleId: ${{ secrets.VAULT_ROLE_ID }}
          user_description: "team-core-features"

  integration-tests-os:
    name: "[IT] Run on OpenSearch"
    runs-on: gcp-core-32-longrunning
    timeout-minutes: 120
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        includedGroups: ['ccsm-test']
        include:
          - includedGroups: 'ccsm-test'
            excludedGroups: 'openSearchSingleTestFailOK'
            profiles: 'ccsm-it'

    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Print metadata
        uses: ./.github/actions/print-metadata

      - name: Setup Maven
        uses: ./.github/actions/setup-build
        with:
          harbor: true
          maven-cache-key-modifier: optimize-tests
          time-zone: Europe/Berlin
          vault-address: ${{ secrets.VAULT_ADDR }}
          vault-role-id: ${{ secrets.VAULT_ROLE_ID }}
          vault-secret-id: ${{ secrets.VAULT_SECRET_ID }}

      - name: Read DB versions
        id: db-versions
        uses: ./.github/actions/read-db-versions

      - name: Start OpenSearch
        uses: ./.github/actions/compose
        with:
          compose_file: .github/actions/compose/docker-compose.opensearch.yml
          project_name: opensearch
        env:
          OPENSEARCH_VERSION: ${{ steps.db-versions.outputs.opensearch-2 }}
          OPENSEARCH_JVM_MEMORY: 16
          OPENSEARCH_HTTP_PORT: 9200

      - uses: ./.github/actions/build-zeebe
        id: build-camunda
        with:
          maven-extra-args: -PskipFrontendBuild

      - name: Verify integration
        uses: ./.github/actions/run-maven
        env:
          LIMITS_CPU: 8
        with:
          threads: 8
          parameters: >
            verify -Dit.test.excludedGroups=${{ matrix.excludedGroups }}
            -Dit.test.includedGroups=${{ matrix.includedGroups }}
            -Dskip.docker -Dskip.fe.build -P${{ matrix.profiles }}
            -Dfailsafe.rerunFailingTestsCount=2
            -Ddatabase.type=opensearch -f optimize/pom.xml -pl backend -am

      - name: Upload Test Results
        if: always()
        uses: ./.github/actions/collect-test-artifacts
        with:
          name: integration-test-opensearch-${{ matrix.includedGroups }}-junit
          path: |
            **/failsafe-reports/**/*.xml

      - name: Docker log dump
        uses: ./.github/actions/docker-logs
        if: always()
        with:
          archive_name: integration-tests-opensearch-${{ matrix.includedGroups }}-docker

      - name: Observe build status
        if: always()
        continue-on-error: true
        uses: ./.github/actions/observe-build-status
        with:
          job_name: "integration-tests-os/${{ matrix.includedGroups }}"
          build_status: ${{ job.status }}
          secret_vault_secretId: ${{ secrets.VAULT_SECRET_ID }}
          secret_vault_address: ${{ secrets.VAULT_ADDR }}
          secret_vault_roleId: ${{ secrets.VAULT_ROLE_ID }}
          user_description: "team-core-features"

  # Rerun failed jobs running on self-hosted runners in case of network issues or node preemption
  rerun-failed-jobs:
    needs:
      - integration-tests
      - integration-tests-os
    if: failure() && fromJSON(github.run_attempt) < 3
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Retrigger job
        uses: camunda/infra-global-github-actions/rerun-failed-run@main
        with:
          error-messages: |
            lost communication with the server
            The runner has received a shutdown signal
          run-id: ${{ github.run_id }}
          repository: ${{ github.repository }}
          vault-addr: ${{ secrets.VAULT_ADDR }}
          vault-role-id: ${{ secrets.VAULT_ROLE_ID }}
          vault-secret-id: ${{ secrets.VAULT_SECRET_ID }}
      - name: Observe build status
        if: always()
        continue-on-error: true
        uses: ./.github/actions/observe-build-status
        with:
          build_status: ${{ job.status }}
          secret_vault_secretId: ${{ secrets.VAULT_SECRET_ID }}
          secret_vault_address: ${{ secrets.VAULT_ADDR }}
          secret_vault_roleId: ${{ secrets.VAULT_ROLE_ID }}
          user_description: "team-core-features"
