---
name: Renovate lint

# owner: @camunda/engineering-operations-team

on:
  pull_request:
    paths:
      - '.github/workflows/renovatelint.yml'
      - '**/renovate.json'

# Limit workflow to 1 concurrent run per ref (branch) and trigger event (push/schedule/etc): new commit -> old runs are canceled to save costs
# Exception for main + stable/* branches: complete builds for every commit needed for confidence
# Exception for deploy jobs that have to wait for each other to avoid overwriting
concurrency:
  cancel-in-progress: true
  group: ${{ format('{0}-{1}-{2}', github.workflow, github.event_name, (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/stable/')) && github.sha || github.ref) }}

jobs:
  renovate-config-validator:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/renovatebot/renovate
      options: --user root
    steps:
      - uses: actions/checkout@v4
      - run: renovate-config-validator --strict
