# description: This is a Workflow runs tests and created updated screenshots of Tasklist
# test location: /tasklist/client/
# type: CI Helper
# owner: @camunda/core-features
name: Tasklist Update Visual Regression Snapshots

on:
  pull_request:
    types: [labeled, synchronize]

# Limit workflow to 1 concurrent run per ref (branch) and trigger event (push/schedule/etc): new commit -> old runs are canceled to save costs
# Exception for main + stable/* branches: complete builds for every commit needed for confidence
# Exception for deploy jobs that have to wait for each other to avoid overwriting
concurrency:
  cancel-in-progress: true
  group: ${{ format('{0}-{1}-{2}', github.workflow, github.event_name, (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/stable/')) && github.sha || github.ref) }}

env:
  CLIENT_DIR: ./tasklist/client

jobs:
  update-snapshots:
    if: github.event.pull_request.state != 'closed' && (github.event.label.name == 'update-snapshots' || contains( github.event.pull_request.labels.*.name, 'update-snapshots'))
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.58.2
      options: --user 1001:1000

    steps:
      - name: Check out repository code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: Setup NodeJS
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: 24
      - name: Install node dependencies
        uses: ./.github/actions/npm-ci-with-retry
        with:
          directory: ${{ env.CLIENT_DIR }}
      - name: Build frontend
        working-directory: ${{ env.CLIENT_DIR }}
        run: npm run build:visual-regression
      - name: Update snapshots
        working-directory: ${{ env.CLIENT_DIR }}
        run: npm run test:visual --update-snapshots
      - name: Commit screenshots
        uses: stefanzweifel/git-auto-commit-action@04702edda442b2e678b25b537cec683a1493fcb9 # v7.1.0
        with:
          commit_message: "test: updated tasklist snapshots"
          file_pattern: "tasklist/client/**/*.png"
