# description: Workflow for running CI tests for Tasklist. Runs a build and Integration Tests
# test location: /tasklist
# type: CI
# owner: @camunda/core-features
---
name: "[Legacy] Tasklist"
on:
  workflow_dispatch:
  push:
    branches:
      - "main"
      - "stable/**"
      - "release**"
  pull_request:
    types: [opened, synchronize, reopened, labeled]

# Limit workflow to 1 concurrent run per ref (branch): new commit -> old runs are canceled to save costs
# Exception for main branch: complete builds for every commit needed for confidenence
concurrency:
  cancel-in-progress: true
  group: ${{ format('{0}-{1}', github.workflow, github.ref == 'refs/heads/main' && github.sha || github.ref) }}

jobs:
  ci-gate:
    name: "CI Gate"
    runs-on: ubuntu-latest
    timeout-minutes: 3
    permissions:
      pull-requests: write
    outputs:
      should-run: ${{ steps.gate.outputs.should-run }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          sparse-checkout: .github/actions/ci-gate
      - uses: ./.github/actions/ci-gate
        id: gate
        with:
          github-token: ${{ github.token }}

  detect-changes:
    outputs:
      tasklist-backend-changes: ${{ steps.filter.outputs.tasklist-backend-changes }}
      tasklist-frontend-changes: ${{ steps.filter.outputs.tasklist-frontend-changes }}
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      pull-requests: read
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      # Detect changes against the base branch
      - name: Detect changes
        uses: ./.github/actions/paths-filter
        id: filter

  run-build:
    name: run-build
    needs: [ci-gate, detect-changes]
    uses: ./.github/workflows/tasklist-ci-build-reusable.yml
    secrets: inherit
    with:
      branch: ${{ github.head_ref || github.ref_name }} # head_ref = branch name on PR, ref_name = `main` or `stable/**`
    if: needs.ci-gate.outputs.should-run == 'true' && (github.event_name == 'workflow_dispatch' || needs.detect-changes.outputs.tasklist-backend-changes == 'true' || needs.detect-changes.outputs.tasklist-frontend-changes == 'true')

  # Does not meet run time requirements for Unified CI
  run-integration-tests:
    name: "Integration"
    needs: [ci-gate, detect-changes]
    uses: ./.github/workflows/tasklist-ci-test-reusable.yml
    secrets: inherit
    permissions: { }
    with:
      branch: ${{ github.head_ref || github.ref_name }}
    if: needs.ci-gate.outputs.should-run == 'true' && (github.event_name == 'workflow_dispatch' || needs.detect-changes.outputs.tasklist-backend-changes == 'true')
