# description: Runs Integration tests on min/max supported versions of Elasticsearch and OpenSearch
# test location: /qa/acceptance-tests
# type: CI
# owner: @camunda/core-features, @camunda/data-layer
name: Search DB Manual/Scheduled Run Integration Tests

on:
  workflow_dispatch:
  pull_request:
    paths:
      - ".github/workflows/zeebe-search-integration-tests.yml"
  schedule:
    - cron: "0 5 * * Mon-Fri"

env:
  GHA_BEST_PRACTICES_LINTER: enabled

defaults:
  run:
    # use bash shell by default to ensure pipefail behavior is the default
    # see https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#exit-codes-and-error-action-preference
    shell: bash

jobs:
  generate-db-versions:
    name: "Generate DB versions"
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
    outputs:
      es-os-matrix: ${{ steps.db-versions.outputs.es-os-matrix }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Read DB versions
        id: db-versions
        uses: ./.github/actions/read-db-versions

  search-integration-tests:
    name: "Search ${{ matrix.database-name }}"
    needs: [ generate-db-versions ]
    permissions:
      actions: write
      contents: read
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.generate-db-versions.outputs.es-os-matrix) }}
    uses: ./.github/workflows/ci-database-integration-tests-reusable.yml
    secrets: inherit
    with:
      database-type: ${{ matrix.database-type }}
      database-container: ${{ matrix.database-container }}
      database-image-version: ${{ matrix.database-image-version }}
      database-name: ${{ matrix.database-name }}
      it-database-type: ${{ matrix.it-database-type }}
      notify-slack-on-failure: ${{ github.event_name == 'schedule' }}

  search-history-tests:
    name: "Search History Tests / ${{ matrix.database-name }}"
    needs: [ generate-db-versions ]
    permissions:
      actions: write
      contents: read
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.generate-db-versions.outputs.es-os-matrix) }}
    uses: ./.github/workflows/ci-database-integration-tests-reusable.yml
    secrets: inherit
    with:
      database-type: "${{ matrix.database-type }}"
      database-container: "${{ matrix.database-container }}"
      database-image-version: "${{ matrix.database-image-version }}"
      database-name: "${{ matrix.database-name }}"
      it-database-type: "${{ matrix.it-database-type }}"
      maven-profiles: "history"
      test-type: "history-tests"
      test-type-label: "History"
      runs-on: "gcp-perf-core-8-default"
      notify-slack-on-failure: ${{ github.event_name == 'schedule' }}

  search-identity-tests:
    name: "Search Identity Tests / ${{ matrix.database-name }}"
    needs: [ generate-db-versions ]
    permissions:
      actions: write
      contents: read
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.generate-db-versions.outputs.es-os-matrix) }}
    uses: ./.github/workflows/ci-database-integration-tests-reusable.yml
    secrets: inherit
    with:
      database-type: "${{ matrix.database-type }}"
      database-container: "${{ matrix.database-container }}"
      database-image-version: "${{ matrix.database-image-version }}"
      database-name: "${{ matrix.database-name }}"
      it-database-type: "${{ matrix.it-database-type }}"
      maven-profiles: "identity-tests"
      test-type: "identity-tests"
      test-type-label: "Identity"
      notify-slack-on-failure: ${{ github.event_name == 'schedule' }}
